// ── Achievement Definitions ─────────────────────────────────────────────────

export type AchievementId =
  | "first_exercise"
  | "first_topic"
  | "perfect_score"
  | "streak_3"
  | "streak_7"
  | "streak_14"
  | "no_hints"
  | "speed_run"
  | "polyglot"
  | "math_master_1"
  | "math_master_2"
  | "math_master_3"
  | "german_master_1"
  | "german_master_2"
  | "german_master_3"
  | "grade_1_complete"
  | "grade_2_complete"
  | "grade_3_complete"
  | "exercises_10"
  | "exercises_50"
  | "exercises_100"
  | "exercises_250"
  | "level_2"
  | "level_3"
  | "level_4"
  | "level_5";

export interface Achievement {
  id: AchievementId;
  emoji: string;
  title: string;
  titleFr: string;
  titleIt: string;
  titleEn: string;
  desc: string;
  descFr: string;
  descIt: string;
  descEn: string;
  rarity: "common" | "rare" | "epic" | "legendary";
  xpReward: number;
}

export const ACHIEVEMENTS: Achievement[] = [
  {
    id: "first_exercise",
    emoji: "🌟",
    title: "Erste Schritte",
    titleFr: "Premiers pas",
    titleIt: "Primi passi",
    titleEn: "First Steps",
    desc: "Erste Aufgabe gelöst!",
    descFr: "Premier exercice résolu !",
    descIt: "Primo esercizio completato!",
    descEn: "First exercise solved!",
    rarity: "common",
    xpReward: 10,
  },
  {
    id: "first_topic",
    emoji: "🏆",
    title: "Thema geschafft!",
    titleFr: "Thème réussi !",
    titleIt: "Argomento completato!",
    titleEn: "Topic Complete!",
    desc: "Erstes Thema vollständig abgeschlossen.",
    descFr: "Premier thème entièrement terminé.",
    descIt: "Primo argomento completato.",
    descEn: "First topic fully completed.",
    rarity: "common",
    xpReward: 20,
  },
  {
    id: "perfect_score",
    emoji: "💯",
    title: "Perfekt!",
    titleFr: "Parfait !",
    titleIt: "Perfetto!",
    titleEn: "Perfect!",
    desc: "Alle Aufgaben richtig!",
    descFr: "Tous les exercices réussis !",
    descIt: "Tutti gli esercizi corretti!",
    descEn: "All exercises correct!",
    rarity: "rare",
    xpReward: 30,
  },
  {
    id: "streak_3",
    emoji: "🔥",
    title: "3-Tage-Streak",
    titleFr: "3 jours de suite",
    titleIt: "3 giorni di fila",
    titleEn: "3-Day Streak",
    desc: "3 Tage in Folge geübt!",
    descFr: "Exercices 3 jours de suite !",
    descIt: "3 giorni consecutivi di esercizi!",
    descEn: "Practiced 3 days in a row!",
    rarity: "common",
    xpReward: 25,
  },
  {
    id: "streak_7",
    emoji: "🔥🔥",
    title: "Woche am Ball",
    titleFr: "Une semaine !",
    titleIt: "Una settimana!",
    titleEn: "Week Warrior",
    desc: "7 Tage in Folge geübt!",
    descFr: "Exercices 7 jours de suite !",
    descIt: "7 giorni consecutivi!",
    descEn: "7 days in a row!",
    rarity: "rare",
    xpReward: 75,
  },
  {
    id: "streak_14",
    emoji: "⚡",
    title: "Unaufhaltbar!",
    titleFr: "Inarrêtable !",
    titleIt: "Inarrestabile!",
    titleEn: "Unstoppable!",
    desc: "14 Tage in Folge geübt!",
    descFr: "14 jours consécutifs !",
    descIt: "14 giorni consecutivi!",
    descEn: "14 days in a row!",
    rarity: "epic",
    xpReward: 150,
  },
  {
    id: "no_hints",
    emoji: "🧠",
    title: "Kein Tipp nötig!",
    titleFr: "Sans aide !",
    titleIt: "Senza suggerimenti!",
    titleEn: "No Hints Needed!",
    desc: "Thema ohne Tipps abgeschlossen.",
    descFr: "Thème terminé sans indices.",
    descIt: "Argomento senza suggerimenti.",
    descEn: "Topic done without any hints.",
    rarity: "rare",
    xpReward: 40,
  },
  {
    id: "speed_run",
    emoji: "⚡",
    title: "Blitzschnell!",
    titleFr: "Éclair !",
    titleIt: "Velocissimo!",
    titleEn: "Speed Runner!",
    desc: "Thema in unter 2 Minuten.",
    descFr: "Thème en moins de 2 minutes.",
    descIt: "Argomento in meno di 2 minuti.",
    descEn: "Topic done in under 2 minutes.",
    rarity: "rare",
    xpReward: 35,
  },
  {
    id: "polyglot",
    emoji: "🌍",
    title: "Sprachtalent",
    titleFr: "Polyglotte",
    titleIt: "Poliglotta",
    titleEn: "Polyglot",
    desc: "In 2 Sprachen geübt.",
    descFr: "Exercices en 2 langues.",
    descIt: "Esercizi in 2 lingue.",
    descEn: "Practiced in 2 languages.",
    rarity: "rare",
    xpReward: 30,
  },
  {
    id: "exercises_10",
    emoji: "✏️",
    title: "10 Aufgaben",
    titleFr: "10 exercices",
    titleIt: "10 esercizi",
    titleEn: "10 Exercises",
    desc: "10 Aufgaben gelöst!",
    descFr: "10 exercices résolus !",
    descIt: "10 esercizi completati!",
    descEn: "10 exercises solved!",
    rarity: "common",
    xpReward: 15,
  },
  {
    id: "exercises_50",
    emoji: "📝",
    title: "50 Aufgaben",
    titleFr: "50 exercices",
    titleIt: "50 esercizi",
    titleEn: "50 Exercises",
    desc: "50 Aufgaben gelöst!",
    descFr: "50 exercices résolus !",
    descIt: "50 esercizi completati!",
    descEn: "50 exercises solved!",
    rarity: "rare",
    xpReward: 50,
  },
  {
    id: "exercises_100",
    emoji: "🎓",
    title: "100 Aufgaben",
    titleFr: "100 exercices",
    titleIt: "100 esercizi",
    titleEn: "100 Exercises",
    desc: "100 Aufgaben gelöst!",
    descFr: "100 exercices résolus !",
    descIt: "100 esercizi completati!",
    descEn: "100 exercises solved!",
    rarity: "epic",
    xpReward: 100,
  },
  {
    id: "exercises_250",
    emoji: "🦸",
    title: "250 Aufgaben",
    titleFr: "250 exercices",
    titleIt: "250 esercizi",
    titleEn: "250 Exercises",
    desc: "250 Aufgaben gelöst!",
    descFr: "250 exercices résolus !",
    descIt: "250 esercizi completati!",
    descEn: "250 exercises solved!",
    rarity: "legendary",
    xpReward: 200,
  },
  {
    id: "math_master_1",
    emoji: "➕",
    title: "Mathe-Ass Kl. 1",
    titleFr: "As des maths 1re",
    titleIt: "Asso matem. 1a",
    titleEn: "Math Ace Gr. 1",
    desc: "Alle Mathe-Themen der 1. Klasse.",
    descFr: "Tous les thèmes de maths 1re.",
    descIt: "Tutti gli argomenti di matem. 1a.",
    descEn: "All grade 1 math topics done.",
    rarity: "epic",
    xpReward: 80,
  },
  {
    id: "math_master_2",
    emoji: "➕",
    title: "Mathe-Ass Kl. 2",
    titleFr: "As des maths 2e",
    titleIt: "Asso matem. 2a",
    titleEn: "Math Ace Gr. 2",
    desc: "Alle Mathe-Themen der 2. Klasse.",
    descFr: "Tous les thèmes de maths 2e.",
    descIt: "Tutti gli argomenti di matem. 2a.",
    descEn: "All grade 2 math topics done.",
    rarity: "epic",
    xpReward: 80,
  },
  {
    id: "math_master_3",
    emoji: "➕",
    title: "Mathe-Ass Kl. 3",
    titleFr: "As des maths 3e",
    titleIt: "Asso matem. 3a",
    titleEn: "Math Ace Gr. 3",
    desc: "Alle Mathe-Themen der 3. Klasse.",
    descFr: "Tous les thèmes de maths 3e.",
    descIt: "Tutti gli argomenti di matem. 3a.",
    descEn: "All grade 3 math topics done.",
    rarity: "epic",
    xpReward: 80,
  },
  {
    id: "german_master_1",
    emoji: "🔤",
    title: "Sprach-Profi Kl. 1",
    titleFr: "Pro de langue 1re",
    titleIt: "Esperto lingua 1a",
    titleEn: "Language Pro Gr. 1",
    desc: "Alle Deutsch-Themen der 1. Klasse.",
    descFr: "Tous les thèmes d'allemand 1re.",
    descIt: "Tutti gli argomenti di tedesco 1a.",
    descEn: "All grade 1 German topics done.",
    rarity: "epic",
    xpReward: 80,
  },
  {
    id: "german_master_2",
    emoji: "🔤",
    title: "Sprach-Profi Kl. 2",
    titleFr: "Pro de langue 2e",
    titleIt: "Esperto lingua 2a",
    titleEn: "Language Pro Gr. 2",
    desc: "Alle Deutsch-Themen der 2. Klasse.",
    descFr: "Tous les thèmes d'allemand 2e.",
    descIt: "Tutti gli argomenti di tedesco 2a.",
    descEn: "All grade 2 German topics done.",
    rarity: "epic",
    xpReward: 80,
  },
  {
    id: "german_master_3",
    emoji: "🔤",
    title: "Sprach-Profi Kl. 3",
    titleFr: "Pro de langue 3e",
    titleIt: "Esperto lingua 3a",
    titleEn: "Language Pro Gr. 3",
    desc: "Alle Deutsch-Themen der 3. Klasse.",
    descFr: "Tous les thèmes d'allemand 3e.",
    descIt: "Tutti gli argomenti di tedesco 3a.",
    descEn: "All grade 3 German topics done.",
    rarity: "epic",
    xpReward: 80,
  },
  {
    id: "grade_1_complete",
    emoji: "🎖️",
    title: "1. Klasse: Meister!",
    titleFr: "1re année : Maître !",
    titleIt: "1a classe: Maestro!",
    titleEn: "Grade 1 Master!",
    desc: "Alle Themen der 1. Klasse.",
    descFr: "Tous les thèmes de 1re année.",
    descIt: "Tutti gli argomenti della 1a classe.",
    descEn: "All grade 1 topics complete.",
    rarity: "legendary",
    xpReward: 200,
  },
  {
    id: "grade_2_complete",
    emoji: "🎖️",
    title: "2. Klasse: Meister!",
    titleFr: "2e année : Maître !",
    titleIt: "2a classe: Maestro!",
    titleEn: "Grade 2 Master!",
    desc: "Alle Themen der 2. Klasse.",
    descFr: "Tous les thèmes de 2e année.",
    descIt: "Tutti gli argomenti della 2a classe.",
    descEn: "All grade 2 topics complete.",
    rarity: "legendary",
    xpReward: 200,
  },
  {
    id: "grade_3_complete",
    emoji: "🎖️",
    title: "3. Klasse: Meister!",
    titleFr: "3e année : Maître !",
    titleIt: "3a classe: Maestro!",
    titleEn: "Grade 3 Master!",
    desc: "Alle Themen der 3. Klasse.",
    descFr: "Tous les thèmes de 3e année.",
    descIt: "Tutti gli argomenti della 3a classe.",
    descEn: "All grade 3 topics complete.",
    rarity: "legendary",
    xpReward: 200,
  },
  {
    id: "level_2",
    emoji: "📚",
    title: "Level 2: Bücherwurm",
    titleFr: "Niveau 2 : Rat de biblio",
    titleIt: "Livello 2: Topolino",
    titleEn: "Level 2: Bookworm",
    desc: "Level 2 erreicht!",
    descFr: "Niveau 2 atteint !",
    descIt: "Livello 2 raggiunto!",
    descEn: "Reached level 2!",
    rarity: "common",
    xpReward: 0,
  },
  {
    id: "level_3",
    emoji: "🥷",
    title: "Level 3: Mathe-Ninja",
    titleFr: "Niveau 3 : Ninja",
    titleIt: "Livello 3: Ninja",
    titleEn: "Level 3: Math Ninja",
    desc: "Level 3 erreicht!",
    descFr: "Niveau 3 atteint !",
    descIt: "Livello 3 raggiunto!",
    descEn: "Reached level 3!",
    rarity: "rare",
    xpReward: 0,
  },
  {
    id: "level_4",
    emoji: "⭐",
    title: "Level 4: Cleverli-Star",
    titleFr: "Niveau 4 : Étoile",
    titleIt: "Livello 4: Stella",
    titleEn: "Level 4: Cleverli Star",
    desc: "Level 4 erreicht!",
    descFr: "Niveau 4 atteint !",
    descIt: "Livello 4 raggiunto!",
    descEn: "Reached level 4!",
    rarity: "epic",
    xpReward: 0,
  },
  {
    id: "level_5",
    emoji: "👑",
    title: "Level 5: Cleverli-Meister",
    titleFr: "Niveau 5 : Maître",
    titleIt: "Livello 5: Maestro",
    titleEn: "Level 5: Cleverli Master",
    desc: "Höchstes Level erreicht!",
    descFr: "Niveau maximum atteint !",
    descIt: "Livello massimo raggiunto!",
    descEn: "Max level reached!",
    rarity: "legendary",
    xpReward: 0,
  },
];

export const RARITY_COLORS: Record<Achievement["rarity"], string> = {
  common:    "from-gray-50 to-gray-100 border-gray-200",
  rare:      "from-blue-50 to-blue-100 border-blue-300",
  epic:      "from-purple-50 to-purple-100 border-purple-300",
  legendary: "from-yellow-50 to-amber-100 border-amber-400",
};

export const RARITY_GLOW: Record<Achievement["rarity"], string> = {
  common:    "",
  rare:      "shadow-blue-200",
  epic:      "shadow-purple-200",
  legendary: "shadow-amber-300",
};
