import type { Lang } from './i18n';
export const LEHRPLAN_LANGS: Lang[] = ['de', 'fr', 'it', 'en'];
export const LEHRPLAN_URL = 'https://www.cleverli.ch/lehrplanbezug';
export const lehrplanUrl = (lang: Lang) => lang === 'de' ? LEHRPLAN_URL : `${LEHRPLAN_URL}?lang=${lang}`;
export const lehrplanGrade = (n: number, lang: Lang) => lang === 'fr' ? `${n === 1 ? '1re' : `${n}e`} année` : lang === 'it' ? `${n}a classe` : lang === 'en' ? `Grade ${n}` : `${n}. Klasse`;
// Explicit separators keep SSR and browsers consistent across ICU versions.
export const lehrplanNumber = (value: number, lang: Lang) => String(value).replace(/\B(?=(\d{3})+(?!\d))/g, lang === 'fr' ? '\u202f' : lang === 'en' ? ',' : "'");
export const lehrplanCopy = {
 de: {
 locale:'de-CH', title:'Lehrplanbezug: Themen und Übungen', description:'Entdecke, wie Cleverli-Themen mit dem Lehrplan 21 verbunden sind. Übersicht nach Klasse, Fach und Themenbereich.', eyebrow:'LERNEN MIT BEZUG ZUM LEHRPLAN 21', heading:'Was dein Kind bei Cleverli übt', intro:'Vom ersten Zählen bis zu anspruchsvolleren Texten: Hier findest du unsere Themen, die passenden Übungen und ihren Bezug zum Lehrplan 21. Nach Klasse und Fach geordnet, damit du schnell das Passende findest.', range:'1 bis 6', grades:'Klassen', topics:'Themen', exercises:'Übungen', overview:'Übersicht des Übungsangebots', orientation:'So liest du die Übersicht',
 paragraphs:['Die 1. und 2. Klasse gehören zum ersten Zyklus, die 3. bis 6. Klasse zum zweiten. Der erste Zyklus umfasst im Lehrplan auch den Kindergarten; diese Übersicht zeigt unsere Primarschulübungen.','Die Lehrplancodes zeigen die bestehenden Zuordnungen unserer Themen. Je nach Thema beziehen sie sich auf einen Kompetenzbereich oder eine konkretere Kompetenz. Ein Code bedeutet nicht, dass eine einzelne Übung die gesamte Kompetenz abdeckt.','Die Übersicht zeigt den gesamten Themenbestand. Welche Fremdsprache zuerst gelernt wird und wann Medien und Informatik dazukommen, hängt vom Kanton ab. Grundlage ist der Lehrplan 21 für die deutschsprachige Schule. Der Unterricht und die Begleitung durch Lehrpersonen bleiben wichtig.'], select:'Klasse auswählen', cycle:'Zyklus', alignment:'Lehrplanbezug', view:'Übungen ansehen', sources:'Der Lehrplan als Grundlage', sourceText:'Die offiziellen Quellen erklären die Kompetenzbereiche und den Aufbau des Lehrplans. Für die Umsetzung ist die jeweilige kantonale Fassung massgebend.', sourceGeneral:'Lehrplan 21: Grundlagen und kantonale Fassungen', sourceZurich:'Lehrplan 21 des Kantons Zürich', disclaimer:'Diese Zuordnung beschreibt das Übungsangebot von Cleverli. Sie ist keine Zertifizierung oder offizielle Empfehlung durch eine Bildungsbehörde.', scope:'Der Lehrplanbezug bleibt in allen Sprachversionen Lehrplan 21. Eine Übersetzung ist keine Zuordnung zum Plan d’études romand oder zum Tessiner Piano di studio.', resource:'Interaktive Übungen', schemaDescription:'Bestehende Lehrplanzuordnungen der Cleverli-Themen für die 1. bis 6. Klasse. Keine Aussage zur vollständigen Abdeckung einzelner Kompetenzen.', subjects:{math:'Mathematik',german:'Deutsch',science:'Natur, Mensch, Gesellschaft (NMG)',english:'Englisch',french:'Französisch',mi:'Medien und Informatik'},
 },
 fr: {
 locale:'fr-CH', title:'Liens avec le Lehrplan 21 : thèmes et exercices', description:'Découvrez les liens entre les thèmes de Cleverli et le Lehrplan 21, par année, matière et domaine.', eyebrow:'APPRENDRE EN LIEN AVEC LE LEHRPLAN 21', heading:'Ce que votre enfant travaille avec Cleverli', intro:'Des premiers nombres aux textes plus exigeants : retrouvez nos thèmes, les exercices correspondants et leurs liens avec le Lehrplan 21. Le classement par année et matière vous aide à trouver ce qui convient à votre enfant.', range:'1 à 6', grades:'Années', topics:'Thèmes', exercises:'Exercices', overview:'Aperçu des exercices proposés', orientation:'Comment lire cet aperçu',
 paragraphs:['Les 1re et 2e années du primaire appartiennent au premier cycle, les 3e à 6e années au deuxième. Dans le Lehrplan 21, le premier cycle comprend aussi l’école enfantine ; cet aperçu présente nos exercices du primaire.','Les codes du programme indiquent les liens existants avec nos thèmes. Selon le thème, ils renvoient à un domaine de compétences ou à une compétence plus précise. Un code ne signifie pas qu’un seul exercice couvre toute la compétence.','Cet aperçu présente l’ensemble des thèmes. L’ordre d’apprentissage des langues étrangères et l’introduction des médias et de l’informatique varient selon le canton. La référence est le Lehrplan 21 pour l’école germanophone. L’enseignement et l’accompagnement par les enseignants restent essentiels.'], select:'Choisir une année', cycle:'Cycle', alignment:'Lien avec le programme', view:'Voir les exercices', sources:'Le programme comme référence', sourceText:'Les sources officielles expliquent les domaines de compétences et la structure du programme. La version cantonale fait référence pour sa mise en œuvre.', sourceGeneral:'Lehrplan 21 : principes et versions cantonales', sourceZurich:'Lehrplan 21 du canton de Zurich', disclaimer:'Ces liens décrivent les exercices proposés par Cleverli. Ils ne constituent ni une certification ni une recommandation officielle d’une autorité éducative.', scope:'Toutes les versions linguistiques se réfèrent au Lehrplan 21. La traduction ne constitue pas un alignement sur le Plan d’études romand ou le Piano di studio tessinois. Les années indiquées suivent la numérotation du primaire du Lehrplan 21, et non la numérotation HarmoS.', resource:'Exercices interactifs', schemaDescription:'Liens existants entre les thèmes de Cleverli et le Lehrplan 21 pour les six années du primaire. Aucune affirmation de couverture complète des compétences.', subjects:{math:'Mathématiques',german:'Allemand',science:'Nature, être humain et société (NMG)',english:'Anglais',french:'Français',mi:'Médias et informatique'},
 },
 it: {
 locale:'it-CH', title:'Collegamenti al Lehrplan 21: temi ed esercizi', description:'Scopri come i temi di Cleverli si collegano al Lehrplan 21, per classe, materia e ambito.', eyebrow:'IMPARARE IN RIFERIMENTO AL LEHRPLAN 21', heading:'Che cosa impara tuo figlio con Cleverli', intro:'Dai primi numeri ai testi più impegnativi: qui trovi i nostri temi, gli esercizi corrispondenti e i collegamenti al Lehrplan 21. Sono organizzati per classe e materia, per trovare facilmente ciò che serve.', range:'Da 1 a 6', grades:'Classi', topics:'Temi', exercises:'Esercizi', overview:'Panoramica degli esercizi disponibili', orientation:'Come leggere la panoramica',
 paragraphs:['La 1a e la 2a classe appartengono al primo ciclo, dalla 3a alla 6a al secondo. Nel Lehrplan 21 il primo ciclo comprende anche la scuola dell’infanzia; questa panoramica presenta i nostri esercizi della scuola primaria.','I codici del programma indicano i collegamenti esistenti con i nostri temi. A seconda del tema, si riferiscono a un ambito di competenze o a una competenza più specifica. Un codice non significa che un singolo esercizio copra l’intera competenza.','La panoramica presenta tutti i temi disponibili. L’ordine delle lingue straniere e l’introduzione di media e informatica dipendono dal cantone. Il riferimento è il Lehrplan 21 per la scuola di lingua tedesca. L’insegnamento e l’accompagnamento dei docenti restano importanti.'], select:'Scegli una classe', cycle:'Ciclo', alignment:'Collegamento al programma', view:'Vedi gli esercizi', sources:'Il programma come riferimento', sourceText:'Le fonti ufficiali spiegano gli ambiti di competenze e la struttura del programma. Per l’attuazione fa stato la rispettiva versione cantonale.', sourceGeneral:'Lehrplan 21: principi e versioni cantonali', sourceZurich:'Lehrplan 21 del Canton Zurigo', disclaimer:'Questi collegamenti descrivono gli esercizi offerti da Cleverli. Non costituiscono una certificazione o una raccomandazione ufficiale di un’autorità educativa.', scope:'Tutte le versioni linguistiche fanno riferimento al Lehrplan 21. La traduzione non costituisce un allineamento al Plan d’études romand o al Piano di studio ticinese. Le classi indicate seguono la struttura del Lehrplan 21.', resource:'Esercizi interattivi', schemaDescription:'Collegamenti esistenti tra i temi di Cleverli e il Lehrplan 21 dalla 1a alla 6a classe. Nessuna affermazione di copertura completa delle competenze.', subjects:{math:'Matematica',german:'Tedesco',science:'Natura, essere umano e società (NMG)',english:'Inglese',french:'Francese',mi:'Media e informatica'},
 },
 en: {
 locale:'en-GB', title:'Curriculum connections: topics and exercises', description:'Explore how Cleverli topics relate to Lehrplan 21, organised by grade, subject and topic.', eyebrow:'LEARNING WITH REFERENCE TO LEHRPLAN 21', heading:'What your child practises with Cleverli', intro:'From counting for the first time to more demanding texts: explore our topics, the matching exercises and their connections to Lehrplan 21. Browse by grade and subject to find what suits your child.', range:'1 to 6', grades:'Grades', topics:'Topics', exercises:'Exercises', overview:'Overview of available exercises', orientation:'How to read this overview',
 paragraphs:['Grades 1 and 2 belong to the first cycle, and grades 3 to 6 to the second. Lehrplan 21 also includes kindergarten in the first cycle; this overview covers our primary school exercises.','The curriculum codes show our existing topic mappings. Depending on the topic, they refer to a competency area or a more specific competency. A code does not mean that one exercise covers the entire competency.','The overview shows the full topic collection. The order of foreign languages and the introduction of media and computing depend on the canton. The reference is Lehrplan 21 for German-language schools. Teaching and guidance from teachers remain important.'], select:'Choose a grade', cycle:'Cycle', alignment:'Curriculum connection', view:'View exercises', sources:'The curriculum as a reference', sourceText:'The official sources explain the competency areas and curriculum structure. The relevant cantonal version governs implementation.', sourceGeneral:'Lehrplan 21: principles and cantonal versions', sourceZurich:'Lehrplan 21 for the canton of Zurich', disclaimer:'These mappings describe the exercises offered by Cleverli. They are not a certification or official endorsement by an education authority.', scope:'All language versions refer to Lehrplan 21. Translation does not imply alignment with the Plan d’études romand or Ticino’s Piano di studio.', resource:'Interactive exercises', schemaDescription:'Existing curriculum mappings for Cleverli topics in grades 1 to 6. No claim of complete coverage of individual competencies.', subjects:{math:'Mathematics',german:'German',science:'Nature, humans and society (NMG)',english:'English',french:'French',mi:'Media and computing'},
 },
};
