import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import * as bridge from '../bridge-builder/engine.mjs';
import * as sentence from '../sentence-detective/engine.mjs';
let checks=0;
const diversity={};
function labelValue(label,grade){if(grade===3)return label.split(' × ').map(Number).reduce((a,b)=>a*b);if(grade===4)return parseInt(label)*(label.endsWith('dm')?10:1);return label.split(' + ').map(t=>t.includes('/')?t.split('/').map(Number).reduce((a,b)=>a/b):Number(t.replace(',','.'))).reduce((a,b)=>a+b)* (grade>=5?100:1);}
for(let grade=1;grade<=6;grade++){
 const signatures=new Set();
 for(let seed=1;seed<=1000;seed++){
  const m=bridge.mission(grade,bridge.rng(seed*811));signatures.add(m.signature);
  assert(m.target<=bridge.PROFILES[grade].max);assert(bridge.alternativePlans(m));assert(m.choices.every(c=>Number.isInteger(c.value)&&c.value>0));
  assert.equal(new Set(m.choices.map(c=>c.value)).size,m.choices.length);assert.equal(new Set(m.choices.map(c=>c.label)).size,m.choices.length);
  for(const c of m.choices)assert(Math.abs(labelValue(c.label,grade)-c.value)<1e-6,c.label);
  let placed=[];for(const id of bridge.solution(m)){const out=bridge.add(m,placed,id);assert(['build','bridge'].includes(out.outcome));placed=out.placed;}
  assert.equal(placed.reduce((n,p)=>n+p.value,0),m.target);assert(placed.length<=m.maxBlocks);
  assert.deepEqual(bridge.add(m,placed,m.choices[0].id).placed,placed);
  // Every accepted intermediate state retains a solution within the visible budget.
  const visit=parts=>{if(parts.length>=m.maxBlocks||parts.reduce((n,p)=>n+p.value,0)===m.target)return;for(const c of m.choices){const out=bridge.add(m,parts,c.id);if(['build','bridge'].includes(out.outcome)){assert(bridge.solution(m,m.target-out.placed.reduce((n,p)=>n+p.value,0),m.maxBlocks-out.placed.length));if(seed<=12)visit(out.placed);}else assert.deepEqual(out.placed,parts);}};visit([]);
  const next=bridge.mission(grade,bridge.rng(seed*29),[m.signature]);assert.notEqual(next.signature,m.signature);checks++;
 }
 assert(signatures.size>=6);diversity[grade]=signatures.size;
 for(let i=0;i<sentence.BANK[grade].length;i++){
  const m=sentence.mission(grade,i);assert.equal(sentence.text(m).normalize('NFC'),sentence.text(m));assert(!sentence.text(m).includes('ß'));
  let prefix=[];for(const v of m.type==='order'?m.words:[m.answer])prefix=sentence.select(m,prefix,v).prefix;
  assert.equal(prefix.length,m.type==='order'?m.words.length:1);assert.deepEqual(sentence.select(m,[],'WRONG').prefix,[]);
  if(m.type==='choice'){assert.equal(m.choices.length,3);assert.equal(new Set(m.choices).size,3);assert(m.choices.includes(m.answer));}
  assert(m.prompt&&m.hint);checks++;
 }
}
function controller(kind,grade,seed,chapter='practice'){const nodes=new Map(),created=[];const gradient={addColorStop(){}};const ctx=new Proxy({createLinearGradient:()=>gradient,measureText:t=>({width:String(t).length*9})},{get:(o,k)=>o[k]||(()=>{})});function node(id){return{ id,value:id==='grade'?String(grade):'',hidden:false,disabled:false,textContent:'',className:'',style:{setProperty(){}},dataset:{},children:[],setAttribute(){},append(...a){this.children.push(...a)},prepend(...a){this.children.unshift(...a)},replaceChildren(...a){this.children=[...a]},focus(){},getBoundingClientRect:()=>({width:900,height:320,top:0,bottom:320}),getContext:()=>ctx};}const get=id=>nodes.get(id)||nodes.set(id,node(id)).get(id);const document={getElementById:get,createElement:t=>{const n=node(t);created.push(n);return n;},querySelector:()=>get('scene-frame'),body:{dataset:{}},activeElement:null,addEventListener(){}};const window={addEventListener(){},dispatchEvent(){}};;const sandbox={document,window,structuredClone,Image:class{complete=true;naturalWidth=400},location:{search:'?internal_qa=1'},URLSearchParams,URL,devicePixelRatio:1,matchMedia:()=>({matches:false}),requestAnimationFrame:()=>1,cancelAnimationFrame(){},ResizeObserver:class{observe(){}},localStorage:{getItem:()=>null,setItem(){}},crypto:{getRandomValues:a=>{a[0]=seed;return a;}},experience:()=>({mode:()=> 'discover',begin(){},configure(){},stop(){},sound(){},speak(){},preferences:()=>({}),audio:()=>({})}),Event:class{},engine:kind==='bridge-builder'?bridge:sentence,drawAlpine(){},sceneReady:()=>true,artReady:()=>true,drawArt(){}};vm.createContext(sandbox);const src=fs.readFileSync('spikes/adventure-shared/view.mjs','utf8').replace(/^import[^\n]+\n/gm,'').replaceAll('import.meta.url',JSON.stringify('https://qa.invalid/labs/'+kind+'/view.js')).replace('export function mountAdventure','function mountAdventure');vm.runInContext(src+String.fromCharCode(10)+'window.controller=mountAdventure('+JSON.stringify(kind)+',engine);',sandbox);created.find(n=>n.id==='chapter').value=chapter;return{api:window.controller,step:dt=>window.adventureTest.step(dt),nodes,get};}
const earned=Object.fromEntries([1,2,3,4,5,6].map(g=>[g,new Set()]));let rounds=0;for(const kind of['bridge-builder','sentence-detective'])for(let g=1;g<=6;g++)for(let seed=1;seed<=50;seed++){const{api,step}=controller(kind,g,Math.imul(seed,2654435761)>>>0);api.start();while(api.state().phase!=='ended'){const s=api.state();if(kind==='bridge-builder'){for(const id of bridge.solution(s.mission)){api.select(id);api.commit();}api.testBridge();}else{for(const v of s.mission.type==='order'?s.mission.words:[s.mission.answer]){const id=api.state().choices.find(c=>c.label===v&&!api.state().used.includes(c.id)).id;api.select(id);api.commit();}earned[g].add(s.mission.id);}assert.equal(api.state().phase,'celebrate');const before=api.state().animation;api.help();step(4);assert.equal(api.state().animation,before);api.resume();step(1.5);api.next();}assert.equal(api.state().completed,(kind==='bridge-builder'?bridge:sentence).PROFILES[g].goals);rounds++;}for(let g=1;g<=6;g++)assert.equal(earned[g].size,sentence.BANK[g].length,'Authored sentence excluded');console.log(JSON.stringify({contentCases:checks,completeControllerRounds:rounds,all72SentenceTasksEarned:true,bridgeMissionDiversity:diversity,alternateBridgeSolutions:true,helpFreezesCrossing:true}));

let storyRounds=0;const storyEarned=new Set();for(let g=1;g<=6;g++)for(let seed=1;seed<=20;seed++){const {api,step}=controller('sentence-detective',g,seed,'story');api.start();while(api.state().phase!=='ended'){const s=api.state();for(const value of s.mission.type==='order'?s.mission.words:[s.mission.answer]){const c=api.state().choices.find(c=>c.label===value&&!api.state().used.includes(c.id));assert(c);api.select(c.id);api.commit();}storyEarned.add(s.mission.id);assert.equal(api.state().phase,'celebrate');step(1.5);api.next();}storyRounds++;}assert.equal(storyEarned.size,17);console.log(JSON.stringify({connectedStoryRounds:storyRounds,all17StoryMessagesEarned:true}));

{const {api,step}=controller('bridge-builder',3,33);api.start();const mission=api.state().mission,plan=bridge.solution(mission);api.select(plan[0]);api.commit();api.testBridge();assert(api.state().previewTime>0);const before=api.state().previewTime;api.help();step(2);assert.equal(api.state().previewTime,before);api.resume();for(const id of bridge.solution(mission,mission.target-api.state().placed.reduce((n,p)=>n+p.value,0),mission.maxBlocks-api.state().placed.length)){api.select(id);api.commit();}api.hint();assert.equal(api.state().phase,'playing');api.testBridge();assert.equal(api.state().phase,'celebrate');assert.equal(api.state().previewTime,0);assert.equal(api.state().completed,1);step(1.5);api.next();assert.equal(api.state().previewTime,0);console.log('Incomplete test/pause/repair/full-length hint/final crossing regression passed');}

for(let g=1;g<=6;g++)for(let seed=1;seed<=40;seed++){const m=bridge.mission(g,bridge.rng(seed*811)),first=bridge.solution(m),signature=first.map(id=>m.choices.find(c=>c.id===id).value).sort((a,b)=>a-b).join(','),second=bridge.alternativeSolution(m,signature);assert(second);const next=second.map(id=>m.choices.find(c=>c.id===id).value);assert.equal(next.reduce((a,b)=>a+b,0),m.target);assert.notEqual(next.sort((a,b)=>a-b).join(','),signature);assert(second.length<=m.maxBlocks);}console.log('240 genuine alternative-plan hint paths passed');
