import{drawAlpine,sceneReady,drawCompanion}from'./theme.js';
export function mountAdventure(kind,engine){
 const $=id=>document.getElementById(id),canvas=$('scene'),ctx=canvas.getContext('2d'),bridge=kind==='bridge-builder';let w=900,h=320,last=0,random=engine.rng(Date.now()),s,epoch=0,previousPhase='ready',drag=null,raf=0;const avatar=new Image();avatar.src='/cleverli-wave.png';const celebrate=new Image();celebrate.src='/cleverli-celebrate.png';const touch=matchMedia('(pointer: coarse)').matches;const motion=!matchMedia('(prefers-reduced-motion: reduce)').matches;
 const safe=f=>{try{return f()}catch{return null}},goalCount=()=>engine.PROFILES[s.grade].goals;
 function clearDrag(){drag=null;}
 function newMission(){$('help-panel').hidden=true;epoch++;clearDrag();s.selected=null;s.prefix=[];s.placed=[];s.animation=0;s.phase='playing';s.mission=bridge?engine.mission(s.grade,random):engine.mission(s.grade,s.order[s.round]);s.choices=bridge?engine.shuffle(s.mission.choices,random):s.mission.type==='order'?engine.shuffle(s.mission.words.map((text,i)=>({id:i,label:text})),random):engine.shuffle(s.mission.choices.map((text,i)=>({id:i,label:text})),random);s.used=[];say(bridge?'Wähle einen Baustein und setze ihn auf die Brücke.':'Wähle ein Teil und setze es in die gelb markierte Lücke.');render();}
 function reset(){epoch++;clearDrag();const grade=Number($('grade').value);if(!engine.PROFILES[grade])throw Error('Invalid grade');s={grade,phase:'ready',round:0,completed:0,stars:0,active:0,animation:0,selected:null,placed:[],prefix:[],used:[],order:bridge?[]:engine.shuffle(engine.BANK[grade].map((_,i)=>i),random),mission:null};$('help-panel').hidden=false;$('work').hidden=true;render();}
 function start(){if(s.phase==='ready'){const seed=crypto.getRandomValues(new Uint32Array(1))[0];random=engine.rng(seed);if(!bridge)s.order=engine.shuffle(engine.BANK[s.grade].map((_,i)=>i),random);newMission();}else if(s.phase==='paused'){s.phase=previousPhase;$('help-panel').hidden=true;render();}}
 function help(){if(s.phase==='playing'||s.phase==='celebrate'){previousPhase=s.phase;s.phase='paused';epoch++;clearDrag();}$('help-panel').hidden=false;render();}
 function resume(){if(s.phase==='paused'){s.phase=previousPhase;$('help-panel').hidden=true;render();}}
 function say(t){$('status').textContent=t;}
 function select(id,stamp=epoch){if(stamp!==epoch||s.phase!=='playing')return;const c=s.choices.find(c=>c.id===id);if(!c||s.used.includes(id))return;s.selected=id;renderWork();$('target').focus({preventScroll:true});}
 function commit(stamp=epoch){if(stamp!==epoch||s.phase!=='playing'||s.selected===null)return;const c=s.choices.find(c=>c.id===s.selected);if(!c)return;clearDrag();if(bridge){const out=engine.add(s.mission,s.placed,c.id);if(out.outcome==='too-long'){say('Dieser Block ist zu lang. Deine Brücke bleibt. Wähle einen kürzeren.');return;}s.placed=out.placed;s.selected=null;epoch++;if(out.outcome==='bridge')win();else say('Gut gebaut! Es fehlen noch '+engine.format(s.mission.target-total(),s.grade)+'.');}else{const out=engine.select(s.mission,s.prefix,c.label);if(out.outcome==='try-again'){say('Das passt noch nicht in diese Lücke. Deine richtigen Teile bleiben.');return;}s.prefix=out.prefix;s.used.push(c.id);s.selected=null;epoch++;if(out.outcome==='message')win();else say('Das passt. Wähle jetzt das nächste Teil.');}render();}
 function total(){return s.placed.reduce((n,p)=>n+p.value,0);}
 function win(){s.completed++;s.stars+=10;s.phase='celebrate';s.animation=0;epoch++;s.selected=null;clearDrag();say(bridge?'Deine Brücke passt genau. Cleverli kann hinüber!':'Nachricht repariert! Du öffnest einen neuen Weg.');safe(()=>localStorage.setItem('cleverli_'+kind+'_private_v1:'+s.grade,String(Math.max(s.stars,Number(localStorage.getItem('cleverli_'+kind+'_private_v1:'+s.grade)||0)))));}
 function next(){if(s.phase!=='celebrate'||s.animation<1.4)return;if(s.completed>=goalCount()){s.phase='ended';epoch++;clearDrag();say('Abenteuer geschafft. Du hast '+s.completed+' Wege geöffnet.');render();return;}s.round++;newMission();}
 function undo(){if(s.phase!=='playing'||!bridge||!s.placed.length)return;s.placed.pop();s.selected=null;epoch++;clearDrag();say('Letzter Block zurückgelegt. Du kannst anders weiterbauen.');render();}
 function hint(){if(!s.mission||s.phase!=='playing')return;if(bridge){const left=s.mission.target-total(),c=[...s.mission.choices].sort((a,b)=>b.value-a.value).find(c=>c.value<=left);say('Tipp: '+c.label+' passt noch. Es gibt auch andere Wege.');}else say('Tipp: '+s.mission.hint);}
 function button(text,fn,cls=''){const b=document.createElement('button');b.type='button';b.textContent=text;b.className=cls;b.onclick=fn;return b;}
 function renderWork(){if(!s.mission)return;const m=s.mission,stamp=epoch;$('work').hidden=s.phase==='ready';$('question').textContent=bridge?'Baue genau '+engine.format(m.target,s.grade)+'.':m.prompt;$('picture').textContent=bridge?'🌉':m.picture;
 $('model').hidden=bridge?s.grade!==1:!engine.PROFILES[s.grade].model;$('model').textContent=bridge?'Zähle die Punkte: '+('●'.repeat(m.target)):engine.text?.(m)||'';
 $('rule').hidden=bridge||s.grade!==6;$('rule').textContent=bridge?'':'Regelhilfe: '+(m.before?.includes('«')||m.after?.includes('«')?'Begleitsatz : «Rede». Nutze das Schema für die Lücke.':'Zwei leicht erkennbare Teilsätze trennt hier ein Komma.');
 $('choices').replaceChildren();for(const c of s.choices){if(s.used.includes(c.id))continue;const b=button(c.label,()=>select(c.id,stamp),'choice'+(s.selected===c.id?' selected':''));b.dataset.choice=String(c.id);b.setAttribute('aria-pressed',String(s.selected===c.id));b.disabled=s.phase!=='playing';if(bridge&&s.grade===1){const dots=document.createElement('small');dots.textContent='●'.repeat(c.value);b.append(dots);}if(bridge&&s.grade>=5){const v=document.createElement('span');v.className='fraction-bar';v.style.setProperty('--portion',Math.min(100,c.value)+'%');v.setAttribute('aria-hidden','true');b.append(v);}b.draggable=!touch&&s.phase==='playing';b.ondragstart=e=>{if(s.phase!=='playing')return e.preventDefault();drag={id:c.id,stamp};e.dataTransfer.setData('text/plain',JSON.stringify(drag));};b.ondragend=clearDrag;$('choices').append(b);}
 const target=$('target');target.disabled=s.phase!=='playing';target.textContent=bridge?(s.selected===null?'Hier Baustein einsetzen':'+ '+s.choices.find(c=>c.id===s.selected)?.label+' einsetzen'):(s.selected===null?'Hier das nächste Teil einsetzen':s.choices.find(c=>c.id===s.selected)?.label+' einsetzen');target.onclick=()=>commit(stamp);target.ondragover=e=>{if(s.phase==='playing'&&drag?.stamp===epoch)e.preventDefault();};target.ondrop=e=>{e.preventDefault();if(drag?.stamp===epoch){const id=drag.id;s.selected=id;commit(epoch);}clearDrag();};
 const drop=el=>{el.onclick=()=>commit(stamp);el.ondragover=target.ondragover;el.ondrop=target.ondrop;};if(bridge){const frame=document.querySelector('.scene-frame');frame.setAttribute('role','button');frame.setAttribute('aria-label','Ausgewählten Baustein auf die Brücke setzen');frame.tabIndex=0;drop(frame);frame.onkeydown=e=>{if(!e.repeat&&(e.key==='Enter'||e.key===' ')){e.preventDefault();commit(stamp);}};}$('slots').replaceChildren();if(bridge){for(const p of s.placed){const span=document.createElement('span');span.className='accepted';span.textContent=p.label;$('slots').append(span);}if(!s.placed.length)$('slots').textContent='Deine Bausteine liegen hier.';}else if(m.type==='order'){m.words.forEach((_,i)=>{const span=i===s.prefix.length?button('___',()=>commit(stamp),'missing'):document.createElement('span');span.className=i<s.prefix.length?'accepted':i===s.prefix.length?'missing':'waiting';if(i===s.prefix.length){span.setAttribute('aria-label','Nächstes Wort in die gelbe Lücke setzen');drop(span);}span.textContent=s.prefix[i]||'___';$('slots').append(span);});}else{const before=document.createElement('span');before.textContent=m.before;const gap=s.prefix.length?document.createElement('span'):button('___',()=>commit(stamp),'missing');gap.className=s.prefix.length?'accepted':'missing';if(!s.prefix.length){gap.setAttribute('aria-label','Gelbe Lücke füllen');drop(gap);}gap.textContent=s.prefix[0]||'___';const after=document.createElement('span');after.textContent=m.after;$('slots').append(before,gap,after);}
 const caption=document.querySelector('.scene-caption strong');if(caption)caption.textContent=bridge?'Ziel '+engine.format(m.target,s.grade)+' · Fehlt '+engine.format(m.target-total(),s.grade):'Gesetzt '+s.prefix.length+' / '+(m.type==='order'?m.words.length:1);$('remaining').textContent=bridge?'Gebaut: '+engine.format(total(),s.grade)+' · Fehlt: '+engine.format(m.target-total(),s.grade):'Gesetzt: '+s.prefix.length+' / '+(m.type==='order'?m.words.length:1);$('undo').hidden=!bridge;$('undo').disabled=s.phase!=='playing'||!s.placed.length;
 }
 function arrangeScene(){const frame=document.querySelector('.scene-frame'),main=document.querySelector('main'),task=$('work');if(!frame?.parentElement||!task?.insertBefore)return;const compact=innerWidth<=740||innerHeight<=500,parent=compact&&s.phase!=='ready'?task:main;if(frame.parentElement!==parent)parent.insertBefore(frame,parent===task?$('choices'):task);document.body.dataset.compact=String(compact);}
 function render(){arrangeScene();document.body.dataset.phase=s.phase;$('grade').disabled=false;$('profile').textContent='Klasse '+s.grade+' · '+engine.LABELS[s.grade]+' · ohne Zeitdruck';$('count').textContent=s.completed+' / '+goalCount();$('stars').textContent=String(s.stars);$('pause').disabled=!['playing','celebrate'].includes(s.phase);$('start').hidden=s.phase!=='ready';$('start').textContent=s.phase==='paused'?'Weiter spielen':bridge?'Brücke bauen!':'Abenteuer starten!';$('resume').hidden=s.phase!=='paused';$('help-title').textContent=s.phase==='paused'?'Kurze Pause':'So spielst du';$('next').hidden=s.phase!=='celebrate';$('next').disabled=s.animation<1.4;$('next').textContent=s.completed>=goalCount()?'Abenteuer abschliessen':bridge?'Nächste Brücke':'Nächste Nachricht';$('again').hidden=s.phase!=='ended';$('work').hidden=s.phase==='ready';if(s.mission)renderWork();$('finish').hidden=s.phase!=='ended';$('finish').textContent='Geschafft: '+s.completed+' Wege geöffnet und '+s.stars+' Sterne gesammelt. Nur für diesen privaten Spieltest.';}
 function draw(){if(!w||!h)return;ctx.clearRect(0,0,w,h);drawAlpine(ctx,w,h);const base=h*.69,progress=(['celebrate','ended'].includes(s.phase)||(s.phase==='paused'&&previousPhase==='celebrate'))?Math.min(1,s.animation/1.4):0;
 if(bridge){const river=ctx.createLinearGradient(0,base-50,0,base+90);river.addColorStop(0,'#62c1dc');river.addColorStop(1,'#257b92');ctx.fillStyle=river;ctx.beginPath();ctx.moveTo(w*.45,h*.43);ctx.bezierCurveTo(w*.48,h*.49,w*.52,h*.5,w*.51,h*.59);ctx.bezierCurveTo(w*.48,h*.78,w*.36,h*.85,w*.19,h);ctx.lineTo(w*.79,h);ctx.bezierCurveTo(w*.66,h*.89,w*.67,h*.76,w*.60,h*.61);ctx.bezierCurveTo(w*.55,h*.5,w*.57,h*.47,w*.55,h*.43);ctx.closePath();ctx.strokeStyle='#dfd1a8';ctx.lineWidth=7;ctx.stroke();ctx.fill();ctx.save();ctx.clip();ctx.strokeStyle='#dcf8ff95';ctx.lineWidth=3;for(let i=0;i<4;i++){const yy=base-20+i*28;ctx.beginPath();ctx.moveTo(w*.36,yy);ctx.quadraticCurveTo(w*.50,yy+(motion?Math.sin(s.active+i)*5:0),w*.64,yy);ctx.stroke();}ctx.restore();const left=w*.26,length=w*.48;ctx.fillStyle='#68492e';ctx.fillRect(left-20,base-8,20,30);ctx.fillRect(left+length,base-8,20,30);let offset=0;for(const p of s.placed){const bw=length*p.value/s.mission.target;const wood=ctx.createLinearGradient(0,base-12,0,base+18);wood.addColorStop(0,'#e9c788');wood.addColorStop(1,'#b38347');ctx.fillStyle=wood;ctx.fillRect(left+offset+1,base-11,Math.max(1,bw-2),27);ctx.strokeStyle='#7c542d';ctx.strokeRect(left+offset+1,base-11,Math.max(1,bw-2),27);if(bw>30){ctx.fillStyle='#4b351f';ctx.font='700 13px system-ui';ctx.textAlign='center';ctx.fillText(engine.format(p.value,s.grade),left+offset+bw/2,base+8);}offset+=bw;}const x=left-35+progress*(length+70),y=base-35-(motion&&progress>0?Math.sin(progress*Math.PI*8)*9:0);drawCompanion(ctx,progress>.8?celebrate:avatar,x,y,Math.min(85,h*.32),'walk');}
 else{const station=s.phase==='ended'?2:Math.min(2,s.round),x=w*.65,y=base;ctx.save();ctx.translate(x,y);ctx.shadowColor='#143c2d33';ctx.shadowBlur=12;if(station===0){ctx.fillStyle='#946f47';ctx.fillRect(-55,-100,15,110);ctx.fillRect(42,-100,15,110);ctx.fillRect(-55,-104,112,16);ctx.save();ctx.translate(-38,0);ctx.rotate(-progress*.95);ctx.fillStyle='#c5a061';ctx.fillRect(0,-85,79,86);ctx.strokeStyle='#785329';for(let i=1;i<5;i++){ctx.beginPath();ctx.moveTo(i*16,-80);ctx.lineTo(i*16,-5);ctx.stroke();}ctx.fillStyle='#f9db71';ctx.beginPath();ctx.arc(63,-42,5,0,Math.PI*2);ctx.fill();ctx.restore();}else if(station===1){ctx.fillStyle='#f1d8a1';ctx.fillRect(-60,-30,120,12);for(let i=0;i<5;i++)ctx.fillRect(-55+i*25,-50-progress*40,9,70);ctx.font='58px system-ui';ctx.textAlign='center';ctx.fillText('🐇',progress*70,-35);}else{ctx.fillStyle='#9c6e35';ctx.fillRect(-57,-45,114,56);ctx.fillStyle='#debc70';ctx.fillRect(-62,-55-progress*30,124,18);ctx.fillStyle='#ffe89c';ctx.fillRect(-6,-43,12,27);if(progress){ctx.font='48px system-ui';ctx.textAlign='center';ctx.fillText('⭐',0,-68-progress*20);}}ctx.restore();drawCompanion(ctx,s.phase==='celebrate'?celebrate:avatar,w*.25+progress*w*.1,base-30,Math.min(85,h*.32),'walk');}
 if(s.phase==='ended'){ctx.fillStyle='#fff8ded9';ctx.beginPath();ctx.roundRect(w*.18,h*.17,w*.64,60,20);ctx.fill();ctx.font='850 '+Math.min(27,w/20)+'px system-ui';ctx.textAlign='center';ctx.fillStyle='#2c5734';ctx.fillText('Dein Abenteuer ist geschafft!',w*.5,h*.17+38);}
 }
 function update(dt){if(['playing','celebrate'].includes(s.phase))s.active+=dt;if(s.phase==='celebrate'){s.animation=Math.min(1.4,s.animation+dt);if(s.animation===1.4)$('next').disabled=false;}}
 function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,3);if(r.width<1||r.height<1)return;w=r.width;h=r.height;canvas.width=Math.round(w*d);canvas.height=Math.round(h*d);ctx.setTransform(d,0,0,d,0,0);draw();}
 function frame(t){const dt=Math.min(.05,(t-last)/1000||0);last=t;update(dt);draw();raf=requestAnimationFrame(frame);}
 $('grade').onchange=reset;$('start').onclick=start;$('resume').onclick=resume;$('help').onclick=help;$('pause').onclick=help;$('next').onclick=next;$('again').onclick=reset;$('undo').onclick=undo;$('hint').onclick=hint;
 window.addEventListener('keydown',e=>{if(document.activeElement?.tagName==='SELECT')return;if(e.repeat&&(e.key==='Enter'||e.key===' '||/^[1-9]$/.test(e.key))){e.preventDefault();return;}if(e.key==='Escape'){help();return;}const i=Number(e.key)-1;if(s.phase==='playing'&&Number.isInteger(i)&&i>=0&&i<s.choices.length){e.preventDefault();select(s.choices[i].id);}});window.addEventListener('blur',()=>{if(['playing','celebrate'].includes(s.phase))help();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&['playing','celebrate'].includes(s.phase))help();});window.addEventListener('pagehide',()=>cancelAnimationFrame(raf));let lastWidth=typeof innerWidth==='number'?innerWidth:900,lastCompact=typeof innerHeight==='number'?(lastWidth<=740||innerHeight<=500):false;window.addEventListener('resize',()=>{const compact=innerWidth<=740||innerHeight<=500;if(innerWidth!==lastWidth||compact!==lastCompact){lastWidth=innerWidth;lastCompact=compact;arrangeScene();}});new ResizeObserver(resize).observe(canvas);reset();resize();raf=requestAnimationFrame(frame);
 if(new URLSearchParams(location.search).has('internal_qa'))window.adventureTest={state:()=>structuredClone(s),sceneReady:()=>sceneReady(ctx)&&avatar.complete&&avatar.naturalWidth>0,step:dt=>{for(let left=dt;left>0;left-=.02)update(Math.min(left,.02));draw();},viewVersion:()=>epoch};
 return{reset,start,select,commit,next,help,resume,undo,hint,state:()=>structuredClone(s)};
}
