export const GRADE_LABELS=['','Buchstaben','Silben','Lautgruppen und Umlaute','Zusammengesetzte Wörter','Wörter verwandeln','Knifflige Schreibweisen'];
export const BANK={
1:[['EIS',['E','I','S'],'🍦'],['HUT',['H','U','T'],'👒'],['BUS',['B','U','S'],'🚌'],['OMA',['O','M','A'],'👵'],['ROT',['R','O','T'],'🔴'],['MAUS',['M','A','U','S'],'🐭']],
2:[['Blume',['Blu','me'],'🌷'],['Hase',['Ha','se'],'🐰'],['Sonne',['Son','ne'],'☀️'],['Lampe',['Lam','pe'],'💡'],['Wolke',['Wol','ke'],'☁️'],['Rose',['Ro','se'],'🌹']],
3:[['Bäume',['B','äu','m','e'],'🌳'],['Füsse',['F','ü','ss','e'],'👣'],['Schule',['Sch','u','l','e'],'🏫'],['spielen',['sp','ie','l','en'],'🎲'],['Freunde',['Fr','eu','n','de'],'🧑‍🤝‍🧑'],['Käfer',['K','ä','f','er'],'🐞']],
4:[['Regenschirm',['Regen','schirm'],'☂️'],['Sonnenblume',['Sonnen','blume'],'🌻'],['Fussball',['Fuss','ball'],'⚽'],['Haustür',['Haus','tür'],'🚪'],['Schneemann',['Schnee','mann'],'⛄'],['Zahnbürste',['Zahn','bürste'],'🪥']],
5:[['lesbar',['les','bar'],'📖'],['unlesbar',['un','les','bar'],'📖'],['freundlich',['freund','lich'],'😊'],['unfreundlich',['un','freund','lich'],'😠'],['glücklich',['glück','lich'],'🍀'],['unglücklich',['un','glück','lich'],'🌧️']],
6:[['Rhythmus',['Rh','y','th','mus'],'🥁'],['Schifffahrt',['Schiff','fahrt'],'🚢'],['Interesse',['Inter','esse'],'🔎'],['verlässlich',['ver','läss','lich'],'🤝'],['Adresse',['A','d','r','e','ss','e'],'📮'],['nämlich',['n','ä','m','lich'],'💬']]
};
export const PROFILES={1:{static:true,staged:true,visible:true,nextHint:true,seconds:0,goals:3,distractors:1},2:{static:true,staged:false,visible:true,nextHint:true,seconds:0,goals:4,distractors:1},3:{static:false,staged:false,visible:true,nextHint:true,seconds:120,goals:0,distractors:2},4:{static:false,staged:false,visible:false,nextHint:false,seconds:110,goals:0,distractors:3},5:{static:false,staged:false,visible:false,nextHint:false,seconds:100,goals:0,distractors:4},6:{static:false,staged:false,visible:false,nextHint:false,seconds:90,goals:0,distractors:3}};
export const CLUES={Regenschirm:'Baue ein Nomen: Regen + Schirm.',Sonnenblume:'Baue ein Nomen: Sonne + Blume.',Fussball:'Baue ein Nomen: Fuss + Ball.',Haustür:'Baue ein Nomen: Haus + Tür.',Schneemann:'Baue ein Nomen: Schnee + Mann.',Zahnbürste:'Baue ein Nomen: Zahn + Bürste.',lesbar:'Beschreibe eine Schrift, die man gut lesen kann. Wortfamilie: lesen.',unlesbar:'Bilde das Gegenteil von lesbar.',freundlich:'Eine Person ist nett und hilfsbereit. Wortfamilie: Freund.',unfreundlich:'Bilde das Gegenteil von freundlich.',glücklich:'Eine Person freut sich sehr. Wortfamilie: Glück.',unglücklich:'Bilde das Gegenteil von glücklich.',Rhythmus:'Wie heisst ein regelmässiger Takt?',Schifffahrt:'Verbinde Schiff und Fahrt zu einem Nomen. Achte auf die Mitte.',Interesse:'Bilde das Nomen zu sich interessieren.',verlässlich:'Auf diese Person kannst du dich verlassen. Wortfamilie: verlassen.',Adresse:'Wie heisst eine Anschrift? Das Nomen beginnt mit A.',nämlich:'Ein Wort mit n bedeutet: und zwar. Achte auf den Umlaut.'};
const NEAR={Rhythmus:['Rhi','i','tt'],Schifffahrt:['Schiffart','Fahrt','farht'],Interesse:['Intresse','ese','eesse'],verlässlich:['läs','lig','ves'],Adresse:['dd','s','At'],nämlich:['e','nem','lih']};
export function rng(seed=1){let n=seed>>>0;return()=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n/4294967296;};}
export function mission(grade,round){if(!Number.isInteger(grade)||grade<1||grade>6)throw Error('Invalid grade');const row=BANK[grade][round%BANK[grade].length];return{grade,word:row[0],parts:[...row[1]],picture:row[2],clue:CLUES[row[0]]||row[0]};}
export function tilesFor(m,r=Math.random,index=0){const p=PROFILES[m.grade];const candidates=[...new Set([...(NEAR[m.word]||[]),...BANK[m.grade].flatMap(row=>row[1])])].filter(x=>!m.parts.includes(x));const bad=candidates.slice(0,p.distractors);const parts=p.staged?[m.parts[index]]:m.parts;const data=[...parts,...bad].map((text,id)=>({id,text,collected:false}));for(let i=data.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[data[i],data[j]]=[data[j],data[i]];}return data.map((t,i)=>({...t,x:p.staged?[.32,.7][i]:[.22,.51,.8][i%3],y:p.staged?.53:[.4,.6,.8][Math.floor(i/3)],phase:r()*6.28}));}
export function collect(m,index,tile){if(tile.collected)return{index,outcome:'already'};if(tile.text!==m.parts[index])return{index,outcome:'wrong'};return{index:index+1,outcome:index+1===m.parts.length?'word':'part'};}
export function wordComplete(m,index){return index===m.parts.length;}
