export const GRADE_LABELS=['','Buchstaben','Silben','Lautgruppen und Umlaute','Zusammengesetzte Wörter','Wörter verwandeln','Stammregel und Alltagswörter'];
export const BANK={
1:[['OMA',['O','M','A'],'👵'],['HUT',['H','U','T'],'👒'],['BUS',['B','U','S'],'🚌'],['OPA',['O','P','A'],'👴'],['ROT',['R','O','T'],'🔴'],['MAMA',['M','A','M','A'],'👩']],
2:[['Blume',['Blu','me'],'🌷'],['Hase',['Ha','se'],'🐰'],['Sonne',['Son','ne'],'☀️'],['Lampe',['Lam','pe'],'💡'],['Wolke',['Wol','ke'],'☁️'],['Rose',['Ro','se'],'🌹']],
3:[['Bäume',['B','äu','m','e'],'🌳'],['Füsse',['F','ü','ss','e'],'👣'],['Schule',['Sch','u','l','e'],'🏫'],['spielen',['sp','ie','l','en'],'🎲'],['Freunde',['Fr','eu','n','de'],'🧑‍🤝‍🧑'],['Käfer',['K','ä','f','er'],'🐞']],
4:[['Regenschirm',['Regen','schirm'],'☂️'],['Sonnenblume',['Sonnen','blume'],'🌻'],['Fussball',['Fuss','ball'],'⚽'],['Haustür',['Haus','tür'],'🚪'],['Schneemann',['Schnee','mann'],'⛄'],['Zahnbürste',['Zahn','bürste'],'🪥']],
5:[['lesbar',['les','bar'],'📖'],['unlesbar',['un','les','bar'],'📖'],['freundlich',['freund','lich'],'😊'],['unfreundlich',['un','freund','lich'],'😠'],['glücklich',['glück','lich'],'🍀'],['unglücklich',['un','glück','lich'],'🌧️']],
6:[['Häuser',['Häus','er'],'🏠'],['Bäume',['Bäum','e'],'🌳'],['fahren',['fahr','en'],'🚲'],['Freundschaft',['Freund','schaft'],'🤝'],['Schlüssel',['Schlüss','el'],'🔑'],['Wasser',['Wass','er'],'💧']]
};
export const PROFILES={1:{static:true,staged:true,visible:true,nextHint:true,seconds:0,goals:2,distractors:1},2:{static:true,staged:false,visible:true,nextHint:true,seconds:0,goals:3,distractors:1},3:{static:true,staged:false,visible:true,nextHint:true,seconds:0,goals:4,distractors:1},4:{static:true,staged:false,visible:false,nextHint:false,seconds:0,goals:4,distractors:1},5:{static:true,staged:false,visible:false,nextHint:false,seconds:0,goals:4,distractors:1},6:{static:true,staged:false,visible:false,nextHint:false,seconds:0,goals:4,distractors:2}};
export const CLUES={Regenschirm:'Baue ein Nomen: Regen + Schirm.',Sonnenblume:'Baue ein Nomen: Sonne + Blume.',Fussball:'Baue ein Nomen: Fuss + Ball.',Haustür:'Baue ein Nomen: Haus + Tür.',Schneemann:'Baue ein Nomen: Schnee + Mann.',Zahnbürste:'Baue ein Nomen: Zahn + Bürste.',lesbar:'Beschreibe eine Schrift, die man gut lesen kann. Wortfamilie: lesen.',unlesbar:'Bilde das Gegenteil von lesbar.',freundlich:'Eine Person ist nett und hilfsbereit. Wortfamilie: Freund.',unfreundlich:'Bilde das Gegenteil von freundlich.',glücklich:'Eine Person freut sich sehr. Wortfamilie: Glück.',unglücklich:'Bilde das Gegenteil von glücklich.',Häuser:'Mehrzahl von Haus. Stammregel: Hier wird a zu ä.',Bäume:'Mehrzahl von Baum. Stammregel: Hier wird au zu äu.',fahren:'Bilde das Verb zum Stamm fahr. Verben enden hier auf en.',Freundschaft:'Bilde ein Nomen aus Freund und schaft. Nomen beginnen gross.',Schlüssel:'Öffnet eine Tür. Doppelkonsonantenregel: Nach kurzem ü wird der s-Laut hier doppelt geschrieben.',Wasser:'Das trinkst du. Doppelkonsonantenregel: Nach kurzem a wird der s-Laut hier doppelt geschrieben.'};
const NEAR={};
export function rng(seed=1){let n=seed>>>0;return()=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n/4294967296;};}
export function mission(grade,round){if(!Number.isInteger(grade)||grade<1||grade>6)throw Error('Invalid grade');const row=BANK[grade][round%BANK[grade].length];return{grade,word:row[0],parts:[...row[1]],picture:row[2],clue:CLUES[row[0]]||row[0]};}
export function tilesFor(m,r=Math.random,index=0){const p=PROFILES[m.grade];const candidates=[...new Set([...(NEAR[m.word]||[]),...BANK[m.grade].flatMap(row=>row[1])])].filter(x=>!m.parts.includes(x));const bad=candidates.slice(0,p.distractors);const parts=p.staged?[m.parts[index]]:m.parts;const data=[...parts,...bad].map((text,id)=>({id,text,collected:false}));for(let i=data.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[data[i],data[j]]=[data[j],data[i]];}return data.map((t,i)=>({...t,x:p.staged?[.32,.7][i]:[.22,.51,.8][i%3],y:p.staged?.53:[.4,.6,.8][Math.floor(i/3)],phase:r()*6.28}));}
export function collect(m,index,tile){if(tile.collected)return{index,outcome:'already'};if(tile.text!==m.parts[index])return{index,outcome:'wrong'};return{index:index+1,outcome:index+1===m.parts.length?'word':'part'};}
export function wordComplete(m,index){return index===m.parts.length;}
