export const GRADE_LABELS=['','Buchstaben','Silben','Lautgruppen und Umlaute','Zusammengesetzte Wörter','Wörter verwandeln','Wortbausteine'];
export const BANK={
1:[['OMA',['O','M','A'],'👵'],['HUT',['H','U','T'],'👒'],['BUS',['B','U','S'],'🚌'],['OPA',['O','P','A'],'👴'],['ROT',['R','O','T'],'🔴'],['MAMA',['M','A','M','A'],'👩']],
2:[['Blume',['Blu','me'],'🌷'],['Hase',['Ha','se'],'🐰'],['Sonne',['Son','ne'],'☀️'],['Lampe',['Lam','pe'],'💡'],['Wolke',['Wol','ke'],'☁️'],['Rose',['Ro','se'],'🌹']],
3:[['Bäume',['B','äu','m','e'],'🌳'],['Füsse',['F','ü','ss','e'],'👣'],['Schule',['Sch','u','l','e'],'🏫'],['spielen',['sp','ie','l','en'],'🎲'],['Freunde',['Fr','eu','n','de'],'🧑‍🤝‍🧑'],['Käfer',['K','ä','f','er'],'🐞']],
4:[['Regenschirm',['Regen','schirm'],'☂️'],['Sonnenblume',['Sonnen','blume'],'🌻'],['Fussball',['Fuss','ball'],'⚽'],['Haustür',['Haus','tür'],'🚪'],['Schneemann',['Schnee','mann'],'⛄'],['Zahnbürste',['Zahn','bürste'],'🪥']],
5:[['lesbar',['les','bar'],'📖'],['unlesbar',['un','les','bar'],'📖'],['freundlich',['freund','lich'],'😊'],['unfreundlich',['un','freund','lich'],'😠'],['glücklich',['glück','lich'],'🍀'],['unglücklich',['un','glück','lich'],'🌧️']],
6:[['Häuser',['Häus','er'],'🏠'],['Bäume',['Bäum','e'],'🌳'],['fahren',['fahr','en'],'🚲'],['Freundschaft',['Freund','schaft'],'🤝'],['Schlüssel',['Schlüss','el'],'🔑'],['Wasser',['Wass','er'],'💧']]
};
export const PROFILES={1:{static:true,staged:true,visible:true,nextHint:true,seconds:0,goals:2,distractors:2},2:{static:true,staged:true,visible:true,nextHint:true,seconds:0,goals:3,distractors:2},3:{static:true,staged:true,visible:true,nextHint:true,seconds:0,goals:4,distractors:2},4:{static:true,staged:true,visible:false,nextHint:false,seconds:0,goals:4,distractors:2},5:{static:true,staged:true,visible:false,nextHint:false,seconds:0,goals:4,distractors:2},6:{static:true,staged:true,visible:false,nextHint:false,seconds:0,goals:4,distractors:2}};
export const CLUES={Regenschirm:'Baue ein Nomen: Regen + Schirm.',Sonnenblume:'Baue ein Nomen: Sonne + Blume.',Fussball:'Baue ein Nomen: Fuss + Ball.',Haustür:'Baue ein Nomen: Haus + Tür.',Schneemann:'Baue ein Nomen: Schnee + Mann.',Zahnbürste:'Baue ein Nomen: Zahn + Bürste.',lesbar:'Beschreibe eine Schrift, die man gut lesen kann. Wortfamilie: lesen.',unlesbar:'Bilde das Gegenteil von lesbar.',freundlich:'Eine Person ist nett und hilfsbereit. Wortfamilie: Freund.',unfreundlich:'Bilde das Gegenteil von freundlich.',glücklich:'Eine Person freut sich sehr. Wortfamilie: Glück.',unglücklich:'Bilde das Gegenteil von glücklich.',Häuser:'Mehrzahl von Haus. Stammregel: Hier wird a zu ä.',Bäume:'Mehrzahl von Baum. Stammregel: Hier wird au zu äu.',fahren:'Bilde das Verb zum Stamm fahr. Verben enden hier auf en.',Freundschaft:'Bilde ein Nomen aus Freund und schaft. Nomen beginnen gross.',Schlüssel:'Öffnet eine Tür. Doppelkonsonantenregel: Nach kurzem ü wird der s-Laut hier doppelt geschrieben.',Wasser:'Das trinkst du. Doppelkonsonantenregel: Nach kurzem a wird der s-Laut hier doppelt geschrieben.'};
const EXTRA={1:['E','N','I','L','F','D','K','V'],2:['Ti','ger','Au','to','Ba','na','ne','Fe','der'],3:['S','a','o','t','ch','st','au','Ei','ck','tz'],4:['Baum','haus','Kinder','zimmer','Spiel','platz'],5:['helf','voll','los','spiel','fahr','ung'],6:['Haus','Baum','Hund','Kind','lich','chen','ung','ss']};
export function rng(seed=1){let n=seed>>>0;return()=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n/4294967296;};}
export function wordOrder(grade,r=Math.random){if(!Number.isInteger(grade)||!BANK[grade])throw Error('Invalid grade');const order=BANK[grade].map((_,i)=>i);for(let i=order.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[order[i],order[j]]=[order[j],order[i]];}if(grade===6&&!order.slice(0,PROFILES[6].goals).some(i=>i>=4)){[order[3],order[4]]=[order[4],order[3]];}return order;}
export function mission(grade,round){if(!Number.isInteger(grade)||grade<1||grade>6)throw Error('Invalid grade');const row=BANK[grade][round%BANK[grade].length];return{grade,word:row[0],parts:[...row[1]],picture:row[2],clue:CLUES[row[0]]||row[0]};}
export function tilesFor(m,r=Math.random,index=0,history=[]){if(index<0||index>=m.parts.length)throw Error('Invalid word step');const norm=x=>x.normalize('NFC').toLowerCase(),needed=m.parts[index],blocked=new Set(history.map(norm)),unique=new Map();for(const x of[...BANK[m.grade].flatMap(row=>row[1]),...EXTRA[m.grade]])if(!unique.has(norm(x)))unique.set(norm(x),x);const pool=[...unique.values()].filter(x=>!m.parts.some(p=>norm(p)===norm(x))&&!norm(m.word).includes(norm(x)));const fresh=pool.filter(x=>!blocked.has(norm(x)));for(let i=fresh.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[fresh[i],fresh[j]]=[fresh[j],fresh[i]];}if(fresh.length<2)throw Error('Insufficient fresh distractors');const data=[needed,...fresh.slice(0,2)].map((text,i)=>({id:m.word+'|'+index+'|'+i,text,collected:false}));for(let i=data.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[data[i],data[j]]=[data[j],data[i]];}return data.map((t,i)=>({...t,x:[.22,.51,.8][i],y:.53,phase:r()*6.28}));}
export function collect(m,index,tile){if(tile.collected)return{index,outcome:'already'};if(tile.text!==m.parts[index])return{index,outcome:'wrong'};return{index:index+1,outcome:index+1===m.parts.length?'word':'part'};}
export function wordComplete(m,index){return index===m.parts.length;}
