import {drawAlpine,drawToken,drawCelebration,sceneReady,drawCompanion} from '/labs/word-magnet/theme.js';
import {GRADE_LABELS,rng,mission,tilesFor,collect,PROFILES} from '/labs/word-magnet/engine.js';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),touch=matchMedia('(pointer: coarse)').matches,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let w=900,h=390,last=0,raf=0,grade=1,slow=true,s,tiles=[],sparks=[],random=rng(Date.now()),toast=0,wrongUntil=0;const held=new Set(),avatar=new Image();avatar.src='/cleverli-wave.png';
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function bestKey(){return'cleverli_word_magnet_prototype_v2:'+grade+':'+(slow?'slow':'normal');}function best(){try{return Number(localStorage.getItem(bestKey()))||0}catch{return 0}}
function newWord(){s.mission=mission(grade,s.round);s.index=0;s.x=.1;s.y=.88;s.tx=s.x;s.ty=s.y;s.userMoved=false;tiles=tilesFor(s.mission,random);wrongUntil=0;slots();}
function reset(){held.clear();s={phase:'ready',grade,round:0,words:0,stars:0,index:0,elapsed:0,mistakes:0,hints:0,cooldown:0,x:.1,y:.88,tx:.1,ty:.88};newWord();hud();guide();}
function slots(){const host=$('slots');host.replaceChildren();s.mission.parts.forEach((text,i)=>{const span=document.createElement('span');span.className='slot'+(i<s.index?' done':i===s.index?' current':'');span.textContent=(PROFILES[grade].visible||i<s.index)?text:'?';host.append(span);});$('target').textContent=PROFILES[grade].visible?s.mission.word:s.mission.clue;$('picture').textContent=s.mission.picture;}
function hud(){document.body?.setAttribute('data-phase',s.phase);document.body?.setAttribute('data-grade',String(grade));$('energy').textContent=s.words+' '+(s.words===1?'Wort':'Wörter');$('remaining').textContent=s.mission.parts.length-s.index+' Teile fehlen';$('fill').style.width=s.index/s.mission.parts.length*100+'%';$('stars').textContent=s.stars+' ★';$('combo').textContent='Wörter: '+s.words;$('mode').textContent=GRADE_LABELS[grade];$('word-label').textContent=PROFILES[grade].visible?'Dein Zielwort':'Deine Wortaufgabe';$('profile-note').textContent=PROFILES[grade].visible?'Klasse '+grade+': '+GRADE_LABELS[grade]+'. '+(PROFILES[grade].seconds?'':'Ohne Zeitdruck, '+PROFILES[grade].goals+' Wörter.'):'Klasse '+grade+': Lies die Wortaufgabe. Das Lösungswort und der nächste Teil bleiben verborgen. 💡 hilft bei Bedarf.';$('need').textContent=s.cooldown>0?'Wort geschafft!':(PROFILES[grade].nextHint?'Fange '+(s.mission.parts[s.index]||''):'Finde den nächsten Wortteil');const left=Math.max(0,Math.ceil(PROFILES[grade].seconds-s.elapsed));$('time').textContent=PROFILES[grade].seconds?Math.floor(left/60)+':'+String(left%60).padStart(2,'0'):s.words+'/'+PROFILES[grade].goals;$('distance').textContent='';$('grade').disabled=['playing','paused'].includes(s.phase);$('slow').disabled=['playing','paused'].includes(s.phase);$('pause').disabled=s.phase!=='playing';$('hint').hidden=grade<=3;$('hint').disabled=s.phase!=='playing'||s.cooldown>0;}
function guide(){const demo=grade<=3?s.mission:mission(1,0);$('demo-goal').textContent=demo.word;const row=$('demo-parts');row.replaceChildren();demo.parts.forEach((part,i)=>{if(i){const arrow=document.createElement('b');arrow.textContent='→';row.append(arrow)}const chip=document.createElement('span');chip.textContent=part;row.append(chip)});$('control-tip').textContent=touch?'Ziehe den Magneten mit dem Finger.':'Pfeiltasten bewegen ihn. Oder klicke ins Spiel.';}
function say(text){$('status').textContent=text;toast=3.5;}
function flash(x,y){if(reduced)return;for(let i=0;i<18;i++)sparks.push({x,y,vx:(random()-.5)*.2,vy:(random()-.5)*.3,t:1+random()});}
function update(dt){if(s.phase!=='playing')return;s.elapsed+=dt;if(PROFILES[grade].seconds&&s.elapsed>=PROFILES[grade].seconds){s.elapsed=PROFILES[grade].seconds;finish();return;}if(PROFILES[grade].goals&&s.words>=PROFILES[grade].goals&&s.cooldown===0){finish();return;}if(held.size){s.userMoved=true;const dx=(held.has('right')?1:0)-(held.has('left')?1:0),dy=(held.has('down')?1:0)-(held.has('up')?1:0),d=Math.hypot(dx,dy)||1;const speed=slow?.44:.68;s.tx=clamp(s.tx+dx/d*dt*speed,.08,.92);s.ty=clamp(s.ty+dy/d*dt*speed,.23,.88);}s.x+=(s.tx-s.x)*Math.min(1,dt*11);s.y+=(s.ty-s.y)*Math.min(1,dt*11);
 if(s.cooldown>0){s.cooldown=Math.max(0,s.cooldown-dt);if(s.cooldown===0){s.round++;newWord();say(PROFILES[grade].visible?'Nächstes Wort: '+s.mission.word:'Nächste Wortaufgabe bereit.');}hud();return;}
 for(const t of tiles){t.px=t.x+((reduced||PROFILES[grade].static)?0:Math.sin(s.elapsed*(slow?.6:1.1)+t.phase)*.014);t.py=t.y+((reduced||PROFILES[grade].static)?0:Math.cos(s.elapsed*.7+t.phase)*.012);}
 if(!s.userMoved){hud();return;}const near=tiles.filter(t=>!t.collected&&Math.abs(s.x-t.px)*w<=tileWidth(t)/2+9&&Math.abs(s.y-t.py)*h<=tileHeight()/2+9).sort((a,b)=>Math.hypot(s.x-a.px,s.y-a.py)-Math.hypot(s.x-b.px,s.y-b.py));const wanted=grade<=3?near.find(t=>t.text===s.mission.parts[s.index]):near[0]?.text===s.mission.parts[s.index]?near[0]:null;if(wanted){const result=collect(s.mission,s.index,wanted);wanted.collected=true;s.index=result.index;flash(s.x,s.y);slots();if(result.outcome==='word'){s.words++;const reward=grade<=3?10:Math.max(4,15-Math.min(8,s.mistakes)-Math.min(3,s.hints));s.stars+=reward;s.cooldown=1.25;say(s.mission.word+' geschafft! +'+reward+' Sterne');}else say(PROFILES[grade].nextHint?'Super! Jetzt fehlt '+s.mission.parts[s.index]+'.':'Wortteil gesammelt. Überlege den nächsten Teil.');if(PROFILES[grade].staged&&s.index<s.mission.parts.length){tiles=tilesFor(s.mission,random,s.index);const next=tiles.find(t=>t.text===s.mission.parts[s.index]);if(Math.abs(next.x-s.x)<.16){for(const t of tiles)t.x=t.x===.32?.7:.32;}}}else if(near.length&&s.elapsed>=wrongUntil){wrongUntil=s.elapsed+1.2;s.mistakes++;say(PROFILES[grade].nextHint?'Dieses Teil ist noch nicht dran. Suche '+s.mission.parts[s.index]+'.':'Dieses Teil passt noch nicht. Dein bisheriges Wort bleibt.');}
 for(const p of sparks){p.x+=p.vx*dt;p.y+=p.vy*dt;p.t-=dt;}sparks=sparks.filter(p=>p.t>0);toast=Math.max(0,toast-dt);if(!toast)$('status').textContent=PROFILES[grade].nextHint?'Suche das gelb markierte Teil. Dein Wort bleibt erhalten.':'Lies die Aufgabe und ordne die Wortteile. 💡 gibt einen Tipp.';hud();}
function tileWidth(t){if(grade===1)return 62;return Math.max(40,t.text.length*(w<600?8:10)+16);}function tileHeight(){if(grade===1)return Math.min(56,h*.2);return Math.min(w<600?38:44,h*.14);}
function draw(){drawAlpine(ctx,w,h,0);
 for(const t of tiles){if(t.collected)continue;const x=(t.px??t.x)*w,y=(t.py??t.y)*h,bw=tileWidth(t),bh=tileHeight();drawToken(ctx,x,y,bw,bh,'word');ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='800 '+(h<250?15:w<600?17:20)+'px system-ui';ctx.fillStyle='#3d2d41';ctx.fillText(t.text,x,y);}
 const x=s.x*w,y=s.y*h,size=Math.min(62,h*.30);drawCompanion(ctx,avatar,x,y,size,'magnet');for(const p of sparks){ctx.fillStyle='#f8d68c';ctx.globalAlpha=Math.min(1,p.t);ctx.beginPath();ctx.arc(p.x*w,p.y*h,3,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;if(s.cooldown>0){drawCelebration(ctx,w,h,'Wort geschafft!');}}
function show(title,text,button,help=false){$('guide').hidden=!(s.phase==='ready'||help);document.body?.setAttribute('data-guide',String(s.phase==='ready'||help));$('overlay-title').textContent=title;$('overlay-text').textContent=text;$('start').textContent=button;$('badge').textContent='🧲';$('overlay').hidden=false;$('overlay').scrollTop=0;if(s.phase==='ready'||help)canvas.style.height='';$('best').textContent='Dein Testrekord: '+best()+' Sterne · Nur auf diesem Gerät';guide();}
function frameArea(){if(touch||w<740)requestAnimationFrame(()=>{const goal=document.querySelector('.word-goal'),controls=document.querySelector('.instructions');const before=canvas.getBoundingClientRect().top-goal.getBoundingClientRect().top,after=controls.getBoundingClientRect().bottom-canvas.getBoundingClientRect().bottom;const space=innerHeight-before-after-12;canvas.style.height=Math.max(145,Math.min(360,space))+'px';goal.scrollIntoView({block:'start',behavior:'auto'});});}
function start(){random=rng(crypto.getRandomValues(new Uint32Array(1))[0]);reset();s.phase='playing';$('overlay').hidden=true;document.body?.setAttribute('data-guide','false');$('again').hidden=true;say(PROFILES[grade].nextHint?'Los geht’s! Fange '+s.mission.parts[0]+'.':'Lies die Aufgabe und baue das passende Wort.');hud();canvas.focus({preventScroll:true});frameArea();}
function pause(){if(s.phase!=='playing')return;held.clear();s.phase='paused';show('Kurze Sammelpause','Dein Wort und die Spielzeit bleiben genau so stehen.','Weitersammeln');$('again').hidden=false;hud();}function resume(){s.phase='playing';$('overlay').hidden=true;document.body?.setAttribute('data-guide','false');$('again').hidden=true;hud();canvas.focus({preventScroll:true});frameArea();}
function finish(){held.clear();s.phase='ended';const record=best();if(s.stars>record)try{localStorage.setItem(bestKey(),String(s.stars))}catch{}show('Dein Wörterwald ist gewachsen!',s.words+' Wörter und '+s.stars+' Sterne gesammelt. '+(s.stars>record?'Neuer persönlicher Testrekord!':'Jedes Wort zählt.'),'Noch einmal sammeln');$('again').hidden=false;hud();}
$('hint').onclick=()=>{if(s.phase!=='playing'||s.cooldown>0)return;s.hints++;say('Tipp: Als Nächstes passt '+s.mission.parts[s.index]+'.');};
$('start').onclick=()=>s.phase==='paused'?resume():start();$('pause').onclick=pause;$('help').onclick=()=>{if(s.phase==='playing')pause();show('So sammelst du','',s.phase==='paused'?'Weitersammeln':'Losspielen!',true)};$('again').onclick=()=>{reset();show('So sammelst du','','Losspielen!');$('again').hidden=true};$('grade').onchange=()=>{grade=Number($('grade').value);reset();show('So sammelst du','','Losspielen!')};$('slow').onclick=()=>{slow=!slow;$('slow').setAttribute('aria-pressed',String(slow));$('slow').textContent=slow?'Gemütlich ✓':'Normal ⚡'};
function point(e){s.userMoved=true;const b=canvas.getBoundingClientRect();s.tx=clamp((e.clientX-b.left)/b.width,.08,.92);s.ty=clamp((e.clientY-b.top)/b.height,.23,.88);}canvas.addEventListener('pointerdown',e=>{if(s.phase!=='playing')return;point(e);canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(s.phase==='playing'&&(e.buttons||canvas.hasPointerCapture?.(e.pointerId)))point(e)});
const dirs={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down',a:'left',d:'right',w:'up',s:'down'};function nudge(dir){s.userMoved=true;s.tx=clamp(s.tx+(dir==='left'?-.08:dir==='right'?.08:0),.08,.92);s.ty=clamp(s.ty+(dir==='up'?-.08:dir==='down'?.08:0),.23,.88);}
for(const b of document.querySelectorAll('[data-dir]')){b.onpointerdown=()=>{if(s.phase==='playing')held.add(b.dataset.dir)};b.onpointerup=b.onpointercancel=()=>held.delete(b.dataset.dir);b.onclick=()=>{if(s.phase==='playing')nudge(b.dataset.dir)}}
window.addEventListener('pointerup',()=>held.clear());window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;const dir=dirs[e.key];if(dir&&s.phase==='playing'){e.preventDefault();held.add(dir);if(!e.repeat)nudge(dir)}if(e.key==='Escape'&&s.phase==='playing')pause()});window.addEventListener('keyup',e=>held.delete(dirs[e.key]));window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});
function resize(){const b=canvas.getBoundingClientRect();w=b.width;h=b.height;const d=Math.min(3,devicePixelRatio||1);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0)}new ResizeObserver(resize).observe(canvas);window.addEventListener('resize',()=>{if(s.phase==='playing')frameArea();});function frame(now){const dt=last?Math.min(.05,(now-last)/1000):0;last=now;update(dt);draw();raf=requestAnimationFrame(frame)}window.addEventListener('pagehide',()=>cancelAnimationFrame(raf));reset();resize();raf=requestAnimationFrame(frame);
if(new URLSearchParams(location.search).get('internal_qa')==='1')window.wordMagnetTest={state:()=>structuredClone(s),tiles:()=>structuredClone(tiles),sceneReady:()=>sceneReady(ctx),step:seconds=>{for(let t=0;t<seconds;t+=.02)update(Math.min(.02,seconds-t))}};
