import {BANK,GRADE_LABELS,rng,mission,tilesFor,collect} from '/labs/word-magnet/engine.js';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),touch=matchMedia('(pointer: coarse)').matches,reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;let w=900,h=390,last=0,raf=0,grade=1,slow=true,s,tiles=[],sparks=[],random=rng(Date.now()),toast=0,wrongUntil=0;const held=new Set(),avatar=new Image();avatar.src='/murmeli-icon-v3-192.png';
const clamp=(x,a,b)=>Math.max(a,Math.min(b,x));
function bestKey(){return'cleverli_word_magnet_prototype_v1:'+grade+':'+(slow?'slow':'normal');}function best(){try{return Number(localStorage.getItem(bestKey()))||0}catch{return 0}}
function newWord(){s.mission=mission(grade,s.round);s.index=0;s.x=.1;s.y=.88;s.tx=s.x;s.ty=s.y;tiles=tilesFor(s.mission,random);wrongUntil=0;slots();}
function reset(){held.clear();s={phase:'ready',grade,round:0,words:0,stars:0,index:0,elapsed:0,cooldown:0,x:.1,y:.88,tx:.1,ty:.88};newWord();hud();guide();}
function slots(){const host=$('slots');host.replaceChildren();s.mission.parts.forEach((text,i)=>{const span=document.createElement('span');span.className='slot'+(i<s.index?' done':i===s.index?' current':'');span.textContent=text;host.append(span);});$('target').textContent=s.mission.word;$('picture').textContent=s.mission.picture;}
function hud(){document.body?.setAttribute('data-phase',s.phase);$('energy').textContent=s.words+' '+(s.words===1?'Wort':'Wörter');$('remaining').textContent=s.mission.parts.length-s.index+' Teile fehlen';$('fill').style.width=s.index/s.mission.parts.length*100+'%';$('stars').textContent=s.stars+' ★';$('combo').textContent='Wörter: '+s.words;$('mode').textContent=GRADE_LABELS[grade];$('need').textContent=s.cooldown>0?'Wort geschafft!':'Fange '+(s.mission.parts[s.index]||'');const left=Math.max(0,Math.ceil(90-s.elapsed));$('time').textContent=Math.floor(left/60)+':'+String(left%60).padStart(2,'0');$('distance').textContent='';$('grade').disabled=['playing','paused'].includes(s.phase);$('slow').disabled=['playing','paused'].includes(s.phase);$('pause').disabled=s.phase!=='playing';}
function guide(){$('demo-goal').textContent=s.mission.word;const row=$('demo-parts');row.replaceChildren();s.mission.parts.forEach((part,i)=>{if(i){const arrow=document.createElement('b');arrow.textContent='→';row.append(arrow)}const chip=document.createElement('span');chip.textContent=part;row.append(chip)});$('control-tip').textContent=touch?'Ziehe den Magneten mit dem Finger.':'Pfeiltasten bewegen ihn. Oder klicke ins Spiel.';}
function say(text){$('status').textContent=text;toast=3.5;}
function flash(x,y){if(reduced)return;for(let i=0;i<18;i++)sparks.push({x,y,vx:(random()-.5)*.2,vy:(random()-.5)*.3,t:1+random()});}
function update(dt){if(s.phase!=='playing')return;s.elapsed=Math.min(90,s.elapsed+dt);if(s.elapsed===90){finish();return;}if(held.size){const dx=(held.has('right')?1:0)-(held.has('left')?1:0),dy=(held.has('down')?1:0)-(held.has('up')?1:0),d=Math.hypot(dx,dy)||1;const speed=slow?.44:.68;s.tx=clamp(s.tx+dx/d*dt*speed,.08,.92);s.ty=clamp(s.ty+dy/d*dt*speed,.23,.88);}s.x+=(s.tx-s.x)*Math.min(1,dt*11);s.y+=(s.ty-s.y)*Math.min(1,dt*11);
 if(s.cooldown>0){s.cooldown=Math.max(0,s.cooldown-dt);if(s.cooldown===0){s.round++;newWord();say('Nächstes Wort: '+s.mission.word);}hud();return;}
 for(const t of tiles){t.px=t.x+(reduced?0:Math.sin(s.elapsed*(slow?.6:1.1)+t.phase)*.014);t.py=t.y+(reduced?0:Math.cos(s.elapsed*.7+t.phase)*.012);}
 const near=tiles.filter(t=>!t.collected&&Math.abs(s.x-t.px)*w<=tileWidth(t)/2+9&&Math.abs(s.y-t.py)*h<=tileHeight()/2+9).sort((a,b)=>Math.hypot(s.x-a.px,s.y-a.py)-Math.hypot(s.x-b.px,s.y-b.py));const wanted=near.find(t=>t.text===s.mission.parts[s.index]);if(wanted){const result=collect(s.mission,s.index,wanted);wanted.collected=true;s.index=result.index;flash(s.x,s.y);slots();if(result.outcome==='word'){s.words++;s.stars+=10;s.cooldown=1.25;say(s.mission.word+' geschafft! Dein Wortschatz wächst. +10 Sterne');}else say('Super! Jetzt fehlt '+s.mission.parts[s.index]+'.');}else if(near.length&&s.elapsed>=wrongUntil){wrongUntil=s.elapsed+1.2;say('Dieses Teil ist noch nicht dran. Suche '+s.mission.parts[s.index]+'.');}
 for(const p of sparks){p.x+=p.vx*dt;p.y+=p.vy*dt;p.t-=dt;}sparks=sparks.filter(p=>p.t>0);toast=Math.max(0,toast-dt);if(!toast)$('status').textContent='Suche das gelb markierte Teil. Dein Wort bleibt erhalten.';hud();}
function tileWidth(t){return Math.max(40,t.text.length*(w<600?8:10)+16);}function tileHeight(){return Math.min(w<600?38:44,h*.14);}
function box(x,y,bw,bh,r=10){ctx.beginPath();if(ctx.roundRect){ctx.roundRect(x,y,bw,bh,r);return;}r=Math.min(r,bw/2,bh/2);ctx.moveTo(x+r,y);ctx.lineTo(x+bw-r,y);ctx.quadraticCurveTo(x+bw,y,x+bw,y+r);ctx.lineTo(x+bw,y+bh-r);ctx.quadraticCurveTo(x+bw,y+bh,x+bw-r,y+bh);ctx.lineTo(x+r,y+bh);ctx.quadraticCurveTo(x,y+bh,x,y+bh-r);ctx.lineTo(x,y+r);ctx.quadraticCurveTo(x,y,x+r,y);ctx.closePath();}
function draw(){const bg=ctx.createLinearGradient(0,0,w,h);bg.addColorStop(0,'#203d43');bg.addColorStop(1,'#15263c');ctx.fillStyle=bg;ctx.fillRect(0,0,w,h);for(let i=0;i<10;i++){const x=(i*.137%1)*w;ctx.fillStyle=i%2?'#62885c28':'#56a29322';ctx.beginPath();ctx.ellipse(x,h*.95,Math.max(38,w*.08),h*.25,0,0,Math.PI*2);ctx.fill();}for(let i=0;i<24;i++){ctx.fillStyle='#cde69d66';ctx.beginPath();ctx.arc(((i*.177)%1)*w,((i*.293)%1)*h,1.3,0,Math.PI*2);ctx.fill();}
 for(const t of tiles){if(t.collected)continue;const x=(t.px??t.x)*w,y=(t.py??t.y)*h,bw=tileWidth(t),bh=tileHeight();ctx.shadowColor='#ddb9ff66';ctx.shadowBlur=12;box(x-bw/2,y-bh/2,bw,bh,10);ctx.fillStyle='#fff0cb';ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#e6b772';ctx.lineWidth=2;ctx.stroke();ctx.textAlign='center';ctx.textBaseline='middle';ctx.font='800 '+(h<250?15:w<600?17:20)+'px system-ui';ctx.fillStyle='#3d2d41';ctx.fillText(t.text,x,y);}
 const x=s.x*w,y=s.y*h,r=Math.min(24,Math.max(17,w*.027));ctx.strokeStyle='#b2cfff22';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,r+12,0,Math.PI*2);ctx.stroke();ctx.strokeStyle='#ccadff';ctx.lineWidth=10;ctx.beginPath();ctx.arc(x,y,r,.2,Math.PI-.2);ctx.stroke();ctx.fillStyle='#ffcd8f';ctx.fillRect(x-r-5,y-8,10,14);ctx.fillStyle='#86d5fc';ctx.fillRect(x+r-5,y-8,10,14);if(avatar.complete&&avatar.naturalWidth){ctx.save();ctx.beginPath();ctx.arc(x,y,12,0,Math.PI*2);ctx.clip();ctx.drawImage(avatar,x-12,y-12,24,24);ctx.restore();}for(const p of sparks){ctx.fillStyle='#f8d68c';ctx.globalAlpha=Math.min(1,p.t);ctx.beginPath();ctx.arc(p.x*w,p.y*h,3,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;if(s.cooldown>0){ctx.fillStyle='#d9c8ff';ctx.font='900 '+(w<600?24:38)+'px system-ui';ctx.textAlign='center';ctx.fillText('WORT GESCHAFFT!',w/2,h*.5);}}
function show(title,text,button,help=false){$('guide').hidden=!(s.phase==='ready'||help);document.body?.setAttribute('data-guide',String(s.phase==='ready'||help));$('overlay-title').textContent=title;$('overlay-text').textContent=text;$('start').textContent=button;$('badge').textContent='🧲';$('overlay').hidden=false;$('best').textContent='Dein Testrekord: '+best()+' Sterne · Nur auf diesem Gerät';guide();}
function frameArea(){if(touch||w<740)requestAnimationFrame(()=>document.querySelector('.word-goal').scrollIntoView({block:'start',behavior:'auto'}));}
function start(){random=rng(crypto.getRandomValues(new Uint32Array(1))[0]);reset();s.phase='playing';$('overlay').hidden=true;document.body?.setAttribute('data-guide','false');$('again').hidden=true;say('Los geht’s! Fange '+s.mission.parts[0]+'.');hud();canvas.focus({preventScroll:true});frameArea();}
function pause(){if(s.phase!=='playing')return;held.clear();s.phase='paused';show('Kurze Sammelpause','Dein Wort und die Spielzeit bleiben genau so stehen.','Weitersammeln');$('again').hidden=false;hud();}function resume(){s.phase='playing';$('overlay').hidden=true;document.body?.setAttribute('data-guide','false');$('again').hidden=true;hud();canvas.focus({preventScroll:true});frameArea();}
function finish(){held.clear();s.phase='ended';const record=best();if(s.stars>record)try{localStorage.setItem(bestKey(),String(s.stars))}catch{}show('Dein Wörterwald ist gewachsen!',s.words+' Wörter und '+s.stars+' Sterne gesammelt. '+(s.stars>record?'Neuer persönlicher Testrekord!':'Jedes Wort zählt.'),'Noch einmal sammeln');$('again').hidden=false;hud();}
$('start').onclick=()=>s.phase==='paused'?resume():start();$('pause').onclick=pause;$('help').onclick=()=>{if(s.phase==='playing')pause();show('So sammelst du','',s.phase==='paused'?'Weitersammeln':'Losspielen!',true)};$('again').onclick=()=>{reset();show('So sammelst du','','Losspielen!');$('again').hidden=true};$('grade').onchange=()=>{grade=Number($('grade').value);reset();show('So sammelst du','','Losspielen!')};$('slow').onclick=()=>{slow=!slow;$('slow').setAttribute('aria-pressed',String(slow));$('slow').textContent=slow?'Gemütlich ✓':'Normal ⚡'};
function point(e){const b=canvas.getBoundingClientRect();s.tx=clamp((e.clientX-b.left)/b.width,.08,.92);s.ty=clamp((e.clientY-b.top)/b.height,.23,.88);}canvas.addEventListener('pointerdown',e=>{if(s.phase!=='playing')return;point(e);canvas.setPointerCapture?.(e.pointerId)});canvas.addEventListener('pointermove',e=>{if(s.phase==='playing'&&(e.buttons||canvas.hasPointerCapture?.(e.pointerId)))point(e)});
const dirs={ArrowLeft:'left',ArrowRight:'right',ArrowUp:'up',ArrowDown:'down',a:'left',d:'right',w:'up',s:'down'};function nudge(dir){s.tx=clamp(s.tx+(dir==='left'?-.08:dir==='right'?.08:0),.08,.92);s.ty=clamp(s.ty+(dir==='up'?-.08:dir==='down'?.08:0),.23,.88);}
for(const b of document.querySelectorAll('[data-dir]')){b.onpointerdown=()=>{if(s.phase==='playing')held.add(b.dataset.dir)};b.onpointerup=b.onpointercancel=()=>held.delete(b.dataset.dir);b.onclick=()=>{if(s.phase==='playing')nudge(b.dataset.dir)}}
window.addEventListener('pointerup',()=>held.clear());window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;const dir=dirs[e.key];if(dir&&s.phase==='playing'){e.preventDefault();held.add(dir);if(!e.repeat)nudge(dir)}if(e.key==='Escape'&&s.phase==='playing')pause()});window.addEventListener('keyup',e=>held.delete(dirs[e.key]));window.addEventListener('blur',pause);document.addEventListener('visibilitychange',()=>{if(document.hidden)pause()});
function resize(){const b=canvas.getBoundingClientRect();w=b.width;h=b.height;const d=Math.min(2,devicePixelRatio||1);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0)}new ResizeObserver(resize).observe(canvas);function frame(now){const dt=last?Math.min(.05,(now-last)/1000):0;last=now;update(dt);draw();raf=requestAnimationFrame(frame)}window.addEventListener('pagehide',()=>cancelAnimationFrame(raf));reset();resize();raf=requestAnimationFrame(frame);
if(new URLSearchParams(location.search).get('internal_qa')==='1')window.wordMagnetTest={state:()=>structuredClone(s),tiles:()=>structuredClone(tiles),step:seconds=>{for(let t=0;t<seconds;t+=.02)update(Math.min(.02,seconds-t))}};
