import assert from'node:assert/strict';import fs from'node:fs';import vm from'node:vm';import * as model from'./engine.mjs';
function game(seed,grade,normal){const els=new Map(),events=new Map();const context=new Proxy({createLinearGradient:()=>({addColorStop(){}})},{get:(o,k)=>o[k]||(()=>{})});const get=id=>{if(!els.has(id))els.set(id,{value:'1',style:{},textContent:'',dataset:{},setAttribute(){},replaceChildren(){},append(){},focus(){},getBoundingClientRect:()=>({width:960,height:390,left:0,top:0}),getContext:()=>context,setPointerCapture(){},addEventListener:(type,fn)=>events.set(type,fn)});return els.get(id)};const keys=new Map();const window={addEventListener:(type,fn)=>keys.set(type,fn)};const document={body:{setAttribute(){}},getElementById:get,createElement:()=>({}),querySelectorAll:()=>['left','up','down','right'].map(dir=>({dataset:{dir}})),addEventListener(){}};const sandbox={sceneReady:()=>true,...model,document,window,console,Image:class{},ResizeObserver:class{observe(){}},matchMedia:()=>({matches:false}),requestAnimationFrame:()=>1,cancelAnimationFrame(){},devicePixelRatio:1,crypto:{getRandomValues:a=>{a[0]=seed;return a}},localStorage:{getItem:()=>null,setItem(){}},structuredClone,URLSearchParams,location:{search:'?internal_qa=1'}};vm.createContext(sandbox);vm.runInContext(fs.readFileSync('spikes/word-magnet/game.mjs','utf8').replace(/^import[^\n]+\n/gm,''),sandbox);get('grade').value=String(grade);get('grade').onchange();if(normal)get('slow').onclick();get('start').onclick();return{api:window.wordMagnetTest,keyDown:(key,repeat=false)=>keys.get('keydown')({key,repeat,preventDefault(){}}),keyUp:key=>keys.get('keyup')({key}),point:(x,y)=>events.get('pointerdown')({clientX:x*960,clientY:y*390,pointerId:1})};}
const coverage=Object.fromEntries([1,2,3,4,5,6].map(g=>[g,new Set()]));let cases=0,words=0,minWords=Infinity;for(let grade=1;grade<=6;grade++)for(const normal of [false,true])for(let seed=1;seed<=20;seed++){const{api,point}=game(Math.imul(seed,2654435761)>>>0,grade,normal),completed=[];while(api.state().phase==='playing'){if(api.state().elapsed>360)throw Error('Goal round not finishing');const s=api.state();if(!s.cooldown){const wanted=api.tiles().find(t=>!t.collected&&t.text===s.mission.parts[s.index]);assert(wanted,'Required word part vanished');point(wanted.px??wanted.x,wanted.py??wanted.y);}api.step(.35);if(api.state().words>s.words){coverage[grade].add(s.mission.word);completed.push(s.mission.word);}}assert.equal(api.state().words,model.PROFILES[grade].goals);assert.equal(api.tiles().length,0,'Completed round must leave no phantom next board');if(grade===6)assert(completed.some(w=>['Schlüssel','Wasser'].includes(w)),'No double-consonant task earned in ordinary short round');minWords=Math.min(minWords,api.state().words);words+=api.state().words;cases++;}console.log(JSON.stringify({cases,words,minWords,winByMovementOnly:true}));

for(let grade=1;grade<=6;grade++)assert.deepEqual([...coverage[grade]].sort(),model.BANK[grade].map(r=>r[0]).sort(),'Authored word unreachable in ordinary controller rounds, grade '+grade);console.log(JSON.stringify({earnedCoverage:Object.fromEntries(Object.entries(coverage).map(([g,v])=>[g,[...v]])),all36AuthoredWordsEarned:true,grade6DoubleConsonantsEveryRound:true}));

const heldCase=game(2,1,false);assert.equal(heldCase.api.state().mission.word,'OPA');heldCase.point(.22,.75);heldCase.api.step(.5);assert.equal(heldCase.api.state().index,0);heldCase.keyDown('ArrowUp');heldCase.api.step(.6);assert.equal(heldCase.api.state().index,1,'One held key collected across board refresh');for(let i=0;i<12;i++){heldCase.keyDown('ArrowUp',true);heldCase.api.step(.1);}assert.equal(heldCase.api.state().index,1,'Auto-repeat rearmed old held key');heldCase.keyUp('ArrowUp');const wanted=heldCase.api.tiles().find(t=>t.text===heldCase.api.state().mission.parts[1]);heldCase.point(wanted.x,wanted.y);heldCase.api.step(.5);assert.equal(heldCase.api.state().index,2,'Fresh input must collect next piece');console.log('Exact OPA seed2 held-arrow/repeat/fresh-release regression passed');

const lastOPA=heldCase.api.tiles().find(t=>t.text===heldCase.api.state().mission.parts[2]);heldCase.point(lastOPA.x,lastOPA.y);heldCase.api.step(.5);assert.equal(heldCase.api.state().words,1);heldCase.keyDown('ArrowUp');heldCase.keyDown('ArrowRight');heldCase.api.step(1.26);assert.equal(heldCase.api.state().mission.word,'MAMA');assert.equal(heldCase.api.state().index,0);heldCase.api.step(1.3);assert.equal(heldCase.api.state().index,0,'Celebration-held keys crossed next-word boundary');heldCase.keyDown('ArrowRight',true);heldCase.api.step(.5);assert.equal(heldCase.api.state().index,0);heldCase.keyUp('ArrowUp');heldCase.keyUp('ArrowRight');const freshM=heldCase.api.tiles().find(t=>t.text==='M');heldCase.point(freshM.x,freshM.y);heldCase.api.step(.5);assert.equal(heldCase.api.state().index,1);console.log('OPA-to-MAMA cooldown key-hold/fresh-action regression passed');
