export const privacyContent = {
  de: {
    title: "Datenschutzerklärung", back: "Zurück zur Startseite", updated: "Stand: 11. September 2026",
    sections: [
      ["1. Verantwortliche Stelle und Kontakt", "Alexandra Gosteli Digital Solutions, Langenmooserstrasse 22, 8467 Truttikon, Schweiz. Fragen zu Datenbearbeitungen, Auskunft, Berichtigung oder Löschung richten Sie an hello@cleverli.ch."],
      ["2. Konten, Kinderprofile und Lernbetrieb", "Wir bearbeiten Kontaktdaten der erwachsenen Kontoinhaber, Anmeldeinformationen, Kinderprofile, Klassenstufe, gewählte Lerninhalte, Lernfortschritte und Belohnungen, um Cleverli bereitzustellen. Daten werden im Browser gespeichert und bei Kontonutzung über Supabase synchronisiert. Für Kinderprofile genügt möglichst ein Spitzname. Bitte tragen Sie keine Gesundheitsdaten oder andere besonders schützenswerte Angaben ein. Technische Nutzungsdaten umfassen pseudonyme Kennungen, Seitenaufrufe sowie Lern-, Anmelde- und Kaufereignisse. Je nach Ereignis können diese mit dem Konto oder Kinderprofil verknüpft sein. Die interne Lerntelemetrie verarbeitet Aufgabenkennungen, Bearbeitungsdauer und Ergebnisangaben, nicht den eingegebenen Antworttext. Freiwillig übermittelte Supportnachrichten, Fehlermeldungen oder Feedback können dagegen die von Ihnen eingegebenen Texte enthalten."],
      ["3. Zwecke und rechtliche Grundlagen", "Die Bearbeitung dient der Bereitstellung des Lernangebots, Kontoverwaltung, Synchronisierung, Zahlungsabwicklung, Unterstützung, Fehlerbehebung, Sicherheit und Verbesserung des Angebots. Massgeblich ist das anwendbare Schweizer Datenschutzrecht. Soweit die DSGVO anwendbar ist, stützen wir die Bearbeitung je nach Zweck auf Vertragserfüllung, gesetzliche Pflichten, berechtigte Interessen am sicheren Betrieb oder eine erforderliche Einwilligung. Eine Einwilligung kann mit Wirkung für die Zukunft widerrufen werden. Diese Erklärung stellt keine behördliche oder kantonale Datenschutzfreigabe dar."],
      ["4. Kinder und schulische Nutzung", "Das Lernangebot richtet sich insbesondere an Kinder der 1. bis 6. Klasse. Konten werden von Erwachsenen geführt. Eltern oder verantwortliche Lehrpersonen begleiten die Nutzung. Vor dem Anlegen personenbezogener Schülerprofile muss die Schule die Rechtsgrundlage, Information der Eltern, erforderliche Einwilligungen und gegebenenfalls eine Vereinbarung zur Auftragsbearbeitung klären. Schulinterne Vorgaben bleiben anwendbar. Die Nutzung zur Vorführung oder gemeinsamen Bearbeitung erfordert nicht, dass für jedes Kind ein personenbezogenes Profil angelegt wird. Wir verkaufen keine Kinderprofile oder Lernfortschritte. Für Lehrerkonten speichern wir zusätzlich die angegebene Schule, den Freigabestatus, die vereinbarte Laufzeit sowie Zeitpunkt und Art administrativer Freischaltungen oder Beendigungen. Diese Angaben dienen der Bereitstellung, Zugriffskontrolle und nachvollziehbaren Verwaltung des Lehrerzugangs. Das Ende der Lizenz löscht die Kinderprofile nicht automatisch."],
      ["5. Keine Werbeanzeigen, aber Nutzungs- und Kampagnenmessung", "Cleverli zeigt keine Werbeanzeigen Dritter in der Lernplattform. Hinweise auf das eigene Premium-Angebot sind davon zu unterscheiden. Für Nutzungs- und Kampagnenmessung setzen wir Google Tag Manager, Google Analytics, Google Ads Conversion Tracking, Meta Pixel und Meta Conversions API ein. Diese Messung ist nicht mit Werbefreiheit gleichzusetzen: technische Kennungen, IP-Adresse, Browserinformationen, Seitenaufrufe und Registrierungs-, Checkout-, Test- oder Kaufereignisse können an Google oder Meta übermittelt werden. E-Mail-Adressen für die serverseitige Zuordnung werden normalisiert und kryptografisch gehasht. Hashing ist keine Anonymisierung. Mit Einwilligung nutzen wir die E-Mail-Adresse in geschützter Form für die Ausrichtung von Cleverli-Angeboten auf Eltern und Kunden. Kinderprofile, Lernfortschritte und Antworttexte werden für diese Zielgruppenbildung nicht verwendet. Personalisierte Werbung für Kinder setzen wir nicht ein. Einen Widerruf oder Widerspruch richten Sie an hello@cleverli.ch. Cookies lassen sich zusätzlich im Browser einschränken; das allein beendet nicht automatisch jede serverseitige Bearbeitung."],
      ["6. Technische Dienstleister und Empfänger", "Vercel: Bereitstellung der Website, Serverfunktionen, Auslieferung und technische Protokolle, insbesondere IP-Adresse und Browserdaten. Supabase: Anmeldung, Datenbank und Synchronisierung von Konten, Profilen, Lernfortschritten und betrieblichen Ereignissen. Stripe: Zahlungsabwicklung und Abonnementverwaltung; Zahlungsdaten werden im Stripe-Checkout erfasst, Cleverli erhält insbesondere Kunden-, Zahlungs- und Abonnementstatus. Resend: Versand von Konto-, Service- und Feedback-E-Mails; verarbeitet Empfängeradresse, Nachrichteninhalt und Zustellinformationen. Einzelne ausdrücklich verlinkte Aktionen können Klickzeit und Linkziel-Kennung erfassen. ElevenLabs: Sprachausgabe; beim Vorlesen wird der vorzulesende Text an den Dienst übermittelt. Es wird dafür keine Mikrofonaufnahme des Kindes benötigt. Google und Meta: Messung gemäss Abschnitt 5. Sentry und PostHog: soweit aktiviert, Fehlerdiagnose und Produktanalyse mit technischen Geräte-, Seiten- und Ereignisdaten. Sentry kann bei Fehlern maskierte Sitzungswiedergaben verarbeiten; PostHog-Sitzungsaufzeichnungen sind in unserer Anwendung deaktiviert. Diese Dienste ersetzen keine anonyme Nutzung. Dienstleister erhalten die für ihre jeweilige Funktion erforderlichen Daten; weitere Offenlegungen können zur Erfüllung gesetzlicher Pflichten erforderlich sein."],
      ["7. Bearbeitung im Ausland", "Unsere Anbieter betreiben internationale Infrastrukturen. Vercel, Supabase, Stripe, Resend, ElevenLabs, Sentry, PostHog, Google und Meta können Daten in der EU beziehungsweise im EWR, den USA oder weiteren Ländern ihrer veröffentlichten Unterauftragnehmer bearbeiten. Der Unternehmenssitz eines Anbieters ist nicht gleichbedeutend mit dem Speicherort jedes Datensatzes. Wir versprechen weder ausschliessliche Speicherung in der Schweiz noch einen einzigen Speicherort. Für Übermittlungen in Länder ohne angemessenes Datenschutzniveau sind die jeweils anwendbaren gesetzlichen Voraussetzungen und geeigneten Garantien erforderlich, beispielsweise anwendbare Standardvertragsklauseln oder eine einschlägige Datenschutzrahmen-Zertifizierung des konkreten Empfängers. Eine allgemeine Anbieterzertifizierung ist keine Zertifizierung von Cleverli. Informationen zur konkreten Verarbeitung und den für einen Schuleinsatz benötigten vertraglichen Unterlagen erhalten Sie über hello@cleverli.ch; ein institutioneller Einsatz setzt deren erforderliche Klärung voraus."],
      ["8. Speicherung und Löschung", "Kontodaten und synchronisierte Lernstände werden für die Nutzung des Kontos gespeichert. Eine Kündigung des Premium-Abonnements löscht das Konto und die Lernstände nicht automatisch. Löschanfragen können an hello@cleverli.ch gerichtet werden. Daten werden gelöscht oder anonymisiert, soweit sie für die genannten Zwecke nicht mehr erforderlich sind und keine gesetzlichen Aufbewahrungspflichten oder berechtigten Ansprüche entgegenstehen. Für aufbewahrungspflichtige Geschäftsunterlagen gelten die gesetzlichen Fristen, insbesondere grundsätzlich zehn Jahre für entsprechende Buchungsbelege. Sicherheitskopien und Protokolle der Dienstleister können abweichenden Aufbewahrungszyklen unterliegen; eine sofortige Entfernung aus sämtlichen Sicherungen wird nicht zugesichert. Es wird keine automatische pauschale Löschfrist für alle Datentypen behauptet. Lokal gespeicherte Daten können zusätzlich durch Löschen der Website-Daten im Browser entfernt werden. Dies löscht nicht automatisch die Serverkopie und kann noch nicht synchronisierte Lernstände unwiederbringlich entfernen."],
      ["9. Sicherheit und Rechte", "Die Website und unsere Schnittstellen verwenden HTTPS. Kontobezogene Zugriffskontrollen und getrennte Berechtigungen beschränken den Zugriff. Dies ist keine Ende-zu-Ende-Verschlüsselung: berechtigte technische Verarbeitung durch Cleverli und Dienstleister bleibt möglich. Absolute Sicherheit oder eine bestimmte Verfügbarkeitsquote wird nicht garantiert. Im Rahmen des anwendbaren Rechts können Sie Auskunft, Berichtigung, Löschung, Einschränkung und Datenherausgabe verlangen, Einwilligungen widerrufen und einer Bearbeitung widersprechen. Zur Bearbeitung einer Anfrage können wir einen angemessenen Identitätsnachweis benötigen. Sie können sich an den Eidgenössischen Datenschutz- und Öffentlichkeitsbeauftragten (EDÖB), eine zuständige kantonale Stelle oder, soweit einschlägig, die zuständige europäische Datenschutzaufsicht wenden."],
      ["10. Weiterführende Anbieterinformationen", "Informationen der Anbieter: vercel.com/legal/privacy-policy, supabase.com/privacy, stripe.com/privacy, resend.com/legal/privacy-policy, elevenlabs.io/privacy-policy, sentry.io/privacy, posthog.com/privacy, policies.google.com/privacy und facebook.com/privacy/policy. Diese Erklärungen beschreiben die jeweilige Anbieterbearbeitung; sie ersetzen keine Prüfung der konkreten Cleverli-Konfiguration. Bei Änderungen unserer Bearbeitungen aktualisieren wir diese Erklärung. Kontakt: hello@cleverli.ch."]
    ]
  },
  fr: {
    title: "Politique de confidentialité", back: "Retour à l’accueil", updated: "Mise à jour : 11 septembre 2026",
    sections: [
      ["1. Responsable et contact", "Alexandra Gosteli Digital Solutions, Langenmooserstrasse 22, 8467 Truttikon, Suisse. Pour toute question, demande d’accès, rectification ou suppression : hello@cleverli.ch."],
      ["2. Comptes et apprentissage", "Nous traitons les coordonnées des adultes, les informations de connexion, profils enfants, niveaux scolaires, contenus choisis, progrès et récompenses pour fournir Cleverli. Les données sont stockées dans le navigateur et synchronisées via Supabase lors de l’utilisation d’un compte. Privilégiez les pseudonymes et ne saisissez pas de données de santé ou sensibles. Les données techniques comprennent des identifiants pseudonymes, pages consultées et événements d’apprentissage, d’inscription ou d’achat, parfois associés au compte ou profil. La télémétrie pédagogique interne traite les identifiants des exercices, durées et résultats, pas les réponses saisies. Les messages d’assistance, signalements et avis volontaires peuvent contenir le texte que vous transmettez."],
      ["3. Finalités et bases juridiques", "Les finalités sont la fourniture du service, la gestion des comptes, la synchronisation, les paiements, l’assistance, la sécurité, le diagnostic et l’amélioration du produit. Le droit suisse applicable régit ces traitements. Si le RGPD s’applique, la base dépend du traitement : contrat, obligation légale, intérêt légitime au fonctionnement sécurisé ou consentement nécessaire. Le consentement peut être retiré pour l’avenir. Cette politique ne constitue pas une autorisation officielle ou cantonale."],
      ["4. Enfants et utilisation scolaire", "L’offre vise principalement les enfants de la 1re à la 6e année. Les comptes sont gérés par des adultes et l’utilisation accompagnée par les parents ou enseignants responsables. Avant de créer des profils élèves identifiables, l’école doit clarifier la base légale, l’information des parents, les consentements et la convention de sous-traitance éventuellement nécessaires. Les règles scolaires restent applicables. Une démonstration ou un exercice collectif ne nécessite pas un profil personnel par enfant. Nous ne vendons pas les profils enfants ni leur progression. Pour les comptes enseignants, nous conservons aussi l’école indiquée, le statut d’activation, la durée convenue ainsi que la date et le type des activations ou fins d’accès administratives, afin de fournir et gérer l’accès de manière traçable. La fin de la licence ne supprime pas automatiquement les profils enfants."],
      ["5. Pas d’annonces publicitaires, mais mesure d’utilisation", "Cleverli n’affiche pas d’annonces de tiers dans la plateforme. Les informations sur notre propre offre Premium sont distinctes. Nous utilisons Google Tag Manager, Analytics, Ads, Meta Pixel et Conversions API pour la mesure. L’absence d’annonces ne signifie pas l’absence de suivi : identifiants techniques, IP, navigateur, pages et événements d’inscription, paiement, essai ou achat peuvent être transmis à Google ou Meta. Les e-mails d’attribution côté serveur sont normalisés et hachés cryptographiquement, ce qui n’est pas une anonymisation. Avec consentement, l’e-mail protégé sert à adapter les offres aux parents et clients. Les profils enfants, progrès et réponses ne servent pas à créer ces audiences. Nous n’utilisons pas de publicité personnalisée pour les enfants. Retrait ou opposition : hello@cleverli.ch. Restreindre les cookies ne met pas automatiquement fin aux traitements serveur."],
      ["6. Prestataires", "Vercel fournit l’hébergement, les fonctions serveur et journaux techniques. Supabase assure l’authentification, la base de données et la synchronisation. Stripe traite les paiements et abonnements dans son checkout ; Cleverli reçoit notamment les identifiants et statuts. Resend traite les destinataires, messages et informations de livraison des e-mails de service et de feedback ; certaines actions liées peuvent enregistrer l’heure du clic et l’identifiant du lien. ElevenLabs reçoit le texte à lire pour la synthèse vocale, sans nécessiter d’enregistrement du microphone de l’enfant. Google et Meta assurent la mesure décrite ci-dessus. Sentry et PostHog, si activés, traitent les données techniques, de pages et d’événements pour le diagnostic et l’analyse. Sentry peut traiter des relectures de session masquées lors d’erreurs ; l’enregistrement de session PostHog est désactivé dans l’application. Ces services ne rendent pas l’utilisation anonyme. Les prestataires reçoivent les données nécessaires à leur fonction ; des obligations légales peuvent aussi imposer une communication."],
      ["7. Traitements à l’étranger", "Ces prestataires utilisent des infrastructures internationales et peuvent traiter des données dans l’UE/EEE, aux États-Unis ou dans d’autres pays de leurs sous-traitants publiés. Leur siège n’est pas le lieu de stockage de chaque donnée. Nous ne promettons ni un hébergement exclusivement suisse ni un lieu unique. Un transfert vers un pays sans protection adéquate exige les conditions légales et garanties appropriées, par exemple des clauses contractuelles types applicables ou une certification pertinente du destinataire. La certification d’un prestataire n’est pas celle de Cleverli. Pour les modalités concrètes et documents contractuels nécessaires à l’école, contactez hello@cleverli.ch ; leur clarification nécessaire précède l’usage institutionnel."],
      ["8. Conservation et suppression", "Les comptes et progrès synchronisés sont conservés pour l’utilisation du compte. Résilier Premium ne supprime pas automatiquement le compte. Demandes de suppression : hello@cleverli.ch. Les données sont supprimées ou anonymisées lorsqu’elles ne sont plus nécessaires, sous réserve des obligations légales ou prétentions justifiées. Les documents comptables concernés sont en principe conservés dix ans. Sauvegardes et journaux peuvent suivre des cycles distincts ; une suppression immédiate de toutes les sauvegardes n’est pas garantie. Il n’existe pas ici de promesse de délai automatique unique. Effacer les données du site dans le navigateur ne supprime pas la copie serveur et peut perdre définitivement des progrès non synchronisés."],
      ["9. Sécurité et droits", "Le site et nos interfaces utilisent HTTPS et des contrôles d’accès liés aux comptes. Il ne s’agit pas d’un chiffrement de bout en bout : les traitements techniques autorisés restent possibles. Aucune sécurité absolue ou disponibilité chiffrée n’est garantie. Selon le droit applicable, vous pouvez demander accès, rectification, suppression, restriction et remise de données, retirer un consentement ou vous opposer au traitement. Une vérification d’identité proportionnée peut être nécessaire. Vous pouvez contacter le PFPDT, l’autorité cantonale compétente ou, si applicable, une autorité européenne de protection des données."],
      ["10. Informations des prestataires", "Sources : vercel.com/legal/privacy-policy, supabase.com/privacy, stripe.com/privacy, resend.com/legal/privacy-policy, elevenlabs.io/privacy-policy, sentry.io/privacy, posthog.com/privacy, policies.google.com/privacy et facebook.com/privacy/policy. Elles ne remplacent pas une vérification de la configuration de Cleverli. Nous actualisons cette politique lorsque les traitements évoluent. Contact : hello@cleverli.ch."]
    ]
  },
  it: {
    title: "Informativa sulla privacy", back: "Torna alla pagina iniziale", updated: "Aggiornamento: 11 settembre 2026",
    sections: [
      ["1. Titolare e contatto", "Alexandra Gosteli Digital Solutions, Langenmooserstrasse 22, 8467 Truttikon, Svizzera. Per informazioni, accesso, rettifica o cancellazione: hello@cleverli.ch."],
      ["2. Account e apprendimento", "Trattiamo contatti degli adulti, dati di accesso, profili bambino, classe, contenuti scelti, progressi e premi per fornire Cleverli. I dati sono salvati nel browser e sincronizzati tramite Supabase quando si usa un account. Preferire soprannomi ed evitare dati sanitari o sensibili. I dati tecnici includono identificatori pseudonimi, pagine ed eventi di apprendimento, registrazione o acquisto, talvolta collegati all’account o profilo. La telemetria interna registra identificativi degli esercizi, durata e risultati, non il testo delle risposte. Messaggi di assistenza, segnalazioni e feedback volontari possono contenere i testi inviati."],
      ["3. Finalità e basi giuridiche", "Le finalità sono servizio, gestione degli account, sincronizzazione, pagamenti, assistenza, sicurezza, diagnosi e miglioramento. Si applica il diritto svizzero pertinente. Ove applicabile il GDPR, la base dipende dal trattamento: contratto, obbligo legale, interesse legittimo al funzionamento sicuro o consenso necessario. Il consenso è revocabile per il futuro. Questa informativa non costituisce un’approvazione ufficiale o cantonale."],
      ["4. Minori e uso scolastico", "L’offerta si rivolge principalmente alla 1a fino alla 6a classe. Gli account sono gestiti da adulti e l’uso accompagnato da genitori o docenti responsabili. Prima di creare profili identificabili degli allievi, la scuola deve chiarire base giuridica, informazione dei genitori, consensi ed eventuale accordo sul trattamento. Restano valide le regole scolastiche. Dimostrazioni ed esercizi collettivi non richiedono un profilo personale per ogni bambino. Non vendiamo profili o progressi dei bambini. Per gli account docente conserviamo anche la scuola indicata, lo stato di attivazione, la durata concordata e la data e il tipo delle attivazioni o cessazioni amministrative, per fornire e gestire l’accesso in modo tracciabile. La fine della licenza non cancella automaticamente i profili bambino."],
      ["5. Nessun annuncio, ma misurazione dell’utilizzo", "Cleverli non mostra annunci di terzi nella piattaforma. Le informazioni sulla nostra offerta Premium sono distinte. Usiamo Google Tag Manager, Analytics, Ads, Meta Pixel e Conversions API per la misurazione. L’assenza di annunci non significa assenza di tracciamento: identificatori tecnici, IP, browser, pagine ed eventi di registrazione, pagamento, prova o acquisto possono essere trasmessi a Google o Meta. Le e-mail per l’attribuzione server vengono normalizzate e sottoposte a hash crittografico, che non equivale ad anonimizzazione. Con consenso, l’e-mail protetta serve ad adattare le offerte a genitori e clienti. Profili bambino, progressi e risposte non sono usati per questi pubblici. Non usiamo pubblicità personalizzata per bambini. Revoca o opposizione: hello@cleverli.ch. Limitare i cookie non interrompe automaticamente i trattamenti sul server."],
      ["6. Fornitori", "Vercel fornisce hosting, funzioni server e log tecnici. Supabase gestisce autenticazione, database e sincronizzazione. Stripe tratta pagamenti e abbonamenti nel proprio checkout; Cleverli riceve identificativi e stati. Resend tratta destinatari, messaggi e informazioni di consegna delle e-mail di servizio e feedback; alcune azioni collegate possono registrare ora del clic e identificativo del link. ElevenLabs riceve il testo da leggere per la sintesi vocale, senza richiedere registrazioni dal microfono del bambino. Google e Meta svolgono la misurazione descritta sopra. Sentry e PostHog, se attivi, trattano dati tecnici, di pagina ed eventi per diagnosi e analisi. Sentry può trattare riproduzioni mascherate delle sessioni in caso di errore; la registrazione PostHog è disattivata nell’applicazione. Questi servizi non rendono anonimo l’uso. I fornitori ricevono i dati necessari alla loro funzione; ulteriori comunicazioni possono essere richieste dalla legge."],
      ["7. Trattamenti all’estero", "I fornitori usano infrastrutture internazionali e possono trattare dati nell’UE/SEE, negli USA o negli altri paesi dei subfornitori pubblicati. La sede non coincide con ogni luogo di conservazione. Non promettiamo conservazione esclusivamente svizzera o in un unico luogo. Trasferimenti verso paesi senza protezione adeguata richiedono condizioni legali e garanzie idonee, come clausole contrattuali standard applicabili o una certificazione pertinente del destinatario. La certificazione del fornitore non certifica Cleverli. Informazioni concrete e documenti contrattuali per la scuola sono richiedibili a hello@cleverli.ch; i chiarimenti necessari precedono l’uso istituzionale."],
      ["8. Conservazione e cancellazione", "Account e progressi sincronizzati sono conservati per l’uso dell’account. Disdire Premium non elimina automaticamente l’account. Richieste di cancellazione: hello@cleverli.ch. I dati vengono eliminati o anonimizzati quando non più necessari, salvo obblighi legali o pretese giustificate. Per i documenti contabili pertinenti vale in linea di principio la conservazione di dieci anni. Backup e log possono avere cicli differenti; non garantiamo cancellazione immediata da ogni backup né un unico termine automatico. Eliminare i dati del sito dal browser non elimina la copia server e può perdere definitivamente progressi non sincronizzati."],
      ["9. Sicurezza e diritti", "Il sito e le nostre interfacce usano HTTPS e controlli di accesso legati agli account. Non si tratta di cifratura da punto a punto: resta possibile il trattamento tecnico autorizzato. Non garantiamo sicurezza assoluta o una percentuale di disponibilità. Secondo il diritto applicabile è possibile chiedere accesso, rettifica, cancellazione, limitazione e consegna dei dati, revocare il consenso e opporsi. Può servire una verifica proporzionata dell’identità. È possibile rivolgersi all’IFPDT, all’autorità cantonale o, se pertinente, europea competente."],
      ["10. Informazioni dei fornitori", "Fonti: vercel.com/legal/privacy-policy, supabase.com/privacy, stripe.com/privacy, resend.com/legal/privacy-policy, elevenlabs.io/privacy-policy, sentry.io/privacy, posthog.com/privacy, policies.google.com/privacy e facebook.com/privacy/policy. Non sostituiscono una verifica della configurazione di Cleverli. Aggiorniamo l’informativa quando cambiano i trattamenti. Contatto: hello@cleverli.ch."]
    ]
  },
  en: {
    title: "Privacy Policy", back: "Back to home", updated: "Last updated: 11 September 2026",
    sections: [
      ["1. Controller and contact", "Alexandra Gosteli Digital Solutions, Langenmooserstrasse 22, 8467 Truttikon, Switzerland. Questions, access, correction and deletion requests: hello@cleverli.ch."],
      ["2. Accounts and learning", "We process adult contact and login details, child profiles, grade, selected content, learning progress and rewards to provide Cleverli. Data is stored in the browser and synchronised through Supabase when an account is used. Prefer nicknames and avoid health or other sensitive information. Technical data includes pseudonymous identifiers, pages and learning, registration or purchase events, sometimes linked to an account or profile. Internal learning telemetry records exercise identifiers, duration and results, not entered answer text. Voluntary support messages, issue reports and feedback may contain the text you submit."],
      ["3. Purposes and legal bases", "Purposes include service provision, account management, synchronisation, payments, support, security, diagnostics and product improvement. Applicable Swiss data protection law governs processing. Where GDPR applies, the basis depends on the purpose: contract, legal obligation, legitimate interests in secure operation or necessary consent. Consent can be withdrawn prospectively. This policy is not an official or cantonal data protection approval."],
      ["4. Children and school use", "The service principally addresses grades 1 to 6. Adults manage accounts and parents or responsible teachers supervise use. Before creating identifiable pupil profiles, schools must clarify the legal basis, parental information, required consents and any necessary processing agreement. School policies still apply. Presenting or jointly completing exercises does not require a personal profile for every child. We do not sell child profiles or learning progress. For teacher accounts, we also store the named school, activation status, agreed duration, and the time and type of administrative grants or revocations, to provide and manage access with an audit trail. Ending the licence does not automatically delete child profiles."],
      ["5. No advertising displays, but usage measurement", "Cleverli does not display third-party advertisements in the learning platform. Information about our own Premium offer is distinct. We use Google Tag Manager, Analytics, Ads, Meta Pixel and Conversions API for measurement. No displayed ads does not mean no tracking: technical identifiers, IP address, browser, pages and registration, checkout, trial or purchase events may be transmitted to Google or Meta. Server-side attribution email addresses are normalised and cryptographically hashed, which is not anonymisation. With consent, protected email addresses help tailor offers to parents and customers. Child profiles, progress and answers are not used to build those audiences. We do not use personalised advertising for children. Withdraw consent or object at hello@cleverli.ch. Restricting browser cookies does not automatically stop server-side processing."],
      ["6. Service providers", "Vercel provides hosting, server functions and technical logs. Supabase provides authentication, databases and synchronisation. Stripe processes payments and subscriptions through its checkout; Cleverli receives identifiers and statuses. Resend processes recipients, messages and delivery information for service and feedback emails; certain linked actions may record click time and link identifier. ElevenLabs receives text for speech synthesis without requiring a recording from a child’s microphone. Google and Meta perform the measurement above. Sentry and PostHog, where enabled, process technical, page and event data for diagnostics and analytics. Sentry may process masked session replays on errors; PostHog session recording is disabled in the application. These services do not make use anonymous. Providers receive data required for their function; legal obligations may require further disclosure."],
      ["7. International processing", "Providers operate international infrastructure and may process data in the EU/EEA, USA or other countries of their published subprocessors. A company’s headquarters is not the storage location of each record. We promise neither exclusively Swiss storage nor one single location. Transfers to countries without adequate protection require applicable legal conditions and suitable safeguards, such as applicable standard contractual clauses or a relevant certification of the specific recipient. A provider’s certification does not certify Cleverli. Contact hello@cleverli.ch for specific processing information and documents needed for school use; necessary clarification must precede institutional use."],
      ["8. Retention and deletion", "Accounts and synchronised progress are retained for account use. Cancelling Premium does not automatically delete the account. Request deletion at hello@cleverli.ch. Data is deleted or anonymised when no longer needed, subject to statutory retention and legitimate claims. Relevant accounting records generally have a ten-year statutory retention period. Backups and logs may follow different cycles; immediate erasure from every backup and a single automatic deletion deadline are not promised. Clearing browser site data does not delete the server copy and can permanently remove unsynchronised progress."],
      ["9. Security and rights", "The website and our interfaces use HTTPS and account-based access controls. This is not end-to-end encryption: authorised technical processing remains possible. Absolute security and a specific uptime percentage are not guaranteed. Depending on applicable law, you may request access, correction, deletion, restriction and data delivery, withdraw consent or object. Proportionate identity verification may be required. You may contact the Swiss FDPIC, a competent cantonal authority or, where applicable, a European data protection authority."],
      ["10. Provider information", "Sources: vercel.com/legal/privacy-policy, supabase.com/privacy, stripe.com/privacy, resend.com/legal/privacy-policy, elevenlabs.io/privacy-policy, sentry.io/privacy, posthog.com/privacy, policies.google.com/privacy and facebook.com/privacy/policy. These do not replace verification of Cleverli’s actual configuration. We update this policy as processing changes. Contact: hello@cleverli.ch."]
    ]
  }
} as const;
