import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { withPageSocial } from "@/lib/pageSocialMetadata";

export const metadata: Metadata = withPageSocial({
 title: "Lernapp für die Primarschule: Geräte, Übungen und Kosten",
 description: "Cleverli als Lernapp für die Schweizer Primarschule nutzen: im Browser auf Handy, Tablet und Computer. Mit Beispielen, Kosten und Tipps für Eltern.",
 alternates: { canonical: "https://www.cleverli.ch/lernapp-primarschule" },
 robots: { index: true, follow: true },
});
const faqs = [
 {question:"Muss ich Cleverli aus einem App Store herunterladen?",answer:"Nein. Cleverli ist eine browserbasierte Lernapp. Öffne cleverli.ch in einem aktuellen Browser. Für den Einstieg ist kein Download aus dem Apple App Store oder Google Play Store nötig."},
 {question:"Ist Cleverli kostenlos?",answer:"Ausgewählte Übungen sind kostenlos zugänglich. Premium kostet CHF 9.90 pro Monat oder CHF 99 pro Jahr für bis zu drei Kinderprofile. Für die siebentägige Premium-Testphase braucht es eine Zahlungskarte. Ohne Kündigung beginnt danach das gewählte kostenpflichtige Abo. Verbindlich sind die Angaben im Checkout."},
 {question:"Passt die Lernapp zum Schweizer Lehrplan 21?",answer:"Cleverli bietet eine Übersicht mit Themen, Lehrplancodes und Übungslinks. Sie hilft beim Einordnen nach Klasse und Fach. Sie ist keine offizielle Zertifizierung und ersetzt weder den Unterricht noch die Einschätzung der Lehrperson. Die Reihenfolge des Schulstoffs kann je nach Schule und Kanton variieren."},
 {question:"Kann mein Kind ohne Internet üben?",answer:"Plane für Cleverli eine Internetverbindung ein. Ein Symbol auf dem Home-Bildschirm ist ein schneller Zugang zur Website, aber keine Zusage, dass alle Übungen und Funktionen offline verfügbar sind."},
 {question:"Wie wähle ich passende Aufgaben aus?",answer:"Beginnt mit der Klasse und einem Thema aus dem aktuellen Unterricht. Lass dein Kind ein Beispiel lösen und seinen Weg erklären. Wenn eine Grundlage noch fehlt, wählt zuerst eine einfachere Aufgabe. Kurze, ruhige Runden sind hilfreicher als möglichst viele Klicks."},
];
const linkClass="inline-flex min-h-11 items-center py-2 font-semibold text-green-800 underline underline-offset-4";
export default function LearningAppGuide(){return <main lang="de" className="bg-white text-gray-900">
 <script type="application/ld+json" dangerouslySetInnerHTML={{__html:JSON.stringify({"@context":"https://schema.org","@type":"FAQPage",mainEntity:faqs.map(f=>({"@type":"Question",name:f.question,acceptedAnswer:{"@type":"Answer",text:f.answer}}))})}}/>
 <article className="mx-auto max-w-4xl px-4 py-10 sm:px-6 sm:py-14">
  <p className="text-sm font-bold text-green-700">Ratgeber für Eltern · Schweizer Primarschule</p>
  <h1 className="mt-3 text-3xl font-extrabold leading-tight sm:text-5xl">Eine Lernapp für die Primarschule: So nutzt ihr Cleverli im Alltag</h1>
  <p className="mt-6 text-lg leading-8 text-gray-700">Du suchst eine Lernapp für dein Kind? Entscheidend sind passende Aufgaben, verständliche Hilfe und ein klarer Überblick über Kosten und Nutzung. Hier zeigen wir, wie Cleverli auf euren Geräten funktioniert und wie ihr einen sinnvollen Einstieg findet.</p>
  <p className="mt-3 text-sm leading-6 text-gray-500">Von Cleverli, dem Anbieter dieser Lernplattform. Dieser Ratgeber erklärt unser eigenes Angebot und ist kein unabhängiger Appvergleich.</p>
  <nav aria-label="Inhaltsverzeichnis" className="my-8 flex flex-wrap gap-x-5 gap-y-2 rounded-2xl bg-green-50 p-5">{[["geraete","Geräte"],["beispiele","Beispiele"],["auswahl","Auswahl"],["kosten","Kosten"],["fragen","Fragen"]].map(([id,label])=><a key={id} className={linkClass} href={'#'+id}>{label}</a>)}</nav>
  <section id="geraete" className="scroll-mt-24"><h2 className="text-2xl font-bold">Lernapp oder Website? Bei Cleverli geht beides im Browser zusammen</h2><p className="mt-4 leading-7">Cleverli läuft als Webanwendung auf Handy, Tablet und Computer. Du brauchst keine separate native App. Ein grösserer Bildschirm kann bei Aufgaben mit mehreren Elementen angenehmer sein. Vorlesen ist verfügbar, wenn Ton und Gerät entsprechend eingestellt sind.</p>
   <div className="mt-6 grid gap-4 sm:grid-cols-3">{[
    ["iPhone und iPad","Öffne cleverli.ch in Safari. Für einen schnellen Zugang kannst du im Teilen-Menü nach «Zum Home-Bildschirm» suchen. Je nach Systemversion kann sich die Bezeichnung oder Position unterscheiden."],
    ["Android","Öffne cleverli.ch in Chrome. Je nach Browser und Gerät findest du im Menü «Zum Startbildschirm hinzufügen» oder «App installieren». Falls diese Option fehlt, kannst du einfach ein Lesezeichen setzen."],
    ["Computer","Öffne cleverli.ch in einem aktuellen Browser und speichere ein Lesezeichen. Ein Konto hilft, gespeicherte Fortschritte auf mehreren Geräten zu nutzen. Achte darauf, jeweils dasselbe Kinderprofil auszuwählen."],
   ].map(([title,text])=><div key={title} className="rounded-2xl border border-green-100 bg-green-50 p-5"><h3 className="font-bold">{title}</h3><p className="mt-3 text-sm leading-7">{text}</p></div>)}</div><p className="mt-4 text-sm leading-7 text-gray-600">Die Menübezeichnungen hängen vom Betriebssystem und Browser ab. Ein Startsymbol macht aus der Website keine separate App aus dem App Store. Für die Nutzung solltest du eine Internetverbindung einplanen.</p>
  </section>
  <section id="beispiele" className="mt-12 scroll-mt-24"><h2 className="text-2xl font-bold">Welche Aufgaben passen zu deinem Kind?</h2><p className="mt-4 leading-7">Cleverli richtet sich an die 1. bis 6. Klasse. Neben Mathematik und Deutsch gibt es Natur, Mensch, Gesellschaft (NMG), Sprachen sowie Medien und Informatik. Welche Themen passen, hängt vom Lernstand und vom Unterricht ab.</p><figure className="mt-6"><Image src="/images/seo/mathe-beispiel.png" alt="Drei echte Matheaufgaben aus Cleverli mit einer geöffneten Lösung" width={1000} height={702} className="h-auto w-full rounded-2xl border border-gray-200" sizes="(min-width:900px) 850px, 100vw"/><figcaption className="mt-2 text-sm text-gray-500">Beispiel aus unserer Seite für Mathe in der 5. Klasse. Die Lösung lässt sich dort aufklappen.</figcaption></figure><ul className="mt-5 space-y-2"><li><Link className={linkClass} href="/mathe-uebungen-5-klasse">Dezimalzahlen, Brüche und Umfang mit Erklärungen ausprobieren</Link></li><li><Link className={linkClass} href="/deutsch-uebungen-3-klasse">Wortarten, Leseverständnis und Grossschreibung ausprobieren</Link></li><li><Link className={linkClass} href="/primarschule-uebungen">Alle Klassen und Fächer entdecken</Link></li></ul></section>
  <section id="auswahl" className="mt-12 scroll-mt-24"><h2 className="text-2xl font-bold">Worauf Eltern bei einer Lernapp achten können</h2><ul className="mt-4 list-disc space-y-3 pl-5 leading-7"><li><strong>Passender Lernstoff:</strong> Wählt ein konkretes Thema aus dem Unterricht, statt nur nach dem Alter zu gehen. Unsere <Link href="/lehrplanbezug" className="font-semibold text-green-800 underline">Übersicht zum Lehrplanbezug</Link> zeigt Themen und Zuordnungen.</li><li><strong>Verständliche Rückmeldung:</strong> Eine hilfreiche Aufgabe zeigt nicht nur richtig oder falsch. Probiert Hinweise und Erklärungen gemeinsam aus.</li><li><strong>Überschaubare Runden:</strong> Startet beispielsweise mit fünf bis zehn Minuten. Eine Pause ist sinnvoll, wenn Konzentration oder Freude nachlassen.</li><li><strong>Elternbegleitung:</strong> Schaut gelegentlich gemeinsam auf die gespeicherten Fortschritte. Eine App ergänzt das Lernen, ersetzt aber weder Lehrpersonen noch persönliche Unterstützung.</li><li><strong>Datenschutz:</strong> Prüft, welche Daten gespeichert werden und wer verantwortlich ist. In unserer <Link href="/datenschutz" className="font-semibold text-green-800 underline">Datenschutzerklärung</Link> stehen die Details. Verwendet für Kinderprofile keine unnötigen persönlichen Angaben.</li></ul><Link href="/parents" className={linkClass}>Die öffentliche Vorschau des Elternbereichs ansehen</Link></section>
  <section id="kosten" className="mt-12 scroll-mt-24 rounded-2xl bg-green-50 p-6"><h2 className="text-2xl font-bold">Kostenlos ausprobieren und Premium unterscheiden</h2><p className="mt-4 leading-7">Ausgewählte Übungen könnt ihr ohne Abo ausprobieren. Für Premium gibt es ein Monatsabo für CHF 9.90 oder ein Jahresabo für CHF 99. Beide gelten für bis zu drei Kinderprofile.</p><p className="mt-3 leading-7">Die siebentägige Premium-Testphase ist etwas anderes als das Ausprobieren einzelner Übungen: Sie benötigt eine Zahlungskarte und geht ohne Kündigung in das gewählte Abo über. Prüft Preis, Laufzeit und Kündigungsbedingungen vor dem Abschluss. Aktuelle Sonderangebote und die verbindlichen Bedingungen seht ihr auf der Preisübersicht und im Checkout.</p><Link href="/upgrade" className={linkClass}>Aktuelle Preise und Angebote prüfen</Link></section>
  <section id="fragen" className="mt-12 scroll-mt-24"><h2 className="text-2xl font-bold">Häufige Fragen zur Lernapp</h2><div className="mt-5 space-y-3">{faqs.map(f=><details key={f.question} className="rounded-2xl border border-gray-200 p-5"><summary className="cursor-pointer py-2 font-bold">{f.question}</summary><p className="mt-3 leading-7 text-gray-700">{f.answer}</p></details>)}</div></section>
  <aside className="mt-12 border-t border-green-100 pt-6"><h2 className="text-xl font-bold">Der passende nächste Schritt</h2><div className="mt-3 flex flex-col items-start"><Link href="/" className={linkClass}>Cleverli als Lernplattform für Familien kennenlernen</Link><Link href="/lehrpersonen" className={linkClass}>Informationen für Lehrpersonen und Schulklassen</Link><Link href="/impressum" className={linkClass}>Wer hinter Cleverli steht</Link></div></aside>
 </article>
</main>}
