"use client";
import Image from "next/image";
import Link from "next/link";
import { useLang } from "@/lib/LangContext";
import CurriculumOverviewLink from "./CurriculumOverviewLink";
const copy = {
  de: {
    title: "Eine Lernplattform für den Familienalltag",
    intro: "Cleverli begleitet Kinder der 1. bis 6. Klasse beim Üben zu Hause. Die Lernapp läuft im Browser auf Handy, Tablet und Computer. Wählt passende Aufgaben in Mathematik, Deutsch, Natur, Mensch, Gesellschaft (NMG), Sprachen oder Medien und Informatik.",
    practice: "Erst ausprobieren, dann gemeinsam auswählen", practiceText: "Kurze Aufgaben, Hinweise und direkte Rückmeldungen helfen beim Einstieg. Die Themenübersicht zeigt, was dein Kind nach Klasse und Fach üben kann. Die Reihenfolge im Unterricht kann je nach Schule und Kanton abweichen.",
    parents: "Den Lernweg begleiten", parentsText: "Im Elternbereich findet ihr den gespeicherten Lernfortschritt und eure Kinderprofile. Persönliche Belohnungen können zusätzliche Motivation geben. Die Übersicht ist eine Orientierung, keine schulische Leistungsdiagnose.",
    sample: "Screenshot einer interaktiven Matheaufgabe in Cleverli, 5. Klasse.", preview: "Öffentliche Vorschau des Elternbereichs mit Beispieldaten, keine echten Lernergebnisse.",
    exercises: "Übungen nach Klasse und Fach finden", parentLink: "Elternbereich kennenlernen", guide: "Lernapp auf Handy, Tablet und Computer nutzen", teachers: "Cleverli im Unterricht einsetzen", cost: "Ausgewählte Übungen könnt ihr kostenlos ausprobieren. Premium kostet CHF 9.90 pro Monat oder CHF 99 pro Jahr für bis zu drei Kinderprofile. Für die siebentägige Premium-Testphase wird eine Zahlungskarte benötigt. Ohne Kündigung geht sie in das gewählte Abo über.", prices: "Preise und Angebote ansehen",
  },
  fr: {
    title: "Une plateforme pour apprendre en famille", intro: "Cleverli accompagne les enfants de la 1re à la 6e année pour réviser à la maison. L’application fonctionne dans le navigateur sur téléphone, tablette et ordinateur. Choisissez des exercices de mathématiques, allemand, sciences, langues ou médias et informatique.",
    practice: "Essayer, puis choisir ensemble", practiceText: "Des exercices courts, des indices et un retour immédiat facilitent le démarrage. Retrouvez les thèmes par année et matière. L’ordre des apprentissages peut varier selon l’école et le canton.", parents: "Accompagner les progrès", parentsText: "L’espace parents présente les progrès enregistrés et les profils des enfants. Des récompenses personnelles peuvent soutenir la motivation. Cette vue est un repère, pas une évaluation scolaire.", sample: "Capture d’un exercice interactif de mathématiques dans Cleverli, 5e année (en allemand).", preview: "Aperçu public de l’espace parents avec des données fictives, sans résultats réels (en allemand).", exercises: "Trouver des exercices par année et matière", parentLink: "Découvrir l’espace parents", guide: "Utiliser Cleverli sur vos appareils (guide en allemand)", teachers: "Utiliser Cleverli en classe", cost: "Certains exercices peuvent être essayés gratuitement. Premium coûte CHF 9.90 par mois ou CHF 99 par an pour trois profils enfants au maximum. L’essai Premium de sept jours nécessite une carte de paiement et se transforme en abonnement choisi sans résiliation.", prices: "Voir les prix et les offres",
  },
  it: {
    title: "Una piattaforma per imparare in famiglia", intro: "Cleverli accompagna i bambini dalla 1a alla 6a classe negli esercizi a casa. L’app funziona nel browser su telefono, tablet e computer. Scegliete esercizi di matematica, tedesco, scienze, lingue o media e informatica.", practice: "Provare e scegliere insieme", practiceText: "Esercizi brevi, suggerimenti e risposte immediate aiutano a iniziare. Gli argomenti sono organizzati per classe e materia. L’ordine può variare secondo la scuola e il cantone.", parents: "Accompagnare i progressi", parentsText: "L’area genitori mostra i progressi salvati e i profili dei bambini. Le ricompense personali possono sostenere la motivazione. La panoramica è un orientamento, non una valutazione scolastica.", sample: "Schermata di un esercizio interattivo di matematica in Cleverli, 5a classe (in tedesco).", preview: "Anteprima pubblica dell’area genitori con dati dimostrativi, non risultati reali (in tedesco).", exercises: "Trovare esercizi per classe e materia", parentLink: "Scoprire l’area genitori", guide: "Usare Cleverli sui tuoi dispositivi (guida in tedesco)", teachers: "Usare Cleverli in classe", cost: "Alcuni esercizi si possono provare gratuitamente. Premium costa CHF 9.90 al mese o CHF 99 all’anno per un massimo di tre profili bambini. La prova Premium di sette giorni richiede una carta di pagamento e diventa l’abbonamento scelto se non viene disdetta.", prices: "Vedere prezzi e offerte",
  },
  en: {
    title: "A learning platform for family life", intro: "Cleverli helps children in grades 1 to 6 practise at home. The learning app runs in the browser on phones, tablets and computers. Choose exercises in maths, German, science, languages or media and computing.", practice: "Try it, then choose together", practiceText: "Short exercises, hints and immediate feedback help children get started. Browse topics by grade and subject. Teaching order can vary by school and canton.", parents: "Support their learning", parentsText: "The parent area shows saved learning progress and child profiles. Personal rewards can support motivation. This overview is guidance, not a school assessment.", sample: "Screenshot of an interactive maths exercise in Cleverli, grade 5 (in German).", preview: "Public parent-area preview with illustrative data, not actual learning results (in German).", exercises: "Find exercises by grade and subject", parentLink: "Explore the parent area", guide: "Use Cleverli on your devices (German guide)", teachers: "Use Cleverli in the classroom", cost: "Selected exercises are free to try. Premium costs CHF 9.90 per month or CHF 99 per year for up to three child profiles. The seven-day Premium trial requires a payment card and converts to the selected subscription unless cancelled.", prices: "View prices and offers",
  },
};
export default function HomePlatformOverview() {
 const {lang}=useLang(); const c=copy[lang]??copy.de;
 return <section className="bg-green-50/60 px-4 py-12 sm:px-6" aria-labelledby="platform-overview"><div className="mx-auto max-w-5xl">
  <h2 id="platform-overview" className="text-2xl font-extrabold text-gray-900 sm:text-3xl">{c.title}</h2><p className="mt-4 max-w-3xl leading-7 text-gray-700">{c.intro}</p>
  <div className="mt-8 grid gap-6 md:grid-cols-2">{[{title:c.practice,text:c.practiceText,src:"/images/seo/mathe-uebung-live.png",caption:c.sample,height:1335,href:"/primarschule-uebungen",label:c.exercises},{title:c.parents,text:c.parentsText,src:"/images/seo/eltern-vorschau.png",caption:c.preview,height:850,href:"/parents",label:c.parentLink}].map(item=><article key={item.href} className="min-w-0 rounded-2xl border border-green-100 bg-white p-5"><h3 className="text-xl font-bold">{item.title}</h3><p className="mt-3 leading-7 text-gray-700">{item.text}</p><figure className="mt-5"><Image src={item.src} alt={item.caption} width={1000} height={item.height} sizes="(min-width:768px) 480px, 100vw" className="h-auto w-full rounded-xl border border-gray-200"/><figcaption className="mt-2 text-xs leading-5 text-gray-500">{item.caption}</figcaption></figure><Link href={item.href} className="mt-4 inline-flex min-h-11 items-center font-bold text-green-800 underline underline-offset-4">{item.label}</Link></article>)}</div>
  <CurriculumOverviewLink/><p className="max-w-3xl leading-7 text-gray-700">{c.cost}</p><div className="mt-4 flex flex-col gap-3 sm:flex-row sm:flex-wrap">{[["/lernapp-primarschule",c.guide],["/upgrade",c.prices],["/lehrpersonen",c.teachers]].map(([href,label])=><Link key={href} href={href} className="inline-flex min-h-11 items-center rounded-xl border border-green-200 bg-white px-4 py-3 font-semibold text-green-800 underline underline-offset-4">{label}</Link>)}</div>
 </div></section>;
}
