import fs from 'node:fs';import assert from 'node:assert/strict';
import {getTopics as baseTopics} from '../../../grade1-nmg-review/src/data';
import {localizeExercise as baseLoc} from '../../../grade1-nmg-review/src/lib/exerciseLocalization';
import {getTopics} from '../../src/data';import {localizeExercise} from '../../src/lib/exerciseLocalization';import {matchOrderedTextAnswer} from '../../src/lib/fillInBlankMatching';
const load=(f:string)=>fs.readFileSync(f,'utf8').trim().split('\n').map(x=>JSON.parse(x));
const old=load('.qa/grade2-math/baseline-de.jsonl'),now=load('.qa/grade2-math/current-de.jsonl');assert.equal(now.length,15190);const baseline=new Map(old.map(r=>[r.key,r]));const unit=now.filter(r=>r.grade===2&&r.subject==='math');assert.equal(unit.length,652);
let corrected=0,outside=0;const ledger=[];
for(const r of now){const b=baseline.get(r.key);assert.ok(b);if(r.grade!==2||r.subject!=='math'){assert.equal(r.hash,b.hash,r.key);outside++;continue;}const e=r.content;assert.equal(e.type,b.content.type);assert.equal(e.difficulty,b.content.difficulty);assert.equal(e.id,b.content.id);assert.equal(e.hints.length,2);assert.ok(e.hints.every((x:string)=>x.trim().length>5 || /^\d+[+×]\d+=\?$/.test(x)));assert.ok(!JSON.stringify(e).includes('ß'));if(e.type==='multiple-choice'){assert.equal(e.options.filter((x:string)=>x===e.answer).length,1);assert.equal(new Set(e.options).size,e.options.length);}if(e.type==='fill-in-blank'){assert.ok(matchOrderedTextAnswer(e.answer,e.answer));assert.ok(!matchOrderedTextAnswer('unpassende Antwort',e.answer));}const changed=r.hash!==b.hash;if(changed)corrected++;ledger.push({key:r.key,id:e.id,topic:r.topic,type:e.type,changed,beforeHash:b.hash,hash:r.hash,changedFields:Object.keys(e).filter(k=>JSON.stringify(e[k])!==JSON.stringify(b.content[k]))});}
assert.equal(corrected,385);assert.equal(outside,14538);
const by=new Map(unit.map(r=>[r.content.id,r.content]));const find=(id:string)=>{const hits=[...by].filter(([k])=>k===id||k.endsWith('-'+id));assert.equal(hits.length,1,id);return hits[0][1]};
for(const [id,answer]of Object.entries({z32:'89',z34:'54',z42:'25',a35:'12',a37:'18',a45:'6',a47:'19',u12:'halbe',u39:'90',lm18:'50',lm30:'150',lm38:'4',lm48:'20',g30:'Jede bekommt CHF 4.50',g40:'48',as40:'100',as48:'30',as50:'20',sy38:'4',sy42:'4',sy50:'2',sc21:'Ca. 30',sc23:'Ca. 60',sa25c:'8',dd11c:'Dienstag',dd15c:'Pizza',dd17c:'C',dd31c:'2A',dd35c:'Woche 3'}))assert.equal(find(id).answer,answer,id);
assert.deepEqual(find('z34').altAnswers,['63','72','81','90']);assert.equal(find('z33').options.filter((s:string)=>Number(s[0])===2*Number(s[1])).length,1);assert.equal(find('as45').options.filter((s:string)=>s.split('+').map(Number).reduce((a:number,b:number)=>a+b,0)===99).length,1);assert.equal(find('e38').pairs.length,4);assert.equal(new Set(find('e38').pairs.map((p:{label:string})=>p.label)).size,4);
for(const id of ['u39','lm18','lm28','lm30','lm36'])assert.ok(!find(id).sequentialAnswer,id);
let foreign=0;const a=baseTopics(2,'math'),b=getTopics(2,'math');for(const lang of ['fr','it','en']as const)for(let t=0;t<a.length;t++)for(let i=0;i<a[t].exercises.length;i++){assert.deepEqual(localizeExercise(b[t].exercises[i],lang),baseLoc(a[t].exercises[i],lang),lang+' '+a[t].exercises[i].id);foreign++;}assert.equal(foreign,1956);
fs.writeFileSync('.qa/grade2-math/review-ledger.json',JSON.stringify({records:ledger},null,2));fs.writeFileSync('.qa/grade2-math/test-review-result.json',JSON.stringify({status:'pass',reviewed:652,corrected,unchanged:652-corrected,outsideUnitUnchanged:outside,foreignLocalizedUnchanged:foreign,independentKeys:29},null,2));console.log('PASS652 reviewed;385 corrected;267 unchanged;14538 outside-unit hashes and1956 foreign-localized records unchanged;29 independent keys');
