#!/usr/bin/env python3
"""
Expands 11 LP21 topic types (across 22 file/topic instances) from 10 → 50 exercises each.
Difficulty spread per topic: 15 easy(1) + 20 medium(2) + 15 hard(3)
Existing 10 exercises are kept; this script adds 40 new ones per instance.
"""

import re, sys

# ─── EXERCISE DATA ─────────────────────────────────────────────────────────────
# Format: (id, type, difficulty, question_DE, question_EN, question_FR, question_IT,
#          answer, options_or_None, hints_DE, dragItems_or_None, dropZones_or_None,
#          dropAnswers_or_None, pairs_or_None)

def mc(id, diff, qDE, qEN, qFR, qIT, ans, opts, h1, h2):
    return {
        "id": id, "type": "multiple-choice", "difficulty": diff,
        "question": qDE, "questionEN": qEN, "questionFR": qFR, "questionIT": qIT,
        "answer": ans, "options": opts, "hints": [h1, h2]
    }

def fib(id, diff, qDE, qEN, qFR, qIT, ans, h1, h2):
    return {
        "id": id, "type": "fill-in-blank", "difficulty": diff,
        "question": qDE, "questionEN": qEN, "questionFR": qFR, "questionIT": qIT,
        "answer": ans, "hints": [h1, h2]
    }

def matching(id, diff, qDE, qEN, qFR, qIT, pairs, h1, h2):
    return {
        "id": id, "type": "matching", "difficulty": diff,
        "question": qDE, "questionEN": qEN, "questionFR": qFR, "questionIT": qIT,
        "answer": "all", "hints": [h1, h2], "pairs": pairs
    }

def dragdrop(id, diff, qDE, qEN, qFR, qIT, items, zones, answers, h1, h2):
    return {
        "id": id, "type": "drag-drop", "difficulty": diff,
        "question": qDE, "questionEN": qEN, "questionFR": qFR, "questionIT": qIT,
        "answer": "all", "hints": [h1, h2],
        "dragItems": items, "dropZones": zones, "dropAnswers": answers
    }

def mem(id, diff, qDE, qEN, qFR, qIT, pairs, h1, h2):
    return {
        "id": id, "type": "memory", "difficulty": diff,
        "question": qDE, "questionEN": qEN, "questionFR": qFR, "questionIT": qIT,
        "answer": "all", "hints": [h1, h2], "pairs": pairs
    }

# ═══════════════════════════════════════════════════════════════════════════════
# TOPIC EXERCISES DATA
# ═══════════════════════════════════════════════════════════════════════════════

# Each topic gets a function returning list of 40 exercises
# Naming convention: prefix + number (e.g. "ph1g1_11" for grade1 physik #11)

# ─── GRADE 1: PHYSIK-BEWEGUNG (prefix ph1g1_) ──────────────────────────────
def make_ph_g1():
    exs = []
    p = "ph"  # just extend existing ph numbering from 11
    # d1 ×11
    exs.append(mc(f"{p}11","1","Was passiert, wenn du auf einen Ball trittst? ⚽","What happens when you kick a ball? ⚽","Que se passe-t-il quand tu donnes un coup de pied dans un ballon ? ⚽","Cosa succede quando calci un pallone? ⚽","Er bewegt sich weg",["Er fängt an zu leuchten","Er bewegt sich weg","Er wird grösser","Er bleibt stehen"],"Kraft bringt Dinge in Bewegung.","Dein Fuss überträgt eine Kraft."))
    exs.append(fib(f"{p}12","1","Wenn du einen Stein loslässt, fällt er nach ___. 🪨","When you let go of a stone, it falls ___. 🪨","Quand tu lâches une pierre, elle tombe vers ___. 🪨","Quando lasci cadere un sasso, cade ___. 🪨","unten","Die Erde zieht alles an.","Schwerkraft wirkt immer nach unten."))
    exs.append(mc(f"{p}13","1","Was braucht ein Objekt, um sich zu bewegen? 💪","What does an object need to move? 💪","De quoi un objet a-t-il besoin pour se déplacer ? 💪","Di cosa ha bisogno un oggetto per muoversi? 💪","Eine Kraft",["Farbe","Eine Kraft","Wasser","Luft"],"Drücken oder Ziehen sind Kräfte.","Ohne Kraft bleibt alles ruhig."))
    exs.append(fib(f"{p}14","1","Ein Magnet hat zwei Pole: Nord und ___. 🧲","A magnet has two poles: North and ___. 🧲","Un aimant a deux pôles : Nord et ___. 🧲","Un magnete ha due poli: Nord e ___. 🧲","Süd","Denke an Kompass-Richtungen.","N und S sind die zwei Pole."))
    exs.append(mc(f"{p}15","1","Was zieht einen Magneten an? 🧲","What does a magnet attract? 🧲","Qu'est-ce qu'un aimant attire ? 🧲","Cosa attrae un magnete? 🧲","Eisen",["Holz","Plastik","Eisen","Glas"],"Magnete haften am Kühlschrank.","Eisen und Stahl werden angezogen."))
    exs.append(fib(f"{p}16","1","Wenn zwei gleiche Magnetpole zusammenkommen, ___ sie sich. 🧲","When two identical magnetic poles meet, they ___ each other. 🧲","Quand deux pôles identiques se rencontrent, ils se ___. 🧲","Quando due poli identici si incontrano, si ___. 🧲","abstossen","Gleich und gleich…","Nord + Nord = abstossen."))
    exs.append(mc(f"{p}17","1","Was ist eine Kraft? 💪","What is a force? 💪","Qu'est-ce qu'une force ? 💪","Che cos'è una forza? 💪","Ein Drücken oder Ziehen",["Ein Farbe","Ein Drücken oder Ziehen","Ein Tier","Eine Zahl"],"Drücken und Ziehen sind Kräfte.","Kräfte verändern Bewegung."))
    exs.append(fib(f"{p}18","1","Wasser fliesst immer nach ___. 🌊","Water always flows ___. 🌊","L'eau coule toujours vers ___. 🌊","L'acqua scorre sempre verso ___. 🌊","unten","Die Schwerkraft zieht Wasser.","Flüsse fliessen bergab."))
    exs.append(mc(f"{p}19","1","Was macht eine Feder? 🌀","What does a spring do? 🌀","Que fait un ressort ? 🌀","Cosa fa una molla? 🌀","Sie kann sich zusammendrücken und ausdehnen",["Sie leuchtet","Sie kann sich zusammendrücken und ausdehnen","Sie fliegt","Sie sinkt"],"Trampoline haben Federn.","Federn speichern Kraft."))
    exs.append(mc(f"{p}20","1","Was ist Reibung? 🛞","What is friction? 🛞","Qu'est-ce que le frottement ? 🛞","Che cos'è l'attrito? 🛞","Eine Kraft, die Bewegung bremst",["Eine Kraft, die beschleunigt","Eine Kraft, die Bewegung bremst","Schwerkraft","Magnetismus"],"Wenn zwei Flächen sich berühren und bewegen.","Schuhsohlen haben Reibung auf dem Boden."))
    exs.append(fib(f"{p}21","1","Ein Hammer schlägt einen Nagel in die Wand, weil er eine ___ auf ihn überträgt.","A hammer drives a nail into the wall because it transfers a ___ to it.","Un marteau enfonce un clou dans le mur parce qu'il lui transmet une ___.","Un martello conficca un chiodo nel muro perché trasferisce una ___ ad esso.","Kraft","Was überträgt der Hammer auf den Nagel?","Druckkraft von oben."))
    # d2 ×15
    exs.append(mc(f"{p}22","2","Was ist ein Hebelarm? ⚖️","What is a lever arm? ⚖️","Qu'est-ce qu'un bras de levier ? ⚖️","Che cos'è un braccio di leva? ⚖️","Der Abstand vom Drehpunkt zur wirkenden Kraft",["Der Abstand vom Drehpunkt zur wirkenden Kraft","Die Farbe des Hebels","Das Gewicht","Die Länge des Seils"],"Eine Wippe ist ein Hebel.","Drehpunkt ist die Mitte."))
    exs.append(fib(f"{p}23","2","Wenn ein Objekt dichter als Wasser ist, ___ es. 🌊","If an object is denser than water, it ___. 🌊","Si un objet est plus dense que l'eau, il ___. 🌊","Se un oggetto è più denso dell'acqua, ___. 🌊","sinkt","Stein ist dichter als Wasser.","Holz ist leichter als Wasser."))
    exs.append(mc(f"{p}24","2","Was beschleunigt ein Objekt auf einer glatten Fläche mehr als auf einer rauen? 🛞","What makes an object speed up more on a smooth surface? 🛞","Qu'est-ce qui fait qu'un objet accélère plus sur une surface lisse ? 🛞","Cosa fa accelerare di più un oggetto su una superficie liscia? 🛞","Weniger Reibung",["Mehr Reibung","Weniger Reibung","Mehr Schwerkraft","Magnetismus"],"Eis hat wenig Reibung.","Je glatter, desto weniger Widerstand."))
    exs.append(fib(f"{p}25","2","Ein Rad hat wenig Reibung, weil es sich ___. 🚲","A wheel has little friction because it ___. 🚲","Une roue a peu de frottement parce qu'elle ___. 🚲","Una ruota ha poca attrito perché ___. 🚲","dreht","Rollen statt Gleiten = weniger Reibung.","Fahrräder fahren leicht dank Rädern."))
    exs.append(mc(f"{p}26","2","Was ist Gewichtskraft? ⚖️","What is weight force? ⚖️","Qu'est-ce que la force gravitationnelle ? ⚖️","Che cos'è la forza peso? ⚖️","Die Kraft, mit der die Erde ein Objekt anzieht",["Die Stärke eines Muskels","Die Kraft, mit der die Erde ein Objekt anzieht","Magnetkraft","Die Kraft des Windes"],"Ein Gewicht drückt auf eine Waage.","Schwer = grosse Gewichtskraft."))
    exs.append(dragdrop(f"{p}27","2","Was zieht Magnete an oder stösst sie ab? 🧲","What attracts or repels magnets? 🧲","Qu'est-ce qui attire ou repousse les aimants ? 🧲","Cosa attrae o respinge i magneti? 🧲",[{"id":"np1","label":"Nord + Süd"},{"id":"np2","label":"Nord + Nord"},{"id":"np3","label":"Süd + Süd"},{"id":"np4","label":"Süd + Nord"}],[{"id":"anzieht","label":"Zieht an"},{"id":"abstösst","label":"Stösst ab"}],{"np1":"anzieht","np2":"abstösst","np3":"abstösst","np4":"anzieht"},"Gleiche Pole stossen ab.","Verschiedene Pole ziehen an."))
    exs.append(mc(f"{p}28","2","Warum fliegt ein Vogel und ein Stein fällt? 🦅🪨","Why does a bird fly and a stone fall? 🦅🪨","Pourquoi un oiseau vole-t-il et une pierre tombe-t-elle ? 🦅🪨","Perché un uccello vola e un sasso cade? 🦅🪨","Der Vogel erzeugt mit den Flügeln Auftrieb",["Beide fliegen","Der Vogel erzeugt mit den Flügeln Auftrieb","Steine sind magnetisch","Vögel haben keine Schwerkraft"],"Flügel erzeugen Auftrieb.","Schwerkraft zieht den Stein nach unten."))
    exs.append(fib(f"{p}29","2","Das Gegenteil von Ruhe ist ___. 🏃","The opposite of rest is ___. 🏃","Le contraire du repos est ___. 🏃","Il contrario di riposo è ___. 🏃","Bewegung","Was macht ein laufendes Kind?","Ruhe → Bewegung."))
    exs.append(mc(f"{p}30","2","Was ist Gleichgewicht? ⚖️","What is balance? ⚖️","Qu'est-ce que l'équilibre ? ⚖️","Che cos'è l'equilibrio? ⚖️","Wenn alle Kräfte sich aufheben",["Wenn eine Kraft grösser ist","Wenn alle Kräfte sich aufheben","Wenn ein Objekt fällt","Wenn ein Objekt beschleunigt"],"Auf einer Wippe: gleiche Gewichte auf beiden Seiten.","Balance = alle Kräfte ausgewogen."))
    exs.append(fib(f"{p}31","2","Wenn du auf einem Skateboard stehst und stillstehst, ist die Summe der Kräfte ___. 🛹","If you stand still on a skateboard, the sum of forces is ___. 🛹","Quand tu te tiens immobile sur un skateboard, la somme des forces est ___. 🛹","Se stai fermo su uno skateboard, la somma delle forze è ___. 🛹","null/gleich null","Stillstand = keine Nettokraft.","Gleichgewicht der Kräfte."))
    exs.append(mc(f"{p}32","2","Wozu dient ein Sicherheitsgurt im Auto? 🚗","Why do cars have seatbelts? 🚗","Pourquoi les voitures ont-elles des ceintures de sécurité ? 🚗","Perché le auto hanno le cinture di sicurezza? 🚗","Er hält dich bei starker Verzögerung fest",["Er macht das Auto schneller","Er hält dich bei starker Verzögerung fest","Er erspart Benzin","Er ist nur Dekoration"],"Bei Bremsung wirkt eine grosse Kraft.","Der Gurt überträgt die Kraft auf den ganzen Körper."))
    exs.append(fib(f"{p}33","2","Luft hat ___, deshalb bremst sie schnell bewegte Objekte. 🌬️","Air has ___, so it slows fast-moving objects. 🌬️","L'air a ___, c'est pourquoi il ralentit les objets qui se déplacent vite. 🌬️","L'aria ha ___, ecco perché rallenta gli oggetti che si muovono velocemente. 🌬️","Luftwiderstand","Was bremst ein Fallschirm?","Luft setzt Bewegung Widerstand entgegen."))
    exs.append(mc(f"{p}34","2","Was ist eine schiefe Ebene? 📐","What is an inclined plane? 📐","Qu'est-ce qu'un plan incliné ? 📐","Che cos'è un piano inclinato? 📐","Eine geneigte Fläche, die das Heben erleichtert",["Ein Spiegel","Eine geneigte Fläche, die das Heben erleichtert","Eine Brücke","Ein Rad"],"Rampen und Rutschbahnen sind schiefe Ebenen.","Man braucht weniger Kraft, aber dafür mehr Weg."))
    exs.append(fib(f"{p}35","2","Wenn eine Kraft parallel zu einer Fläche wirkt und Dinge bewegt, nennt man das ___.","When a force acts parallel to a surface and moves things, we call that ___.","Quand une force agit parallèlement à une surface et déplace des choses, on appelle ça ___.","Quando una forza agisce parallelamente a una superficie e muove le cose, lo chiamiamo ___.","Schub/Druckkraft","Schub bringt Raketen ins All.","Denke an einen stossenden Finger."))
    exs.append(mc(f"{p}36","2","Was braucht ein Pendel, um zu schwingen? ⏱️","What does a pendulum need to swing? ⏱️","De quoi a besoin un pendule pour osciller ? ⏱️","Di cosa ha bisogno un pendolo per oscillare? ⏱️","Schwerkraft und eine Auslenkung",["Magnetismus","Schwerkraft und eine Auslenkung","Reibung","Wind"],"Uhren nutzen Pendel.","Schwerkraft zieht das Pendel zurück."))
    # d3 ×14
    exs.append(fib(f"{p}37","3","Das Gesetz der Trägheit besagt: Ein Objekt behält seine Bewegung, wenn keine ___ auf es wirkt.","The law of inertia: an object keeps its motion if no ___ acts on it.","La loi de l'inertie : un objet garde son mouvement si aucune ___ n'agit sur lui.","La legge di inerzia: un oggetto mantiene il suo moto se nessuna ___ agisce su di esso.","Kraft","Was braucht es, um einen rollenden Ball anzuhalten?","Ohne Kraft: keine Änderung der Bewegung."))
    exs.append(mc(f"{p}38","3","Was bedeutet «Kraft = Masse × Beschleunigung»? ⚗️","What does 'Force = Mass × Acceleration' mean? ⚗️","Que signifie 'Force = Masse × Accélération' ? ⚗️","Cosa significa 'Forza = Massa × Accelerazione'? ⚗️","Je grösser die Masse, desto mehr Kraft braucht man für gleiche Beschleunigung",["Es ist nur eine Zahl","Je grösser die Masse, desto mehr Kraft braucht man für gleiche Beschleunigung","Leichte Objekte fallen schneller","Kraft und Masse sind gleich"],"Ein schwerer LKW braucht mehr Kraft als ein Velo.","Newtons zweites Gesetz."))
    exs.append(fib(f"{p}39","3","Die Einheit der Kraft ist ___. (Nach einem englischen Wissenschaftler benannt)","The unit of force is ___. (Named after an English scientist)","L'unité de force est ___. (Nommée d'après un scientifique anglais)","L'unità di forza è ___. (Intitolata a uno scienziato inglese)","Newton","Isaac Newton entdeckte die Schwerkraft.","Kraft wird in N gemessen."))
    exs.append(mc(f"{p}40","3","Was passiert mit der Schwerkraft, wenn man weiter von der Erde entfernt ist? 🌍","What happens to gravity as you move further from Earth? 🌍","Qu'arrive-t-il à la gravité quand on s'éloigne de la Terre ? 🌍","Cosa succede alla gravità man mano che ci si allontana dalla Terra? 🌍","Sie wird schwächer",["Sie bleibt gleich","Sie wird stärker","Sie verschwindet sofort","Sie kehrt sich um"],"Im Weltall wiegt man weniger.","Schwerkraft nimmt mit Abstand ab."))
    exs.append(fib(f"{p}41","3","Zwei Magnete: Nord und Süd ziehen sich an. Zwei Nordpole ___ sich ab.","Two magnets: North and South attract. Two North poles ___ each other.","Deux aimants : Nord et Sud s'attirent. Deux pôles Nord se ___.","Due magneti: Nord e Sud si attraggono. Due poli Nord si ___.","stossen","Gleiche Pole stossen ab.","Verschiedene Pole: Anziehung."))
    exs.append(mc(f"{p}42","3","Was ist kinetische Energie? 🏃","What is kinetic energy? 🏃","Qu'est-ce que l'énergie cinétique ? 🏃","Che cos'è l'energia cinetica? 🏃","Energie eines bewegten Objekts",["Energie eines ruhenden Objekts","Energie eines bewegten Objekts","Magnetische Energie","Lichtenergie"],"Ein rollender Ball hat kinetische Energie.","Kinetisch = in Bewegung."))
    exs.append(fib(f"{p}43","3","Wenn ein Apfel vom Baum fällt, wird seine Lageenergie zu ___energie. 🍎","When an apple falls from a tree, its potential energy becomes ___ energy. 🍎","Quand une pomme tombe d'un arbre, son énergie potentielle devient énergie ___. 🍎","Quando una mela cade da un albero, la sua energia potenziale diventa energia ___. 🍎","Bewegungs","Lageenergie → Kinetische Energie.","Was macht ein fallender Apfel?"))
    exs.append(mc(f"{p}44","3","Was beschreibt Newtons drittes Gesetz? ⚙️","What describes Newton's third law? ⚙️","Que décrit la troisième loi de Newton ? ⚙️","Cosa descrive la terza legge di Newton? ⚙️","Actio gleich Reactio: jede Kraft hat eine gleich grosse Gegenkraft",["Kraft = Masse × Beschleunigung","Actio gleich Reactio: jede Kraft hat eine gleich grosse Gegenkraft","Trägheitsgesetz","Gravitationsgesetz"],"Wenn du gegen eine Wand drückst, drückt sie zurück.","Actio = Reactio."))
    exs.append(fib(f"{p}45","3","Je grösser die Masse eines Objekts, desto ___ ist seine Trägheit.","The greater the mass of an object, the ___ its inertia.","Plus la masse d'un objet est grande, plus son inertie est ___.","Maggiore è la massa di un oggetto, maggiore è la sua inerzia; quindi la sua inerzia è ___.","grösser","Ein schwerer LKW ist schwerer anzuhalten.","Trägheit ~ Masse."))
    exs.append(mc(f"{p}46","3","Warum sinkt ein Stück Eisen im Wasser, aber ein Schiff nicht? 🚢","Why does a piece of iron sink but a ship doesn't? 🚢","Pourquoi un morceau de fer coule-t-il mais pas un navire ? 🚢","Perché un pezzo di ferro affonda ma una nave no? 🚢","Das Schiff ist innen hohl, daher hat es eine geringere Dichte als Wasser",["Schiffe sind aus Holz","Das Schiff ist innen hohl, daher hat es eine geringere Dichte als Wasser","Eisenpole sind magnetisch","Schiffe haben Motoren"],"Auftrieb = verdrängtes Wasservolumen × Dichte.","Ein hohles Objekt verdrängt mehr Wasser."))
    exs.append(fib(f"{p}47","3","Das Prinzip des Archimedes: Ein Objekt im Wasser wird mit einer Kraft nach oben gedrückt, die gleich dem ___ des verdrängten Wassers ist.","Archimedes' principle: an object in water is pushed up by a force equal to the ___ of the displaced water.","Le principe d'Archimède : un objet dans l'eau est poussé vers le haut avec une force égale au ___ de l'eau déplacée.","Il principio di Archimede: un oggetto in acqua viene spinto verso l'alto con una forza pari al ___ dell'acqua spostata.","Gewicht","Auftrieb = Gewicht des verdrängten Wassers.","Archimedes entdeckte dies in der Badewanne."))
    exs.append(mc(f"{p}48","3","Was ist eine zusammengesetzte Maschine? ⚙️","What is a compound machine? ⚙️","Qu'est-ce qu'une machine complexe ? ⚙️","Che cos'è una macchina composta? ⚙️","Eine Kombination aus mehreren einfachen Maschinen",["Eine einzige einfache Maschine","Eine elektrische Maschine","Eine Kombination aus mehreren einfachen Maschinen","Eine Maschine ohne Teile"],"Ein Fahrrad kombiniert Hebel, Rad, Seil.","Zusammengesetzt = mehrere einfache Maschinen."))
    exs.append(fib(f"{p}49","3","Energie kann nicht erzeugt oder vernichtet werden – das nennt man den Satz von der ___erhaltung.","Energy cannot be created or destroyed – this is called the law of energy ___.","L'énergie ne peut être créée ni détruite – c'est la loi de la ___ d'énergie.","L'energia non può essere creata né distrutta – questo si chiama legge della ___ dell'energia.","Energie","Physikalisches Grundgesetz.","Energie bleibt immer erhalten."))
    exs.append(mc(f"{p}50","3","Was ist der Unterschied zwischen Masse und Gewicht? ⚖️","What is the difference between mass and weight? ⚖️","Quelle est la différence entre masse et poids ? ⚖️","Qual è la differenza tra massa e peso? ⚖️","Masse ist unveränderlich; Gewicht hängt von der Schwerkraft ab",["Beide sind das Gleiche","Masse ist unveränderlich; Gewicht hängt von der Schwerkraft ab","Gewicht ist grösser als Masse","Masse ist auf dem Mond grösser"],"Auf dem Mond wiegt man weniger, aber die Masse bleibt gleich.","Masse in kg, Gewicht in Newton."))
    return exs

# Grade 2 physik-bewegung (same topic, slightly more complex, suffix 'b')
def make_ph_g2():
    exs = []
    p = "ph"
    # d1 ×11
    exs.append(mc(f"{p}11b","1","Was ist Reibungskraft? 🛞","What is friction force? 🛞","Qu'est-ce que la force de frottement ? 🛞","Che cos'è la forza d'attrito? 🛞","Eine Kraft, die Bewegung verlangsamt",["Eine Kraft, die beschleunigt","Eine Kraft, die Bewegung verlangsamt","Magnetismus","Schwerkraft"],"Reibung entsteht an Oberflächen.","Sie kann Wärme erzeugen."))
    exs.append(fib(f"{p}12b","1","Die Schwerkraft auf der Erde zieht alle Objekte nach ___. 🌍","Gravity on Earth pulls all objects ___. 🌍","La gravité sur Terre attire tous les objets vers ___. 🌍","La gravità sulla Terra attira tutti gli oggetti verso ___. 🌍","unten","Alles fällt nach unten.","Die Erde zieht an."))
    exs.append(mc(f"{p}13b","1","Was ist der Unterschied zwischen Drücken und Ziehen? 💪","What is the difference between pushing and pulling? 💪","Quelle est la différence entre pousser et tirer ? 💪","Qual è la differenza tra spingere e tirare? 💪","Beide sind Kräfte, wirken aber in verschiedene Richtungen",["Es gibt keinen Unterschied","Drücken ist stärker","Beide sind Kräfte, wirken aber in verschiedene Richtungen","Ziehen hat keine Wirkung"],"Drücken = von dir weg. Ziehen = zu dir hin.","Beide sind Kräfte."))
    exs.append(fib(f"{p}14b","1","Ein Schiff schwimmt, weil der ___ gleich gross ist wie die Gewichtskraft. 🚢","A ship floats because the ___ equals the gravitational force. 🚢","Un bateau flotte parce que la ___ est égale à la force gravitationnelle. 🚢","Una nave galleggia perché la ___ è uguale alla forza gravitazionale. 🚢","Auftrieb","Auftrieb = Gewicht des verdrängten Wassers.","Kräftegleichgewicht."))
    exs.append(mc(f"{p}15b","1","Was erzeugt ein Hebel? ⚖️","What does a lever produce? ⚖️","Que produit un levier ? ⚖️","Cosa produce una leva? ⚖️","Eine mechanische Kraft-Verstärkung",["Elektrischen Strom","Eine mechanische Kraft-Verstärkung","Wärme","Licht"],"Wippe und Brechstange sind Hebel.","Mit wenig Kraft viel bewegen."))
    exs.append(fib(f"{p}16b","1","Wenn zwei gleiche Magnetpole zusammenkommen, ___ sie sich. 🧲","When two identical magnetic poles meet, they ___ each other. 🧲","Quand deux pôles magnétiques identiques se rencontrent, ils se ___. 🧲","Quando due poli magnetici identici si incontrano, si ___. 🧲","abstossen","Nord+Nord = abstossen.","Verschiedene Pole ziehen an."))
    exs.append(mc(f"{p}17b","1","Was zieht Gegenstände nach unten auf die Erde? 🌍","What pulls objects down to Earth? 🌍","Qu'est-ce qui tire les objets vers la Terre ? 🌍","Cosa tira gli oggetti verso la Terra? 🌍","Die Schwerkraft",["Der Wind","Die Schwerkraft","Ein Magnet","Der Mond"],"Alles fällt, wenn man es loslässt.","Newton und der Apfel."))
    exs.append(fib(f"{p}18b","1","Ein Ball, der rollt, hat ___ als ein Ball der stillsteht. 🎯","A ball that rolls has ___ than one that stands still. 🎯","Une balle qui roule a ___ qu'une balle immobile. 🎯","Una palla che rotola ha ___ rispetto a una ferma. 🎯","mehr Bewegungsenergie","Bewegung = Energie.","Kinetische Energie."))
    exs.append(mc(f"{p}19b","1","Was ist Auftrieb? 🚢","What is buoyancy? 🚢","Qu'est-ce que la poussée d'Archimède ? 🚢","Che cos'è la spinta di Archimede? 🚢","Die Kraft, die Objekte im Wasser nach oben drückt",["Die Kraft nach unten","Die Kraft, die Objekte im Wasser nach oben drückt","Schwerkraft","Magnetismus"],"Schiffe schwimmen dank Auftrieb.","Wasser drückt nach oben."))
    exs.append(mc(f"{p}20b","1","Was beeinflusst, ob ein Objekt schwimmt oder sinkt? 🌊","What affects whether an object floats or sinks? 🌊","Qu'est-ce qui influe sur le fait qu'un objet flotte ou coule ? 🌊","Cosa influisce sul fatto che un oggetto galleggi o affondi? 🌊","Seine Dichte im Vergleich zu Wasser",["Seine Farbe","Seine Dichte im Vergleich zu Wasser","Seine Temperatur","Seine Form allein"],"Holz ist weniger dicht als Wasser.","Dichter als Wasser = sinkt."))
    exs.append(fib(f"{p}21b","1","Kräfte haben eine Richtung und eine ___. 💪","Forces have a direction and a ___. 💪","Les forces ont une direction et une ___. 💪","Le forze hanno una direzione e una ___. 💪","Stärke/Grösse","Was beschreibt eine Kraft vollständig?","Grösse und Richtung."))
    # d2 ×15
    exs.append(mc(f"{p}22b","2","Was ist das Prinzip hinter einem Seil und einer Umlenkrolle? 🔄","What is the principle behind a rope and pulley? 🔄","Quel est le principe d'une corde et d'une poulie ? 🔄","Qual è il principio dietro a una fune e una carrucola? 🔄","Die Kraft wird in eine andere Richtung umgelenkt und evtl. verkleinert",["Nur Umlenkung der Richtung","Die Kraft wird in eine andere Richtung umgelenkt und evtl. verkleinert","Reibung wird erhöht","Schwerkraft erhöht sich"],"Kran und Seilbahn nutzen Rollen.","Richtung und Stärke ändern sich."))
    exs.append(fib(f"{p}23b","2","Je glatter eine Oberfläche, desto ___ ist die Reibungskraft. 🧊","The smoother a surface, the ___ the friction force. 🧊","Plus une surface est lisse, plus la force de frottement est ___. 🧊","Più una superficie è liscia, più la forza d'attrito è ___. 🧊","kleiner","Eis hat wenig Reibung.","Glatt = wenig Widerstand."))
    exs.append(mc(f"{p}24b","2","Was ist mechanischer Vorteil? ⚙️","What is mechanical advantage? ⚙️","Qu'est-ce que l'avantage mécanique ? ⚙️","Che cos'è il vantaggio meccanico? ⚙️","Wenn man mit weniger Kraft die gleiche Arbeit verrichtet",["Wenn man schneller arbeitet","Wenn man mit weniger Kraft die gleiche Arbeit verrichtet","Wenn man mehr Kraft braucht","Wenn man mehr Zeit braucht"],"Ein Hebel gibt mechanischen Vorteil.","Weniger Kraft, mehr Weg."))
    exs.append(fib(f"{p}25b","2","Wenn sich ein Ball in einer Kurve bewegt, wirkt eine ___ nach innen auf ihn. 🔄","When a ball moves in a curve, a ___ acts inward on it. 🔄","Quand une balle se déplace en courbe, une ___ agit vers l'intérieur sur elle. 🔄","Quando una palla si muove in curva, una ___ agisce verso l'interno su di essa. 🔄","Zentripetalkraft","Kreisbewegung braucht eine innere Kraft.","Schleuder-Beispiel."))
    exs.append(mc(f"{p}26b","2","Was ist Impuls? ⚡","What is momentum? ⚡","Qu'est-ce que l'impulsion (quantité de mouvement) ? ⚡","Che cos'è la quantità di moto? ⚡","Masse × Geschwindigkeit eines Objekts",["Kraft × Zeit","Masse × Geschwindigkeit eines Objekts","Energie × Richtung","Gewicht × Reibung"],"Schwere und schnelle Objekte haben viel Impuls.","p = m × v."))
    exs.append(mc(f"{p}27b","2","Warum ist ein Fallschirm sicherer als ohne? 🪂","Why is a parachute safer than without? 🪂","Pourquoi un parachute est-il plus sûr que sans ? 🪂","Perché un paracadute è più sicuro che senza? 🪂","Er vergrössert den Luftwiderstand",["Er macht schwerer","Er vergrössert den Luftwiderstand","Er hat Magnetkraft","Er ist aus Metall"],"Grosse Fläche = mehr Luftwiderstand.","Fallschirmspringer fallen langsam."))
    exs.append(fib(f"{p}28b","2","Das Zahnrad überträgt Kräfte: Ein grosses Zahnrad dreht ein kleines schnell, aber mit ___ Kraft. ⚙️","A gear transmits forces: a large gear turns a small one fast, but with ___ force. ⚙️","Un engrenage transmet des forces : un grand pignon fait tourner un petit vite, mais avec une ___ force. ⚙️","Un ingranaggio trasmette forze: un grande ingranaggio fa girare uno piccolo velocemente, ma con ___ forza. ⚙️","kleinerer","Grosses Zahnrad = schnell aber wenig Kraft.","Übersetzungsverhältnis."))
    exs.append(mc(f"{p}29b","2","Was ist eine einfache Maschine? ⚙️","What is a simple machine? ⚙️","Qu'est-ce qu'une machine simple ? ⚙️","Che cos'è una macchina semplice? ⚙️","Ein Gerät, das Kraft oder Richtung ändert (Hebel, Rad, Rampe)",["Ein elektrisches Gerät","Ein Gerät, das Kraft oder Richtung ändert (Hebel, Rad, Rampe)","Ein Computer","Eine Uhr"],"Hebel, schiefe Ebene, Rolle sind einfache Maschinen.","Sie machen Arbeit leichter."))
    exs.append(fib(f"{p}30b","2","Die Sonne zieht Planeten durch ___ in ihrer Umlaufbahn. ☀️","The sun holds planets in orbit through ___. ☀️","Le soleil maintient les planètes en orbite grâce à ___. ☀️","Il sole mantiene i pianeti in orbita tramite ___. ☀️","Schwerkraft/Gravitation","Planeten umkreisen die Sonne.","Schwerkraft wirkt auch im Weltall."))
    exs.append(mc(f"{p}31b","2","Was bedeutet es, wenn eine Schaukel schwingt? 🎡","What does it mean when a swing oscillates? 🎡","Que signifie quand une balançoire oscille ? 🎡","Cosa significa quando un'altalena oscilla? 🎡","Sie wandelt Lage- und Bewegungsenergie um",["Sie erzeugt Magnetismus","Sie wandelt Lage- und Bewegungsenergie um","Sie verliert Schwerkraft","Sie dreht sich"],"Oben: viel Lageenergie. Unten: viel Bewegungsenergie.","Pendelbewegung = Energieumwandlung."))
    exs.append(fib(f"{p}32b","2","Ein Objekt auf einem Hang neigt zum Rutschen wegen ___ und Schwerkraft. ⛰️","An object on a slope tends to slide due to ___ and gravity. ⛰️","Un objet sur une pente tend à glisser à cause de ___ et de la gravité. ⛰️","Un oggetto su un pendio tende a scivolare a causa di ___ e gravità. ⛰️","Hangabtriebskraft","Bergab = Schwerkraft zieht.","Hangkraft = Teil der Schwerkraft."))
    exs.append(mc(f"{p}33b","2","Was ist Drehmoment? 🔧","What is torque? 🔧","Qu'est-ce que le couple ? 🔧","Che cos'è il momento torcente? 🔧","Kraft × Abstand vom Drehpunkt = Drehtendenz",["Kraft + Gewicht","Kraft × Abstand vom Drehpunkt = Drehtendenz","Masse × Beschleunigung","Energie × Zeit"],"Schraubenschlüssel: langer Griff = mehr Drehmoment.","Drehmoment = Hebelwirkung."))
    exs.append(fib(f"{p}34b","2","Wenn eine Feder gedehnt wird, möchte sie wieder in ihre ___ zurück. 🌀","When a spring is stretched, it wants to return to its ___. 🌀","Quand un ressort est étiré, il veut revenir à sa ___ d'origine. 🌀","Quando una molla viene allungata, vuole tornare alla sua ___. 🌀","Ausgangslage/Ruhelage","Federn sind elastisch.","Rückstellkraft."))
    exs.append(mc(f"{p}35b","2","Warum läuft ein Fahrrad nicht von selbst weg wenn man es auf ebenem Boden loslässt? 🚲","Why doesn't a bike roll away on its own on flat ground? 🚲","Pourquoi un vélo ne roule-t-il pas tout seul sur terrain plat ? 🚲","Perché una bici non va via da sola su terreno piatto? 🚲","Reibung bremst es",["Magnetismus hält es","Reibung bremst es","Es hat keine Räder","Die Schwerkraft hält es"],"Reibung der Reifen auf dem Boden.","Ohne Hangkraft kein Antrieb."))
    exs.append(fib(f"{p}36b","2","Die Erdanziehungskraft beträgt auf der Erde etwa ___ m/s² (Fallbeschleunigung).","Earth's gravitational acceleration is about ___ m/s².","L'accélération gravitationnelle terrestre est d'environ ___ m/s².","L'accelerazione gravitazionale terrestre è circa ___ m/s².","9,81","g ≈ 9,81 m/s².","Objekte beschleunigen beim Fall."))
    # d3 ×14
    exs.append(mc(f"{p}37b","3","Was beschreibt das Hooksche Gesetz? 🌀","What describes Hooke's Law? 🌀","Que décrit la loi de Hooke ? 🌀","Cosa descrive la legge di Hooke? 🌀","Kraft = Federkonstante × Dehnung (F = k×x)",["Kraft = Masse × Beschleunigung","Kraft = Federkonstante × Dehnung (F = k×x)","Auftrieb = Gewicht","Energie = Masse × c²"],"Eine Feder dehnt sich proportional zur Kraft.","F = k×x."))
    exs.append(fib(f"{p}38b","3","Newtons 1. Gesetz: Ein Körper ohne äussere ___ behält seinen Bewegungszustand. ⚗️","Newton's 1st Law: A body without external ___ maintains its state of motion.","1re loi de Newton : un corps sans ___ externe maintient son état de mouvement.","1a legge di Newton: un corpo senza ___ esterne mantiene il suo stato di moto.","Kraft","Trägheitsprinzip.","Ohne Kraft = keine Änderung."))
    exs.append(mc(f"{p}39b","3","Was ist Arbeit in der Physik? (W = F × s) ⚙️","What is work in physics? (W = F × d) ⚙️","Qu'est-ce que le travail en physique ? (W = F × d) ⚙️","Che cos'è il lavoro in fisica? (W = F × s) ⚙️","Kraft × Weg (gemessen in Joule)",["Masse × Beschleunigung","Kraft × Weg (gemessen in Joule)","Energie ÷ Zeit","Spannung × Strom"],"W = F × s. Joule = N×m.","Physikalische Arbeit ≠ Hausaufgaben."))
    exs.append(fib(f"{p}40b","3","Leistung (P) = Arbeit (W) ÷ ___. (gemessen in Watt)","Power (P) = Work (W) ÷ ___. (measured in Watts)","Puissance (P) = Travail (W) ÷ ___. (en Watts)","Potenza (P) = Lavoro (W) ÷ ___. (in Watt)","Zeit","Schnellere Arbeit = mehr Leistung.","P = W/t. Einheit: Watt."))
    exs.append(mc(f"{p}41b","3","Was ist Potential- und Kinetische Energie zusammen? 🏔️","What is potential and kinetic energy together? 🏔️","Qu'est-ce que l'énergie potentielle et cinétique ensemble ? 🏔️","Cos'è l'energia potenziale e cinetica insieme? 🏔️","Mechanische Energie",["Chemische Energie","Elektrische Energie","Mechanische Energie","Thermische Energie"],"E_mech = E_pot + E_kin.","Mechanisch = Bewegung und Lage."))
    exs.append(fib(f"{p}42b","3","Bei einem elastischen Stoss bleibt die ___ erhalten. (Physik)","In an elastic collision, the ___ is conserved.","Dans un choc élastique, la ___ est conservée.","In una collisione elastica, la ___ è conservata.","kinetische Energie/Energie","Elastisch = keine bleibende Verformung.","Billard: elastischer Stoss."))
    exs.append(mc(f"{p}43b","3","Was ist der Unterschied zwischen Vektor- und Skalargrossen? 📐","What is the difference between vector and scalar quantities? 📐","Quelle est la différence entre grandeurs vectorielles et scalaires ? 📐","Qual è la differenza tra grandezze vettoriali e scalari? 📐","Vektoren haben Betrag und Richtung; Skalare nur Betrag",["Vektoren sind grösser","Beide sind gleich","Vektoren haben Betrag und Richtung; Skalare nur Betrag","Skalare haben Richtung"],"Kraft ist ein Vektor, Temperatur ein Skalar.","Richtung wichtig = Vektor."))
    exs.append(fib(f"{p}44b","3","Ein Körper im freien Fall erreicht nach 1 Sekunde eine Geschwindigkeit von etwa ___ m/s.","A body in free fall reaches a speed of about ___ m/s after 1 second.","Un corps en chute libre atteint une vitesse d'environ ___ m/s après 1 seconde.","Un corpo in caduta libera raggiunge una velocità di circa ___ m/s dopo 1 secondo.","9,81/10","g ≈ 9,81 m/s².","Nach 2 Sek: ~20 m/s."))
    exs.append(mc(f"{p}45b","3","Was ist Frequenz einer Schwingung? 🎶","What is the frequency of oscillation? 🎶","Qu'est-ce que la fréquence d'une oscillation ? 🎶","Che cos'è la frequenza di un'oscillazione? 🎶","Die Anzahl Schwingungen pro Sekunde (Hz)",["Die Länge der Schwingung","Die Anzahl Schwingungen pro Sekunde (Hz)","Die Energie der Schwingung","Die Amplitude"],"Hz = Hertz = Schwingungen/Sekunde.","Höherer Ton = höhere Frequenz."))
    exs.append(fib(f"{p}46b","3","Das Gravitationsgesetz von Newton: Zwei Massen ziehen sich mit einer Kraft an, die proportional zu ihrem ___ ist.","Newton's law of gravity: two masses attract with a force proportional to their ___.","Loi de la gravitation de Newton : deux masses s'attirent avec une force proportionnelle à leur ___.","Legge di gravitazione di Newton: due masse si attraggono con una forza proporzionale al loro ___.","Produkt (Masse1 × Masse2)","F ∝ m₁ × m₂.","Mehr Masse = stärkere Anziehung."))
    exs.append(mc(f"{p}47b","3","Was ist ein System im mechanischen Gleichgewicht? ⚖️","What is a system in mechanical equilibrium? ⚖️","Qu'est-ce qu'un système en équilibre mécanique ? ⚖️","Che cos'è un sistema in equilibrio meccanico? ⚖️","Summe aller Kräfte und Drehmomente ist null",["Alle Kräfte sind positiv","Summe aller Kräfte und Drehmomente ist null","Es gibt keine Kräfte","Das System beschleunigt"],"Ruhend und nicht rotierend = Gleichgewicht.","ΣF = 0, ΣM = 0."))
    exs.append(fib(f"{p}48b","3","Die Einheit der Energie und Arbeit ist ___. (benannt nach einem englischen Physiker)","The unit of energy and work is ___. (named after an English physicist)","L'unité d'énergie et de travail est ___. (nommée d'après un physicien anglais)","L'unità di energia e lavoro è ___. (intitolata a un fisico inglese)","Joule","J = Nm = Joule.","James Prescott Joule."))
    exs.append(mc(f"{p}49b","3","Was ist Leistung in der Physik? ⚡","What is power in physics? ⚡","Qu'est-ce que la puissance en physique ? ⚡","Che cos'è la potenza in fisica? ⚡","Arbeit pro Zeiteinheit (P = W/t)",["Kraft pro Fläche","Arbeit pro Zeiteinheit (P = W/t)","Energie pro Masse","Geschwindigkeit × Richtung"],"Ein starker Motor hat viel Leistung.","P = W/t, gemessen in Watt."))
    exs.append(fib(f"{p}50b","3","Der Wirkungsgrad η beschreibt, wie effizient eine Maschine ___  in Nutzenergie umwandelt.","Efficiency η describes how efficiently a machine converts ___ into useful energy.","Le rendement η décrit combien efficacement une machine convertit ___ en énergie utile.","Il rendimento η descrive quanto efficacemente una macchina converte ___ in energia utile.","Eingangsenergie","Wirkungsgrad = Nutzenergie / Eingangsenergie × 100%.","Ideal: η = 1 = 100%."))
    return exs

# ─── SINNE GRADE 1 ───────────────────────────────────────────────────────────
def make_si_g1():
    exs = []
    p = "si"
    # d1 ×11
    exs.append(mc(f"{p}11","1","Mit welchem Organ hören wir? 👂","Which organ do we hear with? 👂","Avec quel organe entendons-nous ? 👂","Con quale organo sentiamo? 👂","Ohren",["Augen","Nase","Ohren","Zunge"],"Töne werden von einem Organ wahrgenommen.","Es sind zwei, an beiden Seiten des Kopfes."))
    exs.append(fib(f"{p}12","1","Mit den Händen können wir ___ wahrnehmen. ✋","With our hands we can perceive ___. ✋","Avec nos mains, nous pouvons percevoir ___. ✋","Con le mani possiamo percepire ___. ✋","Wärme/Kälte/Rauhigkeit","Was fühlt man, wenn man etwas anfasst?","Tastsinn = Haut."))
    exs.append(mc(f"{p}13","1","Welcher Sinn hilft dir, Essen zu schmecken? 🍕","Which sense helps you taste food? 🍕","Quel sens t'aide à goûter la nourriture ? 🍕","Quale senso ti aiuta a gustare il cibo? 🍕","Geschmackssinn",["Sehsinn","Gehörsinn","Geschmackssinn","Tastsinn"],"Die Zunge nimmt Geschmack wahr.","Schmecken = Zunge."))
    exs.append(fib(f"{p}14","1","Der Sehsinn nutzt die ___. 👁️","The sense of sight uses the ___. 👁️","Le sens de la vue utilise les ___. 👁️","Il senso della vista usa gli ___. 👁️","Augen","Licht geht durch Augen ins Gehirn.","Sehen = Augen."))
    exs.append(mc(f"{p}15","1","Mit welchem Sinn kannst du eine Blume riechen? 🌸","Which sense lets you smell a flower? 🌸","Quel sens te permet de sentir une fleur ? 🌸","Quale senso ti permette di annusare un fiore? 🌸","Geruchssinn",["Sehsinn","Gehörsinn","Geruchssinn","Geschmackssinn"],"Die Nase nimmt Gerüche wahr.","Riechen = Nase."))
    exs.append(fib(f"{p}16","1","Bitter, süss, sauer und ___ sind die vier Grundgeschmäcke. 👅","Bitter, sweet, sour and ___ are the four basic tastes. 👅","Amer, sucré, acide et ___ sont les quatre goûts de base. 👅","Amaro, dolce, acido e ___ sono i quattro sapori di base. 👅","salzig","Was schmeckt Salz?","Die vier Grundgeschmäcke."))
    exs.append(mc(f"{p}17","1","Welcher Sinn warnt dich, wenn etwas sehr heiss ist? 🌡️","Which sense warns you when something is very hot? 🌡️","Quel sens t'avertit quand quelque chose est très chaud ? 🌡️","Quale senso ti avverte quando qualcosa è molto caldo? 🌡️","Tastsinn",["Sehsinn","Gehörsinn","Tastsinn","Geruchssinn"],"Die Haut fühlt Wärme und Kälte.","Finger fühlen Temperatur."))
    exs.append(fib(f"{p}18","1","Wir haben ___ Sinne. 🖐️","We have ___ senses. 🖐️","Nous avons ___ sens. 🖐️","Abbiamo ___ sensi. 🖐️","5","Zähle: Sehen, Hören, Riechen, Schmecken, Tasten.","Fünf Sinne!"))
    exs.append(mc(f"{p}19","1","Was passiert, wenn du die Augen zumachst? 🙈","What happens when you close your eyes? 🙈","Que se passe-t-il quand tu fermes les yeux ? 🙈","Cosa succede quando chiudi gli occhi? 🙈","Du kannst nicht mehr sehen",["Du kannst nicht mehr hören","Du kannst nicht mehr sehen","Du verlierst alle Sinne","Du schläfst ein"],"Augen zu = kein Sehen.","Der Sehsinn braucht offene Augen."))
    exs.append(fib(f"{p}20","1","Unsere Sinne helfen uns, die ___ wahrzunehmen. 🌍","Our senses help us perceive the ___. 🌍","Nos sens nous aident à percevoir le ___. 🌍","I nostri sensi ci aiutano a percepire il ___. 🌍","Welt/Umgebung","Wozu dienen unsere Sinne?","Sinne = Kontakt zur Welt."))
    exs.append(mc(f"{p}21","1","Was ist das Sinnesorgan des Gehörsinns? 👂","What is the sensory organ of hearing? 👂","Quel est l'organe sensoriel de l'ouïe ? 👂","Qual è l'organo sensoriale dell'udito? 👂","Ohr",["Nase","Auge","Ohr","Zunge"],"Töne gelangen durch das Ohr ins Gehirn.","Zwei Ohren."))
    # d2 ×15
    exs.append(mc(f"{p}22","2","Was kann die Haut wahrnehmen? ✋","What can the skin perceive? ✋","Que peut percevoir la peau ? ✋","Cosa può percepire la pelle? ✋","Wärme, Kälte, Druck und Schmerz",["Nur Wärme","Nur Kälte","Wärme, Kälte, Druck und Schmerz","Nur Farben"],"Die Haut ist unser grösstes Sinnesorgan.","Tastsinn = viele Empfindungen."))
    exs.append(fib(f"{p}23","2","Wenn Riechen und ___ zusammenarbeiten, schmecken wir viel besser. 👃👅","When smell and ___ work together, we taste much better. 👃👅","Quand l'odorat et ___ travaillent ensemble, nous goûtons bien mieux. 👃👅","Quando l'olfatto e ___ lavorano insieme, guustiamo molto meglio. 👃👅","Schmecken","Bei Erkältung schmeckt Essen fade.","Geruch verstärkt Geschmack."))
    exs.append(mc(f"{p}24","2","Wozu braucht der Mensch den Gehörsinn? 👂","Why does a human need the sense of hearing? 👂","Pourquoi l'être humain a-t-il besoin de l'ouïe ? 👂","Perché l'uomo ha bisogno dell'udito? 👂","Um Töne, Sprache und Geräusche wahrzunehmen",["Um zu sehen","Um zu schmecken","Um Töne, Sprache und Geräusche wahrzunehmen","Um zu riechen"],"Musik, Stimmen, Verkehr = Gehörsinn.","Ohr → Gehirn."))
    exs.append(fib(f"{p}25","2","Die Netzhaut im Auge wandelt ___ in Nervenreize um. 👁️","The retina in the eye converts ___ into nerve signals. 👁️","La rétine de l'œil convertit ___ en signaux nerveux. 👁️","La retina nell'occhio converte ___ in segnali nervosi. 👁️","Licht","Licht → Netzhaut → Gehirn.","Das Bild entsteht im Gehirn."))
    exs.append(mc(f"{p}26","2","Was ist das Trommelfell? 👂","What is the eardrum? 👂","Qu'est-ce que le tympan ? 👂","Che cos'è il timpano? 👂","Eine dünne Membran im Ohr, die Schall aufnimmt",["Ein Knochen","Eine dünne Membran im Ohr, die Schall aufnimmt","Ein Muskel","Ein Nerv"],"Schallwellen lassen es vibrieren.","Trommelfell = Membran im Ohr."))
    exs.append(fib(f"{p}27","2","Bei einer Erkältung riecht man oft ___ so gut. 🤧","During a cold, one often doesn't smell ___ well. 🤧","Lors d'un rhume, on ne sent souvent pas ___ bien. 🤧","Durante un raffreddore, spesso non si sente ___ bene. 🤧","nicht","Nase verstopft → schlechtes Riechen.","Erkältung blockiert Geruchssinn."))
    exs.append(mc(f"{p}28","2","Was ist Tiefenschärfe beim Sehen? 👁️","What is depth perception in vision? 👁️","Qu'est-ce que la profondeur de champ dans la vision ? 👁️","Che cos'è la profondità di campo nella visione? 👁️","Die Fähigkeit, Abstände einzuschätzen",["Die Fähigkeit, Farben zu sehen","Die Fähigkeit, Abstände einzuschätzen","Die Fähigkeit zu träumen","Die Fähigkeit zu lesen"],"Zwei Augen helfen beim Abschätzen von Entfernungen.","Binokulares Sehen."))
    exs.append(fib(f"{p}29","2","Das Gehirn verarbeitet alle Informationen von unseren ___. 🧠","The brain processes all information from our ___. 🧠","Le cerveau traite toutes les informations de nos ___. 🧠","Il cervello elabora tutte le informazioni dai nostri ___. 🧠","Sinnesorganen","Sinne → Nerven → Gehirn.","Das Gehirn ist die Schaltzentrale."))
    exs.append(mc(f"{p}30","2","Was sind Rezeptoren? 🔬","What are receptors? 🔬","Que sont les récepteurs ? 🔬","Cosa sono i recettori? 🔬","Zellen, die Sinnesreize aufnehmen und weiterleiten",["Muskeln","Zellen, die Sinnesreize aufnehmen und weiterleiten","Knochen","Blutgefässe"],"Fotorezeptoren im Auge, Mechanorezeptoren in der Haut.","Rezeptor = Empfänger."))
    exs.append(fib(f"{p}31","2","Der Gleichgewichtssinn liegt im ___ des Ohres. 👂","The sense of balance is located in the ___ of the ear. 👂","Le sens de l'équilibre se trouve dans le ___ de l'oreille. 👂","Il senso dell'equilibrio si trova nel ___ dell'orecchio. 👂","Innenohr","Balance = Innenohr (Bogengänge).","Schwindel bei Drehung = Innenohr."))
    exs.append(mc(f"{p}32","2","Warum können wir im Dunkeln Gegenstände nicht erkennen, aber hören? 🌑","Why can't we see objects in the dark but can still hear? 🌑","Pourquoi ne voyons-nous pas les objets dans le noir mais pouvons-nous entendre ? 🌑","Perché non vediamo gli oggetti al buio ma possiamo sentire? 🌑","Sehen braucht Licht, Hören braucht Schallwellen",["Hören ist stärker","Sehen braucht Licht, Hören braucht Schallwellen","Im Dunkeln hört man besser","Augen schlafen nachts"],"Licht ist nötig für den Sehsinn.","Schallwellen kommen auch im Dunkeln an."))
    exs.append(fib(f"{p}33","2","Schmerz ist eine wichtige ___ des Tastsinn, die uns vor Verletzungen warnt.","Pain is an important ___ of the sense of touch that warns us of injuries.","La douleur est un ___ important du toucher qui nous avertit des blessures.","Il dolore è un ___ importante del tatto che ci avverte delle lesioni.","Schutzfunktion","Schmerz = Warnsignal.","Ohne Schmerz würden wir uns oft verletzen."))
    exs.append(mc(f"{p}34","2","Was geschieht, wenn der Sehnerv beschädigt ist? 👁️","What happens if the optic nerve is damaged? 👁️","Que se passe-t-il si le nerf optique est endommagé ? 👁️","Cosa succede se il nervo ottico è danneggiato? 👁️","Man kann nicht mehr sehen (Blindheit möglich)",["Man hört besser","Man kann nicht mehr sehen (Blindheit möglich)","Man verliert den Tastsinn","Man riecht schärfer"],"Nerv = Leitung zum Gehirn.","Sehnerv verbindet Auge mit Gehirn."))
    exs.append(fib(f"{p}35","2","Wenn man eine Zitrone sieht, läuft einem das ___ im Mund zusammen. 🍋","When you see a lemon, your ___ runs together in your mouth. 🍋","Quand on voit un citron, la ___ nous vient à la bouche. 🍋","Quando si vede un limone, si accumula ___ in bocca. 🍋","Wasser (Speichel)","Das Gehirn reagiert auf den Sehreiz.","Speichelproduktion beim Anblick von Essen."))
    exs.append(mc(f"{p}36","2","Warum haben die meisten Tiere zwei Augen? 👁️👁️","Why do most animals have two eyes? 👁️👁️","Pourquoi la plupart des animaux ont-ils deux yeux ? 👁️👁️","Perché la maggior parte degli animali ha due occhi? 👁️👁️","Für räumliches Sehen (Tiefenschärfe)",["Für mehr Sehfläche","Für räumliches Sehen (Tiefenschärfe)","Weil es symmetrisch ist","Für besseres Nachtsehen"],"Zwei Augen → Überlappungsbereich → 3D-Sehen.","Tiefe einschätzen."))
    # d3 ×14
    exs.append(fib(f"{p}37","3","Die Pupille verkleinert sich bei ___ Licht, um das Auge zu schützen. 👁️","The pupil contracts in ___ light to protect the eye. 👁️","La pupille se rétrécit en lumière ___ pour protéger l'œil. 👁️","La pupilla si restringe in luce ___ per proteggere l'occhio. 👁️","hellem","Dunkle Pupille = wenig Licht.","Helles Licht → Pupille klein."))
    exs.append(mc(f"{p}38","3","Was ist das synästhetische Phänomen? 🎨","What is the synesthetic phenomenon? 🎨","Qu'est-ce que le phénomène synesthésique ? 🎨","Che cos'è il fenomeno sinestesico? 🎨","Wenn ein Sinn einen anderen auslöst (z.B. Töne als Farben sehen)",["Wenn alle Sinne versagen","Wenn ein Sinn einen anderen auslöst (z.B. Töne als Farben sehen)","Wenn man zwei Augen hat","Wenn Riechen und Schmecken sich verbinden"],"Einige Menschen sehen Musik als Farben.","Synästhesie = Sinnesvermischung."))
    exs.append(fib(f"{p}39","3","Das menschliche Ohr kann Frequenzen zwischen etwa 20 und ___ Hz wahrnehmen.","The human ear can perceive frequencies between about 20 and ___ Hz.","L'oreille humaine peut percevoir des fréquences entre environ 20 et ___ Hz.","L'orecchio umano può percepire frequenze tra circa 20 e ___ Hz.","20'000","Ultraschall liegt über 20'000 Hz.","Hz = Hertz = Schwingungen/Sekunde."))
    exs.append(mc(f"{p}40","3","Was ist der Unterschied zwischen Stäbchen und Zapfen im Auge? 👁️","What is the difference between rods and cones in the eye? 👁️","Quelle est la différence entre bâtonnets et cônes dans l'œil ? 👁️","Qual è la differenza tra bastoncelli e coni nell'occhio? 👁️","Stäbchen: Schwarz-Weiss, Dunkel. Zapfen: Farben, Tageslicht.",["Stäbchen sehen Farben, Zapfen Schwarz-Weiss","Stäbchen: Schwarz-Weiss, Dunkel. Zapfen: Farben, Tageslicht.","Beide gleich","Zapfen für Dunkel, Stäbchen für Farben"],"Katzen haben viele Stäbchen → gut im Dunkeln.","Zapfen = Farben."))
    exs.append(fib(f"{p}41","3","Das Innenohr enthält die ___ (Schnecke), die Schall in Nervenreize umwandelt.","The inner ear contains the ___ (cochlea), which converts sound into nerve signals.","L'oreille interne contient la ___ (cochlée), qui convertit le son en signaux nerveux.","L'orecchio interno contiene la ___ (coclea), che converte il suono in segnali nervosi.","Cochlea/Gehörschnecke","Gehörschnecke = Cochlea.","Schall → Cochlea → Hörnerv."))
    exs.append(mc(f"{p}42","3","Was ist olfaktorische Anpassung? 👃","What is olfactory adaptation? 👃","Qu'est-ce que l'adaptation olfactive ? 👃","Che cos'è l'adattamento olfattivo? 👃","Man gewöhnt sich an einen Geruch und nimmt ihn nicht mehr wahr",["Man riecht schärfer","Man verliert den Geruchssinn","Man gewöhnt sich an einen Geruch und nimmt ihn nicht mehr wahr","Man entwickelt neue Geruchssensoren"],"Im Zimmer riecht man einen Geruch bald nicht mehr.","Gewöhnung an Reize."))
    exs.append(fib(f"{p}43","3","Sensorische Adaptation bedeutet, dass ein Sinn nach längerem Reiz ___ wird. 🧠","Sensory adaptation means that a sense becomes ___ after prolonged stimulation.","L'adaptation sensorielle signifie qu'un sens devient ___ après stimulation prolongée.","L'adattamento sensoriale significa che un senso diventa ___ dopo una stimolazione prolungata.","weniger empfindlich","Auge gewöhnt sich an Dunkelheit.","Reize werden ignoriert."))
    exs.append(mc(f"{p}44","3","Was ist das Zwei-Punkt-Diskriminierungsvermögen? 🖐️","What is two-point discrimination? 🖐️","Qu'est-ce que la discrimination entre deux points ? 🖐️","Che cos'è la discriminazione a due punti? 🖐️","Die Fähigkeit, zwei nahe Berührungspunkte zu unterscheiden",["Das Fühlen von Wärme","Die Fähigkeit, zwei nahe Berührungspunkte zu unterscheiden","Das Erkennen von Farben","Das Riechen von Gerüchen"],"Fingerkuppen haben höchste Diskriminierung.","Mehr Rezeptoren = bessere Unterscheidung."))
    exs.append(fib(f"{p}45","3","Der ___ Kortex im Gehirn verarbeitet Informationen vom Tastsinn. 🧠","The ___ cortex in the brain processes touch information.","Le cortex ___ du cerveau traite les informations du toucher.","La corteccia ___ nel cervello elabora le informazioni del tatto.","somatosensorische","Somatosensorisch = Körpergefühl.","Gehirnregion für Körperwahrnehmung."))
    exs.append(mc(f"{p}46","3","Was ist Echolokation? 🦇","What is echolocation? 🦇","Qu'est-ce que l'écholocation ? 🦇","Che cos'è l'ecolocazione? 🦇","Navigation durch ausgesendete und zurückgeworfene Schallwellen",["Sehen im Dunkeln","Navigation durch ausgesendete und zurückgeworfene Schallwellen","Riechen aus grosser Entfernung","Schmecken ohne Zunge"],"Fledermäuse und Delfine nutzen Echolokation.","Schall senden, Echo empfangen → Abstand messen."))
    exs.append(fib(f"{p}47","3","Das Gehirn kann Sinneseindrücke ergänzen: wenn wenig Licht da ist, ___ das Gehirn Informationen. 🧠","The brain can complete sensory input: when there's little light, the brain ___ information.","Le cerveau peut compléter les impressions sensorielles : quand la lumière est faible, le cerveau ___ les informations.","Il cervello può completare le impressioni sensoriali: quando c'è poca luce, il cervello ___ le informazioni.","ergänzt/vervollständigt","Gehirn füllt Lücken.","Mustererkennung."))
    exs.append(mc(f"{p}48","3","Was ist der Unterschied zwischen Nah- und Weitsichtigkeit? 👓","What is the difference between near- and farsightedness? 👓","Quelle est la différence entre myopie et hypermétropie ? 👓","Qual è la differenza tra miopia e ipermetropia? 👓","Kurzsichtig: ferne Objekte unscharf. Weitsichtig: nahe Objekte unscharf.",["Beide sind gleich","Kurzsichtig: ferne Objekte unscharf. Weitsichtig: nahe Objekte unscharf.","Kurzsichtig: keine Farben. Weitsichtig: keine Nacht","Kurzsichtig ist gefährlicher"],"Brille korrigiert beide Fehler.","Linse zu stark/schwach."))
    exs.append(fib(f"{p}49","3","Das ___ Auge eines Tintenfisches kann trotz fehlender Farbrezeptoren Farben durch Polarisation erkennen.","The ___ eye of a cuttlefish can detect colors through polarization despite lacking color receptors.","L'œil ___ d'une seiche peut détecter les couleurs par polarisation malgré l'absence de récepteurs de couleur.","L'occhio ___ di una seppia può rilevare i colori tramite polarizzazione nonostante la mancanza di recettori cromatici.","einheitlich gefärbte","Tintenfischaugen sind hochentwickelt.","Sonderfall in der Natur."))
    exs.append(mc(f"{p}50","3","Was ist Propriozeption? 🧠","What is proprioception? 🧠","Qu'est-ce que la proprioception ? 🧠","Che cos'è la propriocezione? 🧠","Das Wahrnehmen der eigenen Körperposition und -bewegung",["Das Riechen von Gerüchen","Das Wahrnehmen der eigenen Körperposition und -bewegung","Das Sehen von Farben","Das Hören von Musik"],"Auch mit geschlossenen Augen weisst du, wo deine Arme sind.","Propriozeption = Körpergefühl."))
    return exs

# ─── SINNE GRADE 2 ───────────────────────────────────────────────────────────
def make_si_g2():
    exs = []
    p = "si"
    # d1 ×11
    exs.append(mc(f"{p}11b","1","Welches Organ ist für den Tastsinn verantwortlich? ✋","Which organ is responsible for the sense of touch? ✋","Quel organe est responsable du toucher ? ✋","Quale organo è responsabile del tatto? ✋","Haut",["Ohr","Nase","Haut","Auge"],"Die Haut bedeckt den ganzen Körper.","Tast-Rezeptoren sind in der Haut."))
    exs.append(fib(f"{p}12b","1","Wir schmecken mit der ___. 👅","We taste with our ___. 👅","Nous goûtons avec notre ___. 👅","Assaggiamo con la ___. 👅","Zunge","Geschmacksrezeptoren auf der Zunge.","Süss, sauer, salzig, bitter."))
    exs.append(mc(f"{p}13b","1","Wie viele Grundgeschmäcke kann die Zunge unterscheiden? 👅","How many basic tastes can the tongue distinguish? 👅","Combien de goûts de base la langue peut-elle distinguer ? 👅","Quanti sapori di base può distinguere la lingua? 👅","4 (plus Umami = 5)",["2","3","4 (plus Umami = 5)","6"],"Süss, sauer, salzig, bitter = klassisch 4.","Mit Umami sind es 5."))
    exs.append(fib(f"{p}14b","1","Wenn es laut ist, können wir uns ___ konzentrieren. 👂","When it is loud, we can ___ concentrate. 👂","Quand c'est bruyant, on peut se concentrer ___. 👂","Quando è rumoroso, possiamo concentrarci ___. 👂","schlechter/weniger gut","Lärm stört den Gehörsinn.","Viele Geräusche = weniger Fokus."))
    exs.append(mc(f"{p}15b","1","Womit nehmen wir Gerüche wahr? 👃","What do we use to perceive smells? 👃","Avec quoi percevons-nous les odeurs ? 👃","Con cosa percepiamo gli odori? 👃","Nase",["Mund","Nase","Haut","Augen"],"Riechzellen sitzen in der Nase.","Riechen = Nase."))
    exs.append(fib(f"{p}16b","1","Das Gehirn ist das Zentrum, das alle ___ verarbeitet. 🧠","The brain is the centre that processes all ___. 🧠","Le cerveau est le centre qui traite tous les ___. 🧠","Il cervello è il centro che elabora tutti i ___. 🧠","Sinneseindrücke","Sinne → Nerven → Gehirn.","Das Gehirn interpretiert alles."))
    exs.append(mc(f"{p}17b","1","Was kannst du mit dem Tastsinn erkennen? ✋","What can you recognise with the sense of touch? ✋","Que peux-tu reconnaître avec le toucher ? ✋","Cosa puoi riconoscere con il tatto? ✋","Rau, glatt, warm, kalt",["Farben","Rau, glatt, warm, kalt","Töne","Gerüche"],"Haut fühlt Oberflächen und Temperatur.","Tast-Sinn erkennt viele Eigenschaften."))
    exs.append(fib(f"{p}18b","1","Wenn Licht in unsere Augen fällt, leitet der Sehnerv Signale ans ___ weiter. 🧠","When light enters our eyes, the optic nerve sends signals to the ___. 🧠","Quand la lumière entre dans nos yeux, le nerf optique envoie des signaux au ___. 🧠","Quando la luce entra nei nostri occhi, il nervo ottico invia segnali al ___. 🧠","Gehirn","Auge → Sehnerv → Gehirn.","Das Gehirn verarbeitet das Bild."))
    exs.append(mc(f"{p}19b","1","Welcher Sinn hilft uns, Musik zu hören? 🎵","Which sense helps us hear music? 🎵","Quel sens nous aide à entendre de la musique ? 🎵","Quale senso ci aiuta ad ascoltare la musica? 🎵","Gehörsinn",["Sehsinn","Gehörsinn","Tastsinn","Geruchssinn"],"Ohren nehmen Töne wahr.","Gehörsinn = Ohr."))
    exs.append(fib(f"{p}20b","1","Brillen korrigieren Fehler des ___sinns. 👓","Glasses correct defects in ___ vision.","Les lunettes corrigent les défauts de la ___. 👓","Gli occhiali correggono i difetti della ___. 👓","Seh","Kurz- oder Weitsichtigkeit.","Brille hilft beim Sehen."))
    exs.append(mc(f"{p}21b","1","Was ist eine Sinnesüberlastung? 🌊","What is sensory overload? 🌊","Qu'est-ce que la surcharge sensorielle ? 🌊","Che cos'è il sovraccarico sensoriale? 🌊","Wenn zu viele Sinnesreize gleichzeitig auf das Gehirn wirken",["Wenn man schläft","Wenn zu viele Sinnesreize gleichzeitig auf das Gehirn wirken","Wenn alle Sinne perfekt funktionieren","Wenn man im Dunkeln sitzt"],"Laute Musik + grelles Licht = Überlastung.","Zu viel Information."))
    # d2 ×15
    exs.append(mc(f"{p}22b","2","Was ist der Gleichgewichtssinn und wo sitzt er? 🌀","What is the sense of balance and where is it located? 🌀","Qu'est-ce que le sens de l'équilibre et où est-il situé ? 🌀","Che cos'è il senso dell'equilibrio e dove si trova? 🌀","Im Innenohr; er hilft uns, das Gleichgewicht zu halten",["Im Auge","Im Innenohr; er hilft uns, das Gleichgewicht zu halten","In der Nase","Im Magen"],"Innenohr mit Bogengängen.","Gleichgewicht = Innenohr."))
    exs.append(fib(f"{p}23b","2","Ein Mensch ohne Geruchssinn (Anosmie) kann Essen oft nicht gut ___.","A person without a sense of smell (anosmia) often cannot ___ food well.","Une personne sans odorat (anosmie) ne peut souvent pas bien ___ la nourriture.","Una persona senza olfatto (anosmia) spesso non riesce a ___ bene il cibo.","schmecken","Riechen und Schmecken hängen zusammen.","Anosmie = kein Geruchssinn."))
    exs.append(mc(f"{p}24b","2","Was ist ein blinder Fleck im Auge? 👁️","What is a blind spot in the eye? 👁️","Qu'est-ce que le point aveugle dans l'œil ? 👁️","Che cos'è il punto cieco nell'occhio? 👁️","Die Stelle, wo der Sehnerv ansetzt und keine Rezeptoren hat",["Ein schwarzer Fleck","Die Stelle, wo der Sehnerv ansetzt und keine Rezeptoren hat","Die Netzhaut","Die Pupille"],"Dort kann man nichts sehen.","Sehnerv-Eintrittstelle."))
    exs.append(fib(f"{p}25b","2","Das Innenohr enthält die Cochlea (Hörschnecke) und die ___-Bogengänge. 👂","The inner ear contains the cochlea and the ___ semicircular canals. 👂","L'oreille interne contient la cochlée et les canaux semi-circulaires ___. 👂","L'orecchio interno contiene la coclea e i canali semicircolari ___. 👂","drei","Drei Bogengänge für 3 Raumachsen.","Gleichgewichtssinn."))
    exs.append(mc(f"{p}26b","2","Was passiert mit den Sinnen im Alter? 👴","What happens to the senses with age? 👴","Que se passe-t-il avec les sens en vieillissant ? 👴","Cosa succede ai sensi con l'età? 👴","Sie werden oft schwächer (Hören, Sehen)",["Sie werden stärker","Sie verschwinden ganz","Sie werden oft schwächer (Hören, Sehen)","Sie bleiben gleich"],"Alte Menschen brauchen oft Brillen und Hörgeräte.","Sinne schwächen mit dem Alter."))
    exs.append(fib(f"{p}27b","2","Blinde Menschen nutzen oft verstärkt andere Sinne, besonders ___ und ___. 🦯","Blind people often use other senses more strongly, especially ___ and ___. 🦯","Les personnes aveugles utilisent souvent davantage d'autres sens, surtout ___ et ___. 🦯","Le persone cieche spesso usano altri sensi più fortemente, specialmente ___ e ___. 🦯","Tastsinn und Gehörsinn","Braille-Schrift = Tastsinn.","Kompensation."))
    exs.append(mc(f"{p}28b","2","Was ist ein Sinnesorgan? 🔬","What is a sensory organ? 🔬","Qu'est-ce qu'un organe sensoriel ? 🔬","Che cos'è un organo di senso? 🔬","Ein spezielles Organ, das bestimmte Reize aufnimmt",["Ein Knochen","Ein spezielles Organ, das bestimmte Reize aufnimmt","Ein Muskel","Ein Blutgefäss"],"Auge, Ohr, Nase, Zunge, Haut = Sinnesorgane.","Organe für Wahrnehmung."))
    exs.append(fib(f"{p}29b","2","Das Auge ist von einem ___ Augapfel umgeben, der sich dreht. 👁️","The eye is surrounded by a spherical eyeball that ___. 👁️","L'œil est entouré d'un globe oculaire ___ qui tourne. 👁️","L'occhio è circondato da un bulbo oculare ___ che ruota. 👁️","runden/kugelförmigen","Augapfel = Kugel.","Kann sich in alle Richtungen drehen."))
    exs.append(mc(f"{p}30b","2","Was ist Schmerz? 🤕","What is pain? 🤕","Qu'est-ce que la douleur ? 🤕","Che cos'è il dolore? 🤕","Ein Warnsignal des Körpers bei Schädigung",["Eine Freude","Ein Warnsignal des Körpers bei Schädigung","Eine Emotion","Ein Geruch"],"Schmerz schützt uns.","Ohne Schmerz würde man sich nicht kümmern."))
    exs.append(fib(f"{p}31b","2","Die Rezeptoren in der Nase nehmen ___ Moleküle wahr. 👃","The receptors in the nose detect ___ molecules. 👃","Les récepteurs dans le nez détectent les molécules ___. 👃","I recettori nel naso rilevano le molecole ___. 👃","Duft/Geruchs","Geruchsmoleküle binden an Rezeptoren.","Nase = chemischer Sensor."))
    exs.append(mc(f"{p}32b","2","Was ist Raumwahrnehmung? 👁️","What is spatial perception? 👁️","Qu'est-ce que la perception spatiale ? 👁️","Che cos'è la percezione spaziale? 👁️","Die Fähigkeit, Objekte im dreidimensionalen Raum wahrzunehmen",["Das Sehen von Farben","Die Fähigkeit, Objekte im dreidimensionalen Raum wahrzunehmen","Das Hören von Tönen","Das Riechen von Gerüchen"],"Zwei Augen → 3D.","Tiefen einschätzen."))
    exs.append(fib(f"{p}33b","2","Beim Kauen und Riechen zusammen nehmen wir ___ wahr. 🍕","When chewing and smelling together, we perceive ___. 🍕","En mâchant et en sentant ensemble, on perçoit ___. 🍕","Masticando e annusando insieme, percepiamo ___. 🍕","Aroma/Geschmack stärker","Zusammenspiel Nase und Zunge.","Aroma = Geruch + Geschmack."))
    exs.append(mc(f"{p}34b","2","Warum reagieren wir sofort auf laute Geräusche? 👂","Why do we react immediately to loud sounds? 👂","Pourquoi réagissons-nous immédiatement aux sons forts ? 👂","Perché reagiamo immediatamente ai suoni forti? 👂","Reflexantwort zum Schutz",["Weil wir sie mögen","Reflexantwort zum Schutz","Weil wir überrascht sind","Weil wir schlafen"],"Schutzmechanismus.","Laut = mögliche Gefahr."))
    exs.append(fib(f"{p}35b","2","Wenn wir etwas Unangenehmes riechen, können wir den Geruch ___ wahrnehmen.","When we smell something unpleasant, we can perceive the smell ___.","Quand on sent quelque chose de désagréable, on peut le percevoir ___.","Quando annusiamo qualcosa di sgradevole, possiamo percepire l'odore ___.","sofort/stark","Unangenehme Gerüche = Warnsignal.","Gefährliche Dinge oft schlecht riechend."))
    exs.append(mc(f"{p}36b","2","Was ist Wahrnehmung? 🧠","What is perception? 🧠","Qu'est-ce que la perception ? 🧠","Che cos'è la percezione? 🧠","Die Verarbeitung von Sinneseindrücken durch das Gehirn",["Das Aufnehmen von Reizen allein","Die Verarbeitung von Sinneseindrücken durch das Gehirn","Das Vergessen von Eindrücken","Das Schlafen"],"Sehen → Wahrnehmen → Verstehen.","Gehirn interpretiert."))
    # d3 ×14
    exs.append(fib(f"{p}37b","3","Das Weber-Fechner Gesetz beschreibt, dass die Wahrnehmungsstärke ___ zum Reiz zunimmt.","The Weber-Fechner Law states that perceived intensity increases ___ with stimulus.","La loi de Weber-Fechner décrit que l'intensité perçue augmente ___ avec le stimulus.","La legge di Weber-Fechner descrive che l'intensità percepita aumenta ___ con lo stimolo.","logarithmisch","Doppelt so starker Reiz = nicht doppelt so stark wahrgenommen.","Logarithmisch = abnehmende Sensitivität."))
    exs.append(mc(f"{p}38b","3","Was ist sensorische Integration? 🧠","What is sensory integration? 🧠","Qu'est-ce que l'intégration sensorielle ? 🧠","Che cos'è l'integrazione sensoriale? 🧠","Das Zusammenführen von Informationen aus verschiedenen Sinnen",["Das Trennen von Sinneseindrücken","Das Zusammenführen von Informationen aus verschiedenen Sinnen","Das Ausschalten eines Sinnes","Das Verstärken eines Sinnes"],"Gehirn kombiniert Seh- und Höreindrücke.","Integration = zusammenführen."))
    exs.append(fib(f"{p}39b","3","Bei der Dunkeladaption weitet sich die Pupille und die ___ des Auges werden empfindlicher. 👁️","In dark adaptation, the pupil widens and the ___ of the eye become more sensitive. 👁️","Lors de l'adaptation à l'obscurité, la pupille se dilate et les ___ de l'œil deviennent plus sensibles. 👁️","Nell'adattamento al buio, la pupilla si dilata e le ___ dell'occhio diventano più sensibili. 👁️","Stäbchen","Stäbchen sind lichtempfindlicher.","Stäbchen = Nachtsehen."))
    exs.append(mc(f"{p}40b","3","Was ist das McGurk-Effekt? 🎭","What is the McGurk effect? 🎭","Qu'est-ce que l'effet McGurk ? 🎭","Che cos'è l'effetto McGurk? 🎭","Wenn visuelle Lippeninformationen den wahrgenommenen Laut verändern",["Eine optische Täuschung","Wenn visuelle Lippeninformationen den wahrgenommenen Laut verändern","Eine Hörbehinderung","Ein Geruchsphänomen"],"Man hört eine andere Silbe je nachdem was man sieht.","Sehen beeinflusst Hören."))
    exs.append(fib(f"{p}41b","3","Sinneswahrnehmung kann durch Erwartungen und Erfahrungen ___ werden. 🧠","Sensory perception can be ___ by expectations and experiences.","La perception sensorielle peut être ___ par les attentes et les expériences.","La percezione sensoriale può essere ___ da aspettative ed esperienze.","beeinflusst/verändert","Optische Täuschungen täuschen.","Kontext ändert Wahrnehmung."))
    exs.append(mc(f"{p}42b","3","Was ist Phantomschmerz? 🦿","What is phantom pain? 🦿","Qu'est-ce que la douleur fantôme ? 🦿","Che cos'è il dolore fantasma? 🦿","Schmerz in einem amputierten Körperteil",["Ein eingebildeter Schmerz ohne Ursache","Schmerz in einem amputierten Körperteil","Ein besonders starker Schmerz","Schmerz durch Kälte"],"Das Gehirn sendet weiter Signale.","Amputierte berichten davon."))
    exs.append(fib(f"{p}43b","3","Das olfaktorische System sendet Geruchssignale direkt an den ___, ohne den Thalamus. 🧠","The olfactory system sends smell signals directly to the ___, bypassing the thalamus.","Le système olfactif envoie les signaux olfactifs directement au ___, en contournant le thalamus.","Il sistema olfattivo invia segnali olfattivi direttamente al ___, bypassando il talamo.","limbischen System","Geruch → Emotionen direkt.","Daher löst Geruch starke Erinnerungen aus."))
    exs.append(mc(f"{p}44b","3","Was ist die Theorie der Top-Down-Verarbeitung? 🧠","What is the theory of top-down processing? 🧠","Qu'est-ce que la théorie du traitement descendant ? 🧠","Che cos'è la teoria del processing top-down? 🧠","Das Gehirn nutzt Vorwissen, um eingehende Sinnesreize zu interpretieren",["Die Sinne liefern alle Informationen ohne Interpretation","Das Gehirn nutzt Vorwissen, um eingehende Sinnesreize zu interpretieren","Die Sinne arbeiten von unten nach oben","Das Gehirn ignoriert Sinnesreize"],"Kontext beeinflusst Wahrnehmung.","Erwartungen formen, was wir sehen/hören."))
    exs.append(fib(f"{p}45b","3","Die ___ ist die minimale Reizintensität, die gerade noch wahrgenommen werden kann.","The ___ is the minimum stimulus intensity that can just barely be perceived.","Le ___ est l'intensité minimale du stimulus qui peut tout juste être perçue.","Il ___ è l'intensità minima dello stimolo che può essere appena percepita.","Reizschwelle","Zu schwach = nicht wahrgenommen.","Unterhalb der Schwelle kein Bewusstsein."))
    exs.append(mc(f"{p}46b","3","Was ist intermodales Wahrnehmen? 🎭","What is intermodal perception? 🎭","Qu'est-ce que la perception intermodale ? 🎭","Che cos'è la percezione intermodale? 🎭","Die Verknüpfung von Informationen aus verschiedenen Sinnen",["Nur ein Sinn ist aktiv","Die Verknüpfung von Informationen aus verschiedenen Sinnen","Alle Sinne sind ausgeschaltet","Ein Sinn ist besonders stark"],"Sehen + Hören + Fühlen zusammen.","Intermodal = zwischen den Sinnen."))
    exs.append(fib(f"{p}47b","3","Die Stelle im Auge mit der höchsten Sehschärfe heisst ___. 👁️","The point in the eye with the highest visual acuity is called ___.","La zone de l'œil avec la plus haute acuité visuelle s'appelle ___.","Il punto dell'occhio con la maggiore acuità visiva si chiama ___.","Fovea/gelber Fleck","Fovea = Zentrum der Netzhaut.","Höchste Zapfendichte dort."))
    exs.append(mc(f"{p}48b","3","Was ist ein taktiles Halluzination? 🧠","What is a tactile hallucination? 🧠","Qu'est-ce qu'une hallucination tactile ? 🧠","Che cos'è un'allucinazione tattile? 🧠","Das Wahrnehmen einer Berührung ohne tatsächlichen Reiz",["Ein starker Schmerz","Das Wahrnehmen einer Berührung ohne tatsächlichen Reiz","Eine Berührung durch Wind","Eine Massagewirkung"],"Wie Phantomschmerz – Gehirn täuscht sich.","Keine äussere Ursache."))
    exs.append(fib(f"{p}49b","3","Das Gehirn verbraucht trotz ~2% Körpergewicht etwa ___% der Körperenergie. 🧠","Despite being ~2% of body weight, the brain uses about ___% of body energy.","Malgré ~2% du poids corporel, le cerveau consomme environ ___% de l'énergie corporelle.","Nonostante il ~2% del peso corporeo, il cervello usa circa il ___% dell'energia corporea.","20","Gehirn = sehr energiehungrig.","Sinnesverarbeitung braucht viel Energie."))
    exs.append(mc(f"{p}50b","3","Was ist Synapsenplastizität? 🧠","What is synaptic plasticity? 🧠","Qu'est-ce que la plasticité synaptique ? 🧠","Che cos'è la plasticità sinaptica? 🧠","Die Fähigkeit von Synapsen, ihre Verbindungsstärke zu verändern",["Die Anzahl der Synapsen","Die Fähigkeit von Synapsen, ihre Verbindungsstärke zu verändern","Die Farbe von Neuronen","Die Position von Synapsen"],"Lernen stärkt Synapsen.","Plastizität = Anpassung."))
    return exs

# ─── WETTER-KLIMA GRADE 1 ────────────────────────────────────────────────────
def make_wt_g1():
    exs = []
    p = "wt"
    # d1 ×11
    exs.append(mc(f"{p}11","1","Was ist Nebel? 🌫️","What is fog? 🌫️","Qu'est-ce que le brouillard ? 🌫️","Che cos'è la nebbia? 🌫️","Kleine Wassertröpfchen in der Luft",["Rauch","Kleine Wassertröpfchen in der Luft","Sand","Schnee"],"Nebel ist wie eine Wolke am Boden.","Man sieht schlecht im Nebel."))
    exs.append(fib(f"{p}12","1","Im ___ fällt Schnee. ❄️","In ___ it snows. ❄️","En ___ il neige. ❄️","In ___ nevica. ❄️","Winter","Wann ist es am kältesten?","Schnee fällt wenn es kalt ist."))
    exs.append(mc(f"{p}13","1","Was macht die Sonne im Sommer? ☀️","What does the sun do in summer? ☀️","Que fait le soleil en été ? ☀️","Cosa fa il sole in estate? ☀️","Sie scheint lange und warm",["Sie geht früh unter","Sie scheint lange und warm","Sie ist kalt","Sie erscheint selten"],"Im Sommer ist es warm.","Die Tage sind lang."))
    exs.append(fib(f"{p}14","1","Wenn es stark regnet, kann man einen ___ sehen. 🌈","When it rains heavily and the sun shines, you can see a ___. 🌈","Quand il pleut fort et que le soleil brille, on peut voir un ___. 🌈","Quando piove forte e splende il sole, si può vedere un ___. 🌈","Regenbogen","Sonne + Regen = Regenbogen.","7 Farben!"))
    exs.append(mc(f"{p}15","1","Was friert bei -5 Grad Celsius? 🌡️","What freezes at -5 degrees Celsius? 🌡️","Qu'est-ce qui gèle à -5 degrés Celsius ? 🌡️","Cosa ghiaccia a -5 gradi Celsius? 🌡️","Wasser",["Sand","Wasser","Luft","Stein"],"Wasser gefriert unter 0°C.","Eis = gefrorenes Wasser."))
    exs.append(fib(f"{p}16","1","Ein ___ misst die Windgeschwindigkeit. 💨","An ___ measures wind speed. 💨","Un ___ mesure la vitesse du vent. 💨","Un ___ misura la velocità del vento. 💨","Anemometer","Wetterstationen messen den Wind.","Anemometer dreht sich im Wind."))
    exs.append(mc(f"{p}17","1","Wie nennt man Wolken, die tief sind und Regen bringen? 🌧️","What do you call low clouds that bring rain? 🌧️","Comment appelle-t-on les nuages bas qui apportent de la pluie ? 🌧️","Come si chiamano le nuvole basse che portano pioggia? 🌧️","Regenwolken",["Schäfchenwolken","Federwolken","Regenwolken","Gewitterwolken"],"Graue Wolken bringen Regen.","Nimbus = Regenwolke."))
    exs.append(fib(f"{p}18","1","Im ___ wachsen Pflanzen und erwachen Tiere aus dem Winterschlaf. 🌸","In ___ plants grow and animals wake from hibernation. 🌸","Au ___ les plantes poussent et les animaux sortent d'hibernation. 🌸","In ___ le piante crescono e gli animali si svegliano dall'ibernazione. 🌸","Frühling","Frühling = nach dem Winter.","Alles erwacht."))
    exs.append(mc(f"{p}19","1","Was ist ein Gewitter? ⛈️","What is a thunderstorm? ⛈️","Qu'est-ce qu'un orage ? ⛈️","Che cos'è un temporale? ⛈️","Ein Sturm mit Blitz, Donner und starkem Regen",["Leichter Regen","Ein Sturm mit Blitz, Donner und starkem Regen","Schneefall","Sonnenschein"],"Blitz und Donner gehören zum Gewitter.","Immer Vorsicht bei Gewitter!"))
    exs.append(fib(f"{p}20","1","Im ___ fallen die Blätter von den Bäumen. 🍂","In ___ leaves fall from trees. 🍂","En ___ les feuilles tombent des arbres. 🍂","In ___ le foglie cadono dagli alberi. 🍂","Herbst","Nach dem Sommer, vor dem Winter.","Blätter werden gelb und braun."))
    exs.append(mc(f"{p}21","1","Was misst ein Barometer? ⏱️","What does a barometer measure? ⏱️","Que mesure un baromètre ? ⏱️","Cosa misura un barometro? ⏱️","Den Luftdruck",["Die Temperatur","Den Wind","Den Luftdruck","Den Regen"],"Hoher Luftdruck = meistens gutes Wetter.","Barometer = Luftdruckmesser."))
    # d2 ×15
    exs.append(mc(f"{p}22","2","Was ist der Wasserkreislauf? 🌊","What is the water cycle? 🌊","Qu'est-ce que le cycle de l'eau ? 🌊","Che cos'è il ciclo dell'acqua? 🌊","Verdunstung → Wolkenbildung → Regen → wieder zurück",["Wasser fliesst ins Meer","Verdunstung → Wolkenbildung → Regen → wieder zurück","Regen → Verdunstung allein","Schnee → Regen → Ende"],"Wasser verdunstet, steigt auf, bildet Wolken, fällt als Regen.","Kreislauf: kein Ende."))
    exs.append(fib(f"{p}23","2","Wolken entstehen, wenn Wasserdampf ___ und zu Tröpfchen wird. ☁️","Clouds form when water vapour ___ and becomes droplets. ☁️","Les nuages se forment quand la vapeur d'eau ___ et devient des gouttelettes. ☁️","Le nuvole si formano quando il vapore acqueo ___ e diventa goccioline. ☁️","abkühlt/kondensiert","Kühle Luft kann weniger Wasserdampf halten.","Kondensation."))
    exs.append(mc(f"{p}24","2","Was verursacht Wind? 💨","What causes wind? 💨","Qu'est-ce qui cause le vent ? 💨","Cosa causa il vento? 💨","Unterschiede im Luftdruck",["Die Sonne allein","Unterschiede im Luftdruck","Der Mond","Das Wasser"],"Luft strömt von