#!/usr/bin/env python3
"""
Remaining exercise data for topics not yet generated in gen_exercises.py
Run gen_exercises.py first, then this script.
"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from gen_exercises import mc, fib, dd, mt, mem, inject_into_topic, remove_topic

BASE = os.path.expanduser("~/projects/cleverli/src/data")

# ─── WETTER-KLIMA GRADE 2 (remaining) ────────────────────────────────────────
def wt_g2_rest():
    return [
        fib("wt32b","2","In der Schweiz gibt es vier Klimaregionen: Mittelland, Alpen, Alpensüdseite und ___.","In Switzerland there are four climate regions: Plateau, Alps, south side of Alps, and ___.","En Suisse il y a quatre régions climatiques : Plateau, Alpes, versant sud des Alpes et ___.","In Svizzera ci sono quattro regioni climatiche: Altopiano, Alpi, versante sud delle Alpi e ___.","Jura","Vier Klimaregionen der Schweiz.","Jura = weitere Region."),
        fib("wt33b","3","Die Jahreszeiten entstehen, weil die Erde eine ___ Achse hat.","Seasons form because Earth has a ___ axis.","Les saisons existent car la Terre a un axe ___.","Le stagioni esistono perché la Terra ha un asse ___.","geneigte","Geneigte Achse → unterschiedliche Sonnenstrahlung.","Neigung der Erdachse."),
        mc("wt34b","3","Was ist der Treibhauseffekt? 🌍","What is the greenhouse effect?","Qu'est-ce que l'effet de serre ?","Che cos'è l'effetto serra?","Treibhausgase halten Wärme in der Atmosphäre zurück",["Pflanzen wachsen im Treibhaus","Treibhausgase halten Wärme in der Atmosphäre zurück","Die Sonne wird wärmer","Wind kühlt die Erde"],"CO₂, Methan = Treibhausgase.","Erde erwärmt sich."),
        fib("wt35b","3","Das wichtigste Treibhausgas ist ___. 🌡️","The most important greenhouse gas is ___.","Le gaz à effet de serre le plus important est ___.","Il gas serra più importante è ___.","CO₂ (Kohlenstoffdioxid)","Verbrennung erzeugt CO₂.","CO₂ hält Wärme zurück."),
        mc("wt36b","3","Was ist Klimawandel? 🌡️","What is climate change?","Qu'est-ce que le changement climatique ?","Che cos'è il cambiamento climatico?","Langfristige Veränderung des Klimas, vor allem durch menschliche CO₂-Emissionen",["Tägliche Wetterveränderungen","Langfristige Veränderung des Klimas, vor allem durch menschliche CO₂-Emissionen","Ein Sturm","Jahreszeiten"],"Fossil-Brennstoffe → mehr CO₂ → Erwärmung.","Langfristig ≠ Wetter."),
        fib("wt37b","3","Die ___ schützt die Erde vor schädlichen UV-Strahlen der Sonne. 🌍","The ___ protects Earth from harmful UV rays from the sun.","La ___ protège la Terre des rayons UV du soleil.","La ___ protegge la Terra dai raggi UV del sole.","Ozonschicht","Ozon = Schutzschild.","UV-Strahlen → Sonnenbrand."),
        mc("wt38b","3","Was ist Evapotranspiration? 🌿","What is evapotranspiration?","Qu'est-ce que l'évapotranspiration ?","Che cos'è l'evapotraspirazione?","Verdunstung von Wasser durch Boden und Pflanzen zusammen",["Nur Verdunstung vom Meer","Verdunstung von Wasser durch Boden und Pflanzen zusammen","Regen","Kondensation"],"Evaporation (Boden) + Transpiration (Pflanzen).","Wälder kühlen durch Evapotranspiration."),
        fib("wt39b","3","Permafrost ist dauerhaft gefrorener Boden, der durch den ___ zu tauen beginnt.","Permafrost is permanently frozen ground that begins to thaw due to ___.","Le pergélisol est un sol perpétuellement gelé qui commence à dégeler à cause du ___.","Il permafrost è suolo perennemente gelato che inizia a sciogliersi a causa del ___.","Klimawandel / Klimaerwärmung","Erwärmung taut Permafrost.","Arktis betroffen."),
        mc("wt40b","3","Was ist Albedo? ❄️","What is albedo?","Qu'est-ce que l'albédo ?","Che cos'è l'albedo?","Der Anteil des Sonnenlichts, den eine Oberfläche reflektiert",["Die Erdwärme","Der Anteil des Sonnenlichts, den eine Oberfläche reflektiert","Die Lufttemperatur","Der Niederschlag"],"Schnee = hohe Albedo (reflektiert viel).","Ozean = niedrige Albedo (absorbiert viel)."),
        fib("wt41b","3","Passatwinde entstehen durch die ___ der Hadley-Zellen in der Troposphäre.","Trade winds form due to the ___ of Hadley cells in the troposphere.","Les alizés se forment grâce à la ___ des cellules de Hadley dans la troposphère.","Gli alisei si formano grazie alla ___ delle cellule di Hadley nella troposfera.","Zirkulation","Hadley-Zellen = Luftzirkulationsmuster.","Äquator heizt Luft auf."),
        mc("wt42b","3","Welche Klimazone findet man am Äquator? 🌍","Which climate zone is found at the equator?","Quelle zone climatique trouve-t-on à l'équateur ?","Quale zona climatica si trova all'equatore?","Tropisches Klima (immer warm und feucht)",["Polares Klima","Tropisches Klima (immer warm und feucht)","Gemässigtes Klima","Wüstenklima"],"Äquator = heiss und feucht.","Tropisch = Regenwald."),
        fib("wt43b","3","Der ozeanische Einfluss mildert das Klima: Küsten sind ___ als das Inland.","Oceanic influence moderates climate: coasts are ___ than inland.","L'influence océanique modère le climat : les côtes sont ___ que l'intérieur.","L'influenza oceanica modera il clima: le coste sono ___ dell'entroterra.","milder (wärmer im Winter, kühler im Sommer)","Meer puffert Temperatur.","Ozean = Wärmespeicher."),
        mc("wt44b","3","Was ist ein Monsun? 🌧️","What is a monsoon?","Qu'est-ce que la mousson ?","Che cos'è il monsone?","Ein saisonaler Windsystemwechsel mit starkem Regen (Sommer) und Trockenheit (Winter)",["Ein Tornado","Ein saisonaler Windsystemwechsel mit starkem Regen (Sommer) und Trockenheit (Winter)","Ein Gewitter","Dauerwind"],"Indien und Asien = Monsun-Gebiete.","Sommer-Monsun bringt Regen."),
        fib("wt45b","3","Die Atmosphäre der Erde besteht zu ca. 78% aus ___ und 21% Sauerstoff.","Earth's atmosphere is ~78% ___ and 21% oxygen.","L'atmosphère terrestre est composée à ~78% de ___ et 21% d'oxygène.","L'atmosfera terrestre è composta per ~78% di ___ e 21% di ossigeno.","Stickstoff (N₂)","N₂ = häufigstes Gas in der Atmosphäre.","Stickstoff inert, Sauerstoff zum Atmen."),
        mc("wt46b","3","Was sind Isotherme? 🌡️","What are isotherms?","Que sont les isothermes ?","Cosa sono le isoterme?","Linien auf Karten, die Orte gleicher Temperatur verbinden",["Linien für Regen","Linien auf Karten, die Orte gleicher Temperatur verbinden","Linien für Höhe","Linien für Luftdruck"],"Iso = gleich. Therm = Wärme.","Isothermen zeigen Temperaturverteilung."),
        fib("wt47b","3","Das Klima in der Schweiz wird vom Atlantik beeinflusst: Maritime Luftmassen bringen ___ Luftfeuchte.","Switzerland's climate is influenced by the Atlantic: maritime air masses bring ___ humidity.","Le climat suisse est influencé par l'Atlantique : les masses d'air maritimes apportent une humidité ___.","Il clima svizzero è influenzato dall'Atlantico: le masse d'aria marittime portano ___ umidità.","viel / hohe","Westwind bringt atlantische Luft.","Maritime = feuchte Luft."),
        mc("wt48b","3","Was beschreibt das Köppen-Klimaklassifikationssystem? 🌍","What does the Köppen climate classification describe?","Que décrit la classification climatique de Köppen ?","Cosa descrive la classificazione climatica di Köppen?","Ein System zur Einteilung der Klimazonen anhand von Temperatur und Niederschlag",["Ein Wettervorhersagemodell","Ein System zur Einteilung der Klimazonen anhand von Temperatur und Niederschlag","Ein Messinstrument","Eine Wetterkarte"],"Köppen: Buchstabencodes für Klimazonen.","Cfb = ozeanisch gemässigt (wie Schweiz)."),
        fib("wt49b","3","Der Golfstrom transportiert ___ Wasser von der Karibik nach Nordeuropa und mildert das Klima.","The Gulf Stream transports ___ water from the Caribbean to Northern Europe.","Le Gulf Stream transporte des eaux ___ des Caraïbes vers l'Europe du Nord.","La corrente del Golfo trasporta acque ___ dai Caraibi all'Europa del Nord.","warmes","Golfstrom = Heizung für Nordeuropa.","Ohne Golfstrom wäre es viel kälter."),
        mc("wt50b","3","Was ist ein Wetterfrontenmodell (Kaltfront / Warmfront)? 🌦️","What is a weather front model (cold/warm front)?","Qu'est-ce qu'un modèle de front météo (front froid/chaud) ?","Cosa è un modello di fronte meteorologico (fronte freddo/caldo)?","Grenzflächen zwischen Luftmassen unterschiedlicher Temperatur und Feuchtigkeit",["Nur Regengebiete","Grenzflächen zwischen Luftmassen unterschiedlicher Temperatur und Feuchtigkeit","Sonnenzonen","Windlinien"],"Kaltfront = abkühlend, Regen. Warmfront = erwärmend.","Front = Grenze zwischen Luftmassen."),
    ]

# ─── ENERGIE-STOFFE GRADE 3 (es11–es50) ─────────────────────────────────────
def es_g3():
    return [
        mc("es11","1","Was ist ein Aggregatzustand? 🌊","What is a state of matter?","Qu'est-ce qu'un état de la matière ?","Che cos'è uno stato di aggregazione?","Fest, flüssig oder gasförmig",["Eine Farbe","Eine Zahl","Fest, flüssig oder gasförmig","Eine Kraft"],"Wasser kann fest, flüssig oder gasförmig sein.","Drei Aggregatzustände."),
        fib("es12","1","Wenn Eis schmilzt, wird es zu ___ Wasser.","When ice melts, it becomes ___ water.","Quand la glace fond, elle devient de l'eau ___.","Quando il ghiaccio si scioglie, diventa acqua ___.","flüssigem","Eis = fest. Schmelzen = flüssig.","Erwärmung über 0°C."),
        mc("es13","1","Was ist der Unterschied zwischen erneuerbarer und nicht erneuerbarer Energie? ♻️","What is the difference between renewable and non-renewable energy?","Quelle est la différence entre énergie renouvelable et non renouvelable ?","Qual è la differenza tra energia rinnovabile e non rinnovabile?","Erneuerbare: immer nachgeliefert (Sonne, Wind). Nicht erneuerbare: endlich (Kohle, Öl)",["Es gibt keinen Unterschied","Erneuerbare: immer nachgeliefert. Nicht erneuerbare: endlich","Nicht erneuerbare = besser","Erneuerbare = nur Wasser"],"Sonne und Wind = unerschöpflich.","Kohle und Öl = endlich."),
        fib("es14","1","Wasserdampf ist Wasser im ___ Zustand.","Water vapour is water in the ___ state.","La vapeur d'eau est de l'eau à l'état ___.","Il vapore acqueo è acqua allo stato ___.","gasförmigen","Gas = dritter Aggregatzustand.","Dampf = Wasser als Gas."),
        mc("es15","1","Welche Energieform speichert eine Batterie? 🔋","What form of energy does a battery store?","Quelle forme d'énergie stocke une batterie ?","Quale forma di energia immagazzina una batteria?","Chemische Energie",["Lichtenergie","Wärmeenergie","Chemische Energie","Magnetische Energie"],"Batterien speichern chem. Energie.","Beim Entladen → elektrische Energie."),
        fib("es16","1","Wenn Wasser kocht (100°C), wird es zu ___. 🌡️","When water boils (100°C), it becomes ___.","Quand l'eau bout (100°C), elle devient ___.","Quando l'acqua bolle (100°C), diventa ___.","Dampf (Wasserdampf)","Kochen = Verdampfen.","Dampf = gasförmiges Wasser."),
        mc("es17","1","Was ist Lichtenergie? 💡","What is light energy?","Qu'est-ce que l'énergie lumineuse ?","Che cos'è l'energia luminosa?","Energie, die als Licht abgestrahlt wird",["Energie durch Bewegung","Energie, die als Licht abgestrahlt wird","Gespeicherte Energie","Wärmeenergie"],"Sonne und Lampen strahlen Licht.","Licht ist eine Energieform."),
        fib("es18","1","Holz verbrennt und wandelt chemische Energie in ___ und Licht um.","Wood burns and converts chemical energy into ___ and light.","Le bois brûle et convertit l'énergie chimique en ___ et lumière.","Il legno brucia e converte l'energia chimica in ___ e luce.","Wärme","Verbrennung = chemische Energie → Wärme + Licht.","Feuer erzeugt Wärme."),
        mc("es19","1","Was ist Kernenergie? ⚛️","What is nuclear energy?","Qu'est-ce que l'énergie nucléaire ?","Che cos'è l'energia nucleare?","Energie, die aus der Spaltung von Atomkernen gewonnen wird",["Energie aus Wind","Energie aus Sonne","Energie, die aus der Spaltung von Atomkernen gewonnen wird","Energie aus Wasser"],"Atomkraft nutzt Kernspaltung.","Uran = Brennstoff."),
        fib("es20","1","Die Schweiz gewinnt den grössten Teil ihres Stroms aus ___kraft. 💧","Switzerland generates most of its electricity from ___ power.","La Suisse produit la plus grande partie de son électricité grâce à l'énergie ___.","La Svizzera produce la maggior parte dell'elettricità dall'energia ___.","Wasser","Viele Stauseen in der Schweiz.","Wasser dreht Turbinen."),
        fib("es21","1","Ein ___ Körper behält seine Form (Bsp. Stein, Eis). 🧊","A ___ object keeps its shape (e.g. stone, ice).","Un objet ___ garde sa forme (ex. pierre, glace).","Un oggetto ___ mantiene la sua forma (es. pietra, ghiaccio).","fester","Fest = starre Form.","Fest: Stein, Holz, Eis."),
        mc("es22","2","Was ist der Energieerhaltungssatz? ⚡","What is the law of energy conservation?","Qu'est-ce que la loi de conservation de l'énergie ?","Che cos'è la legge di conservazione dell'energia?","Energie kann weder erzeugt noch vernichtet, nur umgewandelt werden",["Energie wächst","Energie schrumpft","Energie kann weder erzeugt noch vernichtet, nur umgewandelt werden","Energie ist sichtbar"],"Physikalisches Grundgesetz.","Energie bleibt immer erhalten."),
        fib("es23","2","Wenn Wasserdampf sich abkühlt, ___ er (wird wieder flüssig). ☁️","When water vapour cools, it ___ (becomes liquid again).","Quand la vapeur d'eau se refroidit, elle ___ (redevient liquide).","Quando il vapore acqueo si raffredda, ___ (diventa di nuovo liquido).","kondensiert","Kondensation = Dampf → Flüssigkeit.","Wolken entstehen durch Kondensation."),
        mc("es24","2","Was ist kinetische Energie? 🏃","What is kinetic energy?","Qu'est-ce que l'énergie cinétique ?","Che cos'è l'energia cinetica?","Energie eines bewegten Körpers",["Energie eines ruhenden Körpers","Energie eines bewegten Körpers","Gespeicherte Energie","Wärme"],"Rollender Ball = kinetische Energie.","Kinetisch = in Bewegung."),
        fib("es25","2","Ein Windrad wandelt ___ energie in elektrische Energie um.","A wind turbine converts ___ energy into electrical energy.","Une éolienne convertit l'énergie ___ en énergie électrique.","Un mulino a vento converte l'energia ___ in energia elettrica.","Wind-","Wind dreht Turbinen → Strom.","Kinetische Windenergie → Elektrizität."),
        mc("es26","2","Was passiert beim Schmelzen? 🌡️","What happens during melting?","Que se passe-t-il lors de la fusion ?","Cosa succede durante la fusione?","Ein fester Stoff wird flüssig (durch Wärmezufuhr)",["Ein Stoff wird gasförmig","Ein fester Stoff wird flüssig (durch Wärmezufuhr)","Wärme wird erzeugt","Ein Stoff erstarrt"],"Eis schmilzt bei 0°C.","Fest → Flüssig = Schmelzen."),
        fib("es27","2","Lageenergie (potentielle Energie) hat ein Objekt, wenn es sich ___ befindet.","Potential energy is stored in an object at ___.","L'énergie potentielle est stockée dans un objet en ___.","L'energia potenziale è immagazzinata in un oggetto in ___.","erhöhter Position / oben","Höhe = Lageenergie.","Apfel auf dem Baum = viel Lageenergie."),
        mc("es28","2","Was ist Biomasse als Energiequelle? 🌿","What is biomass as an energy source?","Qu'est-ce que la biomasse comme source d'énergie ?","Che cos'è la biomassa come fonte di energia?","Organisches Material (Holz, Pflanzen, Abfälle) das verbrannt wird",["Kohle","Erdöl","Organisches Material (Holz, Pflanzen, Abfälle) das verbrannt wird","Kernenergie"],"Holz verbrennen = Biomasse.","Erneuerbar, wenn nachgepflanzt."),
        fib("es29","2","Elektrische Energie wird in Leitungen als ___ transportiert.","Electrical energy is transported in wires as ___.","L'énergie électrique est transportée dans les fils comme ___.","L'energia elettrica è trasportata nei fili come ___.","Strom (elektrischer Strom)","Kabel leiten Strom.","Elektronen fliessen im Kabel."),
        mc("es30","2","Was ist ein Isolator (thermisch)? 🌡️","What is a thermal insulator?","Qu'est-ce qu'un isolant thermique ?","Che cos'è un isolante termico?","Ein Material, das Wärme schlecht leitet",["Ein Material, das Wärme gut leitet","Ein Material, das Wärme schlecht leitet","Ein Metall","Eine Energiequelle"],"Holz und Styropor = Isolatoren.","Häuser isolieren = weniger Heizung."),
        fib("es31","2","Der Unterschied zwischen Wärme und Temperatur: Wärme ist ___. Temperatur ist ein Mass für…","Difference between heat and temperature: heat is ___.","Différence entre chaleur et température : la chaleur est ___.","Differenza tra calore e temperatura: il calore è ___.","Energie","Wärme = Energiemenge.","Temperatur misst wie warm etwas ist."),
        mc("es32","2","Was ist Geothermie? 🌋","What is geothermal energy?","Qu'est-ce que la géothermie ?","Che cos'è la geotermia?","Energie aus der Erdwärme",["Energie aus Wind","Energie aus der Erdwärme","Energie aus Sonne","Energie aus Wasser"],"Erdinneres ist heiss.","Islandische Heizung = Geothermie."),
        fib("es33","2","Energieeffizienz bedeutet, dass man ___ Energie einsetzt, um dasselbe Ziel zu erreichen.","Energy efficiency means using ___ energy to achieve the same goal.","L'efficacité énergétique signifie utiliser ___ d'énergie pour le même objectif.","L'efficienza energetica significa utilizzare ___ energia per raggiungere lo stesso obiettivo.","weniger","LED vs. Glühbirne.","Weniger Energie = effizienter."),
        mc("es34","2","Was ist Sublimation? ❄️","What is sublimation?","Qu'est-ce que la sublimation ?","Che cos'è la sublimazione?","Wenn ein fester Stoff direkt zu Gas wird (ohne flüssig zu werden)",["Wenn ein Gas flüssig wird","Wenn ein fester Stoff direkt zu Gas wird (ohne flüssig zu werden)","Wenn Flüssigkeit gefriert","Wenn Wasser siedet"],"Trockeneis sublimiert bei Raumtemperatur.","Fest → Gas ohne flüssige Phase."),
        fib("es35","2","Wenn man Wasser unter 0°C kühlt, erstarrt es zu ___. 🧊","When water is cooled below 0°C, it solidifies to ___.","Quand l'eau est refroidie en dessous de 0°C, elle se solidifie en ___.","Quando l'acqua viene raffreddata sotto 0°C, si solidifica in ___.","Eis","0°C = Gefrierpunkt.","Erstarren = Flüssig → Fest."),
        mc("es36","2","Was ist CO₂ und warum ist es klimarelevant? 🌍","What is CO₂ and why is it climate-relevant?","Qu'est-ce que le CO₂ et pourquoi est-il climatiquement pertinent ?","Che cos'è il CO₂ e perché è rilevante per il clima?","Kohlenstoffdioxid; es ist ein Treibhausgas, das Wärme in der Atmosphäre zurückhält",["Ein Edelgas ohne Wirkung","Kohlenstoffdioxid; es ist ein Treibhausgas, das Wärme zurückhält","Nur in der Industrie","Ein Metall"],"CO₂ entsteht bei Verbrennung.","Mehr CO₂ = Erderwärmung."),
        fib("es37","3","Der Wirkungsgrad η = Nutzenergie / ___ × 100%.","Efficiency η = useful energy / ___ × 100%.","Le rendement η = énergie utile / ___ × 100%.","Il rendimento η = energia utile / ___ × 100%.","Eingangsenergie (Gesamtenergie)","Wirkungsgrad: wie viel wird genutzt.","Ideal: η = 100%."),
        mc("es38","3","Was ist Enthalpie? ⚗️","What is enthalpy?","Qu'est-ce que l'enthalpie ?","Che cos'è l'entalpia?","Die Gesamtenergie eines Systems einschliesslich innerer Energie und Druckarbeit",["Nur innere Energie","Die Gesamtenergie eines Systems einschliesslich innerer Energie und Druckarbeit","Die kinetische Energie","Die potentielle Energie"],"H = U + pV.","Enthalpie = chemische Energie + Volumenarbeit."),
        fib("es39","3","Ein Wärmetauscher überträgt Wärme von einem ___ auf ein anderes Medium.","A heat exchanger transfers heat from one ___ to another medium.","Un échangeur de chaleur transfère la chaleur d'un ___ à un autre milieu.","Un scambiatore di calore trasferisce il calore da un ___ a un altro mezzo.","Medium / Fluid","Keine direkte Vermischung.","Heizungsanlagen nutzen Wärmetauscher."),
        mc("es40","3","Was ist Spezifische Wärmekapazität? 🌡️","What is specific heat capacity?","Qu'est-ce que la capacité thermique spécifique ?","Che cos'è la capacità termica specifica?","Die Energie, die 1 kg eines Stoffs um 1°C erwärmt (J/kg·K)",["Die Wärme die ein Körper abgibt","Die Energie, die 1 kg eines Stoffs um 1°C erwärmt (J/kg·K)","Die maximale Temperatur","Die Siedetemperatur"],"Wasser: c = 4186 J/kg·K (sehr hoch).","Hohe c = langsames Erwärmen."),
        fib("es41","3","Der erste Hauptsatz der Thermodynamik: Die innere Energie eines abgeschlossenen Systems bleibt ___.","First law of thermodynamics: the internal energy of a closed system remains ___.","1re loi de la thermodynamique : l'énergie interne d'un système fermé reste ___.","1a legge della termodinamica: l'energia interna di un sistema chiuso rimane ___.","konstant / erhalten","Energieerhaltung.","Energie weder erzeugt noch vernichtet."),
        mc("es42","3","Was beschreibt der zweite Hauptsatz der Thermodynamik? ⚡","What does the second law of thermodynamics describe?","Que décrit la 2e loi de la thermodynamique ?","Cosa descrive il secondo principio della termodinamica?","Wärme fliesst von selbst von warm zu kalt, nie umgekehrt",["Energie ist konstant","Wärme fliesst von selbst von warm zu kalt, nie umgekehrt","Energie nimmt zu","Entropie nimmt ab"],"Kaffee kühlt ab, kühle Luft erwärmt sich nicht selbst.","Entropie nimmt zu."),
        fib("es43","3","Fusion (Kernfusion) ist die Vereinigung von leichten Atomkernen zu schweren – dabei wird ___ freigesetzt.","Fusion (nuclear) is the combining of light nuclei into heavy ones – ___ is released.","La fusion (nucléaire) consiste à combiner des noyaux légers – de l'___ est libérée.","La fusione (nucleare) combina nuclei leggeri – viene liberata ___.","Energie","Sonne = Kernfusion.","H → He + Energie."),
        mc("es44","3","Was ist Photovoltaik? ☀️","What is photovoltaics?","Qu'est-ce que le photovoltaïque ?","Che cos'è il fotovoltaico?","Direkte Umwandlung von Sonnenlicht in elektrische Energie durch Solarzellen",["Solarthermie","Direkte Umwandlung von Sonnenlicht in elektrische Energie durch Solarzellen","Windkraft","Wasserkraft"],"Solarzellen auf Dächern = Photovoltaik.","Licht → Strom (direkt)."),
        fib("es45","3","Entropy is the measure of ___ in a system (disorder).","Entropy is the measure of ___ in a system.","L'entropie est la mesure du ___ dans un système.","L'entropia è la misura del ___ in un sistema.","Unordnung / Disorder","2. Hauptsatz: Entropie wächst.","Unordnung nimmt zu."),
        mc("es46","3","Was ist ein Kraftwerk? ⚡","What is a power plant?","Qu'est-ce qu'une centrale électrique ?","Che cos'è una centrale elettrica?","Eine Anlage, die Energie in Strom umwandelt",["Ein Speicher für Energie","Eine Anlage, die Energie in Strom umwandelt","Ein Verteilnetz","Ein Transformator"],"Wasserkraftwerk, Atomkraftwerk = Kraftwerke.","Energie → Strom."),
        fib("es47","3","Elektrolyse ist ein Prozess, bei dem elektrische Energie verwendet wird, um chemische ___ zu treiben.","Electrolysis is a process where electrical energy drives chemical ___.","L'électrolyse est un processus où l'énergie électrique entraîne des ___ chimiques.","L'elettrolisi è un processo in cui l'energia elettrica guida le ___ chimiche.","Reaktionen","Wasser → H₂ + O₂ durch Elektrolyse.","Strom → Chemie."),
        mc("es48","3","Was ist ein Smart Grid? ⚡","What is a smart grid?","Qu'est-ce qu'un réseau intelligent ?","Che cos'è una rete intelligente?","Ein intelligentes Stromnetz, das Erzeugung und Verbrauch digital optimiert",["Ein einfaches Stromnetz","Ein intelligentes Stromnetz, das Erzeugung und Verbrauch digital optimiert","Ein Solarpanel","Ein Wasserkraftwerk"],"Smart Grid = digitales Stromnetz.","Bessere Integration erneuerbarer Energien."),
        fib("es49","3","Sonnenenergie gelangt zur Erde als ___ Strahlung.","Solar energy reaches Earth as ___ radiation.","L'énergie solaire atteint la Terre sous forme de rayonnement ___.","L'energia solare raggiunge la Terra come radiazione ___.","elektromagnetische","Licht = elektromagnetische Welle.","UV, sichtbares Licht, Infrarot."),
        mc("es50","3","Was ist Brennstoffzelle? ⚗️","What is a fuel cell?","Qu'est-ce qu'une pile à combustible ?","Che cos'è una cella a combustibile?","Ein Gerät, das chemische Energie (z.B. Wasserstoff) direkt in Strom umwandelt",["Ein Akkumulator","Ein Gerät, das chemische Energie (z.B. Wasserstoff) direkt in Strom umwandelt","Ein Solarpanel","Ein Motor"],"H₂ + O₂ → H₂O + Strom (in Brennstoffzelle).","Sauber und effizient."),
    ]

# ─── ENERGIE-STOFFE GRADE 4 (es11b–es50b) ─────────────────────────────────
def es_g4():
    # Grade 4 NT - same topic, more advanced
    return [
        mc("es11b2","1","Was ist Energie? ⚡","What is energy?","Qu'est-ce que l'énergie ?","Che cos'è l'energia?","Die Fähigkeit, Arbeit zu leisten",["Ein Material","Die Fähigkeit, Arbeit zu leisten","Eine Farbe","Ein Tier"],"Energie gibt es in vielen Formen.","Ohne Energie geht nichts."),
        fib("es12b","1","Energie kann ___ werden, aber nie vernichtet.","Energy can be ___, but never destroyed.","L'énergie peut être ___, mais jamais détruite.","L'energia può essere ___, ma mai distrutta.","umgewandelt","Energieerhaltungssatz.","Energie bleibt immer erhalten."),
        mc("es13b2","1","Was ist der Unterschied zwischen kinetischer und potentieller Energie? ⚡","Difference between kinetic and potential energy?","Différence entre énergie cinétique et potentielle ?","Differenza tra energia cinetica e potenziale?","Kinetisch = Bewegungsenergie; Potentiell = Lageenergie",["Beide gleich","Kinetisch = Bewegungsenergie; Potentiell = Lageenergie","Kinetisch = gespeichert","Potentiell = Bewegung"],"Rollender Ball = kinetisch; Apfel auf Baum = potentiell.","Zwei Formen mechanischer Energie."),
        fib("es14b","1","Wenn Wasserdampf sich abkühlt und flüssig wird, nennt man das ___.","When water vapour cools and becomes liquid, this is called ___.","Quand la vapeur d'eau refroidit et devient liquide, on appelle ça ___.","Quando il vapore acqueo si raffredda e diventa liquido, si chiama ___.","Kondensation","Dampf → Wasser = Kondensation.","Tau entsteht durch Kondensation."),
        mc("es15b2","1","Was ist elektrische Energie? ⚡","What is electrical energy?","Qu'est-ce que l'énergie électrique ?","Che cos'è l'energia elettrica?","Energie durch fliessende Elektronen",["Energie aus Licht","Energie durch fliessende Elektronen","Wärmeenergie","Windenergie"],"Steckdose liefert elektrische Energie.","Elektronen fliessen durch Leiter."),
        fib("es16b","1","Licht ist eine Form von ___ energie.","Light is a form of ___ energy.","La lumière est une forme d'énergie ___.","La luce è una forma di energia ___.","Strahlung / elektromagnetischer","Licht = elektromagnetische Strahlung.","Sonne strahlt Licht ab."),
        mc("es17b2","1","Was ist Wärme? 🔥","What is heat?","Qu'est-ce que la chaleur ?","Che cos'è il calore?","Eine Form von Energie, die von wärmerem zu kälterem Körper fliesst",["Eine Temperatur","Eine Form von Energie, die von wärmerem zu kälterem Körper fliesst","Strahlung","Bewegung"],"Wärme = Energietransport.","Fliesst immer von warm zu kalt."),
        fib("es18b","1","Solarenergie kommt von der ___ und ist erneuerbar. ☀️","Solar energy comes from the ___ and is renewable.","L'énergie solaire vient du ___ et est renouvelable.","L'energia solare viene dal ___ ed è rinnovabile.","Sonne","Sonne scheint jeden Tag neu.","Erneuerbar = unerschöpflich."),
        mc("es19b2","1","Was ist ein Transformator? ⚡","What is a transformer?","Qu'est-ce qu'un transformateur ?","Che cos'è un trasformatore?","Ein Gerät, das elektrische Spannung erhöht oder senkt",["Ein Energiespeicher","Ein Gerät, das elektrische Spannung erhöht oder senkt","Ein Generator","Ein Akku"],"Transformatoren in Strommast.","Hoch-/Niederspannung."),
        fib("es20b","1","Ein Kilowattstunde (kWh) ist die Einheit für ___ .","A kilowatt-hour (kWh) is the unit of ___.","Un kilowattheure (kWh) est l'unité d'___.","Un kilowattora (kWh) è l'unità di ___.","Energie (Stromverbrauch)","Stromrechnung = kWh.","1 kWh = 3,6 Megajoule."),
        fib("es21b","1","Kernenergie nutzt die ___ von Uran-Atomkernen zur Energieerzeugung. ⚛️","Nuclear energy uses the ___ of uranium nuclei to generate energy.","L'énergie nucléaire utilise la ___ des noyaux d'uranium pour produire de l'énergie.","L'energia nucleare usa la ___ dei nuclei di uranio per generare energia.","Spaltung (Kernspaltung)","Kernspaltung → Wärme → Strom.","Uran = Kernbrennstoff."),
        mc("es22b","2","Was ist ein Generator? ⚡","What is a generator?","Qu'est-ce qu'un générateur ?","Che cos'è un generatore?","Ein Gerät, das mechanische Energie in elektrische umwandelt",["Ein Energiespeicher","Ein Gerät, das mechanische Energie in elektrische umwandelt","Ein Transformer","Ein Akku"],"Kraftwerke nutzen Generatoren.","Bewegung → Strom."),
        fib("es23b","2","Ohmsches Gesetz: Spannung U = ___ × Widerstand R. ⚡","Ohm's law: Voltage U = ___ × Resistance R.","Loi d'Ohm : Tension U = ___ × Résistance R.","Legge di Ohm: Tensione U = ___ × Resistenza R.","Stromstärke I","U = I × R.","Volt = Ampere × Ohm."),
        mc("es24b","2","Was ist elektrischer Widerstand? ⚡","What is electrical resistance?","Qu'est-ce que la résistance électrique ?","Che cos'è la resistenza elettrica?","Der Widerstand eines Materials gegen den Stromfluss (gemessen in Ohm)",["Die Spannung","Der Widerstand eines Materials gegen den Stromfluss (gemessen in Ohm)","Die Stromstärke","Die Leistung"],"R = U/I. Einheit: Ohm (Ω).","Mehr Widerstand = weniger Strom."),
        fib("es25b","2","Ein Solarpanel wandelt ___ energie direkt in elektrische Energie um. ☀️","A solar panel converts ___ energy directly into electrical energy.","Un panneau solaire convertit l'énergie ___ directement en énergie électrique.","Un pannello solare converte l'energia ___ direttamente in energia elettrica.","Licht- (Sonnen-)","Fotovoltaik.","Licht → Strom."),
        mc("es26b","2","Was ist Leistung (elektrisch)? P = U × I ⚡","What is electric power? P = U × I","Qu'est-ce que la puissance électrique ? P = U × I","Che cos'è la potenza elettrica? P = U × I","Spannung × Stromstärke (in Watt)",["Nur Spannung","Nur Stromstärke","Spannung × Stromstärke (in Watt)","Widerstand × Zeit"],"P = U × I. Einheit: Watt (W).","1 Watt = 1 Volt × 1 Ampere."),
        fib("es27b","2","Windkraftanlagen wandeln ___ energie in elektrische Energie um. 💨","Wind turbines convert ___ energy into electrical energy.","Les éoliennes convertissent l'énergie ___ en énergie électrique.","I mulini a vento convertono l'energia ___ in energia elettrica.","Windenergie (kinetische)","Wind dreht Rotor.","Kinetische Energie → Strom."),
        mc("es28b","2","Was ist ein Akku (Akkumulator)? 🔋","What is a rechargeable battery?","Qu'est-ce qu'un accumulateur ?","Che cos'è un accumulatore?","Ein wiederaufladbarer elektrischer Energiespeicher",["Ein Einweg-Energiespeicher","Ein wiederaufladbarer elektrischer Energiespeicher","Ein Generator","Ein Solarpanel"],"Handy-Akku = Akkumulator.","Aufladen und wieder entladen."),
        fib("es29b","2","Der Wirkungsgrad einer LED-Lampe ist ___ als der einer Glühbirne.","The efficiency of an LED bulb is ___ than an incandescent bulb.","Le rendement d'une LED est ___ que celui d'une ampoule incandescente.","Il rendimento di una LED è ___ di quello di una lampadina incandescente.","grösser / höher","LED = weniger Verlust als Wärme.","Effizienz verbessert durch LED."),
        mc("es30b","2","Was ist der Unterschied zwischen Gleich- und Wechselstrom? ⚡","What is the difference between DC and AC?","Quelle est la différence entre courant continu et alternatif ?","Qual è la differenza tra corrente continua e alternata?","Gleichstrom: fliegt immer in eine Richtung; Wechselstrom: wechselt die Richtung periodisch",["Beide gleich","Gleichstrom: fliegt immer in eine Richtung; Wechselstrom: wechselt die Richtung periodisch","Wechselstrom ist stärker","Gleichstrom ist wechselnd"],"Batterie = DC. Steckdose = AC.","50 Hz Wechselstrom in Europa."),
        fib("es31b","2","In Europa beträgt die Netzspannung ___ Volt (Wechselstrom).","In Europe the grid voltage is ___ Volts (AC).","En Europe, la tension du réseau est de ___ Volts (AC).","In Europa la tensione di rete è di ___ Volt (AC).","230","230V AC in Europa.","USA: 110V."),
        mc("es32b","2","Was ist ein Supraleiter? ⚡","What is a superconductor?","Qu'est-ce qu'un supraconducteur ?","Che cos'è un superconduttore?","Ein Material, das bei tiefen Temperaturen keinen elektrischen Widerstand hat",["Ein schlechter Leiter","Ein Material, das bei tiefen Temperaturen keinen elektrischen Widerstand hat","Ein Isolator","Ein Halbleiter"],"Supraleiter bei -200°C+.","Kein Widerstand = kein Energieverlust."),
        fib("es33b","2","Geothermie nutzt die Wärme aus dem ___ der Erde. 🌋","Geothermal energy uses heat from Earth's ___.","La géothermie utilise la chaleur du ___ de la Terre.","La geotermia usa il calore dell'___ della Terra.","Erdinneren (Untergrund)","Magma erhitzt Gesteine.","Island = Geothermie."),
        mc("es34b","2","Was ist Energiespeicherung? 🔋","What is energy storage?","Qu'est-ce que le stockage d'énergie ?","Che cos'è lo stoccaggio di energia?","Das Speichern von Energie für späteren Gebrauch (Akkus, Pumpspeicher)",["Das Erzeugen von Energie","Das Speichern von Energie für späteren Gebrauch","Das Übertragen von Energie","Das Verbrauchen von Energie"],"Akkus, Pumpspeicherkraftwerke = Speicher.","Erneuerbare brauchen Speicher."),
        fib("es35b","2","Ein Pumpspeicherkraftwerk speichert Energie, indem es Wasser ___ pumpt und es später durch Turbinen fliessen lässt.","A pumped hydro plant stores energy by pumping water ___ and later letting it flow through turbines.","Une centrale hydraulique par pompage stocke l'énergie en pompant l'eau ___.","Un impianto idroelettrico a pompaggio immagazzina energia pompando l'acqua ___.","bergauf (nach oben)","Oben = Lageenergie.","Strom → Pumpen → Wasser oben."),
        mc("es36b","2","Was ist die Energiewende? 🌍","What is the energy transition?","Qu'est-ce que la transition énergétique ?","Che cos'è la transizione energetica?","Der Wechsel von fossilen zu erneuerbaren Energiequellen",["Ein Stromausfall","Der Wechsel von fossilen zu erneuerbaren Energiequellen","Höherer Verbrauch","Neue Kraftwerke"],"Weg von Kohle und Öl, hin zu Sonne und Wind.","Klimaschutz."),
        fib("es37b","3","Quantenphysik erklärt, dass Elektronen sich in ___ bewegen, nicht auf fixen Kreisbahnen.","Quantum physics explains that electrons move in ___, not fixed orbits.","La physique quantique explique que les électrons se déplacent dans des ___.","La fisica quantistica spiega che gli elettroni si muovono in ___.","Orbitalen (Wahrscheinlichkeitswolken)","Bohr-Modell vereinfacht.","Quantenmechanik = Orbitale."),
        mc("es38b","3","Was ist die Boltzmann-Konstante? ⚛️","What is the Boltzmann constant?","Qu'est-ce que la constante de Boltzmann ?","Che cos'è la costante di Boltzmann?","Eine fundamentale Konstante, die thermische Energie mit Temperatur verbindet (k = 1,38×10⁻²³ J/K)",["Die Planck-Konstante","Eine fundamentale Konstante, die thermische Energie mit Temperatur verbindet","Die Lichtgeschwindigkeit","Die Gravitationskonstante"],"k_B verbindet mikroskopisch und makroskopisch.","k_B = 1,38 × 10⁻²³ J/K."),
        fib("es39b","3","E = mc² beschreibt die Äquivalenz von ___ und Energie (Einstein). ⚛️","E = mc² describes the equivalence of ___ and energy (Einstein).","E = mc² décrit l'équivalence de la ___ et de l'énergie (Einstein).","E = mc² descrive l'equivalenza di ___ ed energia (Einstein).","Masse","Masse kann in Energie umgewandelt werden.","Kernspaltung nutzt das aus."),
        mc("es40b","3","Was ist Plasma? 🌟","What is plasma?","Qu'est-ce que le plasma ?","Che cos'è il plasma?","Ein vierter Aggregatzustand – ionisiertes Gas mit freien Elektronen",["Flüssigkeit bei hoher Temperatur","Ein vierter Aggregatzustand – ionisiertes Gas mit freien Elektronen","Normales Gas","Ein Feststoff"],"Sonne = Plasma.","Blitze = Plasma."),
        fib("es41b","3","Die Planck-Konstante h beschreibt die Energie von ___ h×f.","Planck's constant h describes the energy of photons: E = h×f.","La constante de Planck h décrit l'énergie de photons : E = h×f.","La costante di Planck h descrive l'energia dei fotoni: E = h×f.","Photonen (Lichtquanten)","Photoeffekt: Licht = Photonen.","E = h × Frequenz."),
        mc("es42b","3","Was beschreibt das Ohm-Gesetz im Kontext von Leitern? ⚡","What does Ohm's law describe for conductors?","Que décrit la loi d'Ohm pour les conducteurs ?","Cosa descrive la legge di Ohm per i conduttori?","U = R × I (Spannung = Widerstand × Strom)",["U = I / R","U = R × I (Spannung = Widerstand × Strom)","R = U × I","I = U × R"],"U = R × I.","Volt = Ohm × Ampere."),
        fib("es43b","3","In einem Supraleiter ist der elektrische Widerstand bei tiefen Temperaturen exakt ___.","In a superconductor, electrical resistance is exactly ___ at low temperatures.","Dans un supraconducteur, la résistance est exactement ___ à basse température.","In un superconduttore, la resistenza è esattamente ___ a bassa temperatura.","null (0 Ω)","Kein Widerstand = kein Verlust.","Supraleitung."),
        mc("es44b","3","Was ist Quantenverschränkung? ⚛️","What is quantum entanglement?","Qu'est-ce que l'intrication quantique ?","Che cos'è l'entanglement quantistico?","Zwei Quantenobjekte sind so verbunden, dass der Zustand eines sofort den anderen beeinflusst",["Zwei Teilchen stossen zusammen","Zwei Quantenobjekte sind so verbunden, dass der Zustand eines sofort den anderen beeinflusst","Normale elektromagnetische Verbindung","Magnetismus zwischen Teilchen"],"Einstein: spukhafte Fernwirkung.","Genutzt für Quantencomputer."),
        fib("es45b","3","Fusionsenergie entsteht, wenn leichte Kerne (z.B. ___ ) zu schwereren verschmelzen.","Fusion energy forms when light nuclei (e.g. ___ ) merge into heavier ones.","L'énergie de fusion se forme quand des noyaux légers (p. ex. ___ ) fusionnent.","L'energia di fusione si forma quando nuclei leggeri (es. ___ ) si fondono.","Wasserstoff (H)","H + H → He + Energie (Sonne).","Kernfusion = Sonnenenergie."),
        mc("es46b","3","Was ist ein Halbleiter? ⚡","What is a semiconductor?","Qu'est-ce qu'un semi-conducteur ?","Che cos'è un semiconduttore?","Ein Material, dessen Leitfähigkeit zwischen Leiter und Isolator liegt",["Ein guter Leiter","Ein Material, dessen Leitfähigkeit zwischen Leiter und Isolator liegt","Ein Isolator","Ein Supraleiter"],"Silizium = klassischer Halbleiter.","Transistoren und Chips."),
        fib("es47b","3","Der photoelektrische Effekt: Licht schlägt ___ aus Metalloberflächen heraus (Einstein 1905).","Photoelectric effect: light ejects ___ from metal surfaces (Einstein 1905).","Effet photoélectrique : la lumière éjecte des ___ des surfaces métalliques (Einstein 1905).","Effetto fotoelettrico: la luce espelle ___ dalle superfici metalliche (Einstein 1905).","Elektronen","Licht → Elektronen = Photoeffekt.","Nobel 1921 für Einstein."),
        mc("es48b","3","Was ist Entropie? ⚗️","What is entropy?","Qu'est-ce que l'entropie ?","Che cos'è l'entropia?","Ein Mass für die Unordnung in einem System",["Die Temperatur","Ein Mass für die Unordnung in einem System","Die Energie","Der Druck"],"2. Hauptsatz: Entropie nimmt zu.","Unordnung wächst."),
        fib("es49b","3","Strom in Haushalten wird als ___ transportiert und in Haushaltsgeräten genutzt.","Power in homes is transported as ___ and used in appliances.","Le courant dans les maisons est transporté sous forme de ___ et utilisé dans les appareils.","La corrente nelle case è trasportata come ___ e usata negli elettrodomestici.","Wechselstrom (AC, 230V)","Steckdose = 230V AC.","Wechselstrom für Haushalte."),
        mc("es50b","3","Was ist die Bedeutung der Planck-Länge? ⚛️","What is the significance of Planck length?","Quelle est la signification de la longueur de Planck ?","Qual è il significato della lunghezza di Planck?","Die kleinste sinnvolle Längenskala in der Physik (~1,6×10⁻³⁵ m)",["Die Grösse eines Atoms","Die kleinste sinnvolle Längenskala in der Physik (~1,6×10⁻³⁵ m)","Die Wellenlänge des Lichts","Die Grösse eines Protons"],"Unterhalb der Planck-Länge bricht die Physik zusammen.","Quantengravitation."),
    ]

# ─── LICHT-OPTIK GRADE 3 (lo11–lo50) ────────────────────────────────────────
def lo_g3():
    return [
        mc("lo11","1","Was ist Licht? 💡","What is light?","Qu'est-ce que la lumière ?","Che cos'è la luce?","Elektromagnetische Strahlung, die wir sehen können",["Ein Gas","Elektromagnetische Strahlung, die wir sehen können","Wärme","Ein Ton"],"Licht = elektromagnetische Welle.","Unser Auge empfängt Licht."),
        fib("lo12","1","Die Sonne ist eine natürliche ___quelle. ☀️","The sun is a natural ___ source.","Le soleil est une source de ___ naturelle.","Il sole è una sorgente di ___ naturale.","Licht","Sonne = Lichtquelle.","Ohne Sonne kein Tageslicht."),
        mc("lo13","1","Was ist eine Lichtquelle? 💡","What is a light source?","Qu'est-ce qu'une source de lumière ?","Che cos'è una sorgente di luce?","Etwas, das selbst Licht erzeugt",["Etwas, das Licht reflektiert","Etwas, das selbst Licht erzeugt","Etwas, das Schatten wirft","Etwas, das Licht absorbiert"],"Sonne, Kerze, Lampe = Lichtquellen.","Erzeugt Licht selbst."),
        fib("lo14","1","Ein Schatten entsteht, wenn Licht von einem ___ Objekt blockiert wird.","A shadow forms when light is blocked by an ___ object.","Une ombre se forme quand la lumière est bloquée par un objet ___.","Un'ombra si forma quando la luce viene bloccata da un oggetto ___.","undurchsichtigen","Glas lässt Licht durch, Holz nicht.","Undurchsichtig = kein Licht."),
        mc("lo15","1","Was ist Reflexion von Licht? 🪞","What is light reflection?","Qu'est-ce que la réflexion de la lumière ?","Che cos'è la riflessione della luce?","Licht prallt von einer Fläche zurück",["Licht wird absorbiert","Licht prallt von einer Fläche zurück","Licht erzeugt Wärme","Licht verschwindet"],"Spiegel reflektieren Licht.","Reflexion = Zurückwerfen."),
        fib("lo16","1","Weisses Licht besteht aus ___ Farben. 🌈","White light consists of ___ colours.","La lumière blanche est composée de ___ couleurs.","La luce bianca è composta da ___ colori.","vielen / allen Regenbogenfarben","Prisma zerlegt weisses Licht.","7 Farben des Regenbogens."),
        mc("lo17","1","Was ist ein transparentes (durchsichtiges) Objekt? 🔍","What is a transparent object?","Qu'est-ce qu'un objet transparent ?","Che cos'è un oggetto trasparente?","Eines, durch das Licht hindurchgeht",["Eines, das Licht reflektiert","Eines, durch das Licht hindurchgeht","Eines, das Schatten wirft","Eines, das Licht absorbiert"],"Fensterglas = transparent.","Transparent = Licht geht durch."),
        fib("lo18","1","Der Mond leuchtet, weil er ___ von der Sonne reflektiert. 🌕","The moon shines because it ___ sunlight.","La lune brille parce qu'elle ___ la lumière du soleil.","La luna brilla perché ___ la luce del sole.","Licht","Mond = Reflektor, keine eigene Lichtquelle.","Sonnenlicht → Mond → Erde."),
        mc("lo19","1","Wie schnell bewegt sich Licht ungefähr? 🚀","How fast does light travel approximately?","À quelle vitesse la lumière se déplace-t-elle environ ?","Con quale velocità viaggia la luce circa?","300'000 km/s",["3'000 km/s","30'000 km/s","300'000 km/s","3'000'000 km/s"],"Licht ist das Schnellste im Universum.","c = 300'000 km/s."),
        fib("lo20","1","Ein ___ Material lässt kein Licht hindurch (z.B. Holz, Metall).","An ___ material lets no light through (e.g. wood, metal).","Un matériau ___ ne laisse pas passer la lumière (ex. bois, métal).","Un materiale ___ non lascia passare la luce (es. legno, metallo).","undurchsichtiges (opakes)","Holz = undurchsichtig.","Kein Licht hindurch = opak."),
        fib("lo21","1","Wenn Licht auf einen Spiegel trifft, wird es im gleichen ___ zurückgeworfen.","When light hits a mirror, it is reflected at the same ___.","Quand la lumière frappe un miroir, elle est réfléchie au même ___.","Quando la luce colpisce uno specchio, viene riflessa allo stesso ___.","Winkel","Einfallswinkel = Ausfallswinkel.","Reflexionsgesetz."),
        mc("lo22","2","Was ist Refraktion (Brechung) von Licht? 💧","What is light refraction?","Qu'est-ce que la réfraction de la lumière ?","Che cos'è la rifrazione della luce?","Licht ändert seine Richtung beim Übergang zwischen Medien",["Licht wird absorbiert","Licht ändert seine Richtung beim Übergang zwischen Medien","Licht prallt zurück","Licht wird dunkler"],"Strohhalm im Wasser sieht gebogen aus.","Luft → Wasser = Richtungsänderung."),
        fib("lo23","2","Ein Prisma zerlegt weisses Licht in seine ___. 🌈","A prism splits white light into its ___.","Un prisme décompose la lumière blanche en ses ___.","Un prisma scompone la luce bianca nei suoi ___.","Farben (Spektrum)","Newton entdeckte Licht-Zerlegung.","Prisma → Regenbogenspektrum."),
        mc("lo24","2","Welche Farben hat das sichtbare Spektrum? 🌈","What colours make up the visible spectrum?","Quelles couleurs composent le spectre visible ?","Quali colori compongono lo spettro visibile?","Rot, Orange, Gelb, Grün, Blau, Indigo, Violett",["Nur Rot, Grün, Blau","Rot, Orange, Gelb, Grün, Blau, Indigo, Violett","Nur Primärfarben","Nur Weiss und Schwarz"],"7 Farben = Regenbogen.","ROGGBIV."),
        fib("lo25","2","Rote Objekte ___ rotes Licht und absorbieren andere Farben.","Red objects ___ red light and absorb other colours.","Les objets rouges ___ la lumière rouge et absorbent les autres couleurs.","Gli oggetti rossi ___ la luce rossa e assorbono gli altri colori.","reflektieren","Farbe = welches Licht reflektiert wird.","Rot = nur rotes Licht zurückgeworfen."),
        mc("lo26","2","Was ist eine Linse? 🔍","What is a lens?","Qu'est-ce qu'une lentille ?","Che cos'è una lente?","Ein Glas-/Plastik-Objekt, das Licht bricht und bündelt oder zerstreut",["Ein Spiegel","Ein Glas-/Plastik-Objekt, das Licht bricht und bündelt oder zerstreut","Eine Lichtquelle","Ein Prisma"],"Brillengläser, Lupengläser = Linsen.","Konvex = sammelnd, Konkav = zerstreuend."),
        fib("lo27","2","Ein Regenbogen entsteht, wenn Sonnenlicht durch ___ gebrochen und reflektiert wird.","A rainbow forms when sunlight is refracted and reflected by ___.","Un arc-en-ciel se forme quand la lumière solaire est réfractée et réfléchie par ___.","Un arcobaleno si forma quando la luce solare viene rifratta e riflessa da ___.","Wassertröpfchen (Regen)","Brechung + Reflexion in Tropfen.","Prisma-Effekt in Regen."),
        mc("lo28","2","Was ist eine Sonnenfinsternis? 🌑","What is a solar eclipse?","Qu'est-ce qu'une éclipse solaire ?","Che cos'è un'eclissi solare?","Wenn der Mond zwischen Sonne und Erde steht und die Sonne verdeckt",["Wenn die Erde den Mond verdeckt","Wenn der Mond zwischen Sonne und Erde steht und die Sonne verdeckt","Wenn es bewölkt ist","Wenn es Nacht ist"],"Der Mond wirft Schatten auf die Erde.","Sonne-Mond-Erde."),
        fib("lo29","2","Eine Lupe (konvexe Linse) ___ Lichtstrahlen und vergrössert Objekte.","A magnifying glass (convex lens) ___ light rays and magnifies objects.","Une loupe (lentille convexe) ___ les rayons lumineux et agrandit les objets.","Una lente d'ingrandimento (convessa) ___ i raggi luminosi e ingrandisce gli oggetti.","bündelt/sammelt","Konvex = Sammellinse.","Brennpunkt einer Sammellinse."),
        mc("lo30","2","Was sind komplementäre Farben? 🎨","What are complementary colours?","Que sont les couleurs complémentaires ?","Cosa sono i colori complementari?","Farben, die sich gegenseitig ergänzen und zusammen Weiss/Grau ergeben",["Gleiche Farben","Farben, die sich gegenseitig ergänzen und zusammen Weiss/Grau ergeben","Nur Primärfarben","Nur Sekundärfarben"],"Rot + Grün + Blau = Weisses Licht (additiv).","Komplementär: Blau + Orange."),
        fib("lo31","2","Der Regenbogeneffekt durch Brechung des Lichts nennt man die Zerlegung in das ___.","The rainbow effect from bending light is called decomposition into the ___.","L'effet arc-en-ciel par réfraction de la lumière s'appelle la décomposition en ___.","L'effetto arcobaleno per rifrazione della luce si chiama scomposizione in ___.","Spektrum","Spektrum = alle Lichtfarben.","Prisma erzeugt Spektrum."),
        mc("lo32","2","Was ist Fluoreszenz? ✨","What is fluorescence?","Qu'est-ce que la fluorescence ?","Che cos'è la fluorescenza?","Wenn ein Material UV-Licht absorbiert und sichtbares Licht aussendet",["Wenn Licht reflektiert wird","Wenn ein Material UV-Licht absorbiert und sichtbares Licht aussendet","Wenn Licht durch ein Prisma geht","Wenn ein Objekt leuchtet"],"Textmarker und Waschmittel fluoreszieren.","UV → sichtbares Licht."),
        fib("lo33","2","Ein Teleskop nutzt Linsen oder Spiegel, um ___ Objekte zu vergrössern.","A telescope uses lenses or mirrors to magnify ___ objects.","Un télescope utilise des lentilles ou des miroirs pour agrandir des objets ___.","Un telescopio usa lenti o specchi per ingrandire oggetti ___.","weit entfernte","Sterne und Planeten = weit weg.","Galilei erfand das Teleskop."),
        mc("lo34","2","Was passiert, wenn Licht von einem Spiegel unter 45° trifft? 🪞","What happens when light hits a mirror at 45°?","Que se passe-t-il quand la lumière frappe un miroir à 45° ?","Cosa succede quando la luce colpisce uno specchio a 45°?","Es wird um 90° abgelenkt",["Es wird absorbiert","Es wird um 90° abgelenkt","Es geht hindurch","Es wird um 180° geworfen"],"Einfallswinkel = Ausfallswinkel.","45° in + 45° out = 90° Ablenkung."),
        fib("lo35","2","Licht breitet sich in geraden ___ aus. 💡","Light travels in straight ___.","La lumière se propage en ___ droites.","La luce si propaga in ___ diretti.","Linien / Strahlen","Licht geht geradeaus.","Schatten entstehen, weil Licht gerade ist."),
        mc("lo36","2","Was ist ein Hologramm? 🌐","What is a hologram?","Qu'est-ce qu'un hologramme ?","Che cos'è un ologramma?","Ein dreidimensionales Bild, erzeugt durch Laserinterferenz",["Ein normales Foto","Ein dreidimensionales Bild, erzeugt durch Laserinterferenz","Ein Schatten","Ein Regenbogen"],"Hologramme auf Kreditkarten.","Laser erzeugt 3D-Muster."),
        fib("lo37","3","Die Lichtgeschwindigkeit im Vakuum beträgt ca. ___ km/s.","The speed of light in vacuum is about ___ km/s.","La vitesse de la lumière dans le vide est d'environ ___ km/s.","La velocità della luce nel vuoto è circa ___ km/s.","300'000","c = 299'792 km/s (≈ 300'000).","Licht = schnellstes im Universum."),
        mc("lo38","3","Was ist der Doppler-Effekt bei Licht? 🌌","What is the Doppler effect for light?","Qu'est-ce que l'effet Doppler pour la lumière ?","Che cos'è l'effetto Doppler per la luce?","Sich entfernende Lichtquellen erscheinen rötlicher (Rotverschiebung)",["Licht wird schneller","Sich entfernende Lichtquellen erscheinen rötlicher (Rotverschiebung)","Licht ändert Farbe zufällig","Licht wird blauer bei Entfernung"],"Galaxien entfernen sich = Rotverschiebung.","Beweis für Universum-Expansion."),
        fib("lo39","3","Der Brechungsindex n beschreibt, wie stark Licht in einem Medium ___ wird.","The refractive index n describes how much light is ___ in a medium.","L'indice de réfraction n décrit combien la lumière est ___ dans un milieu.","L'indice di rifrazione n descrive quanto la luce viene ___ in un mezzo.","gebrochen / verlangsamt","n = c_Vakuum / c_Medium.","Glas: n ≈ 1,5."),
        mc("lo40","3","Was ist die Totalreflexion? 💡","What is total internal reflection?","Qu'est-ce que la réflexion totale interne ?","Che cos'è la riflessione totale interna?","Wenn Licht an einer Grenzfläche nicht mehr austreten kann (Winkel zu gross)",["Wenn Licht vollständig absorbiert wird","Wenn Licht an einer Grenzfläche nicht mehr austreten kann","Wenn Licht total reflektiert von einer Wand","Wenn ein Objekt transparent ist"],"Glasfaserkabel nutzen Totalreflexion.","Licht bleibt im Medium."),
        fib("lo41","3","Glasfaserkabel übertragen Daten als ___ durch Totalreflexion.","Fiber optic cables transmit data as ___ through total internal reflection.","Les câbles à fibre optique transmettent des données sous forme de ___ par réflexion totale.","I cavi in fibra ottica trasmettono dati come ___ attraverso riflessione totale.","Lichtimpulse","Licht = sehr schnell.","Glasfaser = Internet."),
        mc("lo42","3","Was ist Polarisation von Licht? 🔷","What is polarization of light?","Qu'est-ce que la polarisation de la lumière ?","Che cos'è la polarizzazione della luce?","Ausrichtung der Lichtschwingungen in eine bestimmte Richtung",["Brechung von Licht","Ausrichtung der Lichtschwingungen in eine bestimmte Richtung","Reflexion von Licht","Absorption von Licht"],"Polaroids-Brillen filtern polarisiertes Licht.","LCD-Bildschirme nutzen Polarisation."),
        fib("lo43","3","Das Beugungsgitter trennt Licht in Farben, weil Lichtwellen ___ miteinander treten.","A diffraction grating separates light into colours because light waves ___ each other.","Un réseau de diffraction sépare la lumière en couleurs car les ondes lumineuses ___ entre elles.","Un reticolo di diffrazione separa la luce in colori perché le onde luminose ___ tra loro.","interferieren","Interferenz = Wellenprinzip.","Konstruktiv und destruktiv."),
        mc("lo44","3","Was ist ein Laser? 💡","What is a laser?","Qu'est-ce qu'un laser ?","Che cos'è un laser?","Kohärentes, monochromatisches Licht in einem engen Strahl",["Normales helles Licht","Kohärentes, monochromatisches Licht in einem engen Strahl","Ein Spiegel","Ein Prisma"],"Laser = Light Amplification by Stimulated Emission.","Barcode-Scanner, CD-Player."),
        fib("lo45","3","Infrarot-Strahlung ist unsichtbar für unser Auge, aber wir nehmen sie als ___ wahr.","Infrared radiation is invisible to our eyes but we perceive it as ___.","Le rayonnement infrarouge est invisible mais nous le percevons comme ___.","La radiazione infrarossa è invisibile ma la percepiamo come ___.","Wärme","Infrarot = Wärmestrahlung.","Wärmebildkameras."),
        mc("lo46","3","Was ist der photoelektrische Effekt? ⚡","What is the photoelectric effect?","Qu'est-ce que l'effet photoélectrique ?","Che cos'è l'effetto fotoelettrico?","Licht schlägt Elektronen aus Metall heraus (erklärt durch Einstein 1905)",["Licht erwärmt Metall","Licht schlägt Elektronen aus Metall heraus (erklärt durch Einstein 1905)","Licht reflektiert von Metall","Licht bricht an Metall"],"Solarzellen nutzen den Photoeffekt.","Nobel 1921 für Einstein."),
        fib("lo47","3","Die Wellenlänge von sichtbarem Licht liegt zwischen ca. 380 nm (___ ) und 780 nm (___ ).","Visible light wavelengths range from ~380 nm (___ ) to 780 nm (___ ).","La longueur d'onde de la lumière visible va de ~380 nm (___ ) à 780 nm (___ ).","Le lunghezze d'onda della luce visibile vanno da ~380 nm (___ ) a 780 nm (___ ).","violett bis rot","Violett = kurze Wellenlänge.","Rot = längste sichtbare Wellenlänge."),
        mc("lo48","3","Was ist Beugung (Diffraktion) von Licht? 🌊","What is diffraction of light?","Qu'est-ce que la diffraction de la lumière ?","Che cos'è la diffrazione della luce?","Das Umbiegen von Licht um Hindernisse oder durch schmale Spalten",["Reflexion","Das Umbiegen von Licht um Hindernisse oder durch schmale Spalten","Brechung","Absorption"],"Beugung durch Schlitze erzeugt Muster.","Licht als Welle."),
        fib("lo49","3","UV-Strahlung (Ultraviolett) hat eine ___ Wellenlänge als sichtbares Licht.","UV (ultraviolet) radiation has a ___ wavelength than visible light.","Le rayonnement UV a une longueur d'onde ___ que la lumière visible.","La radiazione UV ha una lunghezza d'onda ___ della luce visibile.","kürzere","UV < violett (sichtbar).","Kurzwellig = hochenergetisch."),
        mc("lo50","3","Was unterscheidet kohärentes von inkohärentem Licht? 💡","What distinguishes coherent from incoherent light?","Qu'est-ce qui distingue la lumière cohérente de l'incohérente ?","Cosa distingue la luce coerente da quella incoerente?","Kohärent: gleiche Phase und Wellenlänge (Laser). Inkohärent: verschiedene Phasen (Glühbirne).",["Beide gleich","Kohärent: gleiche Phase und Wellenlänge (Laser). Inkohärent: verschiedene Phasen.","Kohärentes Licht ist heller","Inkohärentes Licht ist ein Laser"],"Laser = kohärent.","Glühbirne = inkohärent."),
    ]

# ─── LICHT-OPTIK GRADE 4 (lo11b–lo50b) ──────────────────────────────────────
def lo_g4():
    # Very similar to grade 3 but ids have 'b' suffix
    g3 = lo_g3()
    result = []
    for line in g3:
        # Replace the exercise ID
        import re
        line = re.sub(r'id: "lo(\d+)"', lambda m: f'id: "lo{m.group(1)}b"', line)
        result.append(line)
    return result

# ─── RAEUME-KARTE GRADE 3 (rk11–rk50) ────────────────────────────────────────
def rk_g3():
    return [
        mc("rk11","1","Was zeigt eine Karte? 🗺️","What does a map show?","Que montre une carte ?","Cosa mostra una cartina?","Eine verkleinerte Darstellung eines Gebietes",["Ein Foto","Eine verkleinerte Darstellung eines Gebietes","Ein Buch","Eine Liste"],"Karten verkleinern die Wirklichkeit.","Aus der Vogelperspektive."),
        fib("rk12","1","Ein Kompass zeigt immer in die Richtung ___. 🧭","A compass always points ___.","Une boussole pointe toujours vers ___.","Una bussola punta sempre verso ___.","Norden","Kompassnadel = magnetisch.","Erdmagnetfeld."),
        mc("rk13","1","Wie viele Himmelsrichtungen gibt es? 🧭","How many cardinal directions are there?","Combien y a-t-il de points cardinaux ?","Quanti punti cardinali esistono?","4 (Nord, Süd, Ost, West)",["2","3","4 (Nord, Süd, Ost, West)","6"],"NOSW = Norden, Osten, Süden, Westen.","Vier Himmelsrichtungen."),
        fib("rk14","1","Die Sonne geht im ___ auf und im Westen unter. ☀️","The sun rises in the ___ and sets in the west.","Le soleil se lève à l'___ et se couche à l'ouest.","Il sole sorge a ___ e tramonta a ovest.","Osten","Sonne = Osten → Süden → Westen.","Tagsüber zieht die Sonne von O nach W."),
        mc("rk15","1","Was ist die Hauptstadt der Schweiz? 🏛️","What is the capital of Switzerland?","Quelle est la capitale de la Suisse ?","Qual è la capitale della Svizzera?","Bern",["Zürich","Bern","Genf","Basel"],"Bundeshaus steht in Bern.","Nicht Zürich!"),
        fib("rk16","1","Die ___ sind das grösste Gebirge der Schweiz. 🏔️","The ___ are Switzerland's largest mountain range.","Les ___ sont la plus grande chaîne de montagnes en Suisse.","Le ___ sono la più grande catena montuosa della Svizzera.","Alpen","Matterhorn, Jungfrau = Alpen.","Sie teilen die Schweiz in Nord und Süd."),
        mc("rk17","1","Welcher Fluss fliesst durch Bern? 🌊","Which river flows through Bern?","Quel fleuve coule à travers Berne ?","Quale fiume scorre attraverso Berna?","Aare",["Rhein","Rhone","Aare","Limmat"],"Bern liegt an der Aare.","Aare fliesst ins Mittelland."),
        fib("rk18","1","Norden ist auf einer Karte meistens ___ (Seite der Karte).","On a map, north is usually ___ (side of map).","Sur une carte, le nord est généralement en ___.","Su una cartina, il nord è solitamente in ___.","oben","Oben = Norden ist Konvention.","Kompass oben = Norden."),
        mc("rk19","1","In wie viele Kantone ist die Schweiz aufgeteilt? 🇨🇭","Into how many cantons is Switzerland divided?","En combien de cantons la Suisse est-elle divisée ?","In quanti cantoni è divisa la Svizzera?","26",["20","23","26","30"],"26 Kantone in der Schweiz.","Uri, Schwyz, Bern usw."),
        fib("rk20","1","Auf einer Karte ist ein ___ ein Zeichen mit einer Erklärung, was jedes Symbol bedeutet.","On a map, a ___ explains what each symbol means.","Sur une carte, une ___ explique ce que signifie chaque symbole.","Su una cartina, una ___ spiega cosa significa ogni simbolo.","Legende","Legende = Zeichenerklärung.","Blau = Wasser, Grün = Wald."),
        fib("rk21","1","Die ___ beschreibt das Verhältnis zwischen Karten- und Wirklichkeits-Entfernung.","The ___ describes the ratio between map and real distance.","L'___ décrit le rapport entre la distance sur la carte et la réalité.","La ___ descrive il rapporto tra distanza sulla carta e nella realtà.","Massstab","1:100000 = 1 cm → 1 km.","Massstab = Verkleinerungsfaktor."),
        mc("rk22","2","Was bedeutet Massstab 1:50'000? 📏","What does scale 1:50,000 mean?","Que signifie l'échelle 1:50'000 ?","Cosa significa scala 1:50'000?","1 cm auf der Karte = 500 m in der Wirklichkeit",["1 m auf der Karte = 50 m in der Wirklichkeit","1 cm auf der Karte = 500 m in der Wirklichkeit","1 cm = 50'000 km","1:1 = echte Grösse"],"50'000 cm = 500 m = 0,5 km.","Karten verkleinern um Faktor 50'000."),
        fib("rk23","2","Höhenlinien auf einer Karte verbinden Punkte gleicher ___. 🏔️","Contour lines connect points of equal ___.","Les courbes de niveau connectent des points de ___ égale.","Le curve di livello collegano punti della stessa ___.","Höhe (Meter über Meer)","Dicht beieinander = steiles Gelände.","Höhenlinie = gleiche Höhe."),
        mc("rk24","2","Welche Sprachen werden in der Schweiz gesprochen? 🇨🇭","What languages are spoken in Switzerland?","Quelles langues parle-t-on en Suisse ?","Quali lingue si parlano in Svizzera?","Deutsch, Französisch, Italienisch und Rätoromanisch",["Nur Deutsch","Deutsch, Französisch, Italienisch und Rätoromanisch","Deutsch und Englisch","Deutsch, Französisch und Englisch"],"4 Nationalsprachen.","Schweizer Mehrsprachigkeit."),
        fib("rk25","2","Der ___ See ist der grösste Süsswassersee der Schweiz. 🌊","Lake ___ is Switzerland's largest freshwater lake.","Le lac ___ est le plus grand lac d'eau douce de Suisse.","Il lago ___ è il più grande lago d'acqua dolce della Svizzera.","Bodensee/Zürich (je nach Quelle Bodensee ist grösser)","Bodensee liegt an der Grenze.","Zürichsee ist rein schweizerisch."),
        mc("rk26","2","Was ist das Mittelland (Schweizer Plateau)? 🌾","What is the Swiss Plateau (Mittelland)?","Qu'est-ce que le Plateau suisse (Mittelland) ?","Che cos'è l'Altopiano svizzero (Mittelland)?","Die flachere Region zwischen Alpen und Jura",["Das Gebirge","Die flachere Region zwischen Alpen und Jura","Die Südseite der Alpen","Die Westschweiz"],"Mittelland = dicht besiedelt.","Bern, Zürich, Basel liegen dort."),
        fib("rk27","2","Der ___ ist der längste Fluss der Schweiz. 🌊","The ___ is the longest river in Switzerland.","La ___ est le plus long fleuve de Suisse.","La ___ è il fiume più lungo della Svizzera.","Aare","Aare fliesst durch Bern.","Von Gletschern bis zum Rhein."),
        mc("rk28","2","Was sind die fünf Nachbarländer der Schweiz? 🌍","What are Switzerland's five neighbouring countries?","Quels sont les cinq pays voisins de la Suisse ?","Quali sono i cinque paesi confinanti con la Svizzera?","Deutschland, Frankreich, Italien, Österreich, Liechtenstein",["Nur Deutschland und Frankreich","Deutschland, Frankreich, Italien, Österreich, Liechtenstein","Spanien, Portugal, Frankreich, Deutschland, Österreich","Deutschland, Frankreich, Belgien, Österreich, Liechtenstein"],"5 Nachbarländer: D, F, I, A, FL.","CH hat keine Meeresküste."),
        fib("rk29","2","Die drei Hauptregionen der Schweiz sind: Alpen, Mittelland und ___. 🏔️","Switzerland's three main regions are: Alps, Plateau and ___.","Les trois principales régions de la Suisse sont : Alpes, Plateau et ___.","Le tre regioni principali della Svizzera sono: Alpi, Altopiano e ___.","Jura","Jura = Gebirge im Nordwesten.","Drei Grossregionen."),
        mc("rk30","2","Was zeigt eine topografische Karte? 🗺️","What does a topographic map show?","Que montre une carte topographique ?","Cosa mostra una carta topografica?","Gelände, Höhen, Gewässer und Siedlungen",["Nur Strassen","Gelände, Höhen, Gewässer und Siedlungen","Nur Grenzen","Nur Städte"],"Höhenlinien = Topografie.","Topo = Gelände."),
        fib("rk31","2","Das ___ des Koordinatensystems beschreibt den Ost-West-Wert einer Position (Längengrad).","The ___ of the coordinate system describes the east-west value of a position (longitude).","Le ___ du système de coordonnées décrit la valeur est-ouest (longitude).","Il ___ del sistema di coordinate descrive il valore est-ovest (longitudine).","Längengrad (Longitude)","Längengrad = Ost-West.","Breitengrad = Nord-Süd."),
        mc("rk32","2","Was ist ein Massstabsbalken auf einer Karte? 📏","What is a scale bar on a map?","Qu'est-ce qu'une barre d'échelle sur une carte ?","Che cos'è una barra di scala su una cartina?","Ein grafisches Lineal, das zeigt, welche Strecke auf der Karte einer echten Entfernung entspricht",["Eine Legende","Ein grafisches Lineal, das zeigt, welche Strecke auf der Karte einer echten Entfernung entspricht","Eine Kompassrose","Ein Nordpfeil"],"Massstabsbalken = visueller Massstab.","Ohne Zahlen direkt lesbar."),
        fib("rk33","2","Auf einer Karte zeigt eine ___ die Himmelsrichtungen. 🧭","On a map, a ___ shows the cardinal directions.","Sur une carte, une ___ indique les points cardinaux.","Su una cartina, una ___ mostra i punti cardinali.","Kompassrose / Windrose","N, O, S, W auf der Karte.","Hilft beim Orientieren."),
        mc("rk34","2","Was ist ein Stadtplan? 🏙️","What is a city map?","Qu'est-ce qu'un plan de ville ?","Che cos'è una mappa urbana?","Eine detaillierte Karte einer Stadt mit Strassen und Gebäuden",["Eine Landkarte","Eine detaillierte Karte einer Stadt mit Strassen und Gebäuden","Eine topografische Karte","Eine Wetterkarte"],"Stadtplan = Strassen, Plätze, Gebäude.","Kleinmassstäbiger als Landeskarte."),
        fib("rk35","2","Der Massstab 1:25'000 bedeutet: 1 cm auf der Karte = ___ m in der Wirklichkeit.","Scale 1:25,000 means: 1 cm on the map = ___ m in reality.","L'échelle 1:25'000 signifie : 1 cm sur la carte = ___ m en réalité.","La scala 1:25'000 significa: 1 cm sulla carta = ___ m nella realtà.","250","25'000 cm = 250 m.","Massstab rechnen: Zahl ÷ 100."),
        mc("rk36","2","Was ist ein Satellitenbild? 🛰️","What is a satellite image?","Qu'est-ce qu'une image satellite ?","Che cos'è un'immagine satellitare?","Ein Foto der Erde aus dem Weltall (vom Satelliten)",["Ein Karten-Ausschnitt","Ein Foto der Erde aus dem Weltall (vom Satelliten)","Eine topografische Karte","Ein Stadtplan"],"Google Earth = Satellitenbilder.","Satelliten umkreisen die Erde."),
        fib("rk37","3","Der Nullmeridian (Längengrad 0°) verläuft durch ___, England.","The prime meridian (longitude 0°) runs through ___, England.","Le méridien zéro (longitude 0°) passe par ___, en Angleterre.","Il meridiano di Greenwich (longitudine 0°) passa per ___, Inghilterra.","Greenwich","Greenwich = Nullmeridian.","Ost und West werden davon gemessen."),
        mc("rk38","3","Was ist der Unterschied zwischen Breiten- und Längengraden? 🌍","What is the difference between latitude and longitude?","Quelle est la différence entre latitude et longitude ?","Qual è la differenza tra latitudine e longitudine?","Breitengrade = Nord/Süd; Längengrade = Ost/West",["Beide sind gleich","Breitengrade = Nord/Süd; Längengrade = Ost/West","Längengrade gehen von oben nach unten","Breitengrade sind vertikal"],"Äquator = 0° Breitengrad.","Greenwich = 0° Längengrad."),
        fib("rk39","3","Die Koordinaten der Schweiz liegen ungefähr zwischen ___ und 48° N Breite.","Switzerland's coordinates are roughly between ___ and 48° N latitude.","Les coordonnées de la Suisse se situent environ entre ___ et 48° N de latitude.","Le coordinate della Svizzera si trovano circa tra ___ e 48° N di latitudine.","45°","45° bis 48° N.","Mitteleuropa-Position."),
        mc("rk40","3","Was ist ein GIS (Geoinformationssystem)? 💻","What is a GIS (Geographic Information System)?","Qu'est-ce qu'un SIG (Système d'Information Géographique) ?","Che cos'è un GIS (Sistema Informativo Geografico)?","Ein digitales System zur Erfassung, Verarbeitung und Darstellung raumbezogener Daten",["Ein normales Computerprogramm","Ein digitales System zur Erfassung, Verarbeitung und Darstellung raumbezogener Daten","Eine App für Wetterdaten","Ein Satellit"],"GIS = digitale Kartographie.","Google Maps = einfaches GIS."),
        fib("rk41","3","Auf Karten werden gleichhohe Bereiche mit ___ dargestellt (braun = hoch, grün = tief).","On maps, areas of equal height are shown with ___ (brown = high, green = low).","Sur les cartes, les zones de même altitude sont représentées par ___.","Sulle carte, le zone della stessa altezza sono rappresentate da ___.","Höhenstufen / Farbschichtung","Farbige Höhenkarten.","Hypsometrie."),
        mc("rk42","3","Was ist Kartografie? 🗺️","What is cartography?","Qu'est-ce que la cartographie ?","Che cos'è la cartografia?","Die Wissenschaft und Kunst der Kartenherstellung",["Das Lesen von Karten","Die Wissenschaft und Kunst der Kartenherstellung","Das Navigieren","Das Fotografieren"],"Kartografen erstellen Karten.","Von Hand bis digital."),
        fib("rk43","3","Mercator-Projektion verzerrt Flächen in der Nähe der ___, macht sie grösser als sie sind.","Mercator projection distorts areas near the ___, making them larger than real.","La projection de Mercator déforme les surfaces près des ___, les rendant plus grandes.","La proiezione di Mercatore distorce le aree vicino ai ___, rendendole più grandi.","Pole","Grönland sieht riesig aus.","Projektion = Verzerrung."),
        mc("rk44","3","Was ist eine Projektion in der Kartografie? 🌍","What is a projection in cartography?","Qu'est-ce qu'une projection en cartographie ?","Che cos'è una proiezione in cartografia?","Eine Methode, die Erdkugel auf eine flache Karte zu übertragen",["Ein Foto der Erde","Eine Methode, die Erdkugel auf eine flache Karte zu übertragen","Eine Art Kompass","Eine Legende"],"Kugel → Flach = Projektion.","Verzerrung unvermeidbar."),
        fib("rk45","3","Google Maps und GPS nutzen das ___ als globales Koordinatensystem.","Google Maps and GPS use ___ as the global coordinate system.","Google Maps et GPS utilisent le ___ comme système de coordonnées mondial.","Google Maps e GPS usano il ___ come sistema di coordinate globale.","WGS 84 (World Geodetic System)","WGS 84 = globaler Standard.","GPS = WGS 84."),
        mc("rk46","3","Was ist eine Isoglosse? 🗺️","What is an isogloss?","Qu'est-ce qu'une isoglosse ?","Che cos'è un'isoglossa?","Eine Linie auf einer Karte, die Gebiete mit ähnlichen Sprachmerkmalen trennt",["Eine Höhenlinie","Eine Linie auf einer Karte, die Gebiete mit ähnlichen Sprachmerkmalen trennt","Eine Wetterlinie","Eine Stadtgrenze"],"Röstigraben = Isoglosse in der Schweiz.","Sprachgrenzen kartieren."),
        fib("rk47","3","Der ___ (Massstab) einer Karte sagt aus, wie weit ein cm auf der Karte in Wirklichkeit ist.","The ___ (scale) of a map says how far 1 cm on the map is in reality.","L'___ (échelle) d'une carte indique combien vaut 1 cm sur la carte en réalité.","Il ___ (scala) di una carta indica quanto lontano è 1 cm sulla carta nella realtà.","Massstab","Massstab = Verkleinerungsfaktor.","Klein = wenig Detailreichtum."),
        mc("rk48","3","Was ist eine Thematische Karte? 🗺️","What is a thematic map?","Qu'est-ce qu'une carte thématique ?","Che cos'è una carta tematica?","Eine Karte, die ein bestimmtes Thema darstellt (z.B. Bevölkerung, Klima, Wirtschaft)",["Eine topografische Karte","Eine Karte, die ein bestimmtes Thema darstellt","Eine Strassenkarte","Eine Landeskarte"],"Klimakarte, Bevölkerungskarte = thematisch.","Ein Thema im Fokus."),
        fib("rk49","3","Die Koordinaten des Rütli, dem Gründungsort der Schweiz, liegen im Kanton ___.","The coordinates of the Rütli, Switzerland's founding site, are in canton ___.","Les coordonnées du Rütli, lieu de fondation de la Suisse, se trouvent dans le canton ___.","Le coordinate del Rütli, luogo di fondazione della Svizzera, sono nel cantone ___.","Uri","Rütli am Vierwaldstättersee.","Uri = Gründungskanton 1291."),
        mc("rk50","3","Was ist der Unterschied zwischen einer Karte und einem Globus? 🌍","What is the difference between a map and a globe?","Quelle est la différence entre une carte et un globe ?","Qual è la differenza tra una carta e un globo?","Ein Globus ist ein dreidimensionales Modell; eine Karte ist eine flache Projektion",["Beide sind gleich","Ein Globus ist dreidimensional; eine Karte ist flach","Ein Globus zeigt nur Europa","Karten sind immer grösser"],"Globus = keine Verzerrung.","Karte = Verzerrung durch Projektion."),
    ]

# ─── RAEUME-KARTE GRADE 4 (rk11b–rk50b) ──────────────────────────────────────
def rk_g4():
    # Same topics but grade 4 — slightly more advanced
    import re
    g3 = rk_g3()
    result = []
    for line in g3:
        line = re.sub(r'id: "rk(\d+)"', lambda m: f'id: "rk{m.group(1)}b2"', line)
        result.append(line)
    return result

# ─── WELTALL GRADE 5 (wa11–wa50) ─────────────────────────────────────────────
def wa_g5():
    return [
        mc("wa11","1","Welcher Planet ist am nächsten zur Sonne? 🌞","Which planet is closest to the sun?","Quelle planète est la plus proche du soleil ?","Quale pianeta è più vicino al sole?","Merkur",["Venus","Erde","Merkur","Mars"],"Merkur = erster Planet.","Nächster zur Sonne."),
        fib("wa12","1","Die Erde umkreist die Sonne in ungefähr ___ Tagen (1 Jahr). 📅","Earth orbits the sun in about ___ days (1 year).","La Terre orbite autour du soleil en environ ___ jours (1 an).","La Terra orbita intorno al sole in circa ___ giorni (1 anno).","365","Ein Jahr = eine Erdumlaufbahn.","365 Tage pro Jahr."),
        mc("wa13","1","Was ist die Milchstrasse? 🌌","What is the Milky Way?","Qu'est-ce que la Voie lactée ?","Che cos'è la Via Lattea?","Unsere Heimatgalaxie",["Ein Planet","Ein Nebel","Unsere Heimatgalaxie","Ein Sternhaufen"],"Sie enthält unser Sonnensystem.","Sieht aus wie ein Band von Sternen."),
        fib("wa14","1","Der Planet mit den sichtbaren Ringen heisst ___. 🪐","The planet with visible rings is called ___.","La planète avec des anneaux visibles s'appelle ___.","Il pianeta con gli anelli visibili si chiama ___.","Saturn","Saturn hat Eisring-System.","6. Planet von der Sonne."),
        mc("wa15","1","Was ist ein Asteroid? ☄️","What is an asteroid?","Qu'est-ce qu'un astéroïde ?","Che cos'è un asteroide?","Ein kleiner Felskörper, der die Sonne umkreist",["Ein kleiner Planet","Ein kleiner Felskörper, der die Sonne umkreist","Ein Mond","Ein Stern"],"Asteroidengürtel zwischen Mars und Jupiter.","Kleine Felsbrocken im All."),
        fib("wa16","1","Jupiter ist der ___ Planet unseres Sonnensystems. 🪐","Jupiter is the ___ planet of our solar system.","Jupiter est la ___ planète de notre système solaire.","Giove è il ___ pianeta del nostro sistema solare.","grösste","Jupiter = grösster Planet.","Alle anderen Planeten passen rein."),
        mc("wa17","1","Was ist ein Meteor? ☄️","What is a meteor?","Qu'est-ce qu'un météore ?","Che cos'è un meteora?","Ein Himmelskörper, der in der Atmosphäre verglüht (Sternschnuppe)",["Ein Planet","Ein Himmelskörper, der in der Atmosphäre verglüht (Sternschnuppe)","Ein Komet","Ein Asteroid"],"Sternschnuppe = Meteor.","Verglüht in der Atmosphäre."),
        fib("wa18","1","Die Erde hat ___ Mond(e). 🌕","Earth has ___ moon(s).","La Terre a ___ lune(s).","La Terra ha ___ luna/e.","1","Unser Mond = der Mond.","Nur ein natürlicher Satellit."),
        mc("wa19","1","Was ist das Sonnensystem? ☀️","What is the solar system?","Qu'est-ce que le système solaire ?","Che cos'è il sistema solare?","Die Sonne und alle Himmelskörper, die sie umkreisen",["Nur die 8 Planeten","Die Sonne und alle Himmelskörper, die sie umkreisen","Nur die Sonne","Die Milchstrasse"],"Planeten, Monde, Kometen usw.","Sonne = Zentrum."),
        fib("wa20","1","Neptun ist der ___ Planet von der Sonne (fernste). 🔵","Neptune is the ___ planet from the sun (farthest).","Neptune est la ___ planète depuis le soleil (la plus éloignée).","Nettuno è il ___ pianeta dal sole (il più lontano).","achte / fernste","8 Planeten. Neptun = 8.","Kalt und weit weg."),
        fib("wa21","1","Die Sonne ist ein ___ aus heissem Gas. ☀️","The sun is a ___ of hot gas.","Le soleil est une ___ de gaz chaud.","Il sole è una ___ di gas caldo.","Stern","Sonne = Stern = leuchtendes Gas.","Wasserstoff → Helium."),
        mc("wa22","2","Was sind Mondphasen? 🌙","What are moon phases?","Que sont les phases de la lune ?","Cosa sono le fasi lunari?","Die verschiedenen Beleuchtungsaspekte des Mondes im Monatsverlauf",["Die Mondtemperatur","Die verschiedenen Beleuchtungsaspekte des Mondes im Monatsverlauf","Die Mondgrösse","Die Mondfarbe"],"Neumond → Vollmond → Neumond.","Mond dreht um Erde in ~29 Tagen."),
        fib("wa23","2","Ein Lichtjahr ist die Distanz, die Licht in ___ zurücklegt. 🚀","A light-year is the distance light travels in ___.","Une année-lumière est la distance parcourue par la lumière en ___.","Un anno luce è la distanza percorsa dalla luce in ___.","einem Jahr","Licht = 300'000 km/s.","In 1 Jahr: ~9,5 Billionen km."),
        mc("wa24","2","Was ist eine Galaxie? 🌌","What is a galaxy?","Qu'est-ce qu'une galaxie ?","Che cos'è una galassia?","Ein riesiges System aus Milliarden von Sternen, Gasen und Staub",["Ein grosser Planet","Ein Komet","Ein riesiges System aus Milliarden von Sternen, Gasen und Staub","Ein Asteroid"],"Milchstrasse = unsere Galaxie.","~200 Milliarden Sterne."),
        fib("wa25","2","Das Universum hat mit dem ___ begonnen (vor ca. 13,8 Milliarden Jahren).","The Universe began with the ___ (about 13.8 billion years ago).","L'Univers a commencé par le ___ (il y a environ 13,8 milliards d'années).","L'Universo è iniziato con il ___ (circa 13,8 miliardi di anni fa).","Urknall (Big Bang)","Big Bang = Urknall.","Universum begann als winziger Punkt."),
        mc("wa26","2","Wie lange braucht Licht von der Sonne bis zur Erde? ☀️","How long does sunlight take to reach Earth?","Combien de temps met la lumière du soleil pour atteindre la Terre ?","Quanto tempo impiega la luce del sole per raggiungere la Terra?","Ca. 8 Minuten",["1 Sekunde","1 Stunde","Ca. 8 Minuten","1 Tag"],"Sonne ist ca. 150 Mio km entfernt.","Licht = 300'000 km/s."),
        fib("wa27","2","Mars wird der ___ Planet genannt wegen seiner roten Oberfläche. 🔴","Mars is called the ___ planet because of its red surface.","Mars est appelé la planète ___ à cause de sa surface rouge.","Marte è chiamato il pianeta ___ per la sua superficie rossa.","rote","Eisenoxid = Rost → rot.","Der rote Planet."),
        mc("wa28","2","Was ist ein Komet? ☄️","What is a comet?","Qu'est-ce qu'une comète ?","Che cos'è una cometa?","Ein Himmelskörper aus Eis und Staub mit leuchtendem Schweif",["Ein kleiner Planet","Ein Mond","Ein Himmelskörper aus Eis und Staub mit leuchtendem Schweif","Ein Asteroid"],"Halley-Komet = bekannter Komet.","Schweif entsteht durch Sonnenwind."),
        fib("wa29","2","Venus ist der ___ Planet und der heisseste, obwohl Merkur näher an der Sonne ist.","Venus is the ___ planet and the hottest, even though Mercury is closer to the sun.","Vénus est la ___ planète et la plus chaude, bien que Mercure soit plus proche du soleil.","Venere è il ___ pianeta ed è il più caldo, anche se Mercurio è più vicino al sole.","zweite","Venus = Treibhauseffekt extremste.","Dichte Atmosphäre hält Wärme."),
        mc("wa30","2","Was ist ein Schwarzes Loch? 🌑","What is a black hole?","Qu'est-ce qu'un trou noir ?","Che cos'è un buco nero?","Ein extrem dichtes Objekt, aus dem nicht mal Licht entkommen kann",["Ein dunkler Planet","Ein extrem dichtes Objekt, aus dem nicht mal Licht entkommen kann","Ein Neutronenstern","Ein Asteroid"],"Schwarze Löcher haben extreme Schwerkraft.","Licht kann nicht entkommen."),
        fib("wa31","2","Der grösste Vulkan im Sonnensystem ist der Olympus Mons auf ___.","The largest volcano in the solar system is Olympus Mons on ___.","Le plus grand volcan du système solaire est Olympus Mons sur ___.","Il più grande vulcano del sistema solare è Olympus Mons su ___.","Mars","Mars hat grosse Vulkane.","Olympus Mons = 27 km hoch."),
        mc("wa32","2","Was unterscheidet innere von äusseren Planeten? 🪐","What distinguishes inner from outer planets?","Qu'est-ce qui distingue les planètes intérieures des extérieures ?","Cosa distingue i pianeti interni da quelli esterni?","Innere: felsig, klein; Äussere: meist Gasgiganten",["Innere sind grösser","Innere: felsig, klein; Äussere: meist Gasgiganten","Äussere sind warm","Innere haben mehr Monde"],"Asteroidengürtel trennt sie.","Merkur-Venus-Erde-Mars vs. Jupiter-Saturn-Uranus-Neptun."),
        fib("wa33","2","Saturn hat über ___ Monde, mehr als jeder andere Planet. 🪐","Saturn has over ___ moons, more than any other planet.","Saturne a plus de ___ lunes, plus que tout autre planète.","Saturno ha oltre ___ lune, più di qualsiasi altro pianeta.","80","Titan = grösster Saturnmond.","Saturn = Mondenrekord."),
        mc("wa34","2","Was ist ein Neutronenstern? ⭐","What is a neutron star?","Qu'est-ce qu'une étoile à neutrons ?","Che cos'è una stella di neutroni?","Der extrem dichte Überrest einer Supernovaexplosion",["Ein normaler Stern","Der extrem dichte Überrest einer Supernovaexplosion","Ein Planet","Ein schwarzes Loch"],"Neutronensterne sind sehr klein aber schwer.","Teelöffel = Millionen Tonnen."),
        fib("wa35","2","Uranus rotiert um seine Seite: seine ___ ist fast 98° geneigt.","Uranus rotates on its side: its ___ is tilted almost 98°.","Uranus tourne sur le côté : son ___ est incliné de presque 98°.","Urano ruota di lato: il suo ___ è inclinato di quasi 98°.","Rotationsachse","Uranus = liegt auf der Seite.","Kollision mit grossem Objekt?"),
        mc("wa36","2","Was ist Parallaxe in der Astronomie? 🔭","What is parallax in astronomy?","Qu'est-ce que la parallaxe en astronomie ?","Che cos'è la parallasse in astronomia?","Scheinbare Verschiebung eines Sterns durch die Erdposition",["Die Grösse eines Sterns","Scheinbare Verschiebung eines Sterns durch die Erdposition","Die Helligkeit eines Sterns","Die Entfernung zur Sonne"],"Nähere Sterne verschieben sich mehr.","Basis für Entfernungsmessung."),
        fib("wa37","3","Ein Lichtjahr in km: Lichtgeschwindigkeit × Sekunden pro Jahr ≈ ___ km.","A light-year in km: speed of light × seconds per year ≈ ___ km.","Une année-lumière en km : vitesse de la lumière × secondes par an ≈ ___ km.","Un anno luce in km: velocità della luce × secondi per anno ≈ ___ km.","9,46 Billionen (9,46 × 10¹²)","c × 31,5 Millionen Sekunden.","Sehr grosse Zahl."),
        mc("wa38","3","Was ist der Unterschied zwischen Meteoroid, Meteor und Meteorit? ☄️","What is the difference between meteoroid, meteor and meteorite?","Quelle est la différence entre météoroïde, météore et météorite ?","Qual è la differenza tra meteoroide, meteora e meteorite?","Meteoroid: im All. Meteor: beim Verglühen. Meteorit: landet auf Erde.",["Alle gleich","Meteoroid: im All. Meteor: beim Verglühen. Meteorit: landet auf Erde.","Nur Grösse unterscheidet sich","Meteor ist der grösste"],"Sternschnuppe = Meteor.","Einschlag = Meteorit."),
        fib("wa39","3","Die nächste Galaxie zur Milchstrasse ist die ___ Galaxie (ca. 2,5 Mio Lichtjahre).","The nearest galaxy to the Milky Way is the ___ Galaxy (~2.5 million light-years).","La galaxie la plus proche de la Voie lactée est la galaxie d'___ (~2,5 millions d'années-lumière).","La galassia più vicina alla Via Lattea è la galassia di ___ (~2,5 milioni di anni luce).","Andromeda","Andromeda = Schwestergalaxie.","Kollision in ~4 Mrd. Jahren."),
        mc("wa40","3","Was ist die Hauptreihe im Hertzsprung-Russell-Diagramm? ⭐","What is the main sequence in the HR diagram?","Qu'est-ce que la séquence principale dans le diagramme HR ?","Che cos'è la sequenza principale nel diagramma HR?","Die Gruppe normaler Sterne (wie die Sonne), die Wasserstoff zu Helium fusionieren",["Alle Sterne","Die Gruppe normaler Sterne, die H→He fusionieren","Nur Rote Riesen","Nur weisse Zwerge"],"HR-Diagramm: Helligkeit vs. Temperatur.","Unsere Sonne ist ein Hauptreihenstern."),
        fib("wa41","3","Ein Roter Riese entsteht, wenn ein Stern den ___ in seinem Kern aufgebraucht hat.","A red giant forms when a star exhausts ___ in its core.","Un géant rouge se forme quand une étoile a épuisé le ___ dans son noyau.","Un gigante rosso si forma quando una stella ha esaurito il ___ nel suo nucleo.","Wasserstoff","Kein H mehr → Stern dehnt sich aus.","Nächste Phase des Sonnentodes."),
        mc("wa42","3","Was ist eine Supernova? 💥","What is a supernova?","Qu'est-ce qu'une supernova ?","Che cos'è una supernova?","Die explosive Endphase eines massiven Sterns",["Ein Sternhaufen","Die explosive Endphase eines massiven Sterns","Eine Galaxienkollision","Ein Komet"],"Supernova heller als ganze Galaxien.","Resultiert in Neutronenstern oder Schwarzem Loch."),
        fib("wa43","3","Der Hubble-Teleskop misst Entfernungen mit der Methode der ___.","The Hubble telescope measures distances using ___.","Le télescope Hubble mesure les distances grâce aux ___.","Il telescopio Hubble misura le distanze usando le ___.","Cepheiden-Variablen (Standardkerzen)","Cepheiden = bekannte Leuchtkraft.","Entfernung durch Vergleich."),
        mc("wa44","3","Was ist Dunkle Materie? 🌑","What is dark matter?","Qu'est-ce que la matière noire ?","Che cos'è la materia oscura?","Nicht sichtbare Materie, die gravitationell wirkt (ca. 27% des Universums)",["Schwarze Löcher","Nicht sichtbare Materie, die gravitationell wirkt (~27% des Universums)","Dunkle Energie","Interstellarer Staub"],"Wir können sie nicht direkt sehen.","Hält Galaxien zusammen."),
        fib("wa45","3","Das kosmische Hintergrundstrahlung (CMB) ist das Nachglühen des ___.","The cosmic microwave background (CMB) is the afterglow of the ___.","Le fond diffus cosmologique (CMB) est l'écho du ___.","Il fondo cosmico a microonde (CMB) è il bagliore residuo del ___.","Urknalls (Big Bang)","CMB entdeckt 1965.","Gleichmässig im Universum."),
        mc("wa46","3","Was ist Dunkle Energie? 🌌","What is dark energy?","Qu'est-ce que l'énergie noire ?","Che cos'è l'energia oscura?","Eine hypothetische Energie, die die beschleunigte Expansion des Universums antreibt (~68%)",["Normale Energie","Eine hypothetische Energie, die die Expansion des Universums antreibt","Schwarze Löcher","Sterne"],"Universum expandiert beschleunigt.","Ursache unbekannt."),
        fib("wa47","3","Auf dem Mond gibt es keine ___, deshalb gibt es keinen Klang und keine Verwitterung.","On the moon there is no ___, so there is no sound and no weathering.","Sur la lune il n'y a pas d'___, donc pas de son ni d'érosion.","Sulla luna non c'è ___, quindi non ci sono suoni né erosione.","Atmosphäre","Atmosphäre hält Klang und schützt vor Meteoriten.","Mond = atmosphärenlos."),
        mc("wa48","3","Was ist das Fermi-Paradoxon? 🌌","What is the Fermi paradox?","Qu'est-ce que le paradoxe de Fermi ?","Che cos'è il paradosso di Fermi?","Die Frage: Warum haben wir noch keine Aliens gefunden, obwohl das Universum riesig ist?",["Die Suche nach Planeten","Die Frage: Warum haben wir noch keine Aliens gefunden?","Die Expansion des Universums","Das Hubble-Gesetz"],"Fermi: Wo sind alle?","Milliarden Sterne, wo sind die Zivilisationen?"),
        fib("wa49","3","Die Oortsche Wolke ist ein ___ aus Kometen am äusseren Rand des Sonnensystems.","The Oort Cloud is a ___ of comets at the outer edge of the solar system.","Le nuage d'Oort est un ___ de comètes à la limite extérieure du système solaire.","La nube di Oort è un ___ di comete al bordo esterno del sistema solare.","Reservoir","Langperiodische Kometen kommen von dort.","Oort-Wolke = Kometenspeicher."),
        mc("wa50","3","Was ist Hubbles Gesetz? 🌌","What is Hubble's law?","Qu'est-ce que la loi de Hubble ?","Che cos'è la legge di Hubble?","Galaxien entfernen sich umso schneller, je weiter sie von uns sind",["Sterne werden heller mit Entfernung","Galaxien entfernen sich umso schneller, je weiter sie von uns sind","Alle Galaxien stehen still","Das Universum schrumpft"],"Hubbles Gesetz beweist Universum-Expansion.","v = H₀ × d."),
    ]

# ─── WELTALL GRADE 6 (wa11b–wa50b) ───────────────────────────────────────────
def wa_g6():
    import re
    g5 = wa_g5()
    result = []
    for line in g5:
        line = re.sub(r'id: "wa(\d+)"', lambda m: f'id: "wa{m.group(1)}b"', line)
        result.append(line)
    return result

# ─── GESCHICHTE-ZEIT GRADE 5 (gz11–gz50) ─────────────────────────────────────
def gz_g5():
    return [
        mc("gz11","1","Was ist ein Jahrzehnt? 📅","What is a decade?","Qu'est-ce qu'une décennie ?","Che cos'è un decennio?","10 Jahre",["1 Jahr","10 Jahre","100 Jahre","1000 Jahre"],"Zehn Jahre.","Dekade = 10."),
        fib("gz12","1","Das 21. Jahrhundert beg