#!/usr/bin/env python3
"""
Expands 22 topic instances from 10 → 50 exercises each.
Injects 40 new exercises per topic into the CORRECT files.
Also removes orphaned topic blocks from grade4/5/6 science.ts.
Difficulty spread target: 15 easy(1) + 20 medium(2) + 15 hard(3).
Existing 10: varies, so we add to reach totals.
"""

import re, os, sys

BASE = os.path.expanduser("~/projects/cleverli/src/data")

# ─── HELPERS ─────────────────────────────────────────────────────────────────

def q(s):
    return s.replace('"', '\\"')

def mc(id, diff, de, en, fr, it, ans, opts, h1, h2):
    o = '", "'.join(opts)
    return f'      {{ id: "{q(id)}", type: "multiple-choice", difficulty: {diff}, question: "{q(de)}", questionEN: "{q(en)}", questionFR: "{q(fr)}", questionIT: "{q(it)}", answer: "{q(ans)}", options: ["{o}"], hints: ["{q(h1)}", "{q(h2)}"] }},'

def fib(id, diff, de, en, fr, it, ans, h1, h2):
    return f'      {{ id: "{q(id)}", type: "fill-in-blank", difficulty: {diff}, question: "{q(de)}", questionEN: "{q(en)}", questionFR: "{q(fr)}", questionIT: "{q(it)}", answer: "{q(ans)}", hints: ["{q(h1)}", "{q(h2)}"] }},'

def dd(id, diff, de, en, fr, it, items, zones, answers, h1, h2):
    items_s = ", ".join(f'{{id:"{i}",label:"{q(l)}"}}' for i,l in items)
    zones_s = ", ".join(f'{{id:"{i}",label:"{q(l)}"}}' for i,l in zones)
    ans_s = ", ".join(f'"{k}":"{v}"' for k,v in answers.items())
    return f'      {{ id: "{q(id)}", type: "drag-drop", difficulty: {diff}, question: "{q(de)}", questionEN: "{q(en)}", questionFR: "{q(fr)}", questionIT: "{q(it)}", answer: "all", hints: ["{q(h1)}", "{q(h2)}"], dragItems: [{items_s}], dropZones: [{zones_s}], dropAnswers: {{{ans_s}}} }},'

def mt(id, diff, de, en, fr, it, pairs, h1, h2):
    pairs_s = ", ".join(f'{{id:"{pi}",label:"{q(pl)}",emoji:"{pe}"}}' for pi,pl,pe in pairs)
    return f'      {{ id: "{q(id)}", type: "matching", difficulty: {diff}, question: "{q(de)}", questionEN: "{q(en)}", questionFR: "{q(fr)}", questionIT: "{q(it)}", answer: "all", hints: ["{q(h1)}", "{q(h2)}"], pairs: [{pairs_s}] }},'

def mem(id, diff, de, en, fr, it, pairs, h1, h2):
    pairs_s = ", ".join(f'{{id:"{pi}",label:"{q(pl)}",emoji:"{pe}"}}' for pi,pl,pe in pairs)
    return f'      {{ id: "{q(id)}", type: "memory", difficulty: {diff}, question: "{q(de)}", questionEN: "{q(en)}", questionFR: "{q(fr)}", questionIT: "{q(it)}", answer: "all", hints: ["{q(h1)}", "{q(h2)}"], pairs: [{pairs_s}] }},'


# ─── INJECT FUNCTION ─────────────────────────────────────────────────────────

def inject_into_topic(filepath, topic_id, new_ts_lines):
    with open(filepath, encoding='utf-8') as f:
        content = f.read()
    
    pat = f'id: "{topic_id}"'
    pos = content.find(pat)
    if pos == -1:
        print(f"  ✗ Topic '{topic_id}' not found in {filepath}")
        return False
    
    exs_marker = 'exercises: ['
    exs_pos = content.find(exs_marker, pos)
    if exs_pos == -1:
        print(f"  ✗ exercises array not found for '{topic_id}'")
        return False
    
    depth = 0
    i = exs_pos + len(exs_marker)
    while i < len(content):
        c = content[i]
        if c == '[':
            depth += 1
        elif c == ']':
            if depth == 0:
                insert = '\n' + '\n'.join(new_ts_lines) + '\n'
                content = content[:i] + insert + content[i:]
                with open(filepath, 'w', encoding='utf-8') as f:
                    f.write(content)
                print(f"  ✓ {topic_id} in {os.path.basename(filepath)}: +{len(new_ts_lines)} exercises")
                return True
            depth -= 1
        i += 1
    print(f"  ✗ Could not find closing bracket for '{topic_id}'")
    return False

def remove_topic(filepath, topic_id):
    with open(filepath, encoding='utf-8') as f:
        content = f.read()
    
    pat = f'    id: "{topic_id}",'
    pos = content.find(pat)
    if pos == -1:
        print(f"  – '{topic_id}' not found in {os.path.basename(filepath)} (already removed?)")
        return True
    
    block_start = content.rfind('  {', 0, pos)
    if block_start == -1:
        print(f"  ✗ Cannot find block start for '{topic_id}'")
        return False
    
    depth = 0
    i = block_start
    while i < len(content):
        c = content[i]
        if c == '{':
            depth += 1
        elif c == '}':
            depth -= 1
            if depth == 0:
                end = i + 1
                if end < len(content) and content[end] == ',':
                    end += 1
                if end < len(content) and content[end] == '\n':
                    end += 1
                content = content[:block_start] + content[end:]
                with open(filepath, 'w', encoding='utf-8') as f:
                    f.write(content)
                print(f"  ✓ Removed '{topic_id}' from {os.path.basename(filepath)}")
                return True
        i += 1
    print(f"  ✗ Cannot find end of block for '{topic_id}'")
    return False

# ═══════════════════════════════════════════════════════════════════════════════
# EXERCISE GENERATION FUNCTIONS
# Each returns a list of TypeScript exercise lines (40 per topic)
# Existing exercises have difficulties already; we spread to reach 15/20/15 total
# Existing 10: roughly 4d1 + 4d2 + 2d3, so we add ~11d1 + 16d2 + 13d3
# ═══════════════════════════════════════════════════════════════════════════════

# ─── PHYSIK-BEWEGUNG GRADE 1 ─────────────────────────────────────────────────
def ph_g1():
    return [
        # d1 (×11)
        mc("ph11","1","Was passiert, wenn du auf einen Ball trittst? ⚽","What happens when you kick a ball?","Que se passe-t-il quand tu donnes un coup de pied dans une balle ?","Cosa succede quando calci un pallone?","Er bewegt sich weg",["Er fängt an zu leuchten","Er bewegt sich weg","Er wird grösser","Er bleibt stehen"],"Kraft bringt Dinge in Bewegung.","Dein Fuss überträgt eine Kraft."),
        fib("ph12","1","Wenn du einen Stein loslässt, fällt er nach ___.","When you release a stone, it falls ___.","Quand tu lâches une pierre, elle tombe vers ___.","Quando lasci andare un sasso, cade ___.","unten","Die Erde zieht alles an.","Schwerkraft wirkt nach unten."),
        mc("ph13","1","Was braucht ein Objekt, um sich zu bewegen? 💪","What does an object need to move?","De quoi a besoin un objet pour se déplacer ?","Di cosa ha bisogno un oggetto per muoversi?","Eine Kraft",["Farbe","Eine Kraft","Wasser","Luft"],"Drücken oder Ziehen sind Kräfte.","Ohne Kraft bleibt alles ruhig."),
        fib("ph14","1","Ein Magnet hat zwei Pole: Nord und ___. 🧲","A magnet has two poles: North and ___.","Un aimant a deux pôles : Nord et ___.","Un magnete ha due poli: Nord e ___.","Süd","Denke an Kompass-Richtungen.","N und S sind die zwei Pole."),
        mc("ph15","1","Was zieht ein Magnet an? 🧲","What does a magnet attract?","Qu'est-ce qu'un aimant attire ?","Cosa attrae un magnete?","Eisen",["Holz","Plastik","Eisen","Glas"],"Magnete haften am Kühlschrank.","Eisen und Stahl werden angezogen."),
        fib("ph16","1","Wasser fliesst immer nach ___.","Water always flows ___.","L'eau coule toujours vers ___.","L'acqua scorre sempre verso ___.","unten","Schwerkraft zieht Wasser.","Flüsse fliessen bergab."),
        mc("ph17","1","Was beschreibt das Wort Kraft? 💪","What does the word force describe?","Que décrit le mot force ?","Cosa descrive la parola forza?","Ein Drücken oder Ziehen",["Eine Farbe","Ein Drücken oder Ziehen","Ein Tier","Eine Zahl"],"Drücken und Ziehen sind Kräfte.","Kräfte verändern Bewegung."),
        mc("ph18","1","Was macht Reibung? 🛞","What does friction do?","Que fait le frottement ?","Cosa fa l'attrito?","Sie verlangsamt Bewegung",["Sie beschleunigt immer","Sie verlangsamt Bewegung","Sie leuchtet","Sie erwärmt nichts"],"Reibung entsteht an Oberflächen.","Schuhsohlen bremsen dank Reibung."),
        fib("ph19","1","Eine Wippe funktioniert wie ein ___.","A seesaw works like a ___.","Une balançoire fonctionne comme un ___.","Un'altalena funziona come una ___.","Hebel","Drehpunkt in der Mitte.","Hebel verstärken Kräfte."),
        mc("ph20","1","Was ist Auftrieb? 🚢","What is buoyancy?","Qu'est-ce que la poussée d'Archimède ?","Che cos'è la spinta di Archimede?","Die Kraft, die Objekte im Wasser nach oben drückt",["Die Kraft nach unten","Die Kraft, die Objekte im Wasser nach oben drückt","Schwerkraft","Magnetismus"],"Schiffe schwimmen dank Auftrieb.","Wasser drückt nach oben."),
        fib("ph21","1","Ein Hammer schlägt einen Nagel in die Wand, weil er eine ___ auf ihn überträgt.","A hammer drives a nail because it transfers a ___ to it.","Un marteau enfonce un clou parce qu'il lui transfère une ___.","Un martello conficca un chiodo perché trasferisce una ___ su di esso.","Kraft","Was überträgt der Hammer?","Druckkraft von oben."),
        # d2 (×16)
        mc("ph22","2","Was ist Schwerkraft? 🌍","What is gravity?","Qu'est-ce que la gravité ?","Che cos'è la gravità?","Eine Kraft, die alles nach unten zieht",["Eine Farbe","Ein Tier","Eine Kraft, die alles nach unten zieht","Eine Zahl"],"Alles fällt zur Erde.","Die Erde zieht an."),
        fib("ph23","2","Wenn ein Objekt dichter als Wasser ist, ___ es.","If an object is denser than water, it ___.","Si un objet est plus dense que l'eau, il ___.","Se un oggetto è più denso dell'acqua, ___.","sinkt","Stein ist dichter als Wasser.","Holz schwimmt, Stein sinkt."),
        mc("ph24","2","Was passiert, wenn zwei gleiche Magnetpole zusammenkommen? 🧲","What happens when two identical poles meet?","Que se passe-t-il quand deux pôles identiques se rencontrent ?","Cosa succede quando due poli identici si incontrano?","Sie stossen sich ab",["Sie ziehen sich an","Sie stossen sich ab","Nichts passiert","Sie verschmelzen"],"Gleich und gleich stösst sich ab.","Nord+Nord = abstossen."),
        fib("ph25","2","Ein Rad hat wenig Reibung, weil es sich ___. 🚲","A wheel has little friction because it ___.","Une roue a peu de frottement parce qu'elle ___.","Una ruota ha poca attrito perché ___.","dreht","Rollen statt Gleiten = weniger Reibung.","Fahrräder sind leicht dank Rädern."),
        mc("ph26","2","Was ist Gewichtskraft? ⚖️","What is weight force?","Qu'est-ce que la force de pesanteur ?","Che cos'è la forza peso?","Die Kraft, mit der die Erde ein Objekt anzieht",["Die Stärke eines Muskels","Die Kraft, mit der die Erde ein Objekt anzieht","Magnetkraft","Windkraft"],"Ein Gewicht drückt auf eine Waage.","Schwer = grosse Gewichtskraft."),
        fib("ph27","2","Holz ___ auf Wasser, weil es leichter als Wasser ist.","Wood ___ on water because it is lighter.","Le bois ___ sur l'eau car il est plus léger.","Il legno ___ sull'acqua perché è più leggero.","schwimmt","Dichte unter 1 g/cm3 = schwimmen.","Holz weniger dicht als Wasser."),
        mc("ph28","2","Warum fällt ein Ball schneller als eine Feder? 🪶","Why does a ball fall faster than a feather?","Pourquoi une balle tombe-t-elle plus vite qu'une plume ?","Perché una palla cade più veloce di una piuma?","Wegen der Luftreibung (die Feder hat mehr Widerstand)",["Wegen des Gewichts allein","Wegen der Luftreibung (die Feder hat mehr Widerstand)","Weil der Ball schwerer ist","Zufall"],"Luftwiderstand bremst leichte Objekte.","Im Vakuum fallen beide gleich schnell."),
        fib("ph29","2","Das Gegenteil von Ruhe ist ___.","The opposite of rest is ___.","Le contraire du repos est ___.","Il contrario di riposo è ___.","Bewegung","Was macht ein laufendes Kind?","Ruhe → Bewegung."),
        mc("ph30","2","Was ist Gleichgewicht auf einer Wippe? ⚖️","What is balance on a seesaw?","Qu'est-ce que l'équilibre sur une balançoire ?","Che cos'è l'equilibrio su un'altalena?","Wenn beide Seiten gleich schwer sind",["Wenn eine Seite schwerer ist","Wenn beide Seiten gleich schwer sind","Wenn die Wippe sich dreht","Wenn niemand sitzt"],"Gleiche Gewichte auf beiden Seiten.","Balance = beide Seiten gleich."),
        fib("ph31","2","Wenn du einen Magneten in zwei Teile schneidest, hat jeder Teil ___ Pole.","If you cut a magnet in half, each part has ___ poles.","Si tu coupes un aimant en deux, chaque partie a ___ pôles.","Se tagli un magnete a metà, ogni parte ha ___ poli.","zwei (Nord und Süd)","Jedes Stück hat immer N und S.","Magnete haben immer beide Pole."),
        mc("ph32","2","Wozu dient ein Sicherheitsgurt im Auto? 🚗","Why do cars have seatbelts?","Pourquoi les voitures ont-elles des ceintures de sécurité ?","Perché le auto hanno le cinture di sicurezza?","Er hält dich bei starker Verzögerung fest",["Er macht das Auto schneller","Er hält dich bei starker Verzögerung fest","Er spart Benzin","Er ist nur Dekoration"],"Bei Bremsung wirkt eine grosse Kraft.","Der Gurt schützt bei Unfall."),
        fib("ph33","2","Luft bremst schnell bewegte Objekte. Diesen Widerstand nennt man ___.","Air slows fast-moving objects. This resistance is called ___.","L'air freine les objets rapides. Cette résistance s'appelle ___.","L'aria frena gli oggetti veloci. Questa resistenza si chiama ___.","Luftwiderstand","Was bremst ein Fallschirm?","Luft setzt Bewegung Widerstand entgegen."),
        mc("ph34","2","Was ist eine schiefe Ebene? 📐","What is an inclined plane?","Qu'est-ce qu'un plan incliné ?","Che cos'è un piano inclinato?","Eine geneigte Fläche, die das Heben erleichtert",["Ein Spiegel","Eine geneigte Fläche, die das Heben erleichtert","Eine Brücke","Ein Rad"],"Rampen und Rutschbahnen sind Beispiele.","Weniger Kraft, aber mehr Weg."),
        fib("ph35","2","Ein langer Hebel braucht ___ Kraft als ein kurzer. ⚖️","A long lever needs ___ force than a short one.","Un bras de levier long nécessite ___ de force qu'un court.","Una leva lunga richiede ___ forza di una corta.","weniger","Längerer Arm = weniger Kraft nötig.","Mechanischer Vorteil des Hebels."),
        mc("ph36","2","Was ist Reibung in einfachen Worten? 🛞","What is friction in simple words?","Qu'est-ce que le frottement en termes simples ?","Che cos'è l'attrito in parole semplici?","Eine Kraft, die Bewegung zwischen Oberflächen verlangsamt",["Etwas, das Dinge beschleunigt","Eine Kraft, die Bewegung zwischen Oberflächen verlangsamt","Ein Tier","Eine Farbe"],"Reibung = Widerstand zwischen zwei Flächen.","Ohne Reibung würde man auf Böden rutschen."),
        fib("ph36b","2","Holz ist ___ als Wasser, deshalb schwimmt es.","Wood is ___ than water, so it floats.","Le bois est ___ que l'eau, donc il flotte.","Il legno è ___ dell'acqua, quindi galleggia.","leichter","Dichte Holz < Dichte Wasser.","Leichter = schwimmen."),
        # d3 (×13)
        fib("ph37","3","Das Gesetz der Trägheit: Ein Objekt hält seinen Bewegungszustand, wenn keine ___ auf es wirkt.","Inertia law: An object keeps its motion if no ___ acts on it.","Loi de l'inertie : sans ___ externe, un objet garde son état de mouvement.","Legge di inerzia: un oggetto mantiene il moto se nessuna ___ agisce su di esso.","Kraft","Was hält einen rollenden Ball an?","Ohne Kraft keine Änderung der Bewegung."),
        mc("ph38","3","Was bedeutet Kraft = Masse × Beschleunigung? ⚗️","What does Force = Mass × Acceleration mean?","Que signifie Force = Masse × Accélération ?","Cosa significa Forza = Massa × Accelerazione?","Grössere Masse braucht mehr Kraft für gleiche Beschleunigung",["Kraft und Masse sind gleich","Leichte Objekte fallen schneller","Grössere Masse braucht mehr Kraft für gleiche Beschleunigung","Kraft ohne Masse ist grösser"],"Schwerer LKW braucht mehr Kraft als ein Fahrrad.","Newtons 2. Gesetz."),
        fib("ph39","3","Die Einheit der Kraft ist der ___, benannt nach einem englischen Wissenschaftler.","The unit of force is the ___, named after an English scientist.","L'unité de force est le ___, d'après un scientifique anglais.","L'unità di forza è il ___, dal nome di uno scienziato inglese.","Newton (N)","Isaac Newton entdeckte die Schwerkraft.","Kraft wird in N gemessen."),
        mc("ph40","3","Was passiert mit der Schwerkraft, je weiter man von der Erde entfernt ist? 🌍","What happens to gravity farther from Earth?","Qu'arrive-t-il à la gravité en s'éloignant de la Terre ?","Cosa succede alla gravità lontano dalla Terra?","Sie wird schwächer",["Sie bleibt gleich","Sie wird stärker","Sie verschwindet sofort","Sie kehrt sich um"],"Im Weltall wiegt man weniger.","Schwerkraft nimmt mit Abstand ab."),
        mc("ph41","3","Was beschreibt Actio = Reactio? ⚙️","What describes Action = Reaction?","Que décrit Action = Réaction ?","Cosa descrive Actio = Reactio?","Jede Kraft hat eine gleich grosse Gegenkraft",["Kräfte sind immer unterschiedlich","Jede Kraft hat eine gleich grosse Gegenkraft","Reaktion ist grösser","Es gibt keine Gegenkraft"],"Wenn du gegen eine Wand drückst, drückt sie zurück.","Actio = Reactio: Newtons 3. Gesetz."),
        mc("ph42","3","Was ist kinetische Energie? 🏃","What is kinetic energy?","Qu'est-ce que l'énergie cinétique ?","Che cos'è l'energia cinetica?","Energie eines bewegten Objekts",["Energie eines ruhenden Objekts","Energie eines bewegten Objekts","Magnetische Energie","Lichtenergie"],"Ein rollender Ball hat kinetische Energie.","Kinetisch = in Bewegung."),
        fib("ph43","3","Wenn ein Apfel vom Baum fällt, wird seine Lageenergie zu ___energie. 🍎","When an apple falls, its potential energy becomes ___ energy.","Quand une pomme tombe, son énergie potentielle devient énergie de ___.","Quando una mela cade, l'energia potenziale diventa energia di ___.","Bewegungs-","Lageenergie → Kinetische Energie.","Was macht ein fallender Apfel?"),
        mc("ph44","3","Warum sinkt ein Stück Eisen, aber schwimmt ein Schiff? 🚢","Why does iron sink but a ship floats?","Pourquoi le fer coule mais un navire flotte ?","Perché il ferro affonda ma una nave galleggia?","Das Schiff ist hohl, also hat es eine geringere Dichte als Wasser",["Schiffe sind aus Holz","Das Schiff ist hohl, also hat es eine geringere Dichte als Wasser","Eisen ist magnetisch","Schiffe haben Motoren"],"Ein hohles Objekt verdrängt mehr Wasser.","Auftrieb = Gewicht des verdrängten Wassers."),
        fib("ph45","3","Das Prinzip des Archimedes: Auftrieb = ___ des verdrängten Wassers.","Archimedes' principle: Buoyancy = ___ of displaced water.","Principe d'Archimède : Poussée = ___ de l'eau déplacée.","Principio di Archimede: Spinta = ___ dell'acqua spostata.","Gewicht","Auftrieb = Gewicht des verdrängten Wassers.","Archimedes in der Badewanne."),
        mc("ph46","3","Was ist mechanischer Vorteil eines Hebels? ⚙️","What is the mechanical advantage of a lever?","Quel est l'avantage mécanique d'un levier ?","Qual è il vantaggio meccanico di una leva?","Mit weniger Kraft die gleiche Arbeit verrichten",["Schneller arbeiten","Mit weniger Kraft die gleiche Arbeit verrichten","Mehr Energie erzeugen","Keine Kraft brauchen"],"Langer Arm = mehr Vorteil.","Hebel = Kraftverstärker."),
        fib("ph47","3","Energie kann nicht erzeugt oder vernichtet, nur ___ werden.","Energy cannot be created or destroyed, only ___.","L'énergie ne peut pas être créée ou détruite, seulement ___.","L'energia non può essere creata né distrutta, solo ___.","umgewandelt","Energieerhaltungssatz.","Physikalisches Grundgesetz."),
        mc("ph48","3","Was ist der Unterschied zwischen Masse und Gewicht? ⚖️","What is the difference between mass and weight?","Quelle est la différence entre masse et poids ?","Qual è la differenza tra massa e peso?","Masse ist überall gleich; Gewicht hängt von der Schwerkraft ab",["Beide sind identisch","Masse ist überall gleich; Gewicht hängt von der Schwerkraft ab","Gewicht ist immer grösser","Masse ist auf dem Mond grösser"],"Auf dem Mond wiegt man weniger, aber die Masse bleibt gleich.","Masse in kg, Gewicht in Newton."),
        fib("ph49","3","Ein Pendel schwingt dank ___ und Trägheit hin und her.","A pendulum swings due to ___ and inertia.","Un pendule oscille grâce à ___ et à l'inertie.","Un pendolo oscilla grazie a ___ e all'inerzia.","Schwerkraft","Uhren nutzen Pendel.","Schwerkraft zieht das Pendel zurück."),
        mc("ph50","3","Was ist Drehmoment? 🔧","What is torque?","Qu'est-ce que le couple ?","Che cos'è il momento torcente?","Kraft × Abstand vom Drehpunkt",["Kraft + Gewicht","Kraft × Abstand vom Drehpunkt","Masse × Beschleunigung","Energie × Zeit"],"Langer Schraubenschlüssel = mehr Drehmoment.","Drehmoment = Hebelwirkung."),
    ]

# ─── PHYSIK-BEWEGUNG GRADE 2 ─────────────────────────────────────────────────
def ph_g2():
    return [
        mc("ph11b","1","Was ist Reibungskraft? 🛞","What is friction force?","Qu'est-ce que la force de frottement ?","Che cos'è la forza d'attrito?","Eine Kraft, die Bewegung verlangsamt",["Eine Kraft, die beschleunigt","Eine Kraft, die Bewegung verlangsamt","Magnetismus","Schwerkraft"],"Reibung entsteht an Oberflächen.","Sie erzeugt auch Wärme."),
        fib("ph12b","1","Die Schwerkraft zieht alle Objekte nach ___.","Gravity pulls all objects ___.","La gravité attire tous les objets vers ___.","La gravità attira tutti gli oggetti verso ___.","unten","Alles fällt, wenn man loslässt.","Die Erde zieht an."),
        mc("ph13b","1","Drücken und Ziehen sind beides ___. 💪","Pushing and pulling are both ___.","Pousser et tirer sont tous les deux des ___.","Spingere e tirare sono entrambi delle ___.","Kräfte",["Farben","Kräfte","Tiere","Zahlen"],"Was überträgt man auf ein Objekt?","Kräfte bringen Dinge in Bewegung."),
        fib("ph14b","1","Ein Schiff schwimmt, weil der ___ gleich gross ist wie die Schwerkraft. 🚢","A ship floats because the ___ equals the gravitational force.","Un bateau flotte parce que la ___ est égale à la gravité.","Una nave galleggia perché la ___ è uguale alla forza gravitazionale.","Auftrieb","Kräftegleichgewicht.","Auftrieb = Gewicht des verdrängten Wassers."),
        mc("ph15b","1","Was erzeugt ein Hebel? ⚖️","What does a lever produce?","Que produit un levier ?","Cosa produce una leva?","Eine mechanische Kraft-Verstärkung",["Elektrischen Strom","Eine mechanische Kraft-Verstärkung","Wärme","Licht"],"Wippe und Brechstange sind Hebel.","Mit wenig Kraft viel bewegen."),
        fib("ph16b","1","Wenn zwei gleiche Magnetpole zusammenkommen, ___ sie sich. 🧲","When identical poles meet, they ___ each other.","Quand deux pôles identiques se rencontrent, ils se ___.","Quando due poli identici si incontrano, si ___.","abstossen","Nord+Nord = abstossen.","Verschiedene Pole ziehen an."),
        mc("ph17b","1","Was zieht Gegenstände zur Erde? 🌍","What pulls objects to Earth?","Qu'est-ce qui attire les objets vers la Terre ?","Cosa attira gli oggetti verso la Terra?","Die Schwerkraft",["Der Wind","Die Schwerkraft","Ein Magnet","Der Mond"],"Alles fällt, wenn man loslässt.","Newton und der Apfel."),
        fib("ph18b","1","Ein rollender Ball hat ___ als ein ruhender Ball.","A rolling ball has ___ than a stationary ball.","Une balle roulante a ___ qu'une balle immobile.","Una palla che rotola ha ___ rispetto a una ferma.","mehr Energie","Bewegung = kinetische Energie.","Kinetische Energie."),
        mc("ph19b","1","Was ist Auftrieb im Wasser? 🚢","What is buoyancy in water?","Qu'est-ce que la poussée d'Archimède dans l'eau ?","Che cos'è la spinta di Archimede nell'acqua?","Eine Kraft, die Objekte nach oben drückt",["Kraft nach unten","Eine Kraft, die Objekte nach oben drückt","Schwerkraft","Magnetismus"],"Schiffe schwimmen dank Auftrieb.","Wasser drückt nach oben."),
        mc("ph20b","1","Was bestimmt, ob ein Objekt schwimmt oder sinkt? 🌊","What determines if an object floats or sinks?","Qu'est-ce qui détermine si un objet flotte ou coule ?","Cosa determina se un oggetto galleggia o affonda?","Dichte im Vergleich zu Wasser",["Farbe","Dichte im Vergleich zu Wasser","Temperatur","Form allein"],"Holz ist weniger dicht als Wasser.","Dichter als Wasser = sinkt."),
        fib("ph21b","1","Kräfte haben eine Richtung und eine ___.","Forces have a direction and a ___.","Les forces ont une direction et une ___.","Le forze hanno una direzione e una ___.","Stärke","Was beschreibt eine Kraft vollständig?","Grösse und Richtung."),
        mc("ph22b","2","Was ist das Prinzip einer Seilrolle? 🔄","What is the principle of a pulley?","Quel est le principe d'une poulie ?","Qual è il principio di una carrucola?","Sie lenkt Kraft um und kann sie verkleinern",["Nur Umlenkung","Sie lenkt Kraft um und kann sie verkleinern","Reibung erhöht sich","Schwerkraft wächst"],"Krane und Seilbahnen nutzen Rollen.","Richtung und Stärke ändern sich."),
        fib("ph23b","2","Je glatter eine Oberfläche, desto ___ ist die Reibungskraft.","The smoother a surface, the ___ the friction force.","Plus une surface est lisse, plus la force de frottement est ___.","Più una superficie è liscia, più la forza d'attrito è ___.","kleiner","Eis hat wenig Reibung.","Glatt = wenig Widerstand."),
        mc("ph24b","2","Was ist mechanischer Vorteil? ⚙️","What is mechanical advantage?","Qu'est-ce que l'avantage mécanique ?","Che cos'è il vantaggio meccanico?","Mit weniger Kraft die gleiche Arbeit verrichten",["Schneller arbeiten","Mit weniger Kraft die gleiche Arbeit verrichten","Mehr Kraft brauchen","Mehr Zeit brauchen"],"Ein Hebel gibt mechanischen Vorteil.","Weniger Kraft, mehr Weg."),
        mc("ph25b","2","Was ist Impuls? ⚡","What is momentum?","Qu'est-ce que la quantité de mouvement ?","Che cos'è la quantità di moto?","Masse × Geschwindigkeit",["Kraft × Zeit","Masse × Geschwindigkeit","Energie × Richtung","Gewicht × Reibung"],"Schwere und schnelle Objekte haben viel Impuls.","p = m × v."),
        mc("ph26b","2","Warum ist ein Fallschirm sicher? 🪂","Why is a parachute safe?","Pourquoi un parachute est-il sûr ?","Perché un paracadute è sicuro?","Er vergrössert den Luftwiderstand",["Er macht schwerer","Er vergrössert den Luftwiderstand","Er hat Magnetkraft","Er ist aus Metall"],"Grosse Fläche = mehr Luftwiderstand.","Langsamer Fall dank Luftwiderstand."),
        fib("ph27b","2","Arbeit in der Physik: W = ___ × Weg. Gemessen in Joule.","In physics, Work: W = ___ × distance. In Joules.","En physique, Travail W = ___ × distance. En Joules.","In fisica, Lavoro W = ___ × distanza. In Joule.","Kraft","W = F × s.","Joule = Newton × Meter."),
        mc("ph28b","2","Was ist eine einfache Maschine? ⚙️","What is a simple machine?","Qu'est-ce qu'une machine simple ?","Che cos'è una macchina semplice?","Ein Gerät, das Kraft oder Richtung ändert",["Ein elektrisches Gerät","Ein Gerät, das Kraft oder Richtung ändert","Ein Computer","Eine Uhr"],"Hebel, schiefe Ebene, Rolle = einfache Maschinen.","Arbeit erleichtern."),
        fib("ph29b","2","Die Sonne hält Planeten durch ___ in ihrer Umlaufbahn. ☀️","The sun holds planets in orbit through ___.","Le soleil maintient les planètes en orbite grâce à ___.","Il sole mantiene i pianeti in orbita tramite ___.","Schwerkraft","Planeten umkreisen die Sonne.","Schwerkraft wirkt auch im Weltall."),
        mc("ph30b","2","Was wandelt eine Schaukel in ihrer Bewegung um? 🎡","What does a swing convert in its motion?","Que convertit une balançoire dans son mouvement ?","Cosa converte un'altalena nel suo moto?","Lage- und Bewegungsenergie wechselseitig",["Nur Magnetismus","Lage- und Bewegungsenergie wechselseitig","Sie verliert Schwerkraft","Sie dreht sich"],"Oben: Lageenergie. Unten: Bewegungsenergie.","Pendelbewegung = Energieumwandlung."),
        fib("ph31b","2","Die Erdanziehungskraft beträgt auf der Erde etwa ___ m/s².","Earth's gravitational acceleration is about ___ m/s².","L'accélération gravitationnelle est d'environ ___ m/s².","L'accelerazione gravitazionale è circa ___ m/s².","9,81","g ≈ 9,81 m/s².","Objekte beschleunigen beim Fall."),
        mc("ph32b","2","Was ist Drehmoment? 🔧","What is torque?","Qu'est-ce que le couple ?","Che cos'è il momento torcente?","Kraft × Abstand vom Drehpunkt",["Kraft + Gewicht","Kraft × Abstand vom Drehpunkt","Masse × Beschleunigung","Energie × Zeit"],"Langer Schraubenschlüssel = mehr Drehmoment.","Drehmoment = Hebelwirkung."),
        mc("ph33b","2","Was ist der Unterschied zwischen Haft- und Gleitreibung? 🛞","What is the difference between static and kinetic friction?","Quelle est la différence entre frottement statique et cinétique ?","Qual è la differenza tra attrito statico e cinetico?","Haftreibung wirkt vor dem Start, Gleitreibung während der Bewegung",["Keine","Haftreibung wirkt vor dem Start, Gleitreibung während der Bewegung","Gleitreibung ist grösser","Haftreibung ist kleiner"],"Ein stillstehendes Auto ist schwerer anzuschieben als zu schieben.","Haft > Gleit."),
        fib("ph34b","2","Wenn eine Feder gedehnt wird, möchte sie in ihre ___ zurück.","When a spring is stretched, it wants to return to its ___.","Quand un ressort est étiré, il veut revenir à sa ___.","Quando una molla viene allungata, vuole tornare alla sua ___.","Ausgangslage","Federn sind elastisch.","Rückstellkraft."),
        fib("ph35b","2","Je grösser die Masse eines Objekts, desto ___ ist seine Trägheit.","The greater the mass, the ___ its inertia.","Plus la masse est grande, plus son inertie est ___.","Maggiore è la massa, ___ è la sua inerzia.","grösser","Schwerer LKW ist schwerer anzuhalten.","Trägheit ~ Masse."),
        mc("ph36b","2","Warum läuft ein Fahrrad nicht von selbst weg? 🚲","Why doesn't a bike roll away on flat ground?","Pourquoi un vélo ne roule-t-il pas tout seul ?","Perché una bici non va via da sola?","Reibung bremst es",["Magnetismus hält es","Reibung bremst es","Es hat keine Räder","Schwerkraft hält es"],"Reibung der Reifen auf dem Boden.","Ohne Antrieb kein Bewegung."),
        # d3 (×13)
        mc("ph37b","3","Was beschreibt das Hooksche Gesetz? 🌀","What does Hooke's Law describe?","Que décrit la loi de Hooke ?","Cosa descrive la legge di Hooke?","Kraft = Federkonstante × Dehnung (F = k×x)",["Kraft = Masse × Beschleunigung","Kraft = Federkonstante × Dehnung (F = k×x)","Auftrieb = Gewicht","E = mc²"],"Eine Feder dehnt sich proportional zur Kraft.","F = k×x."),
        fib("ph38b","3","Newtons 1. Gesetz: Ein Körper ohne äussere ___ behält seinen Bewegungszustand.","Newton's 1st Law: A body without external ___ maintains its motion.","1e loi de Newton : sans ___ externe, un corps garde son état de mouvement.","1a legge di Newton: senza ___ esterne, un corpo mantiene il suo moto.","Kraft","Ohne Kraft keine Änderung.","Trägheitsprinzip."),
        mc("ph39b","3","Was ist Arbeit in der Physik (W = F × s)? ⚙️","What is work in physics (W = F × d)?","Qu'est-ce que le travail en physique (W = F × d) ?","Che cos'è il lavoro in fisica (W = F × s)?","Kraft × Weg (gemessen in Joule)",["Masse × Beschleunigung","Kraft × Weg (gemessen in Joule)","Energie ÷ Zeit","Spannung × Strom"],"W = F × s. Joule = N×m.","Physikalische Arbeit ≠ Hausaufgaben."),
        fib("ph40b","3","Leistung (P) = Arbeit (W) ÷ ___. Gemessen in Watt.","Power (P) = Work (W) ÷ ___ . Measured in Watts.","Puissance (P) = Travail (W) ÷ ___. En Watts.","Potenza (P) = Lavoro (W) ÷ ___. In Watt.","Zeit (t)","Schnellere Arbeit = mehr Leistung.","P = W/t. Einheit: Watt."),
        mc("ph41b","3","Was ist mechanische Gesamtenergie? 🏔️","What is total mechanical energy?","Qu'est-ce que l'énergie mécanique totale ?","Cos'è l'energia meccanica totale?","Lageenergie + kinetische Energie",["Nur Lageenergie","Lageenergie + kinetische Energie","Wärme + Licht","Nur kinetische Energie"],"E_mech = E_pot + E_kin.","Mechanisch = Bewegung und Lage."),
        fib("ph42b","3","Bei einem elastischen Stoss bleibt die ___ erhalten.","In an elastic collision, the ___ is conserved.","Dans un choc élastique, la ___ est conservée.","In una collisione elastica, la ___ è conservata.","kinetische Energie","Elastisch = keine bleibende Verformung.","Billard: elastischer Stoss."),
        mc("ph43b","3","Was ist der Unterschied zwischen Vektor- und Skalargrössen? 📐","Difference between vector and scalar quantities?","Différence entre grandeurs vectorielles et scalaires ?","Differenza tra grandezze vettoriali e scalari?","Vektoren haben Betrag und Richtung; Skalare nur Betrag",["Vektoren sind grösser","Vektoren haben Betrag und Richtung; Skalare nur Betrag","Beide gleich","Skalare haben Richtung"],"Kraft ist ein Vektor, Temperatur ein Skalar.","Richtung wichtig = Vektor."),
        fib("ph44b","3","Ein Körper im freien Fall erreicht nach 1 Sekunde etwa ___ m/s.","A body in free fall reaches about ___ m/s after 1 second.","Un corps en chute libre atteint environ ___ m/s après 1 seconde.","Un corpo in caduta libera raggiunge circa ___ m/s dopo 1 secondo.","9,81 (≈10)","g ≈ 9,81 m/s².","Nach 2 Sek: ~20 m/s."),
        mc("ph45b","3","Was ist die Frequenz einer Schwingung? 🎶","What is the frequency of oscillation?","Qu'est-ce que la fréquence d'une oscillation ?","Che cos'è la frequenza di un'oscillazione?","Anzahl Schwingungen pro Sekunde (Einheit: Hz)",["Die Länge","Anzahl Schwingungen pro Sekunde (Einheit: Hz)","Die Energie","Die Amplitude"],"Hz = Hertz = Schwingungen/Sekunde.","Höherer Ton = höhere Frequenz."),
        fib("ph46b","3","Das Gravitationsgesetz: Kraft proportional zu ___ der zwei Massen.","Gravity law: Force proportional to ___ of the two masses.","Loi de gravitation : force proportionnelle au ___ des deux masses.","Legge di gravitazione: forza proporzionale al ___ delle due masse.","Produkt (m₁ × m₂)","F ∝ m₁ × m₂.","Mehr Masse = stärkere Anziehung."),
        mc("ph47b","3","Was ist ein System im mechanischen Gleichgewicht? ⚖️","System in mechanical equilibrium?","Système en équilibre mécanique ?","Sistema in equilibrio meccanico?","Summe aller Kräfte ist null",["Alle Kräfte sind positiv","Summe aller Kräfte ist null","Keine Kräfte vorhanden","Das System beschleunigt"],"Ruhend = Gleichgewicht.","ΣF = 0."),
        fib("ph48b","3","Die Einheit der Energie und Arbeit ist ___.","The unit of energy and work is ___.","L'unité d'énergie et de travail est ___.","L'unità di energia e lavoro è ___.","Joule (J)","J = Nm = Joule.","James Prescott Joule."),
        mc("ph49b","3","Was ist Leistung in der Physik? ⚡","What is power in physics?","Qu'est-ce que la puissance en physique ?","Che cos'è la potenza in fisica?","Arbeit pro Zeiteinheit (P = W/t)",["Kraft pro Fläche","Arbeit pro Zeiteinheit (P = W/t)","Energie pro Masse","Geschwindigkeit × Richtung"],"Starker Motor = viel Leistung.","P = W/t, in Watt."),
        fib("ph50b","3","Der Wirkungsgrad η beschreibt, wie effizient eine Maschine Energie in Nutzenergie ___.","Efficiency η describes how efficiently a machine converts energy into useful energy ___.","Le rendement η décrit combien efficacement une machine convertit l'énergie en énergie utile ___.","Il rendimento η descrive quanto efficacemente una macchina converte energia in energia utile ___.","umwandelt","Wirkungsgrad = Nutzenergie / Eingangsenergie.","Ideal: η = 1 = 100%."),
    ]

# ─── SINNE GRADE 1 ───────────────────────────────────────────────────────────
def si_g1():
    return [
        mc("si11","1","Mit welchem Organ hören wir? 👂","Which organ do we hear with?","Avec quel organe entendons-nous ?","Con quale organo sentiamo?","Ohren",["Augen","Nase","Ohren","Zunge"],"Töne werden von einem Organ wahrgenommen.","An beiden Seiten des Kopfes."),
        fib("si12","1","Mit den Händen können wir Wärme und ___ wahrnehmen. ✋","With our hands we can feel warmth and ___.","Avec nos mains nous pouvons percevoir la chaleur et ___.","Con le mani possiamo percepire calore e ___.","Kälte","Was fühlt man, wenn man Eis anfasst?","Tastsinn = Haut."),
        mc("si13","1","Welcher Sinn hilft dir, Essen zu schmecken? 🍕","Which sense helps you taste food?","Quel sens t'aide à goûter la nourriture ?","Quale senso ti aiuta a gustare il cibo?","Geschmackssinn",["Sehsinn","Gehörsinn","Geschmackssinn","Tastsinn"],"Die Zunge nimmt Geschmack wahr.","Schmecken = Zunge."),
        fib("si14","1","Der Sehsinn nutzt die ___.","The sense of sight uses the ___.","Le sens de la vue utilise les ___.","Il senso della vista usa gli ___.","Augen","Licht geht durch die Augen ins Gehirn.","Sehen = Augen."),
        mc("si15","1","Mit welchem Sinn riechst du eine Blume? 🌸","Which sense lets you smell a flower?","Quel sens te permet de sentir une fleur ?","Quale senso ti permette di annusare un fiore?","Geruchssinn",["Sehsinn","Gehörsinn","Geruchssinn","Geschmackssinn"],"Die Nase nimmt Gerüche wahr.","Riechen = Nase."),
        fib("si16","1","Bitter, süss, sauer und ___ sind die vier Grundgeschmäcke.","Bitter, sweet, sour and ___ are the four basic tastes.","Amer, sucré, acide et ___ sont les quatre goûts de base.","Amaro, dolce, acido e ___ sono i quattro sapori di base.","salzig","Was schmeckt Salz?","Vier Grundgeschmäcke der Zunge."),
        mc("si17","1","Welcher Sinn warnt dich bei etwas sehr Heissem? 🌡️","Which sense warns you about something very hot?","Quel sens t'avertit quand quelque chose est très chaud ?","Quale senso ti avverte di qualcosa di molto caldo?","Tastsinn",["Sehsinn","Gehörsinn","Tastsinn","Geruchssinn"],"Die Haut fühlt Wärme.","Finger fühlen Temperatur."),
        fib("si18","1","Wir haben ___ Sinne. 🖐️","We have ___ senses.","Nous avons ___ sens.","Abbiamo ___ sensi.","5","Zähle: Sehen, Hören, Riechen, Schmecken, Tasten.","Fünf Sinne!"),
        mc("si19","1","Was passiert, wenn du die Augen zumachst? 🙈","What happens when you close your eyes?","Que se passe-t-il quand tu fermes les yeux ?","Cosa succede quando chiudi gli occhi?","Du kannst nicht mehr sehen",["Du kannst nicht mehr hören","Du kannst nicht mehr sehen","Du verlierst alle Sinne","Du schläfst sofort ein"],"Augen zu = kein Sehen.","Der Sehsinn braucht offene Augen."),
        fib("si20","1","Unsere Sinne helfen uns, die ___ wahrzunehmen.","Our senses help us perceive the ___.","Nos sens nous aident à percevoir le ___.","I nostri sensi ci aiutano a percepire il ___.","Welt / Umgebung","Wozu dienen unsere Sinne?","Sinne = Kontakt zur Welt."),
        mc("si21","1","Was ist das Sinnesorgan des Gehörs? 👂","What is the sensory organ of hearing?","Quel est l'organe sensoriel de l'ouïe ?","Qual è l'organo sensoriale dell'udito?","Ohr",["Nase","Auge","Ohr","Zunge"],"Töne gelangen durch das Ohr ins Gehirn.","Zwei Ohren am Kopf."),
        mc("si22","2","Was kann die Haut wahrnehmen? ✋","What can the skin perceive?","Que peut percevoir la peau ?","Cosa può percepire la pelle?","Wärme, Kälte, Druck und Schmerz",["Nur Wärme","Nur Kälte","Wärme, Kälte, Druck und Schmerz","Nur Farben"],"Die Haut ist unser grösstes Sinnesorgan.","Tastsinn = viele Empfindungen."),
        fib("si23","2","Wenn Riechen und ___ zusammenarbeiten, schmecken wir viel besser.","When smell and ___ work together, we taste much better.","Quand l'odorat et ___ travaillent ensemble, on goûte mieux.","Quando olfatto e ___ lavorano insieme, gustiamo meglio.","Schmecken","Bei Erkältung schmeckt Essen fade.","Geruch verstärkt Geschmack."),
        mc("si24","2","Wozu braucht der Mensch den Gehörsinn? 👂","Why does a human need the sense of hearing?","Pourquoi l'être humain a-t-il besoin de l'ouïe ?","Perché l'uomo ha bisogno dell'udito?","Um Töne, Sprache und Geräusche wahrzunehmen",["Um zu sehen","Um zu schmecken","Um Töne, Sprache und Geräusche wahrzunehmen","Um zu riechen"],"Musik, Stimmen, Verkehr = Gehörsinn.","Ohr → Gehirn."),
        fib("si25","2","Die Netzhaut im Auge wandelt ___ in Nervenreize um.","The retina converts ___ into nerve signals.","La rétine convertit ___ en signaux nerveux.","La retina converte ___ in segnali nervosi.","Licht","Licht → Netzhaut → Gehirn.","Das Bild entsteht im Gehirn."),
        mc("si26","2","Was ist das Trommelfell? 👂","What is the eardrum?","Qu'est-ce que le tympan ?","Che cos'è il timpano?","Eine dünne Membran im Ohr",["Ein Knochen","Eine dünne Membran im Ohr","Ein Muskel","Ein Nerv"],"Schallwellen lassen es vibrieren.","Trommelfell = Membran im Ohr."),
        fib("si27","2","Bei einer Erkältung riecht man oft ___ gut.","During a cold, one often cannot smell ___ well.","Lors d'un rhume, on ne sent souvent pas ___ bien.","Durante un raffreddore, spesso non si sente ___ bene.","nicht","Nase verstopft → schlechtes Riechen.","Erkältung blockiert Geruchssinn."),
        mc("si28","2","Was ist räumliches Sehen? 👁️","What is depth perception?","Qu'est-ce que la perception de la profondeur ?","Che cos'è la percezione della profondità?","Die Fähigkeit, Abstände einzuschätzen",["Farben sehen","Die Fähigkeit, Abstände einzuschätzen","Träumen","Lesen"],"Zwei Augen helfen beim Abschätzen von Entfernungen.","Binokulares Sehen."),
        fib("si29","2","Das Gehirn verarbeitet alle Informationen von unseren ___.","The brain processes all information from our ___.","Le cerveau traite toutes les informations de nos ___.","Il cervello elabora tutte le informazioni dai nostri ___.","Sinnesorganen","Sinne → Nerven → Gehirn.","Das Gehirn ist die Schaltzentrale."),
        mc("si30","2","Was sind Rezeptoren? 🔬","What are receptors?","Que sont les récepteurs ?","Cosa sono i recettori?","Zellen, die Sinnesreize aufnehmen und weiterleiten",["Muskeln","Zellen, die Sinnesreize aufnehmen und weiterleiten","Knochen","Blutgefässe"],"Fotorezeptoren im Auge, Tastrezeptoren in der Haut.","Rezeptor = Empfänger von Reizen."),
        fib("si31","2","Der Gleichgewichtssinn liegt im ___ des Ohres.","The sense of balance is in the ___ of the ear.","Le sens de l'équilibre se trouve dans le ___ de l'oreille.","Il senso dell'equilibrio si trova nel ___ dell'orecchio.","Innenohr","Balance = Innenohr (Bogengänge).","Schwindel bei Drehung = Innenohr."),
        mc("si32","2","Warum können wir im Dunkeln nicht sehen, aber hören? 🌑","Why can't we see in the dark but can hear?","Pourquoi ne voyons-nous pas dans le noir mais pouvons-nous entendre ?","Perché non vediamo al buio ma possiamo sentire?","Sehen braucht Licht, Hören braucht Schallwellen",["Hören ist stärker","Sehen braucht Licht, Hören braucht Schallwellen","Im Dunkeln hört man besser","Augen schlafen nachts"],"Licht nötig für Sehsinn.","Schallwellen kommen auch im Dunkeln."),
        fib("si33","2","Schmerz ist eine wichtige ___, die uns vor Verletzungen warnt.","Pain is an important ___ that warns us of injuries.","La douleur est un ___ important qui nous avertit des blessures.","Il dolore è un ___ importante che ci avverte delle lesioni.","Schutzfunktion","Schmerz = Warnsignal.","Ohne Schmerz würde man sich verletzen."),
        mc("si34","2","Was geschieht, wenn der Sehnerv beschädigt ist? 👁️","What happens if the optic nerve is damaged?","Que se passe-t-il si le nerf optique est endommagé ?","Cosa succede se il nervo ottico è danneggiato?","Man kann nicht mehr sehen (Blindheit möglich)",["Man hört besser","Man kann nicht mehr sehen (Blindheit möglich)","Man verliert den Tastsinn","Man riecht schärfer"],"Sehnerv verbindet Auge mit Gehirn.","Nerv = Leitung zum Gehirn."),
        fib("si35","2","Wenn man eine Zitrone sieht, läuft einem der ___ im Mund zusammen. 🍋","When you see a lemon, ___ runs in your mouth.","Quand on voit un citron, la ___ nous vient à la bouche.","Quando si vede un limone, la ___ si accumula in bocca.","Speichel","Das Gehirn reagiert auf den Sehreiz.","Reaktion auf Essen beim Anblick."),
        mc("si36","2","Warum haben die meisten Tiere zwei Augen? 👁️","Why do most animals have two eyes?","Pourquoi la plupart des animaux ont-ils deux yeux ?","Perché la maggior parte degli animali ha due occhi?","Für räumliches Sehen (Tiefenwahrnehmung)",["Für mehr Sehfläche","Für räumliches Sehen (Tiefenwahrnehmung)","Weil es symmetrisch ist","Für Nachtsehen"],"Zwei Augen → 3D-Sehen.","Tiefe einschätzen."),
        fib("si37","3","Die Pupille verkleinert sich bei ___ Licht, um das Auge zu schützen.","The pupil contracts in ___ light to protect the eye.","La pupille se rétrécit en lumière ___ pour protéger l'œil.","La pupilla si restringe in luce ___ per proteggere l'occhio.","hellem","Helles Licht → Pupille klein.","Dunkle Pupille = wenig Licht."),
        mc("si38","3","Was beschreibt Synästhesie? 🎨","What describes synesthesia?","Que décrit la synesthésie ?","Cosa descrive la sinestesia?","Wenn ein Sinn einen anderen auslöst (z.B. Töne als Farben sehen)",["Wenn alle Sinne versagen","Wenn ein Sinn einen anderen auslöst (z.B. Töne als Farben sehen)","Wenn man zwei Augen hat","Wenn Riechen und Schmecken sich verbinden"],"Einige Menschen sehen Musik als Farben.","Synästhesie = Sinnesvermischung."),
        fib("si39","3","Das menschliche Ohr kann Frequenzen zwischen etwa 20 und ___ Hz wahrnehmen.","The human ear perceives frequencies between about 20 and ___ Hz.","L'oreille humaine perçoit des fréquences entre environ 20 et ___ Hz.","L'orecchio umano percepisce frequenze tra circa 20 e ___ Hz.","20000","Ultraschall liegt über 20000 Hz.","Hz = Schwingungen pro Sekunde."),
        mc("si40","3","Was ist der Unterschied zwischen Stäbchen und Zapfen im Auge? 👁️","Difference between rods and cones in the eye?","Différence entre bâtonnets et cônes dans l'œil ?","Differenza tra bastoncelli e coni nell'occhio?","Stäbchen: Schwarz/Weiss im Dunkeln; Zapfen: Farben im Tageslicht",["Stäbchen sehen Farben","Stäbchen: Schwarz/Weiss im Dunkeln; Zapfen: Farben im Tageslicht","Beide gleich","Zapfen für Dunkel"],"Katzen haben viele Stäbchen → gut im Dunkeln.","Zapfen = Farben sehen."),
        fib("si41","3","Das Innenohr enthält die ___ (Cochlea), die Schall in Nervenreize umwandelt.","The inner ear contains the ___ (cochlea), which converts sound into nerve signals.","L'oreille interne contient la ___ (cochlée), qui convertit le son.","L'orecchio interno contiene la ___ (coclea), che converte il suono.","Gehörschnecke","Cochlea = Gehörschnecke.","Schall → Cochlea → Hörnerv."),
        mc("si42","3","Was ist olfaktorische Adaptation? 👃","What is olfactory adaptation?","Qu'est-ce que l'adaptation olfactive ?","Che cos'è l'adattamento olfattivo?","Man gewöhnt sich an einen Geruch und nimmt ihn kaum mehr wahr",["Man riecht schärfer","Man verliert den Geruchssinn permanent","Man gewöhnt sich an einen Geruch und nimmt ihn kaum mehr wahr","Man entwickelt neue Rezeptoren"],"Im Zimmer merkt man einen Geruch bald nicht mehr.","Gewöhnung an Reize."),
        fib("si43","3","Sinnesadaptation bedeutet, dass ein Sinn nach längerem Reiz ___ wird.","Sensory adaptation means a sense becomes ___ after prolonged stimulation.","L'adaptation sensorielle signifie qu'un sens devient ___ après stimulation prolongée.","L'adattamento sensoriale significa che un senso diventa ___ dopo stimolazione prolungata.","weniger empfindlich","Auge gewöhnt sich an Dunkelheit.","Reize werden ignoriert."),
        mc("si44","3","Was ist das Zwei-Punkt-Diskriminierungsvermögen? 🖐️","What is two-point discrimination?","Qu'est-ce que la discrimination entre deux points ?","Che cos'è la discriminazione a due punti?","Die Fähigkeit, zwei nahe Berührungspunkte zu unterscheiden",["Das Fühlen von Wärme","Die Fähigkeit, zwei nahe Berührungspunkte zu unterscheiden","Farben erkennen","Gerüche riechen"],"Fingerkuppen = sehr feine Unterscheidung.","Mehr Rezeptoren = bessere Diskriminierung."),
        fib("si45","3","Der ___ Kortex im Gehirn verarbeitet Informationen vom Tastsinn.","The ___ cortex processes touch information.","Le cortex ___ traite les informations du toucher.","La corteccia ___ elabora le informazioni del tatto.","somatosensorische","Somatosensorisch = Körpergefühl.","Gehirnregion für Körperwahrnehmung."),
        mc("si46","3","Was ist Echolokation? 🦇","What is echolocation?","Qu'est-ce que l'écholocation ?","Che cos'è l'ecolocazione?","Navigation durch ausgesendete und zurückgeworfene Schallwellen",["Sehen im Dunkeln","Navigation durch ausgesendete und zurückgeworfene Schallwellen","Riechen aus grosser Entfernung","Schmecken ohne Zunge"],"Fledermäuse und Delfine nutzen Echolokation.","Schall senden, Echo empfangen."),
        fib("si47","3","Das Gehirn ergänzt Sinneseindrücke aktiv: Es ___ fehlende Informationen.","The brain actively completes sensory input: it ___ missing information.","Le cerveau complète activement les impressions : il ___ les informations manquantes.","Il cervello completa attivamente le impressioni: ___ le informazioni mancanti.","ergänzt/vervollständigt","Mustererkennung.","Gehirn füllt Lücken."),
        mc("si48","3","Was ist der Unterschied zwischen Kurz- und Weitsichtigkeit? 👓","Difference between near- and farsightedness?","Différence entre myopie et hypermétropie ?","Differenza tra miopia e ipermetropia?","Kurzsichtig: ferne Objekte unscharf; Weitsichtig: nahe Objekte unscharf",["Beide gleich","Kurzsichtig: ferne Objekte unscharf; Weitsichtig: nahe Objekte unscharf","Kurzsichtig: keine Farben","Kurzsichtig ist gefährlicher"],"Brille korrigiert beide.","Linse zu stark/schwach."),
        fib("si49","3","Die Stelle im Auge mit der höchsten Sehschärfe heisst ___.","The point with highest visual acuity is called ___.","La zone de l'œil avec la plus haute acuité s'appelle ___.","Il punto dell'occhio con la maggiore acuità si chiama ___.","Fovea","Fovea = Zentrum der Netzhaut.","Höchste Zapfendichte."),
        mc("si50","3","Was ist Propriozeption? 🧠","What is proprioception?","Qu'est-ce que la proprioception ?","Che cos'è la propriocezione?","Wahrnehmung der eigenen Körperposition ohne Sehen",["Das Riechen","Wahrnehmung der eigenen Körperposition ohne Sehen","Farbsehen","Hören"],"Mit geschlossenen Augen weisst du, wo deine Arme sind.","Propriozeption = Körpergefühl."),
    ]

# ─── SINNE GRADE 2 ───────────────────────────────────────────────────────────
def si_g2():
    return [
        mc("si11b","1","Welches Organ ist für den Tastsinn verantwortlich? ✋","Which organ is responsible for the sense of touch?","Quel organe est responsable du toucher ?","Quale organo è responsabile del tatto?","Haut",["Ohr","Nase","Haut","Auge"],"Die Haut bedeckt den ganzen Körper.","Tastrezeptoren sitzen in der Haut."),
        fib("si12b","1","Wir schmecken mit der ___. 👅","We taste with our ___.","Nous goûtons avec notre ___.","Assaggiamo con la ___.","Zunge","Geschmacksrezeptoren auf der Zunge.","Süss, sauer, salzig, bitter."),
        mc("si13b","1","Wie viele klassische Grundgeschmäcke kennt die Zunge? 👅","How many classic basic tastes does the tongue know?","Combien de goûts de base classiques connaît la langue ?","Quanti sapori di base classici conosce la lingua?","4 (süss, sauer, salzig, bitter)",["2","3","4 (süss, sauer, salzig, bitter)","6"],"Klassisch: 4 Grundgeschmäcke.","Umami ist der fünfte moderne."),
        fib("si14b","1","Wenn es laut ist, können wir uns ___ konzentrieren.","When it is loud, we can ___ concentrate.","Quand c'est bruyant, on peut ___ se concentrer.","Quando è rumoroso, possiamo ___ concentrarci.","schlechter","Lärm stört den Gehörsinn.","Zu viele Geräusche = weniger Fokus."),
        mc("si15b","1","Womit nehmen wir Gerüche wahr? 👃","What do we use to perceive smells?","Avec quoi percevons-nous les odeurs ?","Con cosa percepiamo gli odori?","Nase",["Mund","Nase","Haut","Augen"],"Riechzellen sitzen in der Nase.","Riechen = Nase."),
        fib("si16b","1","Das Gehirn verarbeitet alle ___ von unseren Sinnesorganen.","The brain processes all ___ from our sensory organs.","Le cerveau traite tous les ___ de nos organes sensoriels.","Il cervello elabora tutti i ___ dai nostri organi sensoriali.","Sinneseindrücke","Sinne → Nerven → Gehirn.","Das Gehirn interpretiert alles."),
        mc("si17b","1","Was kannst du mit dem Tastsinn erkennen? ✋","What can you recognize with the sense of touch?","Que peux-tu reconnaître avec le toucher ?","Cosa puoi riconoscere con il tatto?","Rau, glatt, warm, kalt",["Farben","Rau, glatt, warm, kalt","Töne","Gerüche"],"Haut fühlt Oberflächen und Temperatur.","Tast-Sinn erkennt viele Eigenschaften."),
        fib("si18b","1","Wenn Licht in unsere Augen fällt, leitet der Sehnerv Signale ans ___ weiter.","When light enters our eyes, the optic nerve sends signals to the ___.","Quand la lumière entre dans nos yeux, le nerf optique envoie des signaux au ___.","Quando la luce entra negli occhi, il nervo ottico invia segnali al ___.","Gehirn","Auge → Sehnerv → Gehirn.","Das Gehirn verarbeitet das Bild."),
        mc("si19b","1","Welcher Sinn hilft uns, Musik zu hören? 🎵","Which sense helps us hear music?","Quel sens nous aide à entendre de la musique ?","Quale senso ci aiuta ad ascoltare la musica?","Gehörsinn",["Sehsinn","Gehörsinn","Tastsinn","Geruchssinn"],"Ohren nehmen Töne wahr.","Gehörsinn = Ohr."),
        fib("si20b","1","Brillen korrigieren Fehler des ___ sinns.","Glasses correct defects of ___ vision.","Les lunettes corrigent les défauts de la ___.","Gli occhiali correggono i difetti della ___.","Seh","Kurz- oder Weitsichtigkeit.","Brille hilft beim Sehen."),
        mc("si21b","1","Was ist eine Sinnesüberlastung? 🌊","What is sensory overload?","Qu'est-ce que la surcharge sensorielle ?","Che cos'è il sovraccarico sensoriale?","Wenn zu viele Reize gleichzeitig auf das Gehirn einwirken",["Wenn man schläft","Wenn zu viele Reize gleichzeitig auf das Gehirn einwirken","Wenn alle Sinne perfekt funktionieren","Wenn man im Dunkeln sitzt"],"Zu viel Lärm + grelles Licht = Überlastung.","Zu viel Information."),
        mc("si22b","2","Was ist der Gleichgewichtssinn und wo sitzt er? 🌀","What is the sense of balance and where is it?","Qu'est-ce que le sens de l'équilibre et où est-il ?","Che cos'è il senso dell'equilibrio e dove si trova?","Im Innenohr; er hilft uns, das Gleichgewicht zu halten",["Im Auge","Im Innenohr; er hilft uns, das Gleichgewicht zu halten","In der Nase","Im Magen"],"Innenohr mit Bogengängen.","Gleichgewicht = Innenohr."),
        fib("si23b","2","Ein Mensch ohne Geruchssinn (Anosmie) kann Essen oft nicht gut ___.","A person without smell (anosmia) often cannot ___ food well.","Une personne sans odorat (anosmie) ne peut souvent pas bien ___ la nourriture.","Una persona senza olfatto (anosmia) spesso non riesce a ___ bene il cibo.","schmecken","Riechen und Schmecken hängen zusammen.","Anosmie = kein Geruchssinn."),
        mc("si24b","2","Was ist ein blinder Fleck im Auge? 👁️","What is a blind spot in the eye?","Qu'est-ce que le point aveugle dans l'œil ?","Che cos'è il punto cieco nell'occhio?","Die Stelle, wo der Sehnerv ansetzt – keine Rezeptoren",["Ein schwarzer Punkt","Die Stelle, wo der Sehnerv ansetzt – keine Rezeptoren","Die Netzhaut","Die Pupille"],"Dort kann man nichts sehen.","Sehnerv-Eintrittstelle."),
        fib("si25b","2","Das Innenohr enthält die Cochlea und ___ Bogengänge für das Gleichgewicht.","The inner ear contains the cochlea and ___ semicircular canals for balance.","L'oreille interne contient la cochlée et ___ canaux semi-circulaires.","L'orecchio interno contiene la coclea e ___ canali semicircolari.","drei","Drei Bogengänge für 3 Raumachsen.","Gleichgewichtssinn."),
        mc("si26b","2","Was passiert mit den Sinnen im Alter? 👴","What happens to the senses with age?","Que se passe-t-il avec les sens en vieillissant ?","Cosa succede ai sensi con l'età?","Sie werden oft schwächer (Hören, Sehen)",["Sie werden stärker","Sie verschwinden ganz","Sie werden oft schwächer (Hören, Sehen)","Sie bleiben gleich"],"Alte Menschen brauchen oft Brillen und Hörgeräte.","Sinne schwächen mit dem Alter."),
        fib("si27b","2","Blinde Menschen nutzen oft verstärkt den ___ und den Gehörsinn.","Blind people often use ___ and hearing more strongly.","Les personnes aveugles utilisent souvent davantage le ___ et l'ouïe.","Le persone cieche usano spesso di più il ___ e l'udito.","Tastsinn","Braille-Schrift = Tastsinn.","Kompensation anderer Sinne."),
        mc("si28b","2","Was ist ein Sinnesorgan? 🔬","What is a sensory organ?","Qu'est-ce qu'un organe sensoriel ?","Che cos'è un organo di senso?","Ein spezielles Organ, das bestimmte Reize aufnimmt",["Ein Knochen","Ein spezielles Organ, das bestimmte Reize aufnimmt","Ein Muskel","Ein Blutgefäss"],"Auge, Ohr, Nase, Zunge, Haut = Sinnesorgane.","Organe für Wahrnehmung."),
        fib("si29b","2","Das Auge ist von einem ___ Augapfel umgeben.","The eye is surrounded by a ___ eyeball.","L'œil est entouré d'un globe oculaire ___.","L'occhio è circondato da un bulbo oculare ___.","runden / kugelförmigen","Augapfel = Kugel.","Kann in alle Richtungen drehen."),
        mc("si30b","2","Was ist Schmerz biologisch gesehen? 🤕","What is pain biologically?","Qu'est-ce que la douleur biologiquement ?","Che cos'è il dolore biologicamente?","Ein Warnsignal des Körpers bei Schädigung",["Eine Freude","Ein Warnsignal des Körpers bei Schädigung","Eine Emotion","Ein Geruch"],"Schmerz schützt uns.","Ohne Schmerz würde man Verletzungen ignorieren."),
        fib("si31b","2","Die Rezeptoren in der Nase nehmen ___ Moleküle wahr.","The receptors in the nose detect ___ molecules.","Les récepteurs dans le nez détectent les molécules ___.","I recettori nel naso rilevano le molecole ___.","Duft / Geruchs-","Geruchsmoleküle binden an Rezeptoren.","Nase = chemischer Sensor."),
        mc("si32b","2","Was ist räumliches Sehen (3D)? 👁️","What is 3D spatial vision?","Qu'est-ce que la vision spatiale (3D) ?","Che cos'è la visione spaziale (3D)?","Die Fähigkeit, Objekte im dreidimensionalen Raum wahrzunehmen",["Farben sehen","Die Fähigkeit, Objekte im dreidimensionalen Raum wahrzunehmen","Töne hören","Riechen"],"Zwei Augen → 3D.","Tiefen einschätzen."),
        fib("si33b","2","Beim Kauen und Riechen zusammen nehmen wir ___ stärker wahr.","When chewing and smelling together, we perceive ___ more strongly.","En mâchant et en sentant ensemble, on perçoit ___ plus fort.","Masticando e annusando insieme, percepiamo ___ più forte.","Aroma / Geschmack","Zusammenspiel Nase und Zunge.","Aroma = Geruch + Geschmack."),
        mc("si34b","2","Warum reagieren wir sofort auf laute Geräusche? 👂","Why do we react immediately to loud sounds?","Pourquoi réagissons-nous immédiatement aux sons forts ?","Perché reagiamo immediatamente ai suoni forti?","Reflexantwort zum Schutz",["Weil wir sie mögen","Reflexantwort zum Schutz","Weil wir überrascht sind","Weil wir müde sind"],"Schutzmechanismus.","Laut = mögliche Gefahr."),
        fib("si35b","2","Wenn wir etwas Unangenehmes riechen, nehmen wir den Geruch ___ wahr.","When we smell something unpleasant, we perceive it ___.","Quand on sent quelque chose de désagréable, on le perçoit ___.","Quando annusiamo qualcosa di sgradevole, lo percepiamo ___.","sofort / stark","Unangenehme Gerüche = Warnsignal.","Gefährliche Dinge oft schlecht riechend."),
        mc("si36b","2","Was ist Wahrnehmung? 🧠","What is perception?","Qu'est-ce que la perception ?","Che cos'è la percezione?","Die Verarbeitung von Sinneseindrücken durch das Gehirn",["Nur das Aufnehmen von Reizen","Die Verarbeitung von Sinneseindrücken durch das Gehirn","Das Vergessen","Das Schlafen"],"Sehen → Wahrnehmen → Verstehen.","Gehirn interpretiert Eindrücke."),
        fib("si37b","3","Das Weber-Fechner-Gesetz besagt, dass die Wahrnehmungsstärke ___ zum Reiz zunimmt.","The Weber-Fechner Law: perceived intensity increases ___ with stimulus.","La loi de Weber-Fechner : l'intensité perçue augmente ___ avec le stimulus.","La legge di Weber-Fechner: l'intensità percepita aumenta ___ con lo stimolo.","logarithmisch","Doppelt starker Reiz ≠ doppelt so stark wahrgenommen.","Logarithmisch = abnehmende Sensitivität."),
        mc("si38b","3","Was ist sensorische Integration? 🧠","What is sensory integration?","Qu'est-ce que l'intégration sensorielle ?","Che cos'è l'integrazione sensoriale?","Das Zusammenführen von Informationen aus verschiedenen Sinnen",["Das Trennen von Eindrücken","Das Zusammenführen von Informationen aus verschiedenen Sinnen","Das Ausschalten eines Sinnes","Das Verstärken"],"Gehirn kombiniert Seh- und Höreindrücke.","Integration = zusammenführen."),
        fib("si39b","3","Bei der Dunkeladaptation weitet sich die Pupille und die ___ werden empfindlicher.","In dark adaptation, the pupil widens and the ___ become more sensitive.","Lors de l'adaptation à l'obscurité, la pupille se dilate et les ___ deviennent plus sensibles.","Nell'adattamento al buio, la pupilla si dilata e le ___ diventano più sensibili.","Stäbchen","Stäbchen = Nachtsehen.","Stäbchen sind lichtempfindlicher."),
        mc("si40b","3","Was ist der McGurk-Effekt? 🎭","What is the McGurk effect?","Qu'est-ce que l'effet McGurk ?","Che cos'è l'effetto McGurk?","Visuelle Lippeninformationen verändern den wahrgenommenen Laut",["Eine optische Täuschung","Visuelle Lippeninformationen verändern den wahrgenommenen Laut","Eine Hörbehinderung","Ein Geruchsphänomen"],"Man hört eine andere Silbe je nachdem was man sieht.","Sehen beeinflusst Hören."),
        fib("si41b","3","Sinneswahrnehmung kann durch Erwartungen und Erfahrungen ___ werden.","Sensory perception can be ___ by expectations and experiences.","La perception sensorielle peut être ___ par les attentes et les expériences.","La percezione sensoriale può essere ___ da aspettative ed esperienze.","beeinflusst","Optische Täuschungen täuschen.","Kontext ändert Wahrnehmung."),
        mc("si42b","3","Was ist Phantomschmerz? 🦿","What is phantom pain?","Qu'est-ce que la douleur fantôme ?","Che cos'è il dolore fantasma?","Schmerz in einem amputierten Körperteil",["Eingebildeter Schmerz ohne Ursache","Schmerz in einem amputierten Körperteil","Ein besonders starker Schmerz","Schmerz durch Kälte"],"Das Gehirn sendet weiter Schmerzsignale.","Amputierte berichten davon."),
        fib("si43b","3","Das olfaktorische System sendet Geruchssignale direkt an das ___, ohne den Thalamus.","The olfactory system sends smell signals directly to the ___, bypassing the thalamus.","Le système olfactif envoie les signaux directement au ___, sans passer par le thalamus.","Il sistema olfattivo invia segnali direttamente al ___, bypassando il talamo.","limbische System","Geruch → Emotionen direkt.","Daher löst Geruch starke Erinnerungen aus."),
        mc("si44b","3","Was ist die Theorie der Top-Down-Verarbeitung? 🧠","What is top-down processing?","Qu'est-ce que le traitement descendant ?","Cosa è il processing top-down?","Das Gehirn nutzt Vorwissen, um Sinnesreize zu interpretieren",["Sinne liefern alles ohne Interpretation","Das Gehirn nutzt Vorwissen, um Sinnesreize zu interpretieren","Sinne arbeiten von unten nach oben","Das Gehirn ignoriert Sinnesreize"],"Kontext beeinflusst Wahrnehmung.","Erwartungen formen, was wir wahrnehmen."),
        fib("si45b","3","Die ___ ist die minimale Reizintensität, die gerade noch wahrgenommen werden kann.","The ___ is the minimum stimulus intensity that can just barely be perceived.","Le ___ est l'intensité minimale du stimulus qui peut être perçue.","Il ___ è l'intensità minima dello stimolo percepita.","Reizschwelle","Zu schwach = nicht wahrgenommen.","Unterhalb der Schwelle kein Bewusstsein."),
        mc("si46b","3","Was ist intermodale Wahrnehmung? 🎭","What is intermodal perception?","Qu'est-ce que la perception intermodale ?","Che cos'è la percezione intermodale?","Die Verknüpfung von Informationen aus verschiedenen Sinnen",["Nur ein Sinn aktiv","Die Verknüpfung von Informationen aus verschiedenen Sinnen","Alle Sinne ausgeschaltet","Ein Sinn besonders stark"],"Sehen + Hören + Fühlen zusammen.","Intermodal = zwischen den Sinnen."),
        fib("si47b","3","Die Stelle im Auge mit der höchsten Sehschärfe heisst ___.","The point with the highest visual acuity is called ___.","La zone de l'œil avec la plus haute acuité s'appelle ___.","Il punto con la maggiore acuità visiva si chiama ___.","Fovea","Fovea = Zentrum der Netzhaut.","Höchste Zapfendichte."),
        mc("si48b","3","Was ist Habituation (Gewöhnung)? 🧠","What is habituation?","Qu'est-ce que l'habituation ?","Che cos'è l'abituazione?","Gewöhnung an einen wiederholten Reiz – die Reaktion nimmt ab",["Stärkere Reaktion auf Reize","Gewöhnung an einen wiederholten Reiz – die Reaktion nimmt ab","Vergessen von Reizen","Schlaf"],"Uhr tickt: zuerst laut, dann ignoriert.","Wiederholung → weniger Reaktion."),
        fib("si49b","3","Das Gehirn verbraucht trotz ~2% Körpergewicht etwa ___% der Körperenergie.","Despite being ~2% of body weight, the brain uses about ___% of body energy.","Malgré ~2% du poids, le cerveau consomme environ ___% de l'énergie.","Nonostante il ~2% del peso, il cervello usa circa il ___% dell'energia.","20","Gehirn = sehr energiehungrig.","Sinnesverarbeitung braucht viel Energie."),
        mc("si50b","3","Was ist synaptische Plastizität? 🧠","What is synaptic plasticity?","Qu'est-ce que la plasticité synaptique ?","Che cos'è la plasticità sinaptica?","Die Fähigkeit von Synapsen, ihre Verbindungsstärke zu verändern",["Die Anzahl der Synapsen","Die Fähigkeit von Synapsen, ihre Verbindungsstärke zu verändern","Die Farbe von Neuronen","Die Position von Synapsen"],"Lernen stärkt Synapsen.","Plastizität = Anpassung."),
    ]

# ─── WETTER-KLIMA GRADE 1 ────────────────────────────────────────────────────
def wt_g1():
    return [
        mc("wt11","1","Was ist Nebel? 🌫️","What is fog?","Qu'est-ce que le brouillard ?","Che cos'è la nebbia?","Kleine Wassertröpfchen in der Luft",["Rauch","Kleine Wassertröpfchen in der Luft","Sand","Schnee"],"Nebel ist wie eine Wolke am Boden.","Man sieht schlecht im Nebel."),
        fib("wt12","1","Im ___ fällt Schnee. ❄️","In ___ it snows.","En ___ il neige.","In ___ nevica.","Winter","Wann ist es am kältesten?","Schnee fällt wenn es kalt ist."),
        mc("wt13","1","Was macht die Sonne im Sommer? ☀️","What does the sun do in summer?","Que fait le soleil en été ?","Cosa fa il sole in estate?","Sie scheint lange und warm",["Sie geht früh unter","Sie scheint lange und warm","Sie ist kalt","Sie erscheint selten"],"Im Sommer ist es warm.","Die Tage sind lang."),
        fib("wt14","1","Sonne + Regen zusammen ergeben oft einen ___. 🌈","Sun + rain together often make a ___.","Soleil + pluie ensemble font souvent un ___.","Sole + pioggia insieme fanno spesso un ___.","Regenbogen","Was siehst du am Himmel nach dem Regen?","7 Farben am Himmel."),
        mc("wt15","1","Was passiert mit Wasser bei -5 Grad? 🌡️","What happens to water at -5 degrees?","Que se passe-t-il avec l'eau à -5 degrés ?","Cosa succede all'acqua a -5 gradi?","Es gefriert zu Eis",["Es verdunstet","Es gefriert zu Eis","Es wird Dampf","Es verschwindet"],"Wasser gefriert unter 0°C.","Eis = gefrorenes Wasser."),
        fib("wt16","1","Ein ___ misst die Windgeschwindigkeit. 💨","An ___ measures wind speed.","Un ___ mesure la vitesse du vent.","Un ___ misura la velocità del vento.","Anemometer","Wetterstationen messen den Wind.","Dreht sich im Wind."),
        mc("wt17","1","Wie nennt man graue Wolken, die Regen bringen? 🌧️","What do you call grey clouds that bring rain?","Comment appelle-t-on les nuages gris qui apportent de la pluie ?","Come si chiamano le nuvole grigie che portano pioggia?","Regenwolken",["Schäfchenwolken","Federwolken","Regenwolken","Gewitterwolken"],"Graue Wolken bringen Regen.","Nimbus = Regenwolke."),
        fib("wt18","1","Im ___ wachsen Pflanzen und erwachen Tiere aus dem Winterschlaf. 🌸","In ___ plants grow and animals wake from hibernation.","Au ___ les plantes poussent et les animaux se réveillent.","In ___ le piante crescono e gli animali si risvegliano.","Frühling","Nach dem Winter.","Alles erwacht im Frühling."),
        mc("wt19","1","Was ist ein Gewitter? ⛈️","What is a thunderstorm?","Qu'est-ce qu'un orage ?","Che cos'è un temporale?","Ein Sturm mit Blitz, Donner und starkem Regen",["Leichter Regen","Ein Sturm mit Blitz, Donner und starkem Regen","Schneefall","Sonnenschein"],"Blitz und Donner gehören dazu.","Immer Vorsicht bei Gewitter!"),
        fib("wt20","1","Im ___ fallen die Blätter von den Bäumen. 🍂","In ___ leaves fall from trees.","En ___ les feuilles tombent des arbres.","In ___ le foglie cadono dagli alberi.","Herbst","Nach dem Sommer, vor dem Winter.","Blätter werden gelb und braun."),
        mc("wt21","1","Was misst ein Barometer? ⏱️","What does a barometer measure?","Que mesure un baromètre ?","Cosa misura un barometro?","Den Luftdruck",["Die Temperatur","Den Wind","Den Luftdruck","Den Regen"],"Hoher Luftdruck = meistens gutes Wetter.","Barometer = Luftdruckmesser."),
        mc("wt22","2","Was ist der Wasserkreislauf? 🌊","What is the water cycle?","Qu'est-ce que le cycle de l'eau ?","Che cos'è il ciclo dell'acqua?","Verdunstung → Wolkenbildung → Regen → wieder zurück",["Wasser fliesst ins Meer und endet","Verdunstung → Wolkenbildung → Regen → wieder zurück","Nur Regen","Schnee → Regen → Ende"],"Wasser verdunstet, bildet Wolken, fällt als Regen.","Ein Kreislauf ohne Ende."),
        fib("wt23","2","Wolken entstehen, wenn Wasserdampf ___ und zu Tröpfchen wird. ☁️","Clouds form when water vapour ___ and becomes droplets.","Les nuages se forment quand la vapeur d'eau ___ et devient des gouttelettes.","Le nuvole si formano quando il vapore acqueo ___ e diventa goccioline.","abkühlt / kondensiert","Kühle Luft hält weniger Dampf.","Kondensation."),
        mc("wt24","2","Was verursacht Wind? 💨","What causes wind?","Qu'est-ce qui cause le vent ?","Cosa causa il vento?","Unterschiede im Luftdruck",["Die Sonne allein","Unterschiede im Luftdruck","Der Mond","Das Wasser"],"Luft strömt von Hoch zu Tief.","Wind = Luftströmung."),
        fib("wt25","2","Schnee entsteht, wenn Wassertröpfchen in Wolken bei ___ Temperaturen gefrieren.","Snow forms when water droplets in clouds freeze at ___ temperatures.","La neige se forme quand les gouttelettes gèlent à des températures ___.","La neve si forma quando le goccioline gelano a temperature ___.","tiefen / kalten","Unter 0°C gefrieren Tröpfchen.","Schnee = gefrorene Wassertröpfchen."),
        mc("wt26","2","Was ist der Unterschied zwischen Wetter und Klima? 🌍","What is the difference between weather and climate?","Quelle est la différence entre météo et climat ?","Qual è la differenza tra tempo e clima?","Wetter: kurzfristig; Klima: langfristiges Muster",["Es gibt keinen Unterschied","Wetter: kurzfristig; Klima: langfristiges Muster","Klima ist nur im Winter","Wetter ist wärmer"],"Heute Regen = Wetter. Schweiz gemässigt = Klima.","Kurz vs. lang."),
        fib("wt27","2","Bei einem Regenbogen wird Licht durch ___ in seine Farben zerlegt.","In a rainbow, light is split by ___ into its colours.","Dans un arc-en-ciel, la lumière est décomposée par ___.","In un arcobaleno, la luce viene divisa dai ___.","Wassertröpfchen","Brechung in Wassertröpfchen.","Prisma-Effekt in Regentropfen."),
        mc("wt28","2","Was ist ein Hochdruckgebiet (Hoch)? ⛅","What is a high-pressure system?","Qu'est-ce qu'un anticyclone ?","Che cos'è un anticiclone?","Ein Gebiet mit hohem Luftdruck, meist gutes Wetter",["Schlechtwetter-Gebiet","Ein Gebiet mit hohem Luftdruck, meist gutes Wetter","Starke Winde","Gewitter"],"H = Hochdruckgebiet = Sonne.","Hoch = schönes Wetter."),
        fib("wt29","2","Wind entsteht, weil Luft von ___ Luftdruck zu niedrigem fliesst.","Wind forms because air flows from ___ pressure to low pressure.","Le vent se forme car l'air va de ___ pression à basse pression.","Il vento si forma perché l'aria scorre da ___ pressione a bassa pressione.","hohem","Luftdruckunterschied = Wind.","Luft strömt von Hoch zu Tief."),
        mc("wt30","2","Was ist ein Klimadiagramm? 📊","What is a climate diagram?","Qu'est-ce qu'un diagramme climatique ?","Che cos'è un diagramma climatico?","Eine grafische Darstellung von Temperatur und Niederschlag über Monate",["Ein Foto des Wetters","Eine grafische Darstellung von Temperatur und Niederschlag über Monate","Eine Wetterkarte","Ein Thermometer"],"Balken = Regen, Kurve = Temperatur.","Monatliche Durchschnittswerte."),
        fib("wt31","2","Im Schweizer Alpenraum gibt es oft ___ wind (warmer Fallwind). 🏔️","In the Swiss Alps there is often ___ wind (warm föhn).","Dans les Alpes suisses, il y a souvent le ___ (vent chaud).","Nelle Alpi svizzere c'è spesso il vento ___ (vento caldo).","Föhn","Föhn = warmer Abwind aus den Alpen.","Klares Wetter, aber gefährlich für Brände."),
        mc("wt32","2","Warum hat die Schweiz ein gemässigtes Klima? 🌍","Why does Switzerland have a temperate climate?","Pourquoi la Suisse a-t-elle un climat tempéré ?","Perché la Svizzera ha un clima temperato?","Wegen ihrer Lage in Mitteleuropa und den Alpen",["Wegen des Meeres allein","Wegen ihrer Lage in Mitteleuropa und den Alpen","Weil es sehr kalt ist","Weil es keine Jahreszeiten gibt"],"Gemässigt = weder extrem heiss noch kalt.","Mitteleuropa-Klima."),
        fib("wt33","2","Hagel entsteht in einer ___ wolke, wenn Wassertröpfchen aufgewirbelt werden und gefrieren.","Hail forms in a ___ cloud when water droplets are whirled and freeze.","La grêle se forme dans un nuage d'___ quand des gouttelettes gèlent.","La grandine si forma in una nuvola di ___ quando le goccioline gelano.","Gewitter","Hagel = Gewitterphänomen.","Eiskörner aus Gewitterwolken."),
        mc("wt34","2","Was ist Tau? 💧","What is dew?","Qu'est-ce que la rosée ?","Che cos'è la rugiada?","Wassertröpfchen, die sich bei kühlen Nächten auf Oberflächen bilden",["Regen","Wassertröpfchen, die sich bei kühlen Nächten auf Oberflächen bilden","Schnee","Nebel"],"Morgens siehst du Tau auf Gras.","Kühle Oberfläche → Kondensation."),
        fib("wt35","2","Temperatur wird in Grad ___ gemessen. 🌡️","Temperature is measured in degrees ___.","La température se mesure en degrés ___.","La temperatura si misura in gradi ___.","Celsius (°C)","°C = Grad Celsius.","Nach Anders Celsius benannt."),
        mc("wt36","2","Welche Wetterlage bringt in der Regel Niederschlag? ☁️","Which weather system usually brings precipitation?","Quel système météo apporte généralement des précipitations ?","Quale sistema meteorologico porta di solito precipitazioni?","Ein Tiefdruckgebiet (Tief)",["Ein Hochdruckgebiet","Ein Tiefdruckgebiet (Tief)","Wind","Nebel"],"L = Tiefdruckgebiet = Regen.","Tief = schlechtes Wetter."),
        fib("wt37","3","Die Jahreszeiten entstehen, weil die Erde eine ___ Achse hat und um die Sonne kreist.","Seasons exist because Earth has a ___ axis and orbits the sun.","Les saisons existent car la Terre a un axe ___ et orbite autour du soleil.","Le stagioni esistono perché la Terra ha un asse ___ e orbita intorno al sole.","geneigte","Geneigte Achse → unterschiedliche Sonnenstrahlung.","Neigung der Erdachse."),
        mc("wt38","3","Was ist die Insolation? ☀️","What is insolation?","Qu'est-ce que l'insolation ?","Che cos'è l'insolazione?","Die Sonneneinstrahlung auf die Erdoberfläche",["Die Dauer des Winters","Die Sonneneinstrahlung auf die Erdoberfläche","Die Lufttemperatur","Den Niederschlag"],"Insolation = eintreffende Sonnenstrahlung.","Bestimmt die Erwärmung der Erde."),
        fib("wt39","3","Die Albedo beschreibt, wie viel Sonnenlicht eine Oberfläche ___. ❄️","Albedo describes how much sunlight a surface ___.","L'albédo décrit quelle proportion de lumière solaire une surface ___.","L'albedo descrive quanta luce solare una superficie ___.","reflektiert","Schnee hat hohe Albedo.","Eis reflektiert viel Licht."),
        mc("wt40","3","Was ist der Treibhauseffekt? 🌍","What is the greenhouse effect?","Qu'est-ce que l'effet de serre ?","Che cos'è l'effetto serra?","Treibhausgase halten Wärme in der Erdatmosphäre zurück",["Pflanzen wachsen im Treibhaus","Treibhausgase halten Wärme in der Erdatmosphäre zurück","Die Sonne wird wärmer","Der Wind kühlt die Erde"],"CO₂, Methan = Treibhausgase.","Erde erwärmt sich."),
        fib("wt41","3","Das wichtigste Treibhausgas ist ___. 🌡️","The most important greenhouse gas is ___.","Le gaz à effet de serre le plus important est ___.","Il gas serra più importante è ___.","CO₂ (Kohlenstoffdioxid)","Verbrennung von Kohle und Öl erzeugt CO₂.","CO₂ hält Wärme."),
        mc("wt42","3","Wie entsteht ein Tornado? 🌪️","How does a tornado form?","Comment se forme une tornade ?","Come si forma un tornado?","Durch rotierende Luftmassen in Gewitterzellen",["Durch starken Wind allein","Durch rotierende Luftmassen in Gewitterzellen","Durch Regen","Durch Sonnenwärme allein"],"Superzellen-Gewitter erzeugen Tornados.","Aufsteigende warme, absinkende kalte Luft."),
        fib("wt43","3","Klimawandel bedeutet, dass die durchschnittliche Erdtemperatur durch menschliche Aktivitäten ___.","Climate change means Earth's average temperature ___ due to human activity.","Le changement climatique signifie que la température moyenne de la Terre ___ à cause des activités humaines.","Il cambiamento climatico significa che la temperatura media della Terra ___ per le attività umane.","steigt / zunimmt","Fossile Brennstoffe erhöhen CO₂.","Mehr Treibhausgase = wärmer."),
        mc("wt44","3","Was ist ENSO (El Niño/La Niña)? 🌊","What is ENSO (El Niño/La Niña)?","Qu'est-ce que l'ENSO (El Niño/La Niña) ?","Che cos'è ENSO (El Niño/La Niña)?","Eine periodische Erwärmung/Abkühlung des Pazifiks, die das Weltklima beeinflusst",["Ein Sturmsystem","Eine periodische Erwärmung/Abkühlung des Pazifiks, die das Weltklima beeinflusst","Eine Meeresströmung allein","Ein Sonnenphänomen"],"El Niño = Erwärmung; La Niña = Abkühlung.","Beeinflusst Niederschlag weltweit."),
        fib("wt45","3","Die Atmosphäre der Erde besteht zu ca. 78% aus ___ und 21% Sauerstoff.","Earth's atmosphere is ~78% ___ and 21% oxygen.","L'atmosphère terrestre est composée à environ 78% de ___ et 21% d'oxygène.","L'atmosfera terrestre è composta per ~78% di ___ e 21% di ossigeno.","Stickstoff (N₂)","Stickstoff = häufigste Gas.","N₂ ist inert, O₂ zum Atmen."),
        mc("wt46","3","Was ist eine Klimazone? 🌍","What is a climate zone?","Qu'est-ce qu'une zone climatique ?","Che cos'è una zona climatica?","Ein Gebiet mit ähnlichen langfristigen Wetterbedingungen",["Ein Gebiet mit ähnlichem Wetter heute","Ein Gebiet mit ähnlichen langfristigen Wetterbedingungen","Ein Land","Ein Kontinent"],"Tropisch, gemässigt, arktisch = Klimazonen.","Ähnliche Temperaturen und Niederschläge."),
        fib("wt47","3","Der ___ ist das Langzeit-Klimamuster einer Region (über 30+ Jahre).","The ___ is the long-term climate pattern of a region (30+ years).","Le ___ est le modèle climatique à long terme d'une région (30+ ans).","Il ___ è il modello climatico a lungo termine di una regione (30+ anni).","Klimadurchschnitt / Klima","Klima ≠ Wetter.","Langfristig vs. kurzfristig."),
        mc("wt48","3","Was ist die Thermosphäre? 🌌","What is the thermosphere?","Qu'est-ce que la thermosphère ?","Che cos'è la termosfera?","Die äusserste Schicht der Erdatmosphäre (80-700 km)",["Die unterste Schicht","Die mittlere Schicht","Die äusserste Schicht der Erdatmosphäre (80-700 km)","Die Wolkenschicht"],"Thermosphäre = heisseste Schicht.","Satelliten fliegen hier."),
        fib("wt49","3","Ozon in der Stratosphäre schützt die Erde vor ___ Strahlen der Sonne.","Ozone in the stratosphere protects Earth from ___ rays from the sun.","L'ozone dans la stratosphère protège la Terre des rayons ___ du soleil.","L'ozono nella stratosfera protegge la Terra dai raggi ___ del sole.","ultravioletten (UV-)","UV-Strahlung verursacht Sonnenbrand.","Ozonschicht = Schutzschild."),
        mc("wt50","3","Was beschreibt die Hadley-Zelle? 🌍","What describes the Hadley cell?","Que décrit la cellule de Hadley ?","Cosa descrive la cellula di Hadley?","Ein Zirkulationsmuster von aufsteigender Luft am Äquator und absinkender in den Subtropen",["Eine Meeresströmung","Ein Zirkulationsmuster von aufsteigender Luft am Äquator und absinkender in den Subtropen","Ein Sturmsystem","Eine Klimazone"],"Tropenwinde entstehen durch Hadley-Zellen.","Äquator heiss → Luft steigt auf."),
    ]

# ─── WETTER-KLIMA GRADE 2 ────────────────────────────────────────────────────
def wt_g2():
    return [
        mc("wt11b","1","Welche Jahreszeit hat die längsten Tage? ☀️","Which season has the longest days?","Quelle saison a les jours les plus longs ?","Quale stagione ha i giorni più lunghi?","Sommer",["Frühling","Sommer","Herbst","Winter"],"Im Juli ist es sehr lange hell.","Längste Tage = meiste Sonnenstunden."),
        fib("wt12b","1","Ein ___ misst die Temperatur. 🌡️","A ___ measures temperature.","Un ___ mesure la température.","Un ___ misura la temperatura.","Thermometer","Wie heisst das Gerät im Fiebermessen?","Thermometer = Temperaturmesser."),
        mc("wt13b","1","Was ist Schnee? ❄️","What is snow?","Qu'est-ce que la neige ?","Che cos'è la neve?","Gefrorene Wasserkristalle",["Weisse Farbe","Gefrorene Wasserkristalle","Eis in Stücken","Hagel"],"Schneeflocken sind Eiskristalle.","Wasser gefriert zu Schnee."),
        fib("wt14b","1","Auf dem Thermometer liest man die Temperatur in Grad ___. 🌡️","On the thermometer you read temperature in degrees ___.","Sur le thermomètre on lit la température en degrés ___.","Sul termometro si legge la temperatura in gradi ___.","Celsius (°C)","°C = Grad Celsius.","0°C = Gefrierpunkt."),
        mc("wt15b","1","Was ist ein Regenbogen? 🌈","What is a rainbow?","Qu'est-ce qu'un arc-en-ciel ?","Che cos'è un arcobaleno?","Licht, das durch Wassertröpfchen in Farben zerlegt wird",["Ein Tier","Licht, das durch Wassertröpfchen in Farben zerlegt wird","Ein Mineral","Eine Pflanze"],"Sonne + Regen = Regenbogen.","7 Farben."),
        fib("wt16b","1","Im Winter kann man Ski fahren, weil es ___ gibt. ⛷️","In winter you can ski because there is ___.","En hiver on peut skier car il y a de la ___.","In inverno si può sciare perché c'è ___.","Schnee","Schnee fällt im Winter.","Ski braucht Schnee."),
        mc("wt17b","1","Was zeigt ein Wetterballon? 🎈","What does a weather balloon measure?","Que mesure un ballon météo ?","Cosa misura un pallone meteorologico?","Temperatur und Luftdruck in der Höhe",["Windgeschwindigkeit am Boden","Temperatur und Luftdruck in der Höhe","Regenmengen","Sonnenstunden"],"Wetterballons steigen hoch auf.","Sie messen die Atmosphäre."),
        fib("wt18b","1","Im Frühling schmelzen ___ und Gletscher. ❄️→💧","In spring ___ and glaciers melt.","Au printemps, ___ et glaciers fondent.","In primavera ___ e ghiacciai si sciolgono.","Schnee","Was passiert mit Eis im Frühling?","Wärme schmilzt Schnee."),
        mc("wt19b","1","Was ist Hagel? ⛈️","What is hail?","Qu'est-ce que la grêle ?","Che cos'è la grandine?","Gefrorene Regentropfen als Eisstücke",["Weicher Schnee","Gefrorene Regentropfen als Eisstücke","Regen mit Eis gemischt","Grosser Schneefall"],"Hagel fällt aus Gewitterwolken.","Eiskörner, nicht Schneeflocken."),
        fib("wt20b","1","Der ___ ist der Weg des Wassers in der Natur – von Meer zu Wolke zu Regen zu Fluss. 🔄","The ___ is the path of water in nature.","Le ___ est le chemin de l'eau dans la nature.","Il ___ è il percorso dell'acqua in natura.","Wasserkreislauf","Verdunstung → Wolke → Regen → Fluss.","Kreislauf des Wassers."),
        mc("wt21b","1","Welche Wolkenform sieht aus wie Schafswolken? ☁️","Which cloud type looks like cotton wool?","Quel type de nuage ressemble à du coton ?","Quale tipo di nube assomiglia a cotone?","Cumuluswolken (Schäfchenwolken)",["Zirruswolken","Cumuluswolken (Schäfchenwolken)","Stratocumuluswolken","Nimbuswolken"],"Cumulus = aufgetürmt, weiss, schön.","Schönes Wetter bei Cumuluswolken."),
        mc("wt22b","2","Was ist Verdunstung? 💧","What is evaporation?","Qu'est-ce que l'évaporation ?","Che cos'è l'evaporazione?","Wasser wird durch Wärme zu Dampf (gasförmig)",["Wasser gefriert","Wasser wird durch Wärme zu Dampf (gasförmig)","Wasser fällt als Regen","Wasser kondensiert"],"Pfützen trocknen = Verdunstung.","Wärme verwandelt Wasser zu Dampf."),
        fib("wt23b","2","Wolken entstehen durch ___ von Wasserdampf in der kühlen Luft.","Clouds form through ___ of water vapour in cool air.","Les nuages se forment par ___ de la vapeur d'eau dans l'air frais.","Le nuvole si formano attraverso ___ del vapore acqueo nell'aria fredda.","Kondensation","Kühle Luft hält weniger Dampf.","Kondensation = Dampf → Tröpfchen."),
        mc("wt24b","2","Was ist Niederschlag? 🌧️","What is precipitation?","Qu'est-ce que les précipitations ?","Che cos'è la precipitazione?","Regen, Schnee, Hagel oder Tau, der von Wolken fällt",["Nur Regen","Regen, Schnee, Hagel oder Tau, der von Wolken fällt","Nur Schnee","Nebel"],"Niederschlag = jede Form von Wasser aus Wolken.","Regen, Schnee, Hagel = Niederschlag."),
        fib("wt25b","2","Das Symbol H auf einer Wetterkarte steht für ein ___ (Luftdruck).","H on a weather map stands for ___ (pressure).","H sur une carte météo désigne un ___ (pression).","H su una carta meteorologica indica un ___ (pressione).","Hochdruckgebiet","H = Hoch = gutes Wetter.","Hochdruck = Sonnenschein."),
        mc("wt26b","2","Was ist der Unterschied zwischen Wetter und Klima? 🌍","What is the difference between weather and climate?","Quelle est la différence entre météo et climat ?","Qual è la differenza tra tempo e clima?","Wetter: kurzfristig; Klima: langfristiges Muster (30+ Jahre)",["Es gibt keinen Unterschied","Wetter: kurzfristig; Klima: langfristiges Muster (30+ Jahre)","Klima ist wärmer","Wetter ist stabiler"],"Heute Sonne = Wetter. Mittelmeer immer warm = Klima.","Kurz vs. lang."),
        fib("wt27b","2","Wenn Luft über ein Gebirge strömt und auf der anderen Seite wärmer ankommt, nennt man das ___ -effekt. 🏔️","When air flows over a mountain and arrives warmer on the other side, this is called the ___ effect.","Quand l'air passe sur une montagne et arrive plus chaud de l'autre côté, c'est l'effet ___.","Quando l'aria passa su una montagna e arriva più calda dall'altro lato, si chiama effetto ___.","Föhn","Föhn = warmer Fallwind.","Alpen erzeugen Föhneffekt."),
        mc("wt28b","2","Was ist Luftfeuchtigkeit? 💧","What is humidity?","Qu'est-ce que l'humidité de l'air ?","Che cos'è l'umidità dell'aria?","Der Wasserdampfgehalt der Luft",["Die Temperatur","Der Wasserdampfgehalt der Luft","Der Luftdruck","Der Wind"],"100% Luftfeuchtigkeit = Nebel / Wolken.","Feucht = viel Wasserdampf."),
        fib("wt29b","2","Das Symbol L auf einer Wetterkarte steht für ein ___ (führt meist zu Regen).","L on a weather map stands for ___ (usually brings rain).","L sur une carte météo désigne un ___ (amène souvent la pluie).","L su una carta meteorologica indica un ___ (porta spesso pioggia).","Tiefdruckgebiet","L = Tief = schlechtes Wetter.","Tiefdruck = Regen."),
        mc("wt30b","2","Was ist ein Orkan? 🌪️","What is a hurricane?","Qu'est-ce qu'un ouragan ?","Che cos'è un uragano?","Ein tropischer Sturm mit sehr hohen Windgeschwindigkeiten",["Ein einfacher Regenschauer","Ein tropischer Sturm mit sehr hohen Windgeschwindigkeiten","Eine Kaltfront","Nebel"],"Orkane entstehen über warmem Ozean.","Windgeschwindigkeit > 118 km/h."),
        fib("wt31b","2","In der Schweiz gibt es vier Klimazonen: Mittelland, Alpen, Alpensüdseite und _