import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import { getSubjects, getTopics } from "../src/data/index";

const outputPath = resolve(process.cwd(), "src/data/topicCatalog.generated.ts");
const catalog: Record<string, Array<{
  id: string;
  title: string;
  emoji: string;
  exerciseCount: number;
  tierCounts: [number, number, number];
}>> = {};

for (const grade of [1, 2, 3, 4, 5, 6]) {
  const subjectIds = new Set(getSubjects(grade).map((subject) => subject.id));
  if (grade >= 4) {
    subjectIds.add("nt");
    subjectIds.add("rzg");
  }

  for (const subject of subjectIds) {
    catalog[`${grade}-${subject}`] = getTopics(grade, subject).map((topic) => ({
      id: topic.id,
      title: topic.title,
      emoji: topic.emoji,
      exerciseCount: topic.exercises.length,
      tierCounts: [1, 2, 3].map((difficulty) =>
        topic.exercises.filter((exercise) => exercise.difficulty === difficulty).length,
      ) as [number, number, number],
    }));
  }
}

const source = `// Generated by scripts/generate-topic-catalog.ts. Do not edit manually.\n` +
  `export const TOPIC_CATALOG = ${JSON.stringify(catalog)} as const;\n`;

if (process.argv.includes("--check")) {
  const current = readFileSync(outputPath, "utf8");
  if (current !== source) {
    console.error("Topic catalogue is stale. Run: npm run generate:topic-catalog");
    process.exit(1);
  }
  console.log(`Topic catalogue is current (${Object.values(catalog).flat().length} topics).`);
} else {
  writeFileSync(outputPath, source);
  console.log(`Wrote ${outputPath} (${Object.values(catalog).flat().length} topics).`);
}
