#!/usr/bin/env python3
"""
Expands 11 LP21 topics (22 topic instances) from 10 → 50 exercises each.
Injects into the CORRECT files:
  - grades 1-3: science.ts
  - grades 4-6 physics/bio/space/elec: nt.ts
  - grades 4-6 geography/history: rzg.ts
  - grades 1-2 math: math.ts
Also removes orphaned topic blocks from grade4/5/6 science.ts.
"""

import re, os

BASE = os.path.expanduser("~/projects/cleverli/src/data")

# ─── HELPERS ────────────────────────────────────────────────────────────────

def mc(id, diff, q, qEN, qFR, qIT, ans, opts, h1, h2):
    o = '","'.join(opts)
    return f'      {{ id: "{id}", type: "multiple-choice", difficulty: {diff}, question: "{q}", questionEN: "{qEN}", questionFR: "{qFR}", questionIT: "{qIT}", answer: "{ans}", options: ["{o}"], hints: ["{h1}", "{h2}"] }},'

def fib(id, diff, q, qEN, qFR, qIT, ans, h1, h2):
    return f'      {{ id: "{id}", type: "fill-in-blank", difficulty: {diff}, question: "{q}", questionEN: "{qEN}", questionFR: "{qFR}", questionIT: "{qIT}", answer: "{ans}", hints: ["{h1}", "{h2}"] }},'

def drag(id, diff, q, qEN, qFR, qIT, items, zones, answers, h1, h2):
    items_s = ", ".join(f'{{id:"{i}",label:"{l}"}}' for i,l in items)
    zones_s = ", ".join(f'{{id:"{i}",label:"{l}"}}' for i,l in zones)
    ans_s = ", ".join(f'"{k}":"{v}"' for k,v in answers.items())
    return f'      {{ id: "{id}", type: "drag-drop", difficulty: {diff}, question: "{q}", questionEN: "{qEN}", questionFR: "{qFR}", questionIT: "{qIT}", answer: "all", hints: ["{h1}", "{h2}"], dragItems: [{items_s}], dropZones: [{zones_s}], dropAnswers: {{{ans_s}}} }},'

def match(id, diff, q, qEN, qFR, qIT, pairs, h1, h2):
    pairs_s = ", ".join(f'{{id:"{i}",label:"{l}",emoji:"{e}"}}' for i,l,e in pairs)
    return f'      {{ id: "{id}", type: "matching", difficulty: {diff}, question: "{q}", questionEN: "{qEN}", questionFR: "{qFR}", questionIT: "{qIT}", answer: "all", hints: ["{h1}", "{h2}"], pairs: [{pairs_s}] }},'

def mem(id, diff, q, qEN, qFR, qIT, pairs, h1, h2):
    pairs_s = ", ".join(f'{{id:"{i}",label:"{l}",emoji:"{e}"}}' for i,l,e in pairs)
    return f'      {{ id: "{id}", type: "memory", difficulty: {diff}, question: "{q}", questionEN: "{qEN}", questionFR: "{qFR}", questionIT: "{qIT}", answer: "all", hints: ["{h1}", "{h2}"], pairs: [{pairs_s}] }},'

def inject(filepath, topic_id, new_exercises_ts):
    """Find the exercises array closing bracket for topic_id and insert before it."""
    with open(filepath, encoding='utf-8') as f:
        content = f.read()
    
    # Find the topic block start
    pattern = f'id: "{topic_id}"'
    topic_pos = content.find(pattern)
    if topic_pos == -1:
        print(f"  ERROR: topic '{topic_id}' not found in {filepath}")
        return False
    
    # Find 'exercises: [' after the topic position
    exs_pos = content.find('exercises: [', topic_pos)
    if exs_pos == -1:
        print(f"  ERROR: exercises array not found for '{topic_id}'")
        return False
    
    # Count brackets to find the matching '],'
    depth = 0
    i = exs_pos + len('exercises: [')
    while i < len(content):
        c = content[i]
        if c == '[':
            depth += 1
        elif c == ']':
            if depth == 0:
                # This is the closing bracket of exercises array
                # Insert new_exercises_ts before this position
                # Find the newline before this ']'
                insert_pos = i
                new_content = content[:insert_pos] + new_exercises_ts + '\n' + content[insert_pos:]
                with open(filepath, 'w', encoding='utf-8') as f:
                    f.write(new_content)
                print(f"  ✓ Injected {topic_id} into {os.path.basename(filepath)}")
                return True
            depth -= 1
        i += 1
    print(f"  ERROR: could not find closing bracket for exercises in '{topic_id}'")
    return False

def remove_topic_block(filepath, topic_id):
    """Remove an entire topic block (from { id: "topic_id" to the matching closing },)"""
    with open(filepath, encoding='utf-8') as f:
        content = f.read()
    
    # Find '  {\n    id: "topic_id"'  
    pattern = f'    id: "{topic_id}",'
    pos = content.find(pattern)
    if pos == -1:
        print(f"  SKIP: topic '{topic_id}' not found in {filepath} (may already be removed)")
        return True
    
    # Find the opening '{' of this topic block
    block_start = content.rfind('  {', 0, pos)
    if block_start == -1:
        print(f"  ERROR: cannot find block start for '{topic_id}'")
        return False
    
    # Find closing '},' by counting braces
    depth = 0
    i = block_start
    while i < len(content):
        c = content[i]
        if c == '{':
            depth += 1
        elif c == '}':
            depth -= 1
            if depth == 0:
                # This closes the topic block
                # Check for trailing comma
                end = i + 1
                if end < len(content) and content[end] == ',':
                    end += 1
                # Remove including any newline after
                while end < len(content) and content[end] == '\n':
                    end += 1
                    break
                new_content = content[:block_start] + content[end:]
                with open(filepath, 'w', encoding='utf-8') as f:
                    f.write(new_content)
                print(f"  ✓ Removed topic '{topic_id}' from {os.path.basename(filepath)}")
                return True
        i += 1
    print(f"  ERROR: cannot find end of block for '{topic_id}'")
    return False

# ═══════════════════════════════════════════════════════════════════════════════
# EXERCISE DATA PER TOPIC
# ═══════════════════════════════════════════════════════════════════════════════

# ─── PHYSIK-BEWEGUNG GRADE 1 (ph11–ph50) ─────────────────────────────────────
def exs_ph_g1():
    lines = [
        # d1 ×11
        mc("ph11","1","Was passiert, wenn du auf einen Ball trittst? ⚽","What happens when you kick a ball?","Que se passe-t-il quand tu donnes un coup de pied dans un ballon ?","Cosa succede quando calci un pallone?","Er bewegt sich weg",["Er fängt an zu leuchten","Er bewegt sich weg","Er wird grösser","Er bleibt stehen"],"Kraft bringt Dinge in Bewegung.","Dein Fuss überträgt eine Kraft."),
        fib("ph12","1","Wenn du einen Stein loslässt, fällt er nach ___. 🪨","When you release a stone, it falls ___.","Quand tu lâches une pierre, elle tombe vers ___.","Quando lasci andare un sasso, cade ___.","unten","Die Erde zieht alles an.","Schwerkraft wirkt nach unten."),
        mc("ph13","1","Was braucht ein Objekt, um sich zu bewegen? 💪","What does an object need to move?","De quoi a besoin un objet pour se déplacer ?","Di cosa ha bisogno un oggetto per muoversi?","Eine Kraft",["Farbe","Eine Kraft","Wasser","Luft"],"Drücken oder Ziehen sind Kräfte.","Ohne Kraft bleibt alles ruhig."),
        fib("ph14","1","Ein Magnet hat zwei Pole: Nord und ___. 🧲","A magnet has two poles: North and ___.","Un aimant a deux pôles : Nord et ___.","Un magnete ha due poli: Nord e ___.","Süd","Denke an Kompass-Richtungen.","N und S sind die zwei Pole."),
        mc("ph15","1","Was zieht ein Magnet an? 🧲","What does a magnet attract?","Qu'est-ce qu'un aimant attire ?","Cosa attrae un magnete?","Eisen",["Holz","Plastik","Eisen","Glas"],"Magnete haften am Kühlschrank.","Eisen und Stahl werden angezogen."),
        fib("ph16","1","Wenn du einen Ball loslässt, bewegt er sich ___ aufgrund der Schwerkraft.","When you drop a ball, it moves ___ due to gravity.","Quand tu lâches une balle, elle se déplace ___ à cause de la gravité.","Quando lasci cadere una palla, si muove ___ per via della gravità.","nach unten","Die Schwerkraft zieht nach unten.","Alles fällt zur Erde."),
        mc("ph17","1","Was beschreibt das Wort 'Kraft'? 💪","What does the word 'force' describe?","Que décrit le mot 'force' ?","Cosa descrive la parola 'forza'?","Ein Drücken oder Ziehen",["Eine Farbe","Ein Drücken oder Ziehen","Ein Tier","Eine Zahl"],"Drücken und Ziehen sind Kräfte.","Kräfte verändern Bewegung."),
        fib("ph18","1","Wasser fliesst immer nach ___. 🌊","Water always flows ___.","L'eau coule toujours vers ___.","L'acqua scorre sempre verso ___.","unten","Schwerkraft zieht Wasser.","Flüsse fliessen bergab."),
        mc("ph19","1","Was macht Reibung? 🛞","What does friction do?","Que fait le frottement ?","Cosa fa l'attrito?","Sie verlangsamt Bewegung",["Sie beschleunigt","Sie verlangsamt Bewegung","Sie leuchtet","Sie erwärmt nichts"],"Reibung zwischen Sohle und Boden.","Schuhsohlen bremsen dank Reibung."),
        mc("ph20","1","Was passiert, wenn du an einem Seil ziehst? 🪢","What happens when you pull a rope?","Que se passe-t-il quand tu tires une corde ?","Cosa succede quando tiri una corda?","Das Seil bewegt sich zu dir",["Es verlängert sich","Das Seil bewegt sich zu dir","Es verschwindet","Es wird schwerer"],"Ziehen ist eine Kraft.","Die Kraft überträgt sich auf das Objekt."),
        fib("ph21","1","Eine Wippe funktioniert wie ein ___. ⚖️","A seesaw works like a ___.","Une balançoire fonctionne comme un ___.","Un'altalena funziona come una ___.","Hebel","Drehpunkt in der Mitte.","Hebel verstärken Kräfte."),
        # d2 ×15
        mc("ph22","2","Was ist Schwerkraft? 🌍","What is gravity?","Qu'est-ce que la gravité ?","Che cos'è la gravità?","Eine Kraft, die alles nach unten zieht",["Eine Farbe","Ein Tier","Eine Kraft, die alles nach unten zieht","Eine Zahl"],"Alles fällt zur Erde.","Die Erde zieht an."),
        fib("ph23","2","Wenn ein Objekt dichter als Wasser ist, ___ es. 🌊","If an object is denser than water, it ___.","Si un objet est plus dense que l'eau, il ___.","Se un oggetto è più denso dell'acqua, ___.","sinkt","Stein ist dichter als Wasser.","Holz schwimmt, Stein sinkt."),
        mc("ph24","2","Was passiert, wenn zwei gleiche Magnetpole zusammenkommen? 🧲","What happens when two identical poles meet?","Que se passe-t-il quand deux pôles identiques se rencontrent ?","Cosa succede quando due poli identici si incontrano?","Sie stossen sich ab",["Sie ziehen sich an","Sie stossen sich ab","Nichts passiert","Sie verschmelzen"],"Gleich und gleich stösst sich ab.","Nord+Nord = abstossen."),
        fib("ph25","2","Ein Rad hat wenig Reibung, weil es sich ___. 🚲","A wheel has little friction because it ___.","Une roue a peu de frottement parce qu'elle ___.","Una ruota ha poca attrito perché ___.","dreht","Rollen statt Gleiten = weniger Reibung.","Fahrräder fahren leicht dank Rädern."),
        mc("ph26","2","Was ist Gewichtskraft? ⚖️","What is weight force?","Qu'est-ce que la force gravitationnelle ?","Che cos'è la forza peso?","Die Kraft, mit der die Erde ein Objekt anzieht",["Die Stärke eines Muskels","Die Kraft, mit der die Erde ein Objekt anzieht","Magnetkraft","Die Kraft des Windes"],"Ein Gewicht drückt auf eine Waage.","Schwer = grosse Gewichtskraft."),
        fib("ph27","2","Holz ___ auf Wasser, weil es leichter als Wasser ist. 🪵","Wood ___ on water because it is lighter than water.","Le bois ___ sur l'eau car il est plus léger que l'eau.","Il legno ___ sull'acqua perché è più leggero dell'acqua.","schwimmt","Dichte unter 1 g/cm³ → schwimmen.","Holz ist weniger dicht als Wasser."),
        mc("ph28","2","Warum fliegt ein Vogel und fällt ein Stein? 🦅🪨","Why does a bird fly and a stone fall?","Pourquoi un oiseau vole-t-il et une pierre tombe-t-elle ?","Perché un uccello vola e un sasso cade?","Der Vogel erzeugt mit Flügeln Auftrieb",["Beide fliegen","Der Vogel erzeugt mit Flügeln Auftrieb","Steine sind magnetisch","Vögel haben keine Schwerkraft"],"Flügel erzeugen Auftrieb.","Schwerkraft zieht den Stein nach unten."),
        fib("ph29","2","Das Gegenteil von Ruhe ist ___. 🏃","The opposite of rest is ___.","Le contraire du repos est ___.","Il contrario di riposo è ___.","Bewegung","Was macht ein laufendes Kind?","Ruhe → Bewegung."),
        mc("ph30","2","Was ist Gleichgewicht auf einer Wippe? ⚖️","What is balance on a seesaw?","Qu'est-ce que l'équilibre sur une balançoire ?","Che cos'è l'equilibrio su un'altalena?","Wenn beide Seiten gleich schwer sind",["Wenn eine Seite schwerer ist","Wenn beide Seiten gleich schwer sind","Wenn die Wippe sich dreht","Wenn niemand sitzt"],"Gleiche Gewichte auf beiden Seiten.","Balance = beide Seiten gleich."),
        fib("ph31","2","Wenn du einen Magneten in zwei Teile schneidest, hat jeder Teil ___ Pole. 🧲","If you cut a magnet in half, each part has ___ poles.","Si tu coupes un aimant en deux, chaque partie a ___ pôles.","Se tagli un magnete a metà, ogni parte ha ___ poli.","zwei (Nord und Süd)","Jedes Magnetstück hat immer N und S.","Magnete haben immer beide Pole."),
        mc("ph32","2","Wozu dient ein Sicherheitsgurt im Auto? 🚗","Why do cars have seatbelts?","Pourquoi les voitures ont-elles des ceintures de sécurité ?","Perché le auto hanno le cinture di sicurezza?","Er hält dich bei starker Verzögerung fest",["Er macht das Auto schneller","Er hält dich bei starker Verzögerung fest","Er spart Benzin","Er ist nur Dekoration"],"Bei Bremsung wirkt eine grosse Kraft.","Der Gurt schützt bei Unfall."),
        fib("ph33","2","Luft bremst schnell bewegte Objekte. Diesen Widerstand nennt man ___. 🌬️","Air slows fast-moving objects. This resistance is called ___.","L'air ralentit les objets. Cette résistance s'appelle ___.","L'aria rallenta gli oggetti. Questa resistenza si chiama ___.","Luftwiderstand","Was bremst ein Fallschirm?","Luft setzt Bewegung Widerstand entgegen."),
        mc("ph34","2","Was ist eine schiefe Ebene? 📐","What is an inclined plane?","Qu'est-ce qu'un plan incliné ?","Che cos'è un piano inclinato?","Eine geneigte Fläche, die das Heben erleichtert",["Ein Spiegel","Eine geneigte Fläche, die das Heben erleichtert","Eine Brücke","Ein Rad"],"Rampen und Rutschbahnen sind Beispiele.","Weniger Kraft, aber mehr Weg."),
        fib("ph35","2","Ein langer Hebel braucht ___ Kraft, um etwas anzuheben als ein kurzer. ⚖️","A long lever needs ___ force to lift something than a short one.","Un bras de levier long nécessite ___ de force qu'un court.","Una leva lunga richiede ___ forza per sollevare qualcosa rispetto a una corta.","weniger","Längerer Arm = weniger Kraft nötig.","Mechanischer Vorteil des Hebels."),
        mc("ph36","2","Was ist Auftrieb im Wasser? 🚢","What is buoyancy in water?","Qu'est-ce que la poussée d'Archimède ?","Che cos'è la spinta di Archimede?","Eine Kraft, die Objekte nach oben drückt",["Eine Kraft nach unten","Eine Kraft, die Objekte nach oben drückt","Die Schwerkraft","Magnetismus"],"Schiffe schwimmen dank Auftrieb.","Wasser drückt nach oben."),
        # d3 ×14
        fib("ph37","3","Das Gesetz der Trägheit besagt: Ein Objekt hält seinen Bewegungszustand, wenn keine ___ auf es wirkt.","The law of inertia: an object keeps its motion if no ___ acts on it.","La loi de l'inertie : un objet garde son mouvement si aucune ___ n'agit.","La legge di inerzia: un oggetto mantiene il suo moto se nessuna ___ agisce su di esso.","Kraft","Was braucht es, um einen rollenden Ball anzuhalten?","Ohne Kraft keine Änderung der Bewegung."),
        mc("ph38","3","Was bedeutet Kraft = Masse × Beschleunigung? ⚗️","What does Force = Mass × Acceleration mean?","Que signifie Force = Masse × Accélération ?","Cosa significa Forza = Massa × Accelerazione?","Grössere Masse braucht mehr Kraft für gleiche Beschleunigung",["Kraft und Masse sind gleich","Leichte Objekte fallen schneller","Grössere Masse braucht mehr Kraft für gleiche Beschleunigung","Kraft ohne Masse ist grösser"],"Ein LKW braucht mehr Kraft als ein Fahrrad.","Newtons zweites Gesetz."),
        fib("ph39","3","Die Einheit der Kraft ist der ___, benannt nach einem englischen Wissenschaftler.","The unit of force is the ___, named after an English scientist.","L'unité de force est le ___, nommée d'après un scientifique anglais.","L'unità di forza è il ___, intitolata a uno scienziato inglese.","Newton (N)","Isaac Newton entdeckte die Schwerkraft.","Kraft wird in N gemessen."),
        mc("ph40","3","Was passiert mit der Schwerkraft, je weiter man von der Erde entfernt ist? 🌍","What happens to gravity as you move further from Earth?","Qu'arrive-t-il à la gravité en s'éloignant de la Terre ?","Cosa succede alla gravità man mano che ci si allontana dalla Terra?","Sie wird schwächer",["Sie bleibt gleich","Sie wird stärker","Sie verschwindet sofort","Sie kehrt sich um"],"Im Weltall wiegt man weniger.","Schwerkraft nimmt mit Abstand ab."),
        fib("ph41","3","Zwei Nordpole stossen sich ab. Zwei verschiedene Pole (Nord+Süd) ___ sich an.","Two north poles repel. Two different poles (N+S) ___ each other.","Deux pôles nord se repoussent. Deux pôles différents (N+S) s'___.","Due poli nord si respingono. Due poli diversi (N+S) si ___.","ziehen","Verschiedene Pole: Anziehung.","Gleich = abstossen, verschieden = anziehen."),
        mc("ph42","3","Was ist kinetische Energie? 🏃","What is kinetic energy?","Qu'est-ce que l'énergie cinétique ?","Che cos'è l'energia cinetica?","Energie eines bewegten Objekts",["Energie eines ruhenden Objekts","Energie eines bewegten Objekts","Magnetische Energie","Lichtenergie"],"Ein rollender Ball hat kinetische Energie.","Kinetisch = in Bewegung."),
        fib("ph43","3","Wenn ein Apfel vom Baum fällt, wird seine Lageenergie zu ___ -energie. 🍎","When an apple falls, its potential energy becomes ___ energy.","Quand une pomme tombe, son énergie potentielle devient énergie de ___.","Quando una mela cade, la sua energia potenziale diventa energia di ___.","Bewegungs-/kinetischer","Lageenergie → Kinetische Energie.","Was macht ein fallender Apfel?"),
        mc("ph44","3","Was beschreibt Actio = Reactio (Newtons 3. Gesetz)? ⚙️","What describes Action = Reaction (Newton's 3rd Law)?","Que décrit Action = Réaction (3e loi de Newton) ?","Cosa descrive Actio = Reactio (3a legge di Newton)?","Jede Kraft hat eine gleich grosse Gegenkraft",["Kräfte sind immer unterschiedlich","Es gibt keine Gegenkraft","Jede Kraft hat eine gleich grosse Gegenkraft","Reaktion ist grösser"],"Wenn du gegen eine Wand drückst, drückt sie zurück.","Actio = Reactio."),
        fib("ph45","3","Je grösser die Masse, desto ___ ist seine Trägheit. 🏋️","The greater the mass, the ___ its inertia.","Plus la masse est grande, plus son inertie est ___.","Maggiore è la massa, ___ è la sua inerzia.","grösser","Ein schwerer LKW ist schwerer anzuhalten.","Trägheit ~ Masse."),
        mc("ph46","3","Warum sinkt ein Stück Eisen, aber schwimmt ein Schiff? 🚢","Why does iron sink but a ship floats?","Pourquoi le fer coule-t-il mais un navire flotte-t-il ?","Perché il ferro affonda ma una nave galleggia?","Das Schiff ist hohl, also hat es eine geringere Dichte als Wasser",["Schiffe sind aus Holz","Das Schiff ist hohl, also hat es eine geringere Dichte als Wasser","Eisenpole sind magnetisch","Schiffe haben Motoren"],"Ein hohles Objekt verdrängt mehr Wasser.","Auftrieb = Gewicht des verdrängten Wassers."),
        fib("ph47","3","Das Prinzip des Archimedes: Auftrieb = ___ des verdrängten Wassers.","Archimedes' principle: Buoyancy = ___ of displaced water.","Principe d'Archimède : Poussée = ___ de l'eau déplacée.","Principio di Archimede: Spinta = ___ dell'acqua spostata.","Gewicht","Auftrieb = Gewicht des verdrängten Wassers.","Archimedes in der Badewanne."),
        mc("ph48","3","Was ist mechanischer Vorteil eines Hebels? ⚙️","What is the mechanical advantage of a lever?","Quel est l'avantage mécanique d'un levier ?","Qual è il vantaggio meccanico di una leva?","Mit weniger Kraft die gleiche Arbeit verrichten",["Schneller arbeiten","Mit weniger Kraft die gleiche Arbeit verrichten","Mehr Energie erzeugen","Keine Kraft brauchen"],"Langer Arm = mehr Vorteil.","Hebel = Krafrverstärker."),
        fib("ph49","3","Energie kann nicht erzeugt oder vernichtet, nur ___ werden. ⚡","Energy cannot be created or destroyed, only ___.","L'énergie ne peut pas être créée ou détruite, seulement ___.","L'energia non può essere creata né distrutta, solo ___.","umgewandelt","Energieerhaltungssatz.","Physikalisches Grundgesetz."),
        mc("ph50","3","Was ist der Unterschied zwischen Masse und Gewicht? ⚖️","What is the difference between mass and weight?","Quelle est la différence entre masse et poids ?","Qual è la differenza tra massa e peso?","Masse ist überall gleich; Gewicht hängt von der Schwerkraft ab",["Beide sind identisch","Masse ist überall gleich; Gewicht hängt von der Schwerkraft ab","Gewicht ist immer grösser","Masse ist auf dem Mond grösser"],"Auf dem Mond wiegt man weniger, aber die Masse bleibt gleich.","Masse in kg, Gewicht in Newton."),
    ]
    return "\n".join(lines)

# ─── PHYSIK-BEWEGUNG GRADE 2 (ph11b–ph50b) ───────────────────────────────────
def exs_ph_g2():
    lines = [
        mc("ph11b","1","Was ist Reibungskraft? 🛞","What is friction force?","Qu'est-ce que la force de frottement ?","Che cos'è la forza d'attrito?","Eine Kraft, die Bewegung verlangsamt",["Eine Kraft, die beschleunigt","Eine Kraft, die Bewegung verlangsamt","Magnetismus","Schwerkraft"],"Reibung entsteht an Oberflächen.","Sie erzeugt auch Wärme."),
        fib("ph12b","1","Die Schwerkraft auf der Erde zieht alle Objekte nach ___. 🌍","Gravity on Earth pulls all objects ___.","La gravité sur Terre attire tous les objets vers ___.","La gravità sulla Terra attira tutti gli oggetti verso ___.","unten","Alles fällt, wenn man loslässt.","Die Erde zieht an."),
        mc("ph13b","1","Was ist der Unterschied zwischen Drücken und Ziehen? 💪","What is the difference between pushing and pulling?","Quelle est la différence entre pousser et tirer ?","Qual è la differenza tra spingere e tirare?","Beide sind Kräfte, wirken aber in verschiedene Richtungen",["Es gibt keinen Unterschied","Drücken ist stärker","Beide sind Kräfte, wirken aber in verschiedene Richtungen","Ziehen hat keine Wirkung"],"Drücken = von dir weg. Ziehen = zu dir hin.","Beide sind Kräfte."),
        fib("ph14b","1","Ein Schiff schwimmt, weil der ___ gleich gross ist wie die Schwerkraft. 🚢","A ship floats because the ___ equals the gravitational force.","Un bateau flotte parce que la ___ est égale à la force gravitationnelle.","Una nave galleggia perché la ___ è uguale alla forza gravitazionale.","Auftrieb","Auftrieb = Gewicht des verdrängten Wassers.","Kräftegleichgewicht."),
        mc("ph15b","1","Was erzeugt ein Hebel? ⚖️","What does a lever produce?","Que produit un levier ?","Cosa produce una leva?","Eine mechanische Kraft-Verstärkung",["Elektrischen Strom","Eine mechanische Kraft-Verstärkung","Wärme","Licht"],"Wippe und Brechstange sind Hebel.","Mit wenig Kraft viel bewegen."),
        fib("ph16b","1","Wenn zwei gleiche Magnetpole zusammenkommen, ___ sie sich. 🧲","When identical poles meet, they ___ each other.","Quand deux pôles identiques se rencontrent, ils se ___.","Quando due poli identici si incontrano, si ___.","abstossen","Nord+Nord = abstossen.","Verschiedene Pole ziehen an."),
        mc("ph17b","1","Was zieht Gegenstände zur Erde? 🌍","What pulls objects to Earth?","Qu'est-ce qui attire les objets vers la Terre ?","Cosa attira gli oggetti verso la Terra?","Die Schwerkraft",["Der Wind","Die Schwerkraft","Ein Magnet","Der Mond"],"Alles fällt, wenn man loslässt.","Newton und der Apfel."),
        fib("ph18b","1","Ein Ball, der rollt, hat ___ als ein Ball der stillsteht. 🎯","A rolling ball has ___ than one that stands still.","Une balle qui roule a ___ qu'une balle immobile.","Una palla che rotola ha ___ rispetto a una ferma.","mehr Energie","Bewegung = Energie.","Kinetische Energie."),
        mc("ph19b","1","Was ist Auftrieb? 🚢","What is buoyancy?","Qu'est-ce que la poussée d'Archimède ?","Che cos'è la spinta di Archimede?","Die Kraft, die Objekte im Wasser nach oben drückt",["Die Kraft nach unten","Die Kraft, die Objekte im Wasser nach oben drückt","Schwerkraft","Magnetismus"],"Schiffe schwimmen dank Auftrieb.","Wasser drückt nach oben."),
        mc("ph20b","1","Was beeinflusst, ob ein Objekt schwimmt oder sinkt? 🌊","What affects whether an object floats or sinks?","Qu'est-ce qui influe sur le fait qu'un objet flotte ou coule ?","Cosa influisce sul fatto che un oggetto galleggi o affondi?","Seine Dichte im Vergleich zu Wasser",["Seine Farbe","Seine Dichte im Vergleich zu Wasser","Seine Temperatur","Seine Form allein"],"Holz ist weniger dicht als Wasser.","Dichter als Wasser = sinkt."),
        fib("ph21b","1","Kräfte haben eine Richtung und eine ___. 💪","Forces have a direction and a ___.","Les forces ont une direction et une ___.","Le forze hanno una direzione e una ___.","Stärke","Was beschreibt eine Kraft vollständig?","Grösse und Richtung."),
        # d2 ×15
        mc("ph22b","2","Was ist das Prinzip hinter Seil und Umlenkrolle? 🔄","What is the principle of a rope and pulley?","Quel est le principe d'une corde et d'une poulie ?","Qual è il principio di una fune e una carrucola?","Die Kraft wird umgelenkt und evtl. verkleinert",["Nur Umlenkung","Die Kraft wird umgelenkt und evtl. verkleinert","Reibung erhöht sich","Schwerkraft wächst"],"Kran und Seilbahn nutzen Rollen.","Richtung und Stärke ändern sich."),
        fib("ph23b","2","Je glatter eine Oberfläche, desto ___ ist die Reibungskraft. 🧊","The smoother a surface, the ___ the friction force.","Plus une surface est lisse, plus la force de frottement est ___.","Più una superficie è liscia, più la forza d'attrito è ___.","kleiner","Eis hat wenig Reibung.","Glatt = wenig Widerstand."),
        mc("ph24b","2","Was ist mechanischer Vorteil? ⚙️","What is mechanical advantage?","Qu'est-ce que l'avantage mécanique ?","Che cos'è il vantaggio meccanico?","Mit weniger Kraft die gleiche Arbeit verrichten",["Schneller arbeiten","Mit weniger Kraft die gleiche Arbeit verrichten","Mehr Kraft brauchen","Mehr Zeit brauchen"],"Ein Hebel gibt mechanischen Vorteil.","Weniger Kraft, mehr Weg."),
        fib("ph25b","2","Ein Zahnrad überträgt Kräfte: ein grosses dreht ein kleines schnell, aber mit ___ Kraft. ⚙️","A gear: a large one turns a small one fast, but with ___ force.","Un grand engrenage fait tourner un petit vite, mais avec ___ de force.","Un grande ingranaggio fa girare uno piccolo velocemente, ma con ___ forza.","kleinerer","Übersetzungsverhältnis.","Grosses Zahnrad = schnell aber wenig Kraft."),
        mc("ph26b","2","Was ist Impuls? ⚡","What is momentum?","Qu'est-ce que la quantité de mouvement ?","Che cos'è la quantità di moto?","Masse × Geschwindigkeit",["Kraft × Zeit","Masse × Geschwindigkeit","Energie × Richtung","Gewicht × Reibung"],"Schwere und schnelle Objekte haben viel Impuls.","p = m × v."),
        mc("ph27b","2","Warum ist ein Fallschirm sicherer als ohne? 🪂","Why is a parachute safer than without one?","Pourquoi un parachute est-il plus sûr que sans ?","Perché un paracadute è più sicuro che senza?","Er vergrössert den Luftwiderstand",["Er macht schwerer","Er vergrössert den Luftwiderstand","Er hat Magnetkraft","Er ist aus Metall"],"Grosse Fläche = mehr Luftwiderstand.","Fallschirmspringer fallen langsam."),
        fib("ph28b","2","Ein Objekt auf einem Hang neigt zum Rutschen wegen ___ und Schwerkraft. ⛰️","An object on a slope tends to slide due to ___ and gravity.","Un objet sur une pente tend à glisser à cause de ___ et de la gravité.","Un oggetto su un pendio tende a scivolare a causa di ___ e gravità.","Hangabtriebskraft","Bergab = Schwerkraft zieht.","Hangkraft = Teil der Schwerkraft."),
        mc("ph29b","2","Was ist eine einfache Maschine? ⚙️","What is a simple machine?","Qu'est-ce qu'une machine simple ?","Che cos'è una macchina semplice?","Ein Gerät, das Kraft oder Richtung verändert (Hebel, Rad, Rampe)",["Ein elektrisches Gerät","Ein Gerät, das Kraft oder Richtung verändert (Hebel, Rad, Rampe)","Ein Computer","Eine Uhr"],"Hebel, schiefe Ebene, Rolle sind einfache Maschinen.","Arbeit erleichtern."),
        fib("ph30b","2","Die Sonne hält Planeten durch ___ in ihrer Umlaufbahn. ☀️","The sun holds planets in orbit through ___.","Le soleil maintient les planètes en orbite grâce à ___.","Il sole mantiene i pianeti in orbita tramite ___.","Schwerkraft/Gravitation","Planeten umkreisen die Sonne.","Schwerkraft wirkt auch im Weltall."),
        mc("ph31b","2","Was bedeutet es, wenn eine Schaukel schwingt? 🎡","What happens when a swing oscillates?","Que signifie quand une balançoire oscille ?","Cosa significa quando un'altalena oscilla?","Sie wandelt Lage- und Bewegungsenergie um",["Sie erzeugt Magnetismus","Sie wandelt Lage- und Bewegungsenergie um","Sie verliert Schwerkraft","Sie dreht sich"],"Oben: Lageenergie. Unten: Bewegungsenergie.","Pendelbewegung = Energieumwandlung."),
        fib("ph32b","2","Die Erdanziehungskraft beträgt auf der Erde etwa ___ m/s² (Fallbeschleunigung).","Earth's gravitational acceleration is about ___ m/s².","L'accélération gravitationnelle terrestre est d'environ ___ m/s².","L'accelerazione gravitazionale terrestre è circa ___ m/s².","9,81","g ≈ 9,81 m/s².","Objekte beschleunigen beim Fall."),
        mc("ph33b","2","Was ist Drehmoment? 🔧","What is torque?","Qu'est-ce que le couple ?","Che cos'è il momento torcente?","Kraft × Abstand vom Drehpunkt",["Kraft + Gewicht","Kraft × Abstand vom Drehpunkt","Masse × Beschleunigung","Energie × Zeit"],"Langer Schraubenschlüssel = mehr Drehmoment.","Drehmoment = Hebelwirkung."),
        fib("ph34b","2","Wenn eine Feder gedehnt wird, möchte sie in ihre ___ zurück. 🌀","When a spring is stretched, it wants to return to its ___.","Quand un ressort est étiré, il veut revenir à sa ___.","Quando una molla viene allungata, vuole tornare alla sua ___.","Ausgangslage","Federn sind elastisch.","Rückstellkraft."),
        mc("ph35b","2","Warum läuft ein Fahrrad nicht von selbst weg auf ebenem Boden? 🚲","Why doesn't a bike roll away on flat ground?","Pourquoi un vélo ne roule-t-il pas tout seul sur terrain plat ?","Perché una bici non va via da sola su terreno piatto?","Reibung bremst es",["Magnetismus hält es","Reibung bremst es","Es hat keine Räder","Schwerkraft hält es"],"Reibung der Reifen auf dem Boden.","Ohne Antrieb kein Bewegung."),
        fib("ph35b2","2","Arbeit in der Physik: W = ___ × Weg (s). Gemessen in Joule. ⚙️","In physics, Work: W = ___ × distance. Measured in Joules.","En physique, Travail W = ___ × distance. En Joules.","In fisica, Lavoro W = ___ × distanza. In Joule.","Kraft (F)","W = F × s.","Arbeit = Kraft mal Weg."),
        # d3 ×14
        mc("ph37b","3","Was beschreibt das Hooksche Gesetz? 🌀","What does Hooke's Law describe?","Que décrit la loi de Hooke ?","Cosa descrive la legge di Hooke?","Kraft = Federkonstante × Dehnung (F = k×x)",["Kraft = Masse × Beschleunigung","Kraft = Federkonstante × Dehnung (F = k×x)","Auftrieb = Gewicht","Energie = Masse × c²"],"Eine Feder dehnt sich proportional zur Kraft.","F = k×x."),
        fib("ph38b","3","Newtons 1. Gesetz (Trägheitsprinzip): Ein Körper ohne äussere ___ behält seinen Bewegungszustand. ⚗️","Newton's 1st Law: A body without external ___ maintains its state of motion.","1re loi de Newton : sans ___ externe, le corps garde son état de mouvement.","1a legge di Newton: senza ___ esterne, il corpo mantiene il suo stato di moto.","Kraft","Ohne Kraft = keine Änderung.","Trägheitsprinzip."),
        mc("ph39b","3","Was ist Arbeit in der Physik? (W = F × s) ⚙️","What is work in physics? (W = F × d)?","Qu'est-ce que le travail en physique ? (W = F × d)","Che cos'è il lavoro in fisica? (W = F × s)","Kraft × Weg (gemessen in Joule)",["Masse × Beschleunigung","Kraft × Weg (gemessen in Joule)","Energie ÷ Zeit","Spannung × Strom"],"W = F × s. Joule = N×m.","Physikalische Arbeit ≠ Hausaufgaben."),
        fib("ph40b","3","Leistung (P) = Arbeit (W) ÷ ___. (gemessen in Watt)","Power (P) = Work (W) ÷ ___ (in Watts).","Puissance (P) = Travail (W) ÷ ___ (en Watts).","Potenza (P) = Lavoro (W) ÷ ___ (in Watt).","Zeit (t)","Schnellere Arbeit = mehr Leistung.","P = W/t. Einheit: Watt."),
        mc("ph41b","3","Was ist mechanische Gesamtenergie? 🏔️","What is total mechanical energy?","Qu'est-ce que l'énergie mécanique totale ?","Cos'è l'energia meccanica totale?","Lageenergie + kinetische Energie",["Nur Lageenergie","Nur kinetische Energie","Lageenergie + kinetische Energie","Wärme + Licht"],"E_mech = E_pot + E_kin.","Mechanisch = Bewegung und Lage."),
        fib("ph42b","3","Bei einem elastischen Stoss bleibt die ___ erhalten. (Physik)","In an elastic collision, the ___ is conserved.","Dans un choc élastique, la ___ est conservée.","In una collisione elastica, la ___ è conservata.","kinetische Energie","Elastisch = keine bleibende Verformung.","Billard: elastischer Stoss."),
        mc("ph43b","3","Was ist der Unterschied zwischen Vektor- und Skalargrossen? 📐","What is the difference between vector and scalar quantities?","Quelle est la différence entre grandeurs vectorielles et scalaires ?","Qual è la differenza tra grandezze vettoriali e scalari?","Vektoren haben Betrag und Richtung; Skalare nur Betrag",["Vektoren sind grösser","Beide gleich","Vektoren haben Betrag und Richtung; Skalare nur Betrag","Skalare haben Richtung"],"Kraft ist ein Vektor, Temperatur ein Skalar.","Richtung wichtig = Vektor."),
        fib("ph44b","3","Ein Körper im freien Fall erreicht nach 1 Sekunde etwa ___ m/s Geschwindigkeit.","A body in free fall reaches about ___ m/s after 1 second.","Un corps en chute libre atteint environ ___ m/s après 1 seconde.","Un corpo in caduta libera raggiunge circa ___ m/s dopo 1 secondo.","9,81 (≈10)","g ≈ 9,81 m/s².","Nach 2 Sek: ~20 m/s."),
        mc("ph45b","3","Was ist die Frequenz einer Schwingung? 🎶","What is the frequency of oscillation?","Qu'est-ce que la fréquence d'une oscillation ?","Che cos'è la frequenza di un'oscillazione?","Die Anzahl Schwingungen pro Sekunde (Einheit: Hz)",["Die Länge","Die Anzahl Schwingungen pro Sekunde (Einheit: Hz)","Die Energie","Die Amplitude"],"Hz = Hertz = Schwingungen/Sekunde.","Höherer Ton = höhere Frequenz."),
        fib("ph46b","3","Das Gravitationsgesetz: Zwei Massen ziehen sich an mit einer Kraft, die proportional zu ihrem ___ ist.","Newton's gravity law: two masses attract with force proportional to their ___.","Loi de gravitation : deux masses s'attirent avec une force proportionnelle à leur ___.","Legge di gravitazione: due masse si attraggono con forza proporzionale al loro ___.","Produkt (m₁ × m₂)","F ∝ m₁ × m₂.","Mehr Masse = stärkere Anziehung."),
        mc("ph47b","3","Was ist ein System im mechanischen Gleichgewicht? ⚖️","What is a system in mechanical equilibrium?","Qu'est-ce qu'un système en équilibre mécanique ?","Che cos'è un sistema in equilibrio meccanico?","Summe aller Kräfte und Drehmomente ist null",["Alle Kräfte sind positiv","Summe aller Kräfte und Drehmomente ist null","Keine Kräfte vorhanden","Das System beschleunigt"],"Ruhend und nicht rotierend = Gleichgewicht.","ΣF = 0."),
        fib("ph48b","3","Die Einheit der Energie und Arbeit ist ___. (Nach einem englischen Physiker benannt)","The unit of energy and work is ___ (after an English physicist).","L'unité d'énergie et de travail est ___ (d'après un physicien anglais).","L'unità di energia e lavoro è ___ (dal nome di un fisico inglese).","Joule (J)","J = Nm = Joule.","James Prescott Joule."),
        mc("ph49b","3","Was ist Leistung in der Physik? ⚡","What is power in physics?","Qu'est-ce que la puissance en physique ?","Che cos'è la potenza in fisica?","Arbeit pro Zeiteinheit (P = W/t)",["Kraft pro Fläche","Arbeit pro Zeiteinheit (P = W/t)","Energie pro Masse","Geschwindigkeit × Richtung"],"Ein starker Motor hat viel Leistung.","P = W/t, in Watt."),
        fib("ph50b","3","Der Wirkungsgrad η (eta) beschreibt, wie effizient eine Maschine Energie in Nutzenergie ___.",  "Efficiency η describes how efficiently a machine converts energy into useful energy ___.", "Le rendement η décrit combien efficacement une machine convertit l'énergie en énergie utile ___.", "Il rendimento η descrive quanto efficacemente una macchina converte energia in energia utile ___.", "umwandelt", "Wirkungsgrad = Nutzenergie / Eingangsenergie.", "Ideal: η = 1 = 100%."),
    ]
    return "\n".join(lines)

# ─── SINNE GRADE 1 (si11–si50) ───────────────────────────────────────────────
def exs_si_g1():
    lines = [
        mc("si11","1","Mit welchem Organ hören wir? 👂","Which organ do we hear with?","Avec quel organe entendons-nous ?","Con quale organo sentiamo?","Ohren",["Augen","Nase","Ohren","Zunge"],"Töne werden von einem Organ wahrgenommen.","An beiden Seiten des Kopfes."),
        fib("si12","1","Mit den Händen können wir ___ wahrnehmen. ✋","With our hands we can perceive ___.","Avec nos mains nous pouvons percevoir ___.","Con le mani possiamo percepire ___.","Wärme und Kälte / Rauhigkeit","Was fühlt man, wenn man etwas anfasst?","Tastsinn = Haut."),
        mc("si13","1","Welcher Sinn hilft dir, Essen zu schmecken? 🍕","Which sense helps you taste food?","Quel sens t'aide à goûter la nourriture ?","Quale senso ti aiuta a gustare il cibo?","Geschmackssinn",["Sehsinn","Gehörsinn","Geschmackssinn","Tastsinn"],"Die Zunge nimmt Geschmack wahr.","Schmecken = Zunge."),
        fib("si14","1","Der Sehsinn nutzt die ___. 👁️","The sense of sight uses the ___.","Le sens de la vue utilise les ___.","Il senso della vista usa gli ___.","Augen","Licht geht durch Augen ins Gehirn.","Sehen = Augen."),
        mc("si15","1","Mit welchem Sinn kannst du eine Blume riechen? 🌸","Which sense lets you smell a flower?","Quel sens te permet de sentir une fleur ?","Quale senso ti permette di annusare un fiore?","Geruchssinn",["Sehsinn","Gehörsinn","Geruchssinn","Geschmackssinn"],"Die Nase nimmt Gerüche wahr.","Riechen = Nase."),
        fib("si16","1","Bitter, süss, sauer und ___ sind die vier Grundgeschmäcke. 👅","Bitter, sweet, sour and ___ are the four basic tastes.","Amer, sucré, acide et ___ sont les quatre goûts de base.","Amaro, dolce, acido e ___ sono i quattro sapori di base.","salzig","Was schmeckt Salz?","Vier Grundgeschmäcke."),
        mc("si17","1","Welcher Sinn warnt dich, wenn etwas sehr heiss ist? 🌡️","Which sense warns you when something is hot?","Quel sens t'avertit quand quelque chose est chaud ?","Quale senso ti avverte quando qualcosa è caldo?","Tastsinn",["Sehsinn","Gehörsinn","Tastsinn","Geruchssinn"],"Die Haut fühlt Wärme.","Finger fühlen Temperatur."),
        fib("si18","1","Wir haben ___ Sinne. 🖐️","We have ___ senses.","Nous avons ___ sens.","Abbiamo ___ sensi.","5","Zähle: Sehen, Hören, Riechen, Schmecken, Tasten.","Fünf Sinne!"),
        mc("si19","1","Was passiert, wenn du die Augen zumachst? 🙈","What happens when you close your eyes?","Que se passe-t-il quand tu fermes les yeux ?","Cosa succede quando chiudi gli occhi?","Du kannst nicht mehr sehen",["Du kannst nicht mehr hören","Du kannst nicht mehr sehen","Du verlierst alle Sinne","Du schläfst ein"],"Augen zu = kein Sehen.","Der Sehsinn braucht offene Augen."),
        fib("si20","1","Unsere Sinne helfen uns, die ___ wahrzunehmen. 🌍","Our senses help us perceive the ___.","Nos sens nous aident à percevoir le ___.","I nostri sensi ci aiutano a percepire il ___.","Welt","Wozu dienen unsere Sinne?","Sinne = Kontakt zur Welt."),
        mc("si21","1","Was ist das Sinnesorgan des Gehörs? 👂","What is the sensory organ of hearing?","Quel est l'organe sensoriel de l'ouïe ?","Qual è l'organo sensoriale dell'udito?","Ohr",["Nase","Auge","Ohr","Zunge"],"Töne gelangen durch das Ohr ins Gehirn.","Zwei Ohren."),
        # d2 ×15
        mc("si22","2","Was kann die Haut wahrnehmen? ✋","What can the skin perceive?","Que peut percevoir la peau ?","Cosa può percepire la pelle?","Wärme, Kälte, Druck und Schmerz",["Nur Wärme","Nur Kälte","Wärme, Kälte, Druck und Schmerz","Nur Farben"],"Die Haut ist unser grösstes Sinnesorgan.","Tastsinn = viele Empfindungen."),
        fib("si23","2","Wenn Riechen und ___ zusammenarbeiten, schmecken wir viel besser. 👃👅","When smell and ___ work together, we taste much better.","Quand l'odorat et ___ travaillent ensemble, on goûte mieux.","Quando olfatto e ___ lavorano insieme, gustiamo meglio.","Schmecken","Bei Erkältung schmeckt Essen fade.","Geruch verstärkt Geschmack."),
        mc("si24","2","Wozu braucht der Mensch den Gehörsinn? 👂","Why does a human need the sense of hearing?","Pourquoi l'être humain a-t-il besoin de l'ouïe ?","Perché l'uomo ha bisogno dell'udito?","Um Töne, Sprache und Geräusche wahrzunehmen",["Um zu sehen","Um zu schmecken","Um Töne, Sprache und Geräusche wahrzunehmen","Um zu riechen"],"Musik, Stimmen, Verkehr = Gehörsinn.","Ohr → Gehirn."),
        fib("si25","2","Die Netzhaut im Auge wandelt ___ in Nervenreize um. 👁️","The retina in the eye converts ___ into nerve signals.","La rétine de l'œil convertit ___ en signaux nerveux.","La retina nell'occhio converte ___ in segnali nervosi.","Licht","Licht → Netzhaut → Gehirn.","Das Bild entsteht im Gehirn."),
        mc("si26","2","Was ist das Trommelfell? 👂","What is the eardrum?","Qu'est-ce que le tympan ?","Che cos'è il timpano?","Eine dünne Membran im Ohr, die Schall aufnimmt",["Ein Knochen","Eine dünne Membran im Ohr, die Schall aufnimmt","Ein Muskel","Ein Nerv"],"Schallwellen lassen es vibrieren.","Trommelfell = Membran im Ohr."),
        fib("si27","2","Bei einer Erkältung riecht man oft ___ gut. 🤧","During a cold, one often cannot smell ___ well.","Lors d'un rhume, on ne sent souvent pas ___ bien.","Durante un raffreddore, spesso non si sente ___ bene.","nicht","Nase verstopft → schlechtes Riechen.","Erkältung blockiert Geruchssinn."),
        mc("si28","2","Was ist Tiefenwahrnehmung (räumliches Sehen)? 👁️","What is depth perception?","Qu'est-ce que la profondeur de champ dans la vision ?","Che cos'è la percezione della profondità?","Die Fähigkeit, Abstände einzuschätzen",["Die Fähigkeit, Farben zu sehen","Die Fähigkeit, Abstände einzuschätzen","Die Fähigkeit zu träumen","Die Fähigkeit zu lesen"],"Zwei Augen helfen beim Abschätzen von Entfernungen.","Binokulares Sehen."),
        fib("si29","2","Das Gehirn verarbeitet alle Informationen von unseren ___. 🧠","The brain processes all information from our ___.","Le cerveau traite toutes les informations de nos ___.","Il cervello elabora tutte le informazioni dai nostri ___.","Sinnesorganen","Sinne → Nerven → Gehirn.","Das Gehirn ist die Schaltzentrale."),
        mc("si30","2","Was sind Rezeptoren? 🔬","What are receptors?","Que sont les récepteurs ?","Cosa sono i recettori?","Zellen, die Sinnesreize aufnehmen und weiterleiten",["Muskeln","Zellen, die Sinnesreize aufnehmen und weiterleiten","Knochen","Blutgefässe"],"Fotorezeptoren im Auge, Tastrezeptoren in der Haut.","Rezeptor = Empfänger."),
        fib("si31","2","Der Gleichgewichtssinn liegt im ___ des Ohres. 👂","The sense of balance is located in the ___ of the ear.","Le sens de l'équilibre se trouve dans le ___ de l'oreille.","Il senso dell'equilibrio si trova nel ___ dell'orecchio.","Innenohr","Balance = Innenohr (Bogengänge).","Schwindel bei Drehung = Innenohr."),
        mc("si32","2","Warum können wir im Dunkeln nicht sehen, aber hören? 🌑","Why can't we see in the dark but can still hear?","Pourquoi ne voyons-nous pas dans le noir mais pouvons-nous entendre ?","Perché non vediamo al buio ma possiamo sentire?","Sehen braucht Licht, Hören braucht Schallwellen",["Hören ist stärker","Sehen braucht Licht, Hören braucht Schallwellen","Im Dunkeln hört man besser","Augen schlafen nachts"],"Licht ist nötig für den Sehsinn.","Schallwellen kommen auch im Dunkeln an."),
        fib("si33","2","Schmerz ist eine wichtige ___ des Tastsinns, die uns vor Verletzungen warnt.","Pain is an important ___ of the sense of touch warning us of injuries.","La douleur est un ___ important du toucher nous avertissant des blessures.","Il dolore è un ___ importante del tatto che ci avverte delle lesioni.","Schutzfunktion","Schmerz = Warnsignal.","Ohne Schmerz würde man sich verletzen."),
        mc("si34","2","Was geschieht, wenn der Sehnerv beschädigt ist? 👁️","What happens if the optic nerve is damaged?","Que se passe-t-il si le nerf optique est endommagé ?","Cosa succede se il nervo ottico è danneggiato?","Man kann nicht mehr sehen",["Man hört besser","Man kann nicht mehr sehen","Man verliert den Tastsinn","Man riecht schärfer"],"Sehnerv verbindet Auge mit Gehirn.","Nerv = Leitung zum Gehirn."),
        fib("si35","2","Wenn man eine Zitrone sieht, läuft einem der ___ im Mund zusammen. 🍋","When you see a lemon, ___ runs together in your mouth.","Quand on voit un citron, la ___ nous vient à la bouche.","Quando si vede un limone, la ___ si accumula in bocca.","Speichel","Das Gehirn reagiert auf den Sehreiz.","Speichelproduktion beim Anblick von Essen."),
        mc("si36","2","Warum haben die meisten Tiere zwei Augen? 👁️","Why do most animals have two eyes?","Pourquoi la plupart des animaux ont-ils deux yeux ?","Perché la maggior parte degli animali ha due occhi?","Für räumliches Sehen (Tiefenschärfe)",["Für mehr Sehfläche","Für räumliches Sehen (Tiefenschärfe)","Weil es symmetrisch ist","Für besseres Nachtsehen"],"Zwei Augen → 3D-Sehen.","Tiefe einschätzen."),
        # d3 ×14
        fib("si37","3","Die Pupille verkleinert sich bei ___ Licht, um das Auge zu schützen. 👁️","The pupil contracts in ___ light to protect the eye.","La pupille se rétrécit en lumière ___ pour protéger l'œil.","La pupilla si restringe in luce ___ per proteggere l'occhio.","hellem","Dunkle Pupille = wenig Licht.","Helles Licht → Pupille klein."),
        mc("si38","3","Was beschreibt Synästhesie? 🎨","What describes synesthesia?","Que décrit la synesthésie ?","Cosa descrive la sinestesia?","Wenn ein Sinn einen anderen auslöst (z.B. Töne als Farben sehen)",["Wenn alle Sinne versagen","Wenn ein Sinn einen anderen auslöst (z.B. Töne als Farben sehen)","Wenn man zwei Augen hat","Wenn Riechen und Schmecken sich verbinden"],"Einige Menschen sehen Musik als Farben.","Synästhesie = Sinnesvermischung."),
        fib("si39","3","Das menschliche Ohr kann Frequenzen zwischen etwa 20 und ___ Hz wahrnehmen.","The human ear can perceive frequencies between about 20 and ___ Hz.","L'oreille humaine peut percevoir des fréquences entre environ 20 et ___ Hz.","L'orecchio umano può percepire frequenze tra circa 20 e ___ Hz.","20000","Ultraschall liegt über 20000 Hz.","Hz = Schwingungen/Sekunde."),
        mc("si40","3","Was ist der Unterschied zwischen Stäbchen und Zapfen im Auge? 👁️","What is the difference between rods and cones in the eye?","Quelle est la différence entre bâtonnets et cônes dans l'œil ?","Qual è la differenza tra bastoncelli e coni nell'occhio?","Stäbchen: Schwarz/Weiss im Dunkeln. Zapfen: Farben im Tageslicht.",["Stäbchen sehen Farben, Zapfen Schwarz-Weiss","Stäbchen: Schwarz/Weiss im Dunkeln. Zapfen: Farben im Tageslicht.","Beide gleich","Zapfen für Dunkel"],"Katzen haben viele Stäbchen → gut im Dunkeln.","Zapfen = Farben sehen."),
        fib("si41","3","Das Innenohr enthält die ___ (Cochlea), die Schall in Nervenreize umwandelt.","The inner ear contains the ___ (cochlea), which converts sound into nerve signals.","L'oreille interne contient la ___ (cochlée), qui convertit le son en signaux nerveux.","L'orecchio interno contiene la ___ (coclea), che converte il suono in segnali nervosi.","Gehörschnecke","Gehörschnecke = Cochlea.","Schall → Cochlea → Hörnerv."),
        mc("si42","3","Was ist olfaktorische Adaptation? 👃","What is olfactory adaptation?","Qu'est-ce que l'adaptation olfactive ?","Che cos'è l'adattamento olfattivo?","Man gewöhnt sich an einen Geruch und nimmt ihn kaum mehr wahr",["Man riecht schärfer","Man verliert den Geruchssinn","Man gewöhnt sich an einen Geruch und nimmt ihn kaum mehr wahr","Man entwickelt neue Rezeptoren"],"Im Zimmer merkt man einen Geruch bald nicht mehr.","Gewöhnung an Reize."),
        fib("si43","3","Sinnesadaptation bedeutet, dass ein Sinn nach längerem Reiz ___ wird. 🧠","Sensory adaptation means a sense becomes ___ after prolonged stimulation.","L'adaptation sensorielle signifie qu'un sens devient ___ après stimulation prolongée.","L'adattamento sensoriale significa che un senso diventa ___ dopo stimolazione prolungata.","weniger empfindlich","Auge gewöhnt sich an Dunkelheit.","Reize werden ignoriert."),
        mc("si44","3","Was ist das Zwei-Punkt-Diskriminierungsvermögen? 🖐️","What is two-point discrimination?","Qu'est-ce que la discrimination entre deux points ?","Che cos'è la discriminazione a due punti?","Die Fähigkeit, zwei nahe Berührungspunkte zu unterscheiden",["Das Fühlen von Wärme","Die Fähigkeit, zwei nahe Berührungspunkte zu unterscheiden","Das Erkennen von Farben","Das Riechen von Gerüchen"],"Fingerkuppen = sehr feine Unterscheidung.","Mehr Rezeptoren = bessere Diskriminierung."),
        fib("si45","3","Der ___ Kortex im Gehirn verarbeitet Informationen vom Tastsinn. 🧠","The ___ cortex in the brain processes touch information.","Le cortex ___ du cerveau traite les informations du toucher.","La corteccia ___ nel cervello elabora le informazioni del tatto.","somatosensorische","Somatosensorisch = Körpergefühl.","Gehirnregion für Körperwahrnehmung."),
        mc("si46","3","Was ist Echolokation? 🦇","What is echolocation?","Qu'est-ce que l'écholocation ?","Che cos'è l'ecolocazione?","Navigation durch ausgesendete und zurückgeworfene Schallwellen",["Sehen im Dunkeln","Navigation durch ausgesendete und zurückgeworfene Schallwellen","Riechen aus grosser Entfernung","Schmecken ohne Zunge"],"Fledermäuse und Delfine nutzen Echolokation.","Schall senden, Echo empfangen."),
        fib("si47","3","Das Gehirn ergänzt Sinneseindrücke: Wenn wenig Information vorhanden ist, ___ das Gehirn. 🧠","The brain completes sensory input: when little information is present, the brain ___.","Le cerveau complète les impressions : quand peu d'information est disponible, le cerveau ___.","Il cervello completa le impressioni: quando ci sono poche informazioni, il cervello ___.","ergänzt/vervollständigt","Gehirn füllt Lücken.","Mustererkennung."),
        mc("si48","3","Was ist der Unterschied zwischen Kurz- und Weitsichtigkeit? 👓","What is the difference between near- and farsightedness?","Quelle est la différence entre myopie et hypermétropie ?","Qual è la differenza tra miopia e ipermetropia?","Kurzsichtig: ferne Objekte unscharf; Weitsichtig: nahe Objekte unscharf.",["Beide gleich","Kurzsichtig: ferne Objekte unscharf; Weitsichtig: nahe Objekte unscharf.","Kurzsichtig: keine Farben","Kurzsichtig ist gefährlicher"],"Brille korrigiert beide.","Linse zu stark/schwach."),
        fib("si49","3","Die Stelle im Auge mit der höchsten Sehschärfe heisst ___. 👁️","The point in the eye with the highest visual acuity is called ___.","La zone de l'œil avec la plus haute acuité visuelle s'appelle ___.","Il punto dell'occhio con la maggiore acuità visiva si chiama ___.","Fovea","Fovea = Zentrum der Netzhaut.","Höchste Zapfendichte."),
        mc("si50","3","Was ist Propriozeption? 🧠","What is proprioception?","Qu'est-ce que la proprioception ?","Che cos'è la propriocezione?","Wahrnehmung der eigenen Körperposition ohne Sehen",["Das Riechen","Wahrnehmung der eigenen Körperposition ohne Sehen","Farbsehen","Hören von Musik"],"Auch mit geschlossenen Augen weisst du, wo deine Arme sind.","Propriozeption = Körpergefühl."),
    ]
    return "\n".join(lines)

# ─── SINNE GRADE 2 (si11b–si50b) ─────────────────────────────────────────────
def exs_si_g2():
    lines = [
        mc("si11b","1","Welches Organ ist für den Tastsinn verantwortlich? ✋","Which organ is responsible for the sense of touch?","Quel organe est responsable du toucher ?","Quale organo è responsabile del tatto?","Haut",["Ohr","Nase","Haut","Auge"],"Die Haut bedeckt den ganzen Körper.","Tastrezeptoren sind in der Haut."),
        fib("si12b","1","Wir schmecken mit der ___. 👅","We taste with our ___.","Nous goûtons avec notre ___.","Assaggiamo con la ___.","Zunge","Geschmacksrezeptoren auf der Zunge.","Süss, sauer, salzig, bitter."),
        mc("si13b","1","Wie viele Grundgeschmäcke kann die Zunge unterscheiden? 👅","How many basic tastes can the tongue distinguish?","Combien de goûts de base la langue peut-elle distinguer ?","Quanti sapori di base può distinguere la lingua?","4 (klassisch: süss, sauer, salzig, bitter)",["2","3","4 (klassisch: süss, sauer, salzig, bitter)","6"],"Plus Umami = 5 gesamt.","Vier klassische Grundgeschmäcke."),
        fib("si14b","1","Wenn es laut ist, können wir uns ___ konzentrieren. 👂","When it is loud, we can ___ concentrate.","Quand c'est bruyant, on peut ___ se concentrer.","Quando è rumoroso, possiamo concentrarci ___.","schlechter","Lärm stört den Gehörsinn.","Zu viele Geräusche = weniger Fokus."),
        mc("si15b","1","Womit nehmen wir Gerüche wahr? 👃","What do we use to perceive smells?","Avec quoi percevons-nous les odeurs ?","Con cosa percepiamo gli odori?","Nase",["Mund","Nase","Haut","Augen"],"Riechzellen sitzen in der Nase.","Riechen = Nase."),
        fib("si16b","1","Das Gehirn ist das Zentrum, das alle ___ verarbeitet. 🧠","The brain is the centre that processes all ___.","Le cerveau est le centre qui traite tous les ___.","Il cervello è il centro che elabora tutti i ___.","Sinneseindrücke","Sinne → Nerven → Gehirn.","Das Gehirn interpretiert alles."),
        mc("si17b","1","Was kannst du mit dem Tastsinn erkennen? ✋","What can you recognize with the sense of touch?","Que peux-tu reconnaître avec le toucher ?","Cosa puoi riconoscere con il tatto?","Rau, glatt, warm, kalt",["Farben","Rau, glatt, warm, kalt","Töne","Gerüche"],"Haut fühlt Oberflächen und Temperatur.","Tast-Sinn erkennt viele Eigenschaften."),
        fib("si18b","1","Wenn Licht in unsere Augen fällt, leitet der Sehnerv Signale ans ___ weiter. 🧠","When light enters our eyes, the optic nerve sends signals to the ___.","Quand la lumière entre dans nos yeux, le nerf optique envoie des signaux au ___.","Quando la luce entra nei nostri occhi, il nervo ottico invia segnali al ___.","Gehirn","Auge → Sehnerv → Gehirn.","Das Gehirn verarbeitet das Bild."),
        mc("si19b","1","Welcher Sinn hilft uns, Musik zu hören? 🎵","Which sense helps us hear music?","Quel sens nous aide à entendre de la musique ?","Quale senso ci aiuta ad ascoltare la musica?","Gehörsinn",["Sehsinn","Gehörsinn","Tastsinn","Geruchssinn"],"Ohren nehmen Töne wahr.","Gehörsinn = Ohr."),
        fib("si20b","1","Brillen korrigieren Fehler des ___sinns. 👓","Glasses correct defects of ___ vision.","Les lunettes corrigent les défauts de la ___.","Gli occhiali correggono i difetti della ___.","Seh","Kurz- oder Weitsichtigkeit.","Brille hilft beim Sehen."),
        mc("si21b","1","Was ist eine Sinnesüberlastung? 🌊","What is sensory overload?","Qu'est-ce que la surcharge sensorielle ?","Che cos'è il sovraccarico sensoriale?","Wenn zu viele Sinnesreize gleichzeitig auf das Gehirn einwirken",["Wenn man schläft","Wenn zu viele Sinnesreize gleichzeitig auf das Gehirn einwirken","Wenn alle Sinne perfekt funktionieren","Wenn man im Dunkeln sitzt"],"Zu viel Lärm + grelles Licht = Überlastung.","Zu viel Information."),
        # d2 ×15
        mc("si22b","2","Was ist der Gleichgewichtssinn und wo sitzt er? 🌀","What is the sense of balance and where is it located?","Qu'est-ce que le sens de l'équilibre et où est-il situé ?","Che cos'è il senso dell'equilibrio e dove si trova?","Im Innenohr; er hilft uns, das Gleichgewicht zu halten",["Im Auge","Im Innenohr; er hilft uns, das Gleichgewicht zu halten","In der Nase","Im Magen"],"Innenohr mit Bogengängen.","Gleichgewicht = Innenohr."),
        fib("si23b","2","Ein Mensch ohne Geruchssinn (Anosmie) kann Essen oft nicht gut ___.","A person without smell (anosmia) often cannot ___ food well.","Une personne sans odorat (anosmie) ne peut souvent pas bien ___ la nourriture.","Una persona senza olfatto (anosmia) spesso non riesce a ___ bene il cibo.","schmecken","Riechen und Schmecken hängen zusammen.","Anosmie = kein Geruchssinn."),
        mc("si24b","2","Was ist ein blinder Fleck im Auge? 👁️","What is a blind spot in the eye?","Qu'est-ce que le point aveugle dans l'œil ?","Che cos'è il punto cieco nell'occhio?","Die Stelle, wo der Sehnerv ansetzt – keine Rezeptoren",["Ein schwarzer Fleck","Die Stelle, wo der Sehnerv ansetzt – keine Rezeptoren","Die Netzhaut","Die Pupille"],"Dort kann man nichts sehen.","Sehnerv-Eintrittstelle."),
        fib("si25b","2","Das Innenohr enthält die Cochlea und die drei ___-Bogengänge für das Gleichgewicht. 👂","The inner ear contains the cochlea and three ___ semicircular canals for balance.","L'oreille interne contient la cochlée et trois canaux semi-circulaires ___.","L'orecchio interno contiene la coclea e tre canali semicircolari ___ per l'equilibrio.","(Halb)kreisförmigen","Drei Bogengänge für 3 Raumachsen.","Gleichgewichtssinn."),
        mc("si26b","2","Was passiert mit den Sinnen im Alter? 👴","What happens to the senses with age?","Que se passe-t-il avec les sens en vieillissant ?","Cosa succede ai sensi con l'età?","Sie werden oft schwächer (Hören, Sehen)",["Sie werden stärker","Sie verschwinden ganz","Sie werden oft schwächer (Hören, Sehen)","Sie bleiben gleich"],"Alte Menschen brauchen oft Brillen und Hörgeräte.","Sinne schwächen mit dem Alter."),
        fib("si27b","2","Blinde Menschen nutzen oft verstärkt den ___ und den Gehörsinn. 🦯","Blind people often use ___ and hearing more strongly.","Les personnes aveugles utilisent souvent davantage le ___ et l'ouïe.","Le persone cieche usano spesso di più il ___ e l'udito.","Tastsinn","Braille-Schrift = Tastsinn.","Kompensation anderer Sinne."),
        mc("si28b","2","Was ist ein Sinnesorgan? 🔬","What is a sensory organ?","Qu'est-ce qu'un organe sensoriel ?","Che cos'è un organo di senso?","Ein spezielles Organ, das bestimmte Reize aufnimmt",["Ein Knochen","Ein spezielles Organ, das bestimmte Reize aufnimmt","Ein Muskel","Ein Blutgefäss"],"Auge, Ohr, Nase, Zunge, Haut = Sinnesorgane.","Organe für Wahrnehmung."),
        fib("si29b","2","Das Auge ist von einem ___ Augapfel umgeben, der sich in alle Richtungen drehen kann. 👁️","The eye is surrounded by a ___ eyeball that can rotate in all directions.","L'œil est entouré d'un globe oculaire ___ qui peut tourner dans toutes les directions.","L'occhio è circondato da un bulbo oculare ___ che può ruotare in tutte le direzioni.","runden/kugelförmigen","Augapfel = Kugel.","Kann in alle Richtungen drehen."),
        mc("si30b","2","Was ist Schmerz? 🤕","What is pain?","Qu'est-ce que la douleur ?","Che cos'è il dolore?","Ein Warnsignal des Körpers bei Schädigung",["Eine Freude","Ein Warnsignal des Körpers bei Schädigung","Eine Emotion","Ein Geruch"],"Schmerz schützt uns.","Ohne Schmerz würde man sich nicht kümmern."),
        fib("si31b","2","Die Rezeptoren in der Nase nehmen ___ Moleküle wahr. 👃","The receptors in the nose detect ___ molecules.","Les récepteurs dans le nez détectent les molécules ___.","I recettori nel naso rilevano le molecole ___.","Duft/Geruchs","Geruchsmoleküle binden an Rezeptoren.","Nase = chemischer Sensor."),
        mc("si32b","2","Was ist räumliches Wahrnehmen (3D-Sehen)? 👁️","What is spatial perception (3D vision)?","Qu'est-ce que la perception spatiale (vision 3D) ?","Che cos'è la percezione spaziale (visione 3D)?","Die Fähigkeit, Objekte im dreidimensionalen Raum wahrzunehmen",["Das Sehen von Farben","Die Fähigkeit, Objekte im dreidimensionalen Raum wahrzunehmen","Das Hören von Tönen","Das Riechen"],"Zwei Augen → 3D.","Tiefen einschätzen."),
        fib("si33b","2","Beim Kauen und Riechen zusammen nehmen wir ___ stärker wahr. 🍕","When chewing and smelling together, we perceive ___ more strongly.","En mâchant et en sentant ensemble, on perçoit ___ plus fort.","Masticando e annusando insieme, percepiamo ___ più forte.","Aroma/Geschmack","Zusammenspiel Nase und Zunge.","Aroma = Geruch + Geschmack."),
        mc("si34b","2","Warum reagieren wir sofort auf laute Geräusche? 👂","Why do we react immediately to loud sounds?","Pourquoi réagissons-nous immédiatement aux sons forts ?","Perché reagiamo immediatamente ai suoni forti?","Reflexantwort zum Schutz",["Weil wir sie mögen","Reflexantwort zum Schutz","Weil wir überrascht sind","Weil wir schlafen"],"Schutzmechanismus.","Laut = mögliche Gefahr."),
        fib("si35b","2","Wenn wir etwas Unangenehmes riechen, nehmen wir den Geruch ___ wahr.","When we smell something unpleasant, we perceive the smell ___.","Quand on sent quelque chose de désagréable, on le perçoit ___.","Quando annusiamo qualcosa di sgradevole, percepiamo l'odore ___.","sofort/stark","Unangenehme Gerüche = Warnsignal.","Gefährliche Dinge oft schlecht riechend."),
        mc("si36b","2","Was ist Wahrnehmung? 🧠","What is perception?","Qu'est-ce que la perception ?","Che cos'è la percezione?","Die Verarbeitung von Sinneseindrücken durch das Gehirn",["Das Aufnehmen von Reizen allein","Die Verarbeitung von Sinneseindrücken durch das Gehirn","Das Vergessen","Das Schlafen"],"Sehen → Wahrnehmen → Verstehen.","Gehirn interpretiert Eindrücke."),
        # d3 ×14
        fib("si37b","3","Das Weber-Fechner-Gesetz besagt, dass die Wahrnehmungsstärke ___ zum Reiz zunimmt.","The Weber-Fechner Law states that perceived intensity increases ___ with stimulus.","La loi de Weber-Fechner dit que l'intensité perçue augmente ___ avec le stimulus.","La legge di Weber-Fechner dice che l'intensità percepita aumenta ___ con lo stimolo.","logarithmisch","Doppelt so starker Reiz ≠ doppelt so stark wahrgenommen.","Logarithmisch = abnehmende Sensitivität."),
        mc("si38b","3","Was ist sensorische Integration? 🧠","What is sensory integration?","Qu'est-ce que l'intégration sensorielle ?","Che cos'è l'integrazione sensoriale?","Das Zusammenführen von Informationen aus verschiedenen Sinnen",["Das Trennen von Sinneseindrücken","Das Zusammenführen von Informationen aus verschiedenen Sinnen","Das Ausschalten eines Sinnes","Das Verstärken eines Sinnes"],"Gehirn kombiniert Seh- und Höreindrücke.","Integration = zusammenführen."),
        fib("si39b","3","Bei der Dunkeladaptation weitet sich die Pupille und die ___ des Auges werden empfindlicher. 👁️","In dark adaptation, the pupil widens and the ___ of the eye become more sensitive.","Lors de l'adaptation à l'obscurité, la pupille se dilate et les ___ de l'œil deviennent plus sensibles.","Nell'adattamento al buio, la pupilla si dilata e le ___ dell'occhio diventano più sensibili.","Stäbchen","Stäbchen sind lichtempfindlicher.","Stäbchen = Nachtsehen."),
        mc("si40b","3","Was ist der McGurk-Effekt? 🎭","What is the McGurk effect?","Qu'est-ce que l'effet McGurk ?","Che cos'è l'effetto McGurk?","Visuelle Lippeninformationen verändern den wahrgenommenen Laut",["Eine optische Täuschung","Visuelle Lippeninformationen verändern den wahrgenommenen Laut","Eine Hörbehinderung","Ein Geruchsphänomen"],"Man hört eine andere Silbe je nachdem was man sieht.","Sehen beeinflusst Hören."),
        fib("si41b","3","Sinneswahrnehmung kann durch Erwartungen und Erfahrungen ___ werden. 🧠","Sensory perception can be ___ by expectations and experiences.","La perception sensorielle peut être ___ par les attentes et les expériences.","La percezione sensoriale può essere ___ da aspettative ed esperienze.","beeinflusst","Optische Täuschungen täuschen.","Kontext ändert Wahrnehmung."),
        mc("si42b","3","Was ist Phantomschmerz? 🦿","What is phantom pain?","Qu'est-ce que la douleur fantôme ?","Che cos'è il dolore fantasma?","Schmerz in einem amputierten Körperteil",["Ein eingebildeter Schmerz ohne Ursache","Schmerz in einem amputierten Körperteil","Ein besonders starker Schmerz","Schmerz durch Kälte"],"Das Gehirn sendet weiter Schmerzsignale.","Amputierte berichten davon."),
        fib("si43b","3","Das olfaktorische System sendet Geruchssignale direkt an das ___, ohne den Thalamus zu passieren. 🧠","The olfactory system sends smell signals directly to the ___, bypassing the thalamus.","Le système olfactif envoie les signaux directement au ___, en contournant le thalamus.","Il sistema olfattivo invia segnali direttamente al ___, bypassando il talamo.","limbische System","Geruch → Emotionen direkt.","Daher löst Geruch starke Erinnerungen aus."),
        mc("si44b","3","Was ist die Theorie der Top-Down-Verarbeitung? 🧠","What is the theory of top-down processing?","Qu'est-ce que la théorie du traitement descendant ?","Che cos'è la teoria del processing top-down?","Das Gehirn nutzt Vorwissen, um Sinnesreize zu interpretieren",["Sinne liefern alle Informationen ohne Interpretation","Das Gehirn nutzt Vorwissen, um Sinnesreize zu interpretieren","Sinne arbeiten von unten nach oben","Das Gehirn ignoriert Sinnesreize"],"Kontext beeinflusst Wahrnehmung.","Erwartungen formen, was wir wahrnehmen."),
        fib("si45b","3","Die ___ ist die minimale Reizintensität, die gerade noch wahrgenommen werden kann.","The ___ is the minimum stimulus intensity that can just barely be perceived.","Le ___ est l'intensité minimale du stimulus qui peut tout juste être perçue.","Il ___ è l'intensità minima dello stimolo che può essere appena percepita.","Reizschwelle","Zu schwach = nicht wahrgenommen.","Unterhalb der Schwelle kein Bewusstsein."),
        mc("si46b","3","Was ist intermodale Wahrnehmung? 🎭","What is intermodal perception?","Qu'est-ce que la perception intermodale ?","Che cos'è la percezione intermodale?","Die Verknüpfung von Informationen aus verschiedenen Sinnen",["Nur ein Sinn ist aktiv","Die Verknüpfung von Informationen aus verschiedenen Sinnen","Alle Sinne ausgeschaltet","Ein Sinn besonders stark"],"Sehen + Hören + Fühlen zusammen.","Intermodal = zwischen den Sinnen."),
        fib("si47b","3","Die Stelle im Auge mit der höchsten Sehschärfe heisst ___. 👁️","The point in the eye with the highest visual acuity is called ___.","La zone de l'œil avec la plus haute acuité visuelle s'appelle ___.","Il punto dell'occhio con la maggiore acuità visiva si chiama ___.","Fovea","Fovea = Zentrum der Netzhaut.","Höchste Zapfendichte."),
        mc("si48b","3","Was ist eine taktile Halluzination? 🧠","What is a tactile hallucination?","Qu'est-ce qu'une hallucination tactile ?","Che cos'è un'allucinazione tattile?","Das Wahrnehmen einer Berührung ohne tatsächlichen Reiz",["Ein starker Schmerz","Das Wahrnehmen einer Berührung ohne tatsächlichen Reiz","Eine Berührung durch Wind","Eine Massagewirkung"],"Wie Phantomschmerz – Gehirn täuscht sich.","Keine äussere Ursache."),
        fib("si49b","3","Das Gehirn verbraucht trotz ~2% Körpergewicht etwa ___% der Körperenergie. 🧠","Despite being ~2% of body weight, the brain uses about ___% of body energy.","Malgré ~2% du poids corporel, le cerveau consomme environ ___% de l'énergie.","Nonostante il ~2% del peso, il cervello usa circa il ___% dell'energia corporea.","20","Gehirn = sehr energiehungrig.","Sinnesverarbeitung braucht viel Energie."),
        mc("si50b","3","Was ist synaptische Plastizität? 🧠","What is synaptic plasticity?","Qu'est-ce que la plasticité synaptique ?","Che cos'è la plasticità sinaptica?","Die Fähigkeit von Synapsen, ihre Verbindungsstärke zu verändern",["Die Anzahl der Synapsen","Die Fähigkeit von Synapsen, ihre Verbindungsstärke zu verändern","Die Farbe von Neuronen","Die Position von Synapsen"],"Lernen stärkt Synapsen.","Plastizität = Anpassung."),
    ]
    return "\n".join(lines)

# ─── WETTER-KLIMA GRADE 1 (wt11–wt50) ───────────────────────────────────────
def exs_wt_g1():
    lines = [
        mc("wt11","1","Was ist Nebel? 🌫️","What is fog?","Qu'est-ce que le brouillard ?","Che cos'è la nebbia?","Kleine Wassertröpfchen in der Luft",["Rauch","Kleine Wassertröpfchen in der Luft","Sand","Schnee"],"Nebel ist wie eine Wolke am Boden.","Man sieht schlecht im Nebel."),
        fib("wt12","1","Im ___ fällt Schnee. ❄️","In ___ it snows.","En ___ il neige.","In ___ nevica.","Winter","Wann ist es am kältesten?","Schnee fällt wenn es kalt ist."),
        mc("wt13","1","Was macht die Sonne im Sommer? ☀️","What does the sun do in summer?","Que fait le soleil en été ?","Cosa fa il sole in estate?","Sie scheint lange und warm",["Sie geht früh unter","Sie scheint lange und warm","Sie ist kalt","Sie erscheint selten"],"Im Sommer ist es warm.","Die Tage sind lang."),
        fib("wt14","1","Sonne + Regen = ___. 🌈","Sun + Rain = ___.","Soleil + Pluie = ___.","Sole + Pioggia = ___.","Regenbogen","Was siehst du nach dem Regen?","7 Farben am Himmel."),
        mc("wt15","1","Was friert bei -5 Grad Celsius? 🌡️","What freezes at -5 degrees Celsius?","Qu'est-ce qui gèle à -5 degrés Celsius ?","Cosa ghiaccia a -5 gradi Celsius?","Wasser",["Sand","Wasser","Luft","Stein"],"Wasser gefriert unter 0°C.","Eis = gefrorenes Wasser."),
        fib("wt16","1","Ein ___ misst die Windgeschwindigkeit. 💨","An ___ measures wind speed.","Un ___ mesure la vitesse du vent.","Un ___ misura la velocità del vento.","Anemometer","Wetterstationen messen den Wind.","Dreht sich im Wind."),
        mc("wt17","1","Wie nennt man Wolken, die tief sind und Regen bringen? 🌧️","What do you call low clouds that bring rain?","Comment appelle-t-on les nuages bas qui apportent de la pluie ?","Come si chiamano le nuvole basse che portano pioggia?","Regenwolken",["Schäfchenwolken","Federwolken","Regenwolken","Gewitterwolken"],"Graue Wolken bringen Regen.","Nimbus = Regenwolke."),
        fib("wt18","1","Im ___ wachsen Pflanzen und erwachen Tiere aus dem Winterschlaf. 🌸","In ___ plants grow and animals wake from hibernation.","Au ___ les plantes poussent et les animaux sortent d'hibernation.","In ___ le piante crescono e gli animali si svegliano.","Frühling","Frühling = nach dem Winter.","Alles erwacht."),
        mc("wt19","1","Was ist ein Gewitter? ⛈️","What is a thunderstorm?","Qu'est-ce qu'un orage ?","Che cos'è un temporale?","Ein Sturm mit Blitz, Donner und starkem Regen",["Leichter Regen","Ein Sturm mit Blitz, Donner und starkem Regen","Schneefall","Sonnenschein"],"Blitz und Donner gehören dazu.","Immer Vorsicht bei Gewitter!"),
        fib("wt20","1","Im ___ fallen die Blätter von den Bäumen. 🍂","In ___ leaves fall from trees.","En ___ les feuilles tombent des arbres.","In ___ le foglie cadono dagli alberi.","Herbst","Nach dem Sommer, vor dem Winter.","Blätter werden gelb und braun."),
        mc("wt21","1","Was misst ein Barometer? ⏱️","What does a barometer measure?","Que mesure un baromètre ?","Cosa misura un barometro?","Den Luftdruck",["Die Temperatur","Den Wind","Den Luftdruck","Den Regen"],"Hoher Luftdruck = meistens gutes Wetter.","Barometer = Luftdruckmesser."),
        # d2 ×15
        mc("wt22","2","Was ist der Wasserkreislauf? 🌊","What is the water cycle?","Qu'est-ce que le cycle de l'eau ?","Che cos'è il ciclo dell'acqua?","Verdunstung → Wolkenbildung → Regen → zurück",["Wasser fliesst ins Meer","Verdunstung → Wolkenbildung → Regen → zurück","Nur Regen","Schnee → Regen"],"Wasser verdunstet, steigt auf, bildet Wolken, fällt als Regen.","Ein Kreislauf ohne Ende."),
        fib("wt23","2","Wolken entstehen, wenn Wasserdampf ___ und zu Tröpfchen wird. ☁️","Clouds form when water vapour ___ and becomes droplets.","Les nuages se forment quand la vapeur d'eau ___ et devient des gouttelettes.","Le nuvole si formano quando il vapore acqueo ___ e diventa goccioline.","abkühlt","Kühle Luft kann weniger Dampf halten.","Kondensation."),
        mc("wt24","2","Was verursacht Wind? 💨","What causes wind?","Qu'est-ce qui cause le vent ?","Cosa causa il vento?","Unterschiede im Luftdruck",["Die Sonne allein","Unterschiede im Luftdruck","Der Mond","Das Wasser"],"Luft strömt von Hochdruck zu Tiefdruck.","Wind = Luftströmung."),
        fib("wt25","2","Schnee entsteht, wenn Wassertröpfchen in den Wolken bei ___ Temperaturen gefrieren. ❄️","Snow forms when water droplets in clouds freeze at ___ temperatures.","La neige se forme quand les gouttelettes d'eau dans les nuages gèlent à des températures ___.","La neve si forma quando le goccioline nelle nuvole gelano a temperature ___.","tiefen/kalten","Unter 0°C gefrieren Tröpfchen.","Schnee = gefrorene Wassertröpfchen."),
        mc("wt26","2","Was ist der Unterschied zwischen Wetter und Klima? 🌍","What is the difference between weather and climate?","Quelle est la différence entre météo et climat ?","Qual è la differenza tra tempo e clima?","Wetter: kurzfristig (heute). Klima: langfristiges Muster (Jahre)",["Es gibt keinen Unterschied","Wetter: kurzfristig (heute). Klima: langfristiges Muster (Jahre)","Klima ist nur im Winter","Wetter ist wärmer"],"Heute Regen = Wetter. Schweiz ist gemässigt = Klima.","Kurz vs. lang."),
        fib("wt27","2","Bei einem Regenbogen wird Licht durch ___ in seine Farben zerlegt. 🌈","In a rainbow, light is split into its colours by ___.","Dans un arc-en-ciel, la lumière est décomposée par ___.","In un arcobaleno, la luce viene divisa dai ___.","Wassertröpfchen","Brechung in Wassertröpfchen.","Prisma-Effekt in Regentropfen."),
        mc("wt28","2","Was ist ein Hoch (Hochdruckgebiet)? ⛅","What is a high-pressure system?","Qu'est-ce qu'un anticyclone ?","Che cos'è un anticiclone?","Ein Gebiet mit hohem Luftdruck, meistens gutes Wetter",["Schlechtwetter","Ein Gebiet mit hohem Luftdruck, meistens gutes Wetter","Starke Winde","Gewitter"],"H = Hochdruckgebiet = Sonne.","Hoch = schönes Wetter."),
        fib("wt29","2","Wind entsteht, weil Luft von ___ Luftdruck zu niedrigem fliesst. 💨","Wind forms because air flows from ___ pressure to low pressure.","Le vent se forme car l'air va de ___ pression à basse pression.","Il vento si forma perché l'aria scorre da ___ pressione a bassa pressione.","hohem","Luftdruckunterschied = Wind.","Luft strömt bergab."),
        mc("wt30","2","Was ist ein Klimadiagramm? 📊","What is a climate diagram?","Qu'est-ce qu'un diagramme climatique ?","Che cos'è un diagramma climatico?","Eine grafische Darstellung von Temperatur und Niederschlag über Monate",["Ein Foto des Wetters","Eine grafische Darstellung von Temperatur und Niederschlag über Monate","Eine Wetterkarte","Ein Thermometer"],"Balken = Regen, Kurve = Temperatur.","Monatliche Durchschnittswerte."),
        fib("wt31","2","Im Schweizer Alpenraum gibt es oft ___wind (warmer Fallwind). 🏔️","In the Swiss Alps there is often ___ wind (warm föhn wind).","Dans les Alpes suisses, il y a souvent le ___ (vent chaud de vallée).","Nelle Alpi svizzere c'è spesso il vento ___ (vento caldo discendente).","Föhn","Föhn = warmer Abwind aus den Alpen.","Klares Wetter, aber gefährlich für Brände."),
        mc("wt32","2","Warum ist die Schweiz ein gemässigtes Klima? 🌍","Why does Switzerland have a temperate climate?","Pourquoi la Suisse a-t-elle un climat tempéré ?","Perché la Svizzera ha un clima temperato?","Wegen ihrer Lage in Mitteleuropa und den Alpen",["Wegen des Meeres allein","Wegen ihrer Lage in Mitteleuropa und den Alpen","Weil es sehr kalt ist","Weil es keine Jahreszeiten gibt"],"Gemässigt = weder extrem heiss noch kalt.","Mitteleuropa-Klima."),
        fib("wt33","2","Hagel entsteht, wenn Wassertröpfchen in einer Gewitterwolke ___ gefrieren. ⛈️","Hail forms when water droplets in a thundercloud ___ freeze.","La grêle se forme quand des gouttelettes dans un nuage d'orage ___ gèlent.","La grandine si forma quando