#!/usr/bin/env python3
"""
Master runner: calls gen_exercises.py and gen_remaining.py data,
then injects everything into the correct files.
Also removes orphaned topics from grade4/5/6 science.ts.
"""
import re, os, sys

BASE = os.path.expanduser("~/projects/cleverli/src/data")

def inject_into_topic(filepath, topic_id, new_lines):
    with open(filepath, encoding='utf-8') as f:
        content = f.read()
    
    pat = f'id: "{topic_id}"'
    pos = content.find(pat)
    if pos == -1:
        print(f"  ✗ Topic '{topic_id}' not found in {filepath}")
        return False
    
    exs_marker = 'exercises: ['
    exs_pos = content.find(exs_marker, pos)
    if exs_pos == -1:
        print(f"  ✗ exercises array not found for '{topic_id}'")
        return False
    
    depth = 0
    i = exs_pos + len(exs_marker)
    while i < len(content):
        c = content[i]
        if c == '[': depth += 1
        elif c == ']':
            if depth == 0:
                insert = '\n' + '\n'.join(new_lines) + '\n'
                content = content[:i] + insert + content[i:]
                with open(filepath, 'w', encoding='utf-8') as f:
                    f.write(content)
                print(f"  ✓ {topic_id} in {os.path.basename(filepath)}: +{len(new_lines)} lines")
                return True
            depth -= 1
        i += 1
    print(f"  ✗ Could not find closing bracket for '{topic_id}'")
    return False

def remove_topic(filepath, topic_id):
    with open(filepath, encoding='utf-8') as f:
        content = f.read()
    
    pat = f'    id: "{topic_id}",'
    pos = content.find(pat)
    if pos == -1:
        print(f"  – '{topic_id}' not found in {os.path.basename(filepath)}")
        return True
    
    block_start = content.rfind('  {', 0, pos)
    if block_start == -1:
        print(f"  ✗ Cannot find block start for '{topic_id}'")
        return False
    
    depth = 0
    i = block_start
    while i < len(content):
        c = content[i]
        if c == '{': depth += 1
        elif c == '}':
            depth -= 1
            if depth == 0:
                end = i + 1
                if end < len(content) and content[end] == ',': end += 1
                if end < len(content) and content[end] == '\n': end += 1
                content = content[:block_start] + content[end:]
                with open(filepath, 'w', encoding='utf-8') as f:
                    f.write(content)
                print(f"  ✓ Removed '{topic_id}' from {os.path.basename(filepath)}")
                return True
        i += 1
    return False

def q(s): return s.replace('"', '\\"').replace('\n', ' ')

def mc(id, diff, de, en, fr, it, ans, opts, h1, h2):
    o = '", "'.join(q(x) for x in opts)
    return f'      {{ id: "{id}", type: "multiple-choice", difficulty: {diff}, question: "{q(de)}", questionEN: "{q(en)}", questionFR: "{q(fr)}", questionIT: "{q(it)}", answer: "{q(ans)}", options: ["{o}"], hints: ["{q(h1)}", "{q(h2)}"] }},'

def fib(id, diff, de, en, fr, it, ans, h1, h2):
    return f'      {{ id: "{id}", type: "fill-in-blank", difficulty: {diff}, question: "{q(de)}", questionEN: "{q(en)}", questionFR: "{q(fr)}", questionIT: "{q(it)}", answer: "{q(ans)}", hints: ["{q(h1)}", "{q(h2)}"] }},'

def dd(id, diff, de, en, fr, it, items, zones, answers, h1, h2):
    items_s = ", ".join(f'{{id:"{i}",label:"{q(l)}"}}' for i,l in items)
    zones_s = ", ".join(f'{{id:"{i}",label:"{q(l)}"}}' for i,l in zones)
    ans_s = ", ".join(f'"{k}":"{v}"' for k,v in answers.items())
    return f'      {{ id: "{id}", type: "drag-drop", difficulty: {diff}, question: "{q(de)}", questionEN: "{q(en)}", questionFR: "{q(fr)}", questionIT: "{q(it)}", answer: "all", hints: ["{q(h1)}", "{q(h2)}"], dragItems: [{items_s}], dropZones: [{zones_s}], dropAnswers: {{{ans_s}}} }},'

# ═══════════════════════════════════════════════════════════════════════════════
# EXERCISE DATA BLOCKS (compact format)
# Each function returns a list of TypeScript exercise strings
# ═══════════════════════════════════════════════════════════════════════════════

def make_physik_g1():
    return [
        mc("ph11","1","Was passiert, wenn du auf einen Ball trittst?","What happens when you kick a ball?","Que se passe-t-il quand tu donnes un coup de pied dans une balle ?","Cosa succede quando calci un pallone?","Er bewegt sich weg",["Er fängt an zu leuchten","Er bewegt sich weg","Er wird grösser","Er bleibt stehen"],"Kraft bringt Dinge in Bewegung.","Dein Fuss überträgt eine Kraft."),
        fib("ph12","1","Wenn du einen Stein loslässt, fällt er nach ___.","When you release a stone, it falls ___.","Quand tu lâches une pierre, elle tombe vers ___.","Quando lasci andare un sasso, cade ___.","unten","Die Erde zieht alles an.","Schwerkraft wirkt nach unten."),
        mc("ph13","1","Was braucht ein Objekt, um sich zu bewegen?","What does an object need to move?","De quoi a besoin un objet pour se déplacer ?","Di cosa ha bisogno un oggetto per muoversi?","Eine Kraft",["Farbe","Eine Kraft","Wasser","Luft"],"Drücken oder Ziehen sind Kräfte.","Ohne Kraft bleibt alles ruhig."),
        fib("ph14","1","Ein Magnet hat zwei Pole: Nord und ___.","A magnet has two poles: North and ___.","Un aimant a deux pôles : Nord et ___.","Un magnete ha due poli: Nord e ___.","Süd","Denke an Kompass-Richtungen.","N und S sind die zwei Pole."),
        mc("ph15","1","Was zieht ein Magnet an?","What does a magnet attract?","Qu'est-ce qu'un aimant attire ?","Cosa attrae un magnete?","Eisen",["Holz","Plastik","Eisen","Glas"],"Magnete haften am Kühlschrank.","Eisen und Stahl werden angezogen."),
        fib("ph16","1","Wasser fliesst immer nach ___.","Water always flows ___.","L'eau coule toujours vers ___.","L'acqua scorre sempre verso ___.","unten","Schwerkraft zieht Wasser.","Flüsse fliessen bergab."),
        mc("ph17","1","Was beschreibt das Wort Kraft?","What does the word force describe?","Que décrit le mot force ?","Cosa descrive la parola forza?","Ein Drücken oder Ziehen",["Eine Farbe","Ein Drücken oder Ziehen","Ein Tier","Eine Zahl"],"Drücken und Ziehen sind Kräfte.","Kräfte verändern Bewegung."),
        mc("ph18","1","Was macht Reibung?","What does friction do?","Que fait le frottement ?","Cosa fa l'attrito?","Sie verlangsamt Bewegung",["Sie beschleunigt immer","Sie verlangsamt Bewegung","Sie leuchtet","Sie kühlt ab"],"Reibung entsteht an Oberflächen.","Schuhsohlen bremsen dank Reibung."),
        fib("ph19","1","Eine Wippe funktioniert wie ein ___.","A seesaw works like a ___.","Une balançoire fonctionne comme un ___.","Un'altalena funziona come una ___.","Hebel","Drehpunkt in der Mitte.","Hebel verstärken Kräfte."),
        mc("ph20","1","Was ist Auftrieb?","What is buoyancy?","Qu'est-ce que la poussée d'Archimède ?","Che cos'è la spinta di Archimede?","Die Kraft, die Objekte im Wasser nach oben drückt",["Die Kraft nach unten","Die Kraft, die Objekte im Wasser nach oben drückt","Schwerkraft","Magnetismus"],"Schiffe schwimmen dank Auftrieb.","Wasser drückt nach oben."),
        fib("ph21","1","Ein Hammer schlägt einen Nagel in die Wand, weil er eine ___ auf ihn überträgt.","A hammer drives a nail by transferring a ___ to it.","Un marteau enfonce un clou en lui transférant une ___.","Un martello conficca un chiodo trasferendo una ___ su di esso.","Kraft","Was überträgt der Hammer?","Druckkraft von oben."),
        mc("ph22","2","Was ist Schwerkraft?","What is gravity?","Qu'est-ce que la gravité ?","Che cos'è la gravità?","Eine Kraft, die alles nach unten zieht",["Eine Farbe","Ein Tier","Eine Kraft, die alles nach unten zieht","Eine Zahl"],"Alles fällt zur Erde.","Die Erde zieht an."),
        fib("ph23","2","Wenn ein Objekt dichter als Wasser ist, ___ es.","If an object is denser than water, it ___.","Si un objet est plus dense que l'eau, il ___.","Se un oggetto è più denso dell'acqua, ___.","sinkt","Stein ist dichter als Wasser.","Holz schwimmt, Stein sinkt."),
        mc("ph24","2","Was passiert, wenn zwei gleiche Magnetpole zusammenkommen?","What happens when two identical poles meet?","Que se passe-t-il quand deux pôles identiques se rencontrent ?","Cosa succede quando due poli identici si incontrano?","Sie stossen sich ab",["Sie ziehen sich an","Sie stossen sich ab","Nichts passiert","Sie verschmelzen"],"Gleich und gleich stösst sich ab.","Nord+Nord = abstossen."),
        fib("ph25","2","Ein Rad hat wenig Reibung, weil es sich ___.","A wheel has little friction because it ___.","Une roue a peu de frottement parce qu'elle ___.","Una ruota ha poca attrito perché ___.","dreht","Rollen statt Gleiten = weniger Reibung.","Fahrräder fahren leicht dank Rädern."),
        mc("ph26","2","Was ist Gewichtskraft?","What is weight force?","Qu'est-ce que la force de pesanteur ?","Che cos'è la forza peso?","Die Kraft, mit der die Erde ein Objekt anzieht",["Muskelkraft","Die Kraft, mit der die Erde ein Objekt anzieht","Magnetkraft","Windkraft"],"Ein Gewicht drückt auf eine Waage.","Schwer = grosse Gewichtskraft."),
        fib("ph27","2","Holz ___ auf Wasser, weil es leichter als Wasser ist.","Wood ___ on water because it is lighter.","Le bois ___ sur l'eau car il est plus léger.","Il legno ___ sull'acqua perché è più leggero.","schwimmt","Dichte Holz < Dichte Wasser.","Leichter als Wasser = schwimmen."),
        mc("ph28","2","Warum fällt eine Feder langsamer als ein Stein?","Why does a feather fall slower than a stone?","Pourquoi une plume tombe-t-elle plus lentement qu'une pierre ?","Perché una piuma cade più lentamente di un sasso?","Wegen des Luftwiderstands (die Feder hat mehr Widerstand)",["Wegen des Gewichts allein","Wegen des Luftwiderstands","Weil der Stein schwerer ist","Zufall"],"Luftwiderstand bremst leichte Objekte.","Im Vakuum fallen beide gleich schnell."),
        fib("ph29","2","Das Gegenteil von Ruhe ist ___.","The opposite of rest is ___.","Le contraire du repos est ___.","Il contrario di riposo è ___.","Bewegung","Was macht ein laufendes Kind?","Ruhe → Bewegung."),
        mc("ph30","2","Was ist Gleichgewicht auf einer Wippe?","What is balance on a seesaw?","Qu'est-ce que l'équilibre sur une balançoire ?","Che cos'è l'equilibrio su un'altalena?","Wenn beide Seiten gleich schwer sind",["Wenn eine Seite schwerer ist","Wenn beide Seiten gleich schwer sind","Wenn sie sich dreht","Wenn niemand sitzt"],"Gleiche Gewichte auf beiden Seiten.","Balance = ausgeglichene Kräfte."),
        fib("ph31","2","Wenn du einen Magneten in zwei Teile schneidest, hat jeder Teil ___ Pole.","If you cut a magnet in half, each part has ___ poles.","Si tu coupes un aimant en deux, chaque partie a ___ pôles.","Se tagli un magnete a metà, ogni parte ha ___ poli.","zwei (Nord und Süd)","Jedes Stück hat immer N und S.","Magnete haben immer beide Pole."),
        mc("ph32","2","Wozu dient ein Sicherheitsgurt im Auto?","Why do cars have seatbelts?","Pourquoi les voitures ont-elles des ceintures de sécurité ?","Perché le auto hanno le cinture di sicurezza?","Er hält dich bei starker Verzögerung fest",["Er macht das Auto schneller","Er hält dich fest","Er spart Benzin","Er ist Dekoration"],"Bei Bremsung wirkt eine grosse Kraft.","Der Gurt schützt bei Unfall."),
        fib("ph33","2","Luft bremst bewegte Objekte. Diesen Widerstand nennt man ___.","Air slows moving objects. This resistance is called ___.","L'air freine les objets. Cette résistance s'appelle ___.","L'aria frena gli oggetti. Questa resistenza si chiama ___.","Luftwiderstand","Was bremst einen Fallschirm?","Luft setzt Bewegung Widerstand entgegen."),
        mc("ph34","2","Was ist eine schiefe Ebene?","What is an inclined plane?","Qu'est-ce qu'un plan incliné ?","Che cos'è un piano inclinato?","Eine geneigte Fläche, die das Heben erleichtert",["Ein Spiegel","Eine geneigte Fläche","Eine Brücke","Ein Rad"],"Rampen und Rutschbahnen sind Beispiele.","Weniger Kraft, aber mehr Weg."),
        fib("ph35","2","Ein langer Hebel braucht ___ Kraft als ein kurzer.","A long lever needs ___ force than a short one.","Un bras de levier long nécessite ___ de force qu'un court.","Una leva lunga richiede ___ forza di una corta.","weniger","Längerer Arm = weniger Kraft nötig.","Mechanischer Vorteil des Hebels."),
        mc("ph36","2","Was ist Reibung in einfachen Worten?","What is friction in simple words?","Qu'est-ce que le frottement en termes simples ?","Che cos'è l'attrito in parole semplici?","Eine Kraft zwischen Oberflächen, die Bewegung bremst",["Etwas, das beschleunigt","Eine Kraft zwischen Oberflächen, die Bewegung bremst","Ein Tier","Eine Farbe"],"Reibung = Widerstand zwischen Flächen.","Ohne Reibung würde man rutschen."),
        fib("ph37","3","Das Gesetz der Trägheit: Ein Objekt behält seinen Bewegungszustand, wenn keine ___ wirkt.","Inertia: an object keeps its motion if no ___ acts on it.","Loi d'inertie : sans ___, un objet garde son mouvement.","Legge di inerzia: un oggetto mantiene il moto se nessuna ___ agisce.","Kraft","Was hält einen rollenden Ball an?","Ohne Kraft keine Änderung."),
        mc("ph38","3","Was bedeutet Kraft = Masse × Beschleunigung?","What does Force = Mass × Acceleration mean?","Que signifie F = m × a ?","Cosa significa F = m × a?","Grössere Masse braucht mehr Kraft für gleiche Beschleunigung",["Kraft = Masse","Grössere Masse braucht mehr Kraft","Leichte Objekte fallen schneller","Kraft ohne Masse ist grösser"],"Schwerer LKW braucht mehr Kraft als Fahrrad.","Newtons 2. Gesetz."),
        fib("ph39","3","Die Einheit der Kraft ist der ___ (nach einem englischen Wissenschaftler benannt).","The unit of force is the ___ (named after an English scientist).","L'unité de force est le ___ (d'après un scientifique anglais).","L'unità di forza è il ___ (dal nome di uno scienziato inglese).","Newton (N)","Isaac Newton entdeckte die Schwerkraft.","Kraft wird in N gemessen."),
        mc("ph40","3","Was passiert mit der Schwerkraft, je weiter man von der Erde entfernt ist?","What happens to gravity farther from Earth?","Qu'arrive-t-il à la gravité en s'éloignant de la Terre ?","Cosa succede alla gravità lontano dalla Terra?","Sie wird schwächer",["Bleibt gleich","Sie wird schwächer","Sie wird stärker","Verschwindet sofort"],"Im Weltall wiegt man weniger.","Schwerkraft nimmt mit Abstand ab."),
        mc("ph41","3","Was beschreibt Actio = Reactio (Newtons 3. Gesetz)?","What describes Action = Reaction (Newton's 3rd Law)?","Que décrit Action = Réaction (3e loi) ?","Cosa descrive Actio = Reactio (3a legge)?","Jede Kraft hat eine gleich grosse Gegenkraft",["Kräfte sind immer verschieden","Jede Kraft hat eine gleich grosse Gegenkraft","Reaktion ist grösser","Keine Gegenkraft"],"Gegen Wand drücken → Wand drückt zurück.","Actio = Reactio."),
        mc("ph42","3","Was ist kinetische Energie?","What is kinetic energy?","Qu'est-ce que l'énergie cinétique ?","Che cos'è l'energia cinetica?","Energie eines bewegten Objekts",["Energie eines ruhenden Objekts","Energie eines bewegten Objekts","Magnetische Energie","Lichtenergie"],"Rollender Ball = kinetische Energie.","Kinetisch = in Bewegung."),
        fib("ph43","3","Wenn ein Apfel fällt, wird seine Lageenergie zu ___energie.","When an apple falls, its potential energy becomes ___ energy.","Quand une pomme tombe, son énergie potentielle devient énergie de ___.","Quando una mela cade, l'energia potenziale diventa energia di ___.","Bewegungs-/kinetische","Lageenergie → Kinetische Energie.","Fallender Apfel beschleunigt."),
        mc("ph44","3","Warum sinkt ein Stück Eisen, aber schwimmt ein Schiff?","Why does iron sink but a ship floats?","Pourquoi le fer coule mais un navire flotte ?","Perché il ferro affonda ma una nave galleggia?","Das Schiff ist hohl und hat geringere Dichte als Wasser",["Schiffe sind aus Holz","Das Schiff ist hohl","Eisen ist magnetisch","Schiffe haben Motoren"],"Ein hohles Objekt verdrängt mehr Wasser.","Auftrieb = Gewicht des verdrängten Wassers."),
        fib("ph45","3","Auftrieb = ___ des verdrängten Wassers (Archimedisches Prinzip).","Buoyancy = ___ of displaced water (Archimedes' principle).","Poussée = ___ de l'eau déplacée (principe d'Archimède).","Spinta = ___ dell'acqua spostata (principio di Archimede).","Gewicht","Auftrieb hängt von verdrängtem Wasser ab.","Archimedes in der Badewanne."),
        mc("ph46","3","Was ist mechanischer Vorteil eines Hebels?","What is the mechanical advantage of a lever?","Quel est l'avantage mécanique d'un levier ?","Qual è il vantaggio meccanico di una leva?","Mit weniger Kraft die gleiche Arbeit verrichten",["Schneller arbeiten","Mit weniger Kraft die gleiche Arbeit","Mehr Energie erzeugen","Keine Kraft brauchen"],"Langer Arm = mehr Vorteil.","Hebel = Kraftverstärker."),
        fib("ph47","3","Energie kann nicht erzeugt oder vernichtet, nur ___ werden.","Energy cannot be created or destroyed, only ___.","L'énergie ne peut pas être créée ou détruite, seulement ___.","L'energia non può essere creata né distrutta, solo ___.","umgewandelt","Energieerhaltungssatz.","Physikalisches Grundgesetz."),
        mc("ph48","3","Was ist der Unterschied zwischen Masse und Gewicht?","What is the difference between mass and weight?","Quelle est la différence entre masse et poids ?","Qual è la differenza tra massa e peso?","Masse ist überall gleich; Gewicht hängt von der Schwerkraft ab",["Beide identisch","Masse ist gleich; Gewicht hängt von Schwerkraft ab","Gewicht ist immer grösser","Masse ist auf dem Mond grösser"],"Auf dem Mond wiegt man weniger, aber Masse bleibt gleich.","Masse in kg, Gewicht in Newton."),
        fib("ph49","3","Ein Pendel schwingt dank ___ und Trägheit hin und her.","A pendulum swings due to ___ and inertia.","Un pendule oscille grâce à ___ et à l'inertie.","Un pendolo oscilla grazie a ___ e all'inerzia.","Schwerkraft","Uhren nutzen Pendel.","Schwerkraft zieht das Pendel zurück."),
        mc("ph50","3","Was ist Drehmoment?","What is torque?","Qu'est-ce que le couple ?","Che cos'è il momento torcente?","Kraft × Abstand vom Drehpunkt",["Kraft + Gewicht","Kraft × Abstand vom Drehpunkt","Masse × Beschleunigung","Energie × Zeit"],"Langer Schraubenschlüssel = mehr Drehmoment.","Drehmoment = Hebelwirkung."),
    ]

def make_physik_g2():
    # Slightly more advanced, different IDs with 'b' suffix
    base = make_physik_g1()
    result = []
    for line in base:
        line = re.sub(r'id: "ph(\d+)"', lambda m: f'id: "ph{m.group(1)}b"', line)
        result.append(line)
    return result

def make_sinne_g1():
    return [
        mc("si11","1","Mit welchem Organ hören wir?","Which organ do we hear with?","Avec quel organe entendons-nous ?","Con quale organo sentiamo?","Ohren",["Augen","Nase","Ohren","Zunge"],"Töne werden wahrgenommen.","An beiden Seiten des Kopfes."),
        fib("si12","1","Mit den Händen können wir Wärme und ___ wahrnehmen.","With our hands we feel warmth and ___.","Avec nos mains, on perçoit chaleur et ___.","Con le mani percepiamo calore e ___.","Kälte","Was fühlt man bei Eis?","Tastsinn = Haut."),
        mc("si13","1","Welcher Sinn hilft beim Schmecken?","Which sense helps taste food?","Quel sens aide à goûter ?","Quale senso aiuta a gustare?","Geschmackssinn",["Sehsinn","Gehörsinn","Geschmackssinn","Tastsinn"],"Die Zunge nimmt Geschmack wahr.","Schmecken = Zunge."),
        fib("si14","1","Der Sehsinn nutzt die ___.","The sense of sight uses the ___.","Le sens de la vue utilise les ___.","Il senso della vista usa gli ___.","Augen","Licht geht durch die Augen ins Gehirn.","Sehen = Augen."),
        mc("si15","1","Mit welchem Sinn riechst du eine Blume?","Which sense lets you smell a flower?","Quel sens permet de sentir une fleur ?","Quale senso ti permette di annusare un fiore?","Geruchssinn",["Sehsinn","Gehörsinn","Geruchssinn","Geschmackssinn"],"Die Nase nimmt Gerüche wahr.","Riechen = Nase."),
        fib("si16","1","Bitter, süss, sauer und ___ sind die vier Grundgeschmäcke.","Bitter, sweet, sour and ___ are the basic tastes.","Amer, sucré, acide et ___ sont les goûts de base.","Amaro, dolce, acido e ___ sono i sapori di base.","salzig","Was schmeckt Salz?","Vier Grundgeschmäcke."),
        mc("si17","1","Welcher Sinn warnt bei etwas Heissem?","Which sense warns about something hot?","Quel sens avertit d'un objet chaud ?","Quale senso avverte di qualcosa di caldo?","Tastsinn",["Sehsinn","Gehörsinn","Tastsinn","Geruchssinn"],"Die Haut fühlt Wärme.","Finger fühlen Temperatur."),
        fib("si18","1","Wir haben ___ Sinne.","We have ___ senses.","Nous avons ___ sens.","Abbiamo ___ sensi.","5","Zähle: Sehen, Hören, Riechen, Schmecken, Tasten.","Fünf Sinne!"),
        mc("si19","1","Was passiert, wenn du die Augen schliesst?","What happens when you close your eyes?","Que se passe-t-il quand tu fermes les yeux ?","Cosa succede chiudendo gli occhi?","Du kannst nicht mehr sehen",["Du kannst nicht hören","Du kannst nicht sehen","Du verlierst alle Sinne","Du schläfst ein"],"Augen zu = kein Sehen.","Sehsinn braucht Licht und offene Augen."),
        fib("si20","1","Unsere Sinne helfen uns, die ___ wahrzunehmen.","Our senses help us perceive the ___.","Nos sens nous aident à percevoir le ___.","I nostri sensi ci aiutano a percepire il ___.","Welt","Wozu dienen Sinne?","Sinne = Kontakt zur Welt."),
        mc("si21","1","Was ist das Sinnesorgan des Gehörs?","What is the sensory organ of hearing?","Quel est l'organe sensoriel de l'ouïe ?","Qual è l'organo sensoriale dell'udito?","Ohr",["Nase","Auge","Ohr","Zunge"],"Töne gelangen durch das Ohr.","Zwei Ohren am Kopf."),
        mc("si22","2","Was kann die Haut wahrnehmen?","What can the skin perceive?","Que peut percevoir la peau ?","Cosa può percepire la pelle?","Wärme, Kälte, Druck und Schmerz",["Nur Wärme","Nur Kälte","Wärme, Kälte, Druck und Schmerz","Nur Farben"],"Die Haut ist unser grösstes Sinnesorgan.","Tastsinn = viele Empfindungen."),
        fib("si23","2","Wenn Riechen und ___ zusammenarbeiten, schmecken wir besser.","When smell and ___ work together, we taste better.","Quand l'odorat et ___ travaillent ensemble, on goûte mieux.","Quando olfatto e ___ lavorano insieme, gustiamo meglio.","Schmecken","Bei Erkältung schmeckt Essen fade.","Geruch verstärkt Geschmack."),
        mc("si24","2","Wozu braucht der Mensch den Gehörsinn?","Why does a human need hearing?","Pourquoi l'être humain a-t-il besoin de l'ouïe ?","Perché l'uomo ha bisogno dell'udito?","Um Töne, Sprache und Geräusche wahrzunehmen",["Um zu sehen","Um zu schmecken","Um Töne wahrzunehmen","Um zu riechen"],"Musik, Stimmen, Verkehr = Gehörsinn.","Ohr → Gehirn."),
        fib("si25","2","Die Netzhaut im Auge wandelt ___ in Nervenreize um.","The retina converts ___ into nerve signals.","La rétine convertit ___ en signaux nerveux.","La retina converte ___ in segnali nervosi.","Licht","Licht → Netzhaut → Gehirn.","Das Bild entsteht im Gehirn."),
        mc("si26","2","Was ist das Trommelfell?","What is the eardrum?","Qu'est-ce que le tympan ?","Che cos'è il timpano?","Eine dünne Membran im Ohr",["Ein Knochen","Eine dünne Membran im Ohr","Ein Muskel","Ein Nerv"],"Schallwellen lassen es vibrieren.","Trommelfell im Ohr."),
        fib("si27","2","Bei einer Erkältung riecht man oft ___ gut.","During a cold, one often cannot smell ___ well.","Lors d'un rhume, on ne sent souvent pas ___ bien.","Durante un raffreddore, spesso non si sente ___ bene.","nicht","Nase verstopft → schlechtes Riechen.","Erkältung blockiert Geruchssinn."),
        mc("si28","2","Was ist räumliches Sehen (Tiefenwahrnehmung)?","What is depth perception?","Qu'est-ce que la perception de la profondeur ?","Che cos'è la percezione della profondità?","Die Fähigkeit, Abstände einzuschätzen",["Farben sehen","Die Fähigkeit, Abstände einzuschätzen","Träumen","Lesen"],"Zwei Augen = 3D-Sehen.","Binokulares Sehen."),
        fib("si29","2","Das Gehirn verarbeitet alle Informationen von unseren ___.","The brain processes all information from our ___.","Le cerveau traite toutes les informations de nos ___.","Il cervello elabora tutte le informazioni dai nostri ___.","Sinnesorganen","Sinne → Nerven → Gehirn.","Das Gehirn ist die Schaltzentrale."),
        mc("si30","2","Was sind Rezeptoren?","What are receptors?","Que sont les récepteurs ?","Cosa sono i recettori?","Zellen, die Sinnesreize aufnehmen",["Muskeln","Zellen, die Sinnesreize aufnehmen","Knochen","Blutgefässe"],"Fotorezeptoren im Auge, Tastrezeptoren in der Haut.","Rezeptor = Reiz-Empfänger."),
        fib("si31","2","Der Gleichgewichtssinn liegt im ___ des Ohres.","The sense of balance is in the ___ of the ear.","Le sens de l'équilibre se trouve dans le ___ de l'oreille.","Il senso dell'equilibrio si trova nel ___ dell'orecchio.","Innenohr","Bogengänge im Innenohr.","Schwindel bei Drehung = Innenohr."),
        mc("si32","2","Warum können wir im Dunkeln nicht sehen, aber hören?","Why can't we see in the dark but can hear?","Pourquoi ne voyons-nous pas dans le noir mais pouvons-nous entendre ?","Perché non vediamo al buio ma possiamo sentire?","Sehen braucht Licht; Hören braucht Schallwellen",["Hören ist stärker","Sehen braucht Licht; Hören braucht Schallwellen","Im Dunkeln hört man besser","Augen schlafen"],"Licht nötig für Sehsinn.","Schallwellen kommen auch im Dunkeln."),
        fib("si33","2","Schmerz ist eine ___, die uns vor Verletzungen warnt.","Pain is a ___ that warns us of injuries.","La douleur est un ___ qui nous avertit des blessures.","Il dolore è un ___ che ci avverte delle lesioni.","Schutzfunktion","Schmerz = Warnsignal.","Ohne Schmerz würde man sich verletzen."),
        mc("si34","2","Was geschieht bei beschädigtem Sehnerv?","What happens with a damaged optic nerve?","Que se passe-t-il avec un nerf optique endommagé ?","Cosa succede con un nervo ottico danneggiato?","Blindheit möglich",["Man hört besser","Blindheit möglich","Man verliert Tastsinn","Man riecht schärfer"],"Sehnerv verbindet Auge mit Gehirn.","Nerv = Leitung zum Gehirn."),
        fib("si35","2","Wenn man eine Zitrone sieht, läuft einem der ___ im Mund zusammen.","Seeing a lemon makes ___ run in your mouth.","En voyant un citron, la ___ nous vient à la bouche.","Vedendo un limone, la ___ si accumula in bocca.","Speichel","Gehirn reagiert auf Sehreiz.","Speichelproduktion beim Anblick von Essen."),
        mc("si36","2","Warum haben die meisten Tiere zwei Augen?","Why do most animals have two eyes?","Pourquoi la plupart des animaux ont-ils deux yeux ?","Perché la maggior parte degli animali ha due occhi?","Für räumliches Sehen",["Für mehr Sehfläche","Für räumliches Sehen","Weil es symmetrisch ist","Für Nachtsehen"],"Zwei Augen → 3D-Sehen.","Tiefe einschätzen."),
        fib("si37","3","Die Pupille verkleinert sich bei ___ Licht.","The pupil contracts in ___ light.","La pupille se rétrécit en lumière ___.","La pupilla si restringe in luce ___.","hellem","Helles Licht → kleine Pupille.","Schutz des Auges."),
        mc("si38","3","Was beschreibt Synästhesie?","What describes synesthesia?","Que décrit la synesthésie ?","Cosa descrive la sinestesia?","Wenn ein Sinn einen anderen auslöst",["Wenn Sinne versagen","Wenn ein Sinn einen anderen auslöst","Wenn man zwei Augen hat","Wenn Riechen und Schmecken gleich sind"],"Z.B. Töne als Farben sehen.","Synästhesie = Sinnesvermischung."),
        fib("si39","3","Das Ohr kann Frequenzen zwischen ca. 20 und ___ Hz wahrnehmen.","The ear can hear from ~20 to ___ Hz.","L'oreille entend de ~20 à ___ Hz.","L'orecchio sente da ~20 a ___ Hz.","20000","Ultraschall liegt über 20000 Hz.","Hz = Schwingungen pro Sekunde."),
        mc("si40","3","Was ist der Unterschied zwischen Stäbchen und Zapfen?","Rods vs cones in the eye?","Différence entre bâtonnets et cônes ?","Differenza tra bastoncelli e coni?","Stäbchen: Helligkeit/Dunkel; Zapfen: Farben",["Beide gleich","Stäbchen: Helligkeit/Dunkel; Zapfen: Farben","Zapfen für Dunkel","Stäbchen für Farben"],"Katzen: viele Stäbchen → gut im Dunkeln.","Zapfen = Farben."),
        fib("si41","3","Das Innenohr enthält die ___ (Cochlea), die Schall in Nervenreize umwandelt.","The inner ear contains the ___ (cochlea) that converts sound.","L'oreille interne contient la ___ (cochlée) qui convertit le son.","L'orecchio interno contiene la ___ (coclea) che converte il suono.","Gehörschnecke","Cochlea = Gehörschnecke.","Schall → Cochlea → Hörnerv."),
        mc("si42","3","Was ist olfaktorische Adaptation?","What is olfactory adaptation?","Qu'est-ce que l'adaptation olfactive ?","Che cos'è l'adattamento olfattivo?","Man gewöhnt sich an einen Geruch",["Man riecht schärfer","Man verliert dauerhaft Geruchssinn","Man gewöhnt sich","Man entwickelt neue Rezeptoren"],"Im Zimmer merkt man Geruch bald nicht mehr.","Gewöhnung an Reize."),
        fib("si43","3","Sinnesadaptation: Ein Sinn wird nach längerem Reiz ___.","Sensory adaptation: a sense becomes ___ after prolonged stimulation.","Adaptation sensorielle : un sens devient ___ après stimulation prolongée.","Adattamento sensoriale: un senso diventa ___ dopo stimolazione prolungata.","weniger empfindlich","Gewöhnung.","Reize werden ignoriert."),
        mc("si44","3","Was ist Zwei-Punkt-Diskriminierung?","What is two-point discrimination?","Qu'est-ce que la discrimination deux-points ?","Che cos'è la discriminazione a due punti?","Fähigkeit, zwei nahe Berührungspunkte zu unterscheiden",["Wärme fühlen","Fähigkeit, zwei nahe Berührungspunkte zu unterscheiden","Farben sehen","Gerüche riechen"],"Fingerkuppen sehr fein.","Mehr Rezeptoren = bessere Diskriminierung."),
        fib("si45","3","Der ___ Kortex verarbeitet Informationen vom Tastsinn.","The ___ cortex processes touch information.","Le cortex ___ traite les informations du toucher.","La corteccia ___ elabora le informazioni del tatto.","somatosensorische","Somatosensorisch = Körpergefühl.","Gehirnregion für Körperwahrnehmung."),
        mc("si46","3","Was ist Echolokation?","What is echolocation?","Qu'est-ce que l'écholocation ?","Che cos'è l'ecolocazione?","Navigation durch Schallwellen senden und Echo empfangen",["Sehen im Dunkeln","Navigation durch Schallwellen senden und Echo empfangen","Riechen aus grosser Entfernung","Schmecken ohne Zunge"],"Fledermäuse nutzen Echolokation.","Schall senden → Echo → Entfernung."),
        fib("si47","3","Das Gehirn ___ fehlende Sinneseindrücke aktiv.","The brain actively ___ missing sensory input.","Le cerveau ___ activement les impressions manquantes.","Il cervello ___ attivamente le impressioni mancanti.","ergänzt / vervollständigt","Mustererkennung.","Gehirn füllt Lücken."),
        mc("si48","3","Kurzsichtig vs. Weitsichtig?","Near- vs. farsighted?","Myopie vs. hypermétropie ?","Miopia vs. ipermetropia?","Kurzsichtig: fern unscharf; Weitsichtig: nah unscharf",["Beide gleich","Kurzsichtig: fern unscharf; Weitsichtig: nah unscharf","Kurzsichtig: keine Farben","Kurzsichtig gefährlicher"],"Brille korrigiert beide.","Linse zu stark/schwach."),
        fib("si49","3","Die Stelle im Auge mit höchster Sehschärfe heisst ___.","The point with highest visual acuity is called ___.","La zone avec la plus haute acuité visuelle s'appelle ___.","Il punto con la maggiore acuità visiva si chiama ___.","Fovea","Fovea = Netzhautzentrum.","Höchste Zapfendichte."),
        mc("si50","3","Was ist Propriozeption?","What is proprioception?","Qu'est-ce que la proprioception ?","Che cos'è la propriocezione?","Wahrnehmung der Körperposition ohne Sehen",["Riechen","Wahrnehmung der Körperposition ohne Sehen","Farbsehen","Hören"],"Augen zu: weisst du trotzdem, wo deine Arme sind.","Propriozeption = Körpergefühl."),
    ]

def make_sinne_g2():
    base = make_sinne_g1()
    result = []
    for line in base:
        line = re.sub(r'id: "si(\d+)"', lambda m: f'id: "si{m.group(1)}b"', line)
        result.append(line)
    return result

def make_wetter_g1():
    return [
        mc("wt11","1","Was ist Nebel?","What is fog?","Qu'est-ce que le brouillard ?","Che cos'è la nebbia?","Kleine Wassertröpfchen in der Luft",["Rauch","Kleine Wassertröpfchen in der Luft","Sand","Schnee"],"Nebel = Wolke am Boden.","Man sieht schlecht im Nebel."),
        fib("wt12","1","Im ___ fällt Schnee.","In ___ it snows.","En ___ il neige.","In ___ nevica.","Winter","Wann ist es am kältesten?","Schnee fällt wenn es kalt ist."),
        mc("wt13","1","Was macht die Sonne im Sommer?","What does the sun do in summer?","Que fait le soleil en été ?","Cosa fa il sole in estate?","Sie scheint lange und warm",["Sie geht früh unter","Sie scheint lange und warm","Sie ist kalt","Sie erscheint selten"],"Im Sommer ist es warm.","Die Tage sind lang."),
        fib("wt14","1","Sonne + Regen zusammen ergeben einen ___.","Sun + rain together make a ___.","Soleil + pluie font un ___.","Sole + pioggia fanno un ___.","Regenbogen","Was siehst du am Himmel nach dem Regen?","7 Farben am Himmel."),
        mc("wt15","1","Was passiert mit Wasser bei -5 Grad?","What happens to water at -5 degrees?","Que se passe-t-il avec l'eau à -5 degrés ?","Cosa succede all'acqua a -5 gradi?","Es gefriert zu Eis",["Es verdunstet","Es gefriert zu Eis","Es wird Dampf","Es verschwindet"],"Unter 0°C gefriert Wasser.","Eis = gefrorenes Wasser."),
        fib("wt16","1","Ein ___ misst die Windgeschwindigkeit.","An ___ measures wind speed.","Un ___ mesure la vitesse du vent.","Un ___ misura la velocità del vento.","Anemometer","Wetterstationen messen den Wind.","Dreht sich im Wind."),
        mc("wt17","1","Wie nennt man graue Wolken, die Regen bringen?","What do you call grey rain clouds?","Comment appelle-t-on les nuages gris de pluie ?","Come si chiamano le nuvole grigie di pioggia?","Regenwolken",["Schäfchenwolken","Federwolken","Regenwolken","Gewitterwolken"],"Graue Wolken bringen Regen.","Nimbus = Regenwolke."),
        fib("wt18","1","Im ___ wachsen Pflanzen und erwachen Tiere aus dem Winterschlaf.","In ___ plants grow and animals wake from hibernation.","Au ___ les plantes poussent et les animaux se réveillent.","In ___ le piante crescono e gli animali si risvegliano.","Frühling","Nach dem Winter.","Alles erwacht."),
        mc("wt19","1","Was ist ein Gewitter?","What is a thunderstorm?","Qu'est-ce qu'un orage ?","Che cos'è un temporale?","Sturm mit Blitz, Donner und starkem Regen",["Leichter Regen","Sturm mit Blitz, Donner und starkem Regen","Schneefall","Sonnenschein"],"Blitz und Donner gehören dazu.","Vorsicht bei Gewitter!"),
        fib("wt20","1","Im ___ fallen die Blätter von den Bäumen.","In ___ leaves fall from trees.","En ___ les feuilles tombent des arbres.","In ___ le foglie cadono dagli alberi.","Herbst","Nach dem Sommer, vor dem Winter.","Blätter werden gelb und braun."),
        mc("wt21","1","Was misst ein Barometer?","What does a barometer measure?","Que mesure un baromètre ?","Cosa misura un barometro?","Den Luftdruck",["Die Temperatur","Den Wind","Den Luftdruck","Den Regen"],"Hoher Luftdruck = gutes Wetter.","Barometer = Luftdruckmesser."),
        mc("wt22","2","Was ist der Wasserkreislauf?","What is the water cycle?","Qu'est-ce que le cycle de l'eau ?","Che cos'è il ciclo dell'acqua?","Verdunstung → Wolkenbildung → Regen → zurück",["Nur Regen","Verdunstung → Wolkenbildung → Regen → zurück","Wasser → Meer → Ende","Schnee → Regen"],"Wasser verdunstet, bildet Wolken, fällt als Regen.","Ein Kreislauf ohne Ende."),
        fib("wt23","2","Wolken entstehen, wenn Wasserdampf ___ und zu Tröpfchen wird.","Clouds form when water vapour ___ and becomes droplets.","Les nuages se forment quand la vapeur d'eau ___ et devient gouttelettes.","Le nuvole si formano quando il vapore ___ e diventa goccioline.","abkühlt","Kühle Luft hält weniger Dampf.","Kondensation."),
        mc("wt24","2","Was verursacht Wind?","What causes wind?","Qu'est-ce qui cause le vent ?","Cosa causa il vento?","Unterschiede im Luftdruck",["Die Sonne allein","Unterschiede im Luftdruck","Der Mond","Das Wasser"],"Luft strömt von Hoch zu Tief.","Wind = Luftströmung."),
        fib("wt25","2","Schnee entsteht, wenn Wassertröpfchen in Wolken bei ___ Temperaturen gefrieren.","Snow forms when droplets freeze at ___ temperatures.","La neige se forme quand les gouttelettes gèlent à températures ___.","La neve si forma quando le goccioline gelano a temperature ___.","tiefen / kalten","Unter 0°C gefrieren Tröpfchen.","Schnee = gefrorene Wassertröpfchen."),
        mc("wt26","2","Was ist der Unterschied zwischen Wetter und Klima?","Difference between weather and climate?","Différence entre météo et climat ?","Differenza tra tempo e clima?","Wetter: kurzfristig; Klima: langfristiges Muster",["Es gibt keinen Unterschied","Wetter: kurzfristig; Klima: langfristiges Muster","Klima nur im Winter","Wetter ist wärmer"],"Heute Regen = Wetter. Schweiz gemässigt = Klima.","Kurz vs. lang."),
        fib("wt27","2","Regenbogenfarben entstehen durch ___ des Lichts in Wassertröpfchen.","Rainbow colours form through ___ of light in droplets.","Les couleurs arc-en-ciel se forment par ___ de la lumière dans les gouttelettes.","I colori dell'arcobaleno si formano per ___ della luce nelle goccioline.","Brechung (Refraktion)","Brechung in Tropfen.","Prisma-Effekt in Regen."),
        mc("wt28","2","Was ist ein Hochdruckgebiet (Hoch)?","What is a high-pressure system?","Qu'est-ce qu'un anticyclone ?","Che cos'è un anticiclone?","Hoher Luftdruck, meist gutes Wetter",["Schlechtwetter","Hoher Luftdruck, meist gutes Wetter","Starke Winde","Gewitter"],"H = Hochdruckgebiet = Sonne.","Hoch = schönes Wetter."),
        fib("wt29","2","Wind entsteht, weil Luft von ___ Luftdruck zu niedrigem Druck strömt.","Wind forms because air flows from ___ pressure to low pressure.","Le vent se forme car l'air va de ___ pression à basse pression.","Il vento si forma perché l'aria scorre da ___ pressione a bassa pressione.","hohem","Luftdruckunterschied = Wind.","Luft strömt bergab."),
        mc("wt30","2","Was ist ein Klimadiagramm?","What is a climate diagram?","Qu'est-ce qu'un diagramme climatique ?","Che cos'è un diagramma climatico?","Grafische Darstellung von Temperatur und Niederschlag über Monate",["Ein Foto des Wetters","Grafische Darstellung von Temperatur und Niederschlag","Eine Wetterkarte","Ein Thermometer"],"Balken = Regen, Kurve = Temperatur.","Monatliche Durchschnittswerte."),
        fib("wt31","2","Im Schweizer Alpenraum gibt es oft ___ wind (warmer Fallwind).","In the Swiss Alps there is often ___ wind (warm föhn).","Dans les Alpes suisses, il y a souvent le ___ (vent chaud).","Nelle Alpi svizzere c'è spesso il vento ___ (vento caldo).","Föhn","Föhn = warmer Abwind.","Klares Wetter, aber Brandgefahr."),
        mc("wt32","2","Warum hat die Schweiz ein gemässigtes Klima?","Why does Switzerland have a temperate climate?","Pourquoi la Suisse a-t-elle un climat tempéré ?","Perché la Svizzera ha un clima temperato?","Wegen Lage in Mitteleuropa und den Alpen",["Wegen des Meeres allein","Wegen Lage in Mitteleuropa und den Alpen","Weil es kalt ist","Keine Jahreszeiten"],"Gemässigt = weder extrem heiss noch kalt.","Mitteleuropa-Klima."),
        fib("wt33","2","Hagel entsteht in einer ___ wolke, wenn Tröpfchen aufgewirbelt werden und gefrieren.","Hail forms in a ___ cloud when droplets are whirled and freeze.","La grêle se forme dans un nuage d'___ quand les gouttelettes gèlent.","La grandine si forma in una nuvola di ___ quando le goccioline gelano.","Gewitter","Hagel = Gewitterphänomen.","Eiskörner aus Gewitterwolken."),
        mc("wt34","2","Was ist Tau?","What is dew?","Qu'est-ce que la rosée ?","Che cos'è la rugiada?","Wassertröpfchen, die sich nachts auf Oberflächen bilden",["Regen","Wassertröpfchen nachts auf Oberflächen","Schnee","Nebel"],"Morgens Tau auf Gras.","Kühle Oberfläche → Kondensation."),
        fib("wt35","2","Temperatur wird in Grad ___ gemessen.","Temperature is measured in degrees ___.","La température se mesure en degrés ___.","La temperatura si misura in gradi ___.","Celsius (°C)","0°C = Gefrierpunkt.","°C = Grad Celsius."),
        mc("wt36","2","Was bringt ein Tiefdruckgebiet (Tief) oft?","What does a low-pressure system usually bring?","Que les dépressions apportent-elles souvent ?","Cosa porta spesso un ciclone?","Niederschlag und schlechtes Wetter",["Sonnenschein","Niederschlag und schlechtes Wetter","Wind allein","Frost"],"L = Tiefdruckgebiet = Regen.","Tief = schlechtes Wetter."),
        fib("wt37","3","Die Jahreszeiten entstehen, weil die Erde eine ___ Achse hat.","Seasons exist because Earth has a ___ axis.","Les saisons existent car la Terre a un axe ___.","Le stagioni esistono perché la Terra ha un asse ___.","geneigte","Geneigte Achse → unterschiedliche Sonnenstrahlung.","Neigung der Erdachse."),
        mc("wt38","3","Was ist der Treibhauseffekt?","What is the greenhouse effect?","Qu'est-ce que l'effet de serre ?","Che cos'è l'effetto serra?","Treibhausgase halten Wärme in der Atmosphäre zurück",["Pflanzen wachsen im Treibhaus","Treibhausgase halten Wärme zurück","Die Sonne wird wärmer","Wind kühlt die Erde"],"CO₂, Methan = Treibhausgase.","Erde erwärmt sich."),
        fib("wt39","3","Das wichtigste Treibhausgas ist ___.","The most important greenhouse gas is ___.","Le gaz à effet de serre le plus important est ___.","Il gas serra più importante è ___.","CO₂ (Kohlenstoffdioxid)","Verbrennung erzeugt CO₂.","CO₂ hält Wärme zurück."),
        mc("wt40","3","Was ist Klimawandel?","What is climate change?","Qu'est-ce que le changement climatique ?","Che cos'è il cambiamento climatico?","Langfristige Veränderung des Klimas durch menschliche CO₂-Emissionen",["Tägliche Wetterveränderungen","Langfristige Veränderung durch CO₂","Ein Sturm","Jahreszeiten"],"Fossil-Brennstoffe → CO₂ → Erwärmung.","Langfristig ≠ Wetter."),
        fib("wt41","3","Die ___ schützt die Erde vor schädlichen UV-Strahlen.","The ___ protects Earth from harmful UV rays.","La ___ protège la Terre des rayons UV.","La ___ protegge la Terra dai raggi UV.","Ozonschicht","Ozon = Schutzschild.","UV-Strahlen → Sonnenbrand."),
        mc("wt42","3","Wie entsteht ein Tornado?","How does a tornado form?","Comment se forme une tornade ?","Come si forma un tornado?","Durch rotierende Luftmassen in Gewitterzellen",["Starker Wind allein","Durch rotierende Luftmassen in Gewitterzellen","Durch Regen","Durch Sonnenwärme"],"Superzellen-Gewitter → Tornados.","Aufsteigende warme, absinkende kalte Luft."),
        fib("wt43","3","Klimawandel bedeutet, dass die durchschnittliche Erdtemperatur durch menschliche Aktivitäten ___.","Climate change means Earth's average temp ___ due to human activity.","Le changement climatique signifie que la temp. moyenne de la Terre ___.","Il cambiamento climatico significa che la temp. media della Terra ___.","steigt","Fossile Brennstoffe erhöhen CO₂.","Mehr Treibhausgase = wärmer."),
        mc("wt44","3","Was ist die Albedo?","What is albedo?","Qu'est-ce que l'albédo ?","Che cos'è l'albedo?","Der Anteil des Sonnenlichts, den eine Oberfläche reflektiert",["Die Erdwärme","Der Anteil des Sonnenlichts, den eine Oberfläche reflektiert","Die Lufttemperatur","Den Niederschlag"],"Schnee = hohe Albedo.","Ozean = niedrige Albedo."),
        fib("wt45","3","Die Atmosphäre besteht zu ca. 78% aus ___ und 21% Sauerstoff.","The atmosphere is ~78% ___ and 21% oxygen.","L'atmosphère est composée à ~78% de ___ et 21% d'oxygène.","L'atmosfera è composta per ~78% di ___ e 21% di ossigeno.","Stickstoff (N₂)","N₂ = häufigstes Gas in der Atmosphäre.","Stickstoff inert."),
        mc("wt46","3","Was ist eine Klimazone?","What is a climate zone?","Qu'est-ce qu'une zone climatique ?","Che cos'è una zona climatica?","Gebiet mit ähnlichen langfristigen Wetterbedingungen",["Tagesgebiet","Gebiet mit ähnlichen langfristigen Wetterbedingungen","Ein Land","Ein Kontinent"],"Tropisch, gemässigt, arktisch = Klimazonen.","Ähnliche Temperatur + Niederschlag."),
        fib("wt47","3","Der ___ ist das Langzeit-Klimamuster einer Region (30+ Jahre).","The ___ is the long-term climate pattern of a region (30+ years).","Le ___ est le modèle climatique à long terme d'une région (30+ ans).","Il ___ è il modello climatico a lungo termine di una regione (30+ anni).","Klimadurchschnitt / Klima","Klima ≠ Wetter.","Langfristig vs. kurzfristig."),
        mc("wt48","3","Was ist die Thermosphäre?","What is the thermosphere?","Qu'est-ce que la thermosphère ?","Che cos'è la termosfera?","Die äusserste Schicht der Erdatmosphäre (80-700 km)",["Die unterste Schicht","Die mittlere Schicht","Die äusserste Schicht (80-700 km)","Die Wolkenschicht"],"Thermosphäre = heisseste Schicht.","Satelliten fliegen dort."),
        fib("wt49","3","Ozon in der Stratosphäre schützt vor ___ Strahlen der Sonne.","Ozone in the stratosphere protects from ___ rays.","L'ozone protège des rayons ___ du soleil.","L'ozono protegge dai raggi ___ del sole.","UV- (ultravioletten)","UV-Strahlung → Sonnenbrand.","Ozonschicht = Schutzschild."),
        mc("wt50","3","Was beschreibt die Hadley-Zelle?","What is a Hadley cell?","Que décrit la cellule de Hadley ?","Cosa descrive la cellula di Hadley?","Zirkulationsmuster aufsteigender Luft am Äquator und absinkender in Subtropen",["Eine Meeresströmung","Zirkulationsmuster aufsteigender Luft am Äquator","Ein Sturmsystem","Eine Klimazone"],"Tropenwinde entstehen durch Hadley-Zellen.","Äquator heiss → Luft steigt auf."),
    ]

def make_wetter_g2():
    base = make_wetter_g1()
    result = []
    for line in base:
        line = re.sub(r'id: "wt(\d+)"', lambda m: f'id: "wt{m.group(1)}b"', line)
        result.append(line)
    return result

def make_energie_g3():
    return [
        mc("es11","1","Was ist ein Aggregatzustand?","What is a state of matter?","Qu'est-ce qu'un état de la matière ?","Che cos'è uno stato di aggregazione?","Fest, flüssig oder gasförmig",["Eine Farbe","Eine Zahl","Fest, flüssig oder gasförmig","Eine Kraft"],"Wasser kann in allen drei Zuständen sein.","Drei Aggregatzustände."),
        fib("es12","1","Wenn Eis schmilzt, wird es zu ___ Wasser.","When ice melts, it becomes ___ water.","Quand la glace fond, elle devient de l'eau ___.","Quando il ghiaccio si scioglie, diventa acqua ___.","flüssigem","Eis = fest. Schmelzen = flüssig.","Erwärmung über 0°C."),
        mc("es13","1","Was ist erneuerbare Energie?","What is renewable energy?","Qu'est-ce que l'énergie renouvelable ?","Che cos'è l'energia rinnovabile?","Energie, die sich natürlich erneuert (Sonne, Wind, Wasser)",["Energie die endlich ist","Energie, die sich natürlich erneuert","Nur Solarenergie","Kernenergie"],"Sonne und Wind = unerschöpflich.","Erneuerbar = immer wieder neu."),
        fib("es14","1","Wasserdampf ist Wasser im ___ Zustand.","Water vapour is water in the ___ state.","La vapeur d'eau est l'eau à l'état ___.","Il vapore acqueo è acqua allo stato ___.","gasförmigen","Gas = dritter Aggregatzustand.","Dampf = gasförmiges Wasser."),
        mc("es15","1","Welche Energieform speichert eine Batterie?","What form of energy does a battery store?","Quelle forme d'énergie stocke une batterie ?","Quale forma di energia immagazzina una batteria?","Chemische Energie",["Lichtenergie","Wärmeenergie","Chemische Energie","Magnetische Energie"],"Batterien speichern chemische Energie.","Beim Entladen → elektrische Energie."),
        fib("es16","1","Wenn Wasser bei 100°C kocht, wird es zu ___.","When water boils at 100°C, it becomes ___.","Quand l'eau bout à 100°C, elle devient ___.","Quando l'acqua bolle a 100°C, diventa ___.","Dampf (Wasserdampf)","Kochen = Verdampfen.","Dampf = gasförmiges Wasser."),
        mc("es17","1","Was ist Lichtenergie?","What is light energy?","Qu'est-ce que l'énergie lumineuse ?","Che cos'è l'energia luminosa?","Energie, die als Licht abgestrahlt wird",["Energie durch Bewegung","Energie, die als Licht abgestrahlt wird","Gespeicherte Energie","Wärmeenergie"],"Sonne und Lampen strahlen Licht.","Licht ist eine Energieform."),
        fib("es18","1","Holz verbrennt und wandelt chemische Energie in ___ und Licht um.","Wood burns converting chemical energy to ___ and light.","Le bois brûle et convertit l'énergie chimique en ___ et lumière.","Il legno brucia e converte l'energia chimica in ___ e luce.","Wärme","Verbrennung = chem. Energie → Wärme.","Feuer erzeugt Wärme."),
        mc("es19","1","Was ist Kernenergie?","What is nuclear energy?","Qu'est-ce que l'énergie nucléaire ?","Che cos'è l'energia nucleare?","Energie aus Spaltung von Atomkernen",["Windenergie","Sonnenenergie","Energie aus Spaltung von Atomkernen","Wasserenergie"],"Atomkraft nutzt Kernspaltung.","Uran = Brennstoff."),
        fib("es20","1","Die Schweiz gewinnt den grössten Teil ihres Stroms aus ___kraft.","Switzerland generates most electricity from ___ power.","La Suisse produit le plus d'électricité grâce à l'énergie ___.","La Svizzera produce la maggior parte dell'elettricità dall'energia ___.","Wasser","Viele Stauseen in der Schweiz.","Wasser dreht Turbinen."),
        fib("es21","1","Ein ___ Körper behält seine Form (z.B. Stein, Eis).","A ___ body keeps its shape (e.g. stone, ice).","Un corps ___ garde sa forme (ex. pierre, glace).","Un corpo ___ mantiene la sua forma (es. pietra, ghiaccio).","fester","Fest = starre Form.","Drei Aggregatzustände: fest, flüssig, gasförmig."),
        mc("es22","2","Was ist der Energieerhaltungssatz?","What is the law of energy conservation?","Qu'est-ce que la loi de conservation de l'énergie ?","Che cos'è la legge di conservazione dell'energia?","Energie kann nur umgewandelt werden, nicht erzeugt oder vernichtet",["Energie wächst","Energie kann nur umgewandelt werden","Energie schrumpft","Energie ist sichtbar"],"Physikalisches Grundgesetz.","Energie bleibt immer erhalten."),
        fib("es23","2","Wenn Wasserdampf sich abkühlt, ___ er (wird wieder flüssig).","When water vapour cools, it ___ (becomes liquid again).","Quand la vapeur d'eau refroidit, elle ___ (redevient liquide).","Quando il vapore acqueo si raffredda, ___ (diventa liquido di nuovo).","kondensiert","Kondensation = Dampf → Flüssigkeit.","Wolken entstehen durch Kondensation."),
        mc("es24","2","Was ist kinetische Energie?","What is kinetic energy?","Qu'est-ce que l'énergie cinétique ?","Che cos'è l'energia cinetica?","Energie eines bewegten Körpers",["Energie eines ruhenden Körpers","Energie eines bewegten Körpers","Gespeicherte Energie","Wärme allein"],"Rollender Ball = kinetische Energie.","Kinetisch = in Bewegung."),
        fib("es25","2","Ein Windrad wandelt ___ energie in elektrische Energie um.","A wind turbine converts ___ energy into electrical energy.","Une éolienne convertit l'énergie ___ en énergie électrique.","Un mulino a vento converte l'energia ___ in energia elettrica.","Wind-","Wind dreht Turbinen → Strom.","Kinetische Windenergie → Elektrizität."),
        mc("es26","2","Was passiert beim Schmelzen?","What happens during melting?","Que se passe-t-il lors de la fusion ?","Cosa succede durante la fusione?","Fester Stoff wird durch Wärme flüssig",["Gas wird flüssig","Fester Stoff wird durch Wärme flüssig","Wärme wird erzeugt","Stoff erstarrt"],"Eis schmilzt bei 0°C.","Fest → Flüssig = Schmelzen."),
        fib("es27","2","Lageenergie (potentielle Energie) hat ein Objekt, wenn es sich ___ befindet.","Potential energy is in an object at ___.","L'énergie potentielle est dans un objet en ___.","L'energia potenziale è in un oggetto in ___.","erhöhter Position / oben","Höhe = Lageenergie.","Apfel oben = viel Lageenergie."),
        mc("es28","2","Was ist Biomasse als Energiequelle?","What is biomass as an energy source?","Qu'est-ce que la biomasse comme source d'énergie ?","Che cos'è la biomassa come fonte di energia?","Organisches Material (Holz, Pflanzen, Abfälle)",["Kohle","Erdöl","Organisches Material (Holz, Pflanzen, Abfälle)","Kernenergie"],"Holz verbrennen = Biomasse.","Erneuerbar wenn nachgepflanzt."),
        fib("es29","2","Elektrische Energie wird in Leitungen als ___ transportiert.","Electrical energy is transported in wires as ___.","L'énergie électrique est transportée dans les fils comme ___.","L'energia elettrica è trasportata nei fili come ___.","Strom","Kabel leiten Strom.","Elektronen fliessen im Kabel."),
        mc("es30","2","Was ist ein thermischer Isolator?","What is a thermal insulator?","Qu'est-ce qu'un isolant thermique ?","Che cos'è un isolante termico?","Material, das Wärme schlecht leitet",["Guter Wärmeleiter","Material, das Wärme schlecht leitet","Ein Metall","Eine Energiequelle"],"Holz und Styropor = Isolatoren.","Isolierung = weniger Heizung."),
        fib("es31","2","Wärme ist eine Form von ___ . Temperatur misst wie warm etwas ist.","Heat is a form of ___. Temperature measures warmth.","La chaleur est une forme d'___. La température mesure la chaleur.","Il calore è una forma di ___. La temperatura misura il calore.","Energie","Wärme = Energiemenge.","Temperatur ≠ Wärme."),
        mc("es32","2","Was ist Geothermie?","What is geothermal energy?","Qu'est-ce que la géothermie ?","Che cos'è la geotermia?","Energie aus der Erdwärme",["Windenergie","Energie aus der Erdwärme","Sonnenenergie","Wasserenergie"],"Erdinneres ist heiss.","Island = Geothermie."),
        fib("es33","2","Energieeffizienz: man setzt ___ Energie ein, um dasselbe Ziel zu erreichen.","Energy efficiency: use ___ energy to achieve the same goal.","Efficacité énergétique : utiliser ___ d'énergie pour le même objectif.","Efficienza energetica: usare ___ energia per lo stesso obiettivo.","weniger","LED vs. Glühbirne.","Weniger Energie = effizienter."),
        mc("es34","2","Was ist Sublimation?","What is sublimation?","Qu'est-ce que la sublimation ?","Che cos'è la sublimazione?","Fester Stoff wird direkt zu Gas (ohne flüssig zu sein)",["Gas wird flüssig","Fester Stoff wird direkt zu Gas","Flüssigkeit gefriert","Wasser siedet"],"Trockeneis sublimiert bei Raumtemperatur.","Fest → Gas ohne flüssige Phase."),
        fib("es35","2","Wenn man Wasser unter 0°C kühlt, erstarrt es zu ___.","When water is cooled below 0°C, it solidifies to ___.","Quand l'eau est refroidie sous 0°C, elle se solidifie en ___.","Quando l'acqua viene raffreddata sotto 0°C, si solidifica in ___.","Eis","0°C = Gefrierpunkt.","Erstarren = Flüssig → Fest."),
        mc("es36","2","Warum ist CO₂ klimarelevant?","Why is CO₂ climate-relevant?","Pourquoi le CO₂ est-il climatiquement pertinent ?","Perché il CO₂ è rilevante per il clima?","Es ist ein Treibhausgas, das Wärme zurückhält",["Ein Edelgas ohne Wirkung","Es ist ein Treibhausgas, das Wärme zurückhält","Nur in der Industrie","Ein Metall"],"CO₂ entsteht bei Verbrennung.","Mehr CO₂ = Erderwärmung."),
        fib("es37","3","Der Wirkungsgrad η = Nutzenergie / ___ × 100%.","Efficiency η = useful energy / ___ × 100%.","Le rendement η = énergie utile / ___ × 100%.","Il rendimento η = energia utile / ___ × 100%.","Eingangsenergie","Wirkungsgrad: wie viel wird genutzt.","Ideal: η = 100%."),
        mc("es38","3","Was ist Enthalpie?","What is enthalpy?","Qu'est-ce que l'enthalpie ?","Che cos'è l'entalpia?","Gesamtenergie eines Systems (innere Energie + Druckarbeit)",["Nur innere Energie","Gesamtenergie eines Systems","Nur kinetische Energie","Nur potentielle Energie"],"H = U + pV.","Enthalpie = chem. Energie + Volumenarbeit."),
        fib("es39","3","Ein Wärmetauscher überträgt Wärme von einem ___ auf ein anderes, ohne Vermischung.","A heat exchanger transfers heat from one ___ to another without mixing.","Un échangeur transfère la chaleur d'un ___ à un autre sans mélange.","Uno scambiatore trasferisce il calore da un ___ a un altro senza mescolare.","Medium / Fluid","Keine direkte Vermischung.","Heizungsanlagen nutzen Wärmetauscher."),
        mc("es40","3","Was ist spezifische Wärmekapazität?","What is specific heat capacity?","Qu'est-ce que la capacité thermique spécifique ?","Che cos'è la capacità termica specifica?","Energie zum Erwärmen von 1 kg eines Stoffs um 1°C (J/kg·K)",["Maximale Temperatur","Energie zum Erwärmen von 1 kg um 1°C","Die Siedetemperatur","Die Schmelztemperatur"],"Wasser: c = 4186 J/kg·K.","Hohe c = langsames Erwärmen."),
        fib("es41","3","Erster Hauptsatz der Thermodynamik: Die innere Energie eines abgeschlossenen Systems bleibt ___.","First law of thermodynamics: internal energy of closed system remains ___.","1re loi : l'énergie interne d'un système fermé reste ___.","1a legge: l'energia interna di un sistema chiuso rimane ___.","konstant / erhalten","Energieerhaltung.","Energie nicht erzeugt oder vernichtet."),
        mc("es42","3","Was beschreibt der zweite Hauptsatz der Thermodynamik?","What does the second law of thermodynamics describe?","Que décrit le 2e principe de la thermodynamique ?","Cosa descrive il secondo principio della termodinamica?","Wärme fliesst von warm zu kalt; Entropie nimmt zu",["Energie ist konstant","Wärme fliesst von warm zu kalt; Entropie nimmt zu","Energie nimmt zu","Entropie nimmt ab"],"Kaffee kühlt ab von selbst.","2. Hauptsatz = Entropie."),
        fib("es43","3","Fusion (Kernfusion) vereinigt leichte Kerne, dabei wird ___ freigesetzt.","Fusion combines light nuclei, releasing ___.","La fusion combine des noyaux légers, libérant de l'___.","La fusione combina nuclei leggeri, rilasciando ___.","Energie","Sonne = Kernfusion.","H → He + Energie."),
        mc("es44","3","Was ist Photovoltaik?","What is photovoltaics?","Qu'est-ce que le photovoltaïque ?","Che cos'è il fotovoltaico?","Direkte Umwandlung von Sonnenlicht in Strom durch Solarzellen",["Solarthermie","Direkte Umwandlung von Sonnenlicht in Strom","Windkraft","Wasserkraft"],"Solarzellen auf Dächern.","Licht → Strom direkt."),
        fib("es45","3","Entropie ist das Mass für die ___ in einem System.","Entropy is the measure of ___ in a system.","L'entropie est la mesure du ___ dans un système.","L'entropia è la misura del ___ in un sistema.","Unordnung","2. Hauptsatz: Entropie wächst.","Unordnung nimmt zu."),
        mc("es46","3","Was ist ein Kraftwerk?","What is a power plant?","Qu'est-ce qu'une centrale électrique ?","Che cos'è una centrale elettrica?","Anlage, die Energie in Strom umwandelt",["Energiespeicher","Anlage, die Energie in Strom umwandelt","Verteilnetz","Transformator"],"Wasserkraft-, Atomkraftwerk = Kraftwerk.","Energie → Strom."),
        fib("es47","3","Elektrolyse nutzt elektrische Energie, um chemische ___ zu treiben.","Electrolysis uses electrical energy to drive chemical ___.","L'électrolyse utilise l'énergie électrique pour entraîner des ___ chimiques.","L'elettrolisi usa l'energia elettrica per guidare le ___ chimiche.","Reaktionen","Wasser → H₂ + O₂ durch Elektrolyse.","Strom → Chemie."),
        mc("es48","3","Was ist ein Smart Grid?","What is a smart grid?","Qu'est-ce qu'un réseau intelligent ?","Che cos'è una rete intelligente?","Intelligentes Stromnetz, das Erzeugung und Verbrauch digital optimiert",["Einfaches Stromnetz","Intelligentes Stromnetz","Ein Solarpanel","Ein Wasserkraftwerk"],"Smart Grid = digitales Stromnetz.","Bessere Integration erneuerbarer Energien."),
        fib("es49","3","Sonnenenergie erreicht die Erde als ___ Strahlung.","Solar energy reaches Earth as ___ radiation.","L'énergie solaire atteint la Terre sous forme de rayonnement ___.","L'energia solare raggiunge la Terra come radiazione ___.","elektromagnetische","Licht = elektromagnetische Welle.","UV, Infrarot, sichtbares Licht."),
        mc("es50","3","Was ist eine Brennstoffzelle?","What is a fuel cell?","Qu'est-ce qu'une pile à combustible ?","Che cos'è una cella a combustibile?","Gerät, das chemische Energie (z.B. H₂) direkt in Strom umwandelt",["Ein Akku","Gerät, das chemische Energie direkt in Strom umwandelt","Ein Solarpanel","Ein Motor"],"H₂ + O₂ → H₂O + Strom.","Sauber und effizient."),
    ]

def make_energie_g4():
    base = make_energie_g3()
    result = []
    for line in base:
        line = re.sub(r'id: "es(\d+)"', lambda m: f'id: "es{m.group(1)}b2"', line)
        result.append(line)
    return result

def make_licht_g3():
    return [
        mc("lo11","1","Was ist Licht?","What is light?","Qu'est-ce que la lumière ?","Che cos'è la luce?","Elektromagnetische Strahlung, die wir sehen können",["Ein Gas","Elektromagnetische Strahlung","Wärme","Ein Ton"],"Licht = elektromagnetische Welle.","Unser Auge empfängt Licht."),
        fib("lo12","1","Die Sonne ist eine natürliche ___quelle.","The sun is a natural ___ source.","Le soleil est une source de ___ naturelle.","Il sole è una sorgente di ___ naturale.","Licht","Sonne = Lichtquelle.","Ohne Sonne kein Tageslicht."),
        mc("lo13","1","Was ist eine Lichtquelle?","What is a light source?","Qu'est-ce qu'une source de lumière ?","Che cos'è una sorgente di luce?","Etwas, das selbst Licht erzeugt",["Etwas, das Licht reflektiert","Etwas, das selbst Licht erzeugt","Etwas, das Schatten wirft","Etwas, das Licht absorbiert"],"Sonne, Kerze, Lampe = Lichtquellen.","Erzeugt Licht selbst."),
        fib("lo14","1","Ein Schatten entsteht, wenn Licht von einem ___ Objekt blockiert wird.","A shadow forms when light is blocked by an ___ object.","Une ombre se forme quand la lumière est bloquée par un objet ___.","Un'ombra si forma quando la luce viene bloccata da un oggetto ___.","undurchsichtigen","Glas lässt Licht durch, Holz nicht.","Undurchsichtig = kein Licht."),
        mc("lo15","1","Was ist Reflexion?","What is reflection?","Qu'est-ce que la réflexion ?","Che cos'è la riflessione?","Licht prallt von einer Fläche zurück",["Licht wird absorbiert","Licht prallt von einer Fläche zurück","Licht erzeugt Wärme","Licht verschwindet"],"Spiegel reflektieren Licht.","Reflexion = Zurückwerfen."),
        fib("lo16","1","Weisses Licht besteht aus ___ Farben.","White light consists of ___ colours.","La lumière blanche est composée de ___ couleurs.","La luce bianca è composta da ___ colori.","vielen / allen Regenbogenfarben","Prisma zerlegt weisses Licht.","7 Farben des Regenbogens."),
        mc("lo17","1","Was ist ein transparentes Objekt?","What is a transparent object?","Qu'est-ce qu'un objet transparent ?","Che cos'è un oggetto trasparente?","Eines, durch das Licht hindurchgeht",["Eines, das Licht reflektiert","Eines, durch das Licht hindurchgeht","Eines, das Schatten wirft","Eines, das absorbiert"],"Fensterglas = transparent.","Transparent = Licht durch."),
        fib("lo18","1","Der Mond leuchtet, weil er ___ von der Sonne reflektiert.","The moon shines because it ___ sunlight.","La lune brille parce qu'elle ___ la lumière du soleil.","La luna brilla perché ___ la luce del sole.","Licht","Mond = Reflektor, kein Licht.","Sonnenlicht → Mond → Erde."),
        mc("lo19","1","Wie schnell bewegt sich Licht?","How fast does light travel?","À quelle vitesse la lumière se déplace-t-elle ?","Con quale velocità viaggia la luce?","300'000 km/s",["3'000 km/s","30'000 km/s","300'000 km/s","3'000'000 km/s"],"Licht ist das Schnellste.","c = 300'000 km/s."),
        fib("lo20","1","Ein ___ Material lässt kein Licht hindurch (z.B. Holz, Metall).","An ___ material lets no light through (e.g. wood, metal).","Un matériau ___ ne laisse pas passer la lumière.","Un materiale ___ non lascia passare la luce.","undurchsichtiges (opakes)","Holz = undurchsichtig.","Kein Licht = opak."),
        fib("lo21","1","Wenn Licht auf einen Spiegel trifft, wird es im gleichen ___ zurückgeworfen.","When light hits a mirror, it is reflected at the same ___.","Quand la lumière frappe un miroir, elle est réfléchie au même ___.","Quando la luce colpisce uno specchio, viene riflessa allo stesso ___.","Winkel","Einfallswinkel = Ausfallswinkel.","Reflexionsgesetz."),
        mc("lo22","2","Was ist Refraktion (Brechung) von Licht?","What is light refraction?","Qu'est-ce que la réfraction de la lumière ?","Che cos'è la rifrazione della luce?","Licht ändert Richtung beim Übergang zwischen Medien",["Licht absorbiert","Licht ändert Richtung zwischen Medien","Licht prallt zurück","Licht wird dunkler"],"Strohhalm im Wasser sieht gebogen aus.","Luft → Wasser = Richtungsänderung."),
        fib("lo23","2","Ein Prisma zerlegt weisses Licht in seine ___.","A prism splits white light into its ___.","Un prisme décompose la lumière blanche en ses ___.","Un prisma scompone la luce bianca nei suoi ___.","Farben (Spektrum)","Newton entdeckte Licht-Zerlegung.","Prisma → Spektrum."),
        mc("lo24","2","Welche Farben hat das sichtbare Spektrum?","What colours make the visible spectrum?","Quelles couleurs composent le spectre visible ?","Quali colori compongono lo spettro visibile?","Rot, Orange, Gelb, Grün, Blau, Indigo, Violett",["Nur Rot, Grün, Blau","Rot, Orange, Gelb, Grün, Blau, Indigo, Violett","Nur Primärfarben","Nur Weiss und Schwarz"],"7 Farben = Regenbogen.","ROGGBIV."),
        fib("lo25","2","Rote Objekte ___ rotes Licht und absorbieren andere Farben.","Red objects ___ red light and absorb other colours.","Les objets rouges ___ la lumière rouge.","Gli oggetti rossi ___ la luce rossa.","reflektieren","Farbe = welches Licht reflektiert wird.","Rot = nur rotes Licht zurück."),
        mc("lo26","2","Was ist eine Linse?","What is a lens?","Qu'est-ce qu'une lentille ?","Che cos'è una lente?","Ein Objekt, das Licht bricht und bündelt oder zerstreut",["Ein Spiegel","Ein Objekt, das Licht bricht","Eine Lichtquelle","Ein Prisma"],"Brillengläser, Lupen = Linsen.","Konvex = sammelnd."),
        fib("lo27","2","Ein Regenbogen entsteht, wenn Sonnenlicht durch ___ gebrochen und reflektiert wird.","A rainbow forms when sunlight is refracted by ___.","Un arc-en-ciel se forme quand la lumière est réfractée par ___.","Un arcobaleno si forma quando la luce viene rifratta da ___.","Wassertröpfchen","Brechung + Reflexion in Tropfen.","Prisma-Effekt in Regen."),
        mc("lo28","2","Was ist eine Sonnenfinsternis?","What is a solar eclipse?","Qu'est-ce qu'une éclipse solaire ?","Che cos'è un'eclissi solare?","Wenn der Mond zwischen Sonne und Erde steht",["Erde verdeckt Mond","Mond zwischen Sonne und Erde","Bewölkt","Nacht"],"Der Mond wirft Schatten auf die Erde.","Sonne-Mond-Erde."),
        fib("lo29","2","Eine Lupe (konvexe Linse) ___ Lichtstrahlen und vergrössert Objekte.","A magnifying glass (convex lens) ___ light rays and magnifies.","Une loupe (lentille convexe) ___ les rayons et agrandit.","Una lente d'ingrandimento (convessa) ___ i raggi e ingrandisce.","bündelt","Konvex = Sammellinse.","Brennpunkt."),
        mc("lo30","2","Was sind komplementäre Farben?","What are complementary colours?","Que sont les couleurs complémentaires ?","Cosa sono i colori complementari?","Farben, die zusammen Weiss/Grau ergeben",["Gleiche Farben","Farben, die zusammen Weiss/Grau ergeben","Nur Primärfarben","Nur Sekundärfarben"],"Rot + Grün + Blau = Weiss (additiv).","Komplementär ergänzen sich."),
        fib("lo31","2","Die Zerlegung des Lichts in alle Farben nennt man das ___.","The decomposition of light into all colours is called the ___.","La décomposition de la lumière en toutes les couleurs s'appelle le ___.","La scomposizione della luce in tutti i colori si chiama ___.","Spektrum","Prisma erzeugt Spektrum.","Spektrum = alle Lichtfarben."),
        mc("lo32","2","Was ist Fluoreszenz?","What is fluorescence?","Qu'est-ce que la fluorescence ?","Che cos'è la fluorescenza?","UV-Licht absorbiert und sichtbares Licht ausgesandt",["Licht reflektiert","UV absorbiert und sichtbares Licht ausgesandt","Licht durch Prisma","Objekt leuchtet von innen"],"Textmarker fluoreszieren.","UV → sichtbares Licht."),
        fib("lo33","2","Ein Teleskop nutzt Linsen oder Spiegel, um ___ Objekte zu vergrössern.","A telescope uses lenses or mirrors to magnify ___ objects.","Un télescope utilise des lentilles pour agrandir des objets ___.","Un telescopio usa lenti per ingrandire oggetti ___.","weit entfernte","Sterne = weit weg.","Galilei erfand das Teleskop."),
        mc("lo34","2","Was passiert, wenn Licht unter 45° auf einen Spiegel trifft?","What happens when light hits a mirror at 45°?","Que se passe-t-il quand la lumière frappe un miroir à 45° ?","Cosa succede quando la luce colpisce uno specchio a 45°?","Es wird um 90° abgelenkt",["Es wird absorbiert","Es wird um 90° abgelenkt","Es geht hindurch","Es wird um 180° geworfen"],"Einfallswinkel = Ausfallswinkel.","45° in + 45° out = 90° Ablenkung."),
        fib("lo35","2","Licht breitet sich in geraden ___ aus.","Light travels in straight ___.","La lumière se propage en ___ droites.","La luce si propaga in ___ diretti.","Linien / Strahlen","Licht geht geradeaus.","Schatten entstehen wegen gerader Ausbreitung."),
        mc("lo36","2","Was ist ein Hologramm?","What is a hologram?","Qu'est-ce qu'un hologramme ?","Che cos'è un ologramma?","Dreidimensionales Bild durch Laserinterferenz",["Normales Foto","Dreidimensionales Bild durch Laserinterferenz","Schatten","Regenbogen"],"Hologramme auf Kreditkarten.","Laser = 3D-Muster."),
        fib("lo37","3","Die Lichtgeschwindigkeit im Vakuum beträgt ca. ___ km/s.","The speed of light in vacuum is about ___ km/s.","La vitesse de la lumière dans le vide est d'environ ___ km/s.","La velocità della luce nel vuoto è circa ___ km/s.","300'000","c ≈ 299'792 km/s.","Schnellstes im Universum."),
        mc("lo38","3","Was ist der Doppler-Effekt bei Licht?","What is the Doppler effect for light?","Qu'est-ce que l'effet Doppler pour la lumière ?","Che cos'è l'effetto Doppler per la luce?","Entfernende Quellen erscheinen rötlicher (Rotverschiebung)",["Licht wird schneller","Entfernende Quellen erscheinen rötlicher","Farbe wechselt zufällig","Licht wird blauer"],"Galaxien entfernen sich = Rotverschiebung.","Universum-Expansion."),
        fib("lo39","3","Der Brechungsindex n beschreibt, wie stark Licht in einem Medium ___ wird.","The refractive index n describes how much light is ___ in a medium.","L'indice de réfraction n décrit combien la lumière est ___ dans un milieu.","L'indice di rifrazione n descrive quanto la luce viene ___ in un mezzo.","gebrochen / verlangsamt","n = c_Vakuum / c_Medium.","Glas: n ≈ 1,5."),
        mc("lo40","3","Was ist Totalreflexion?","What is total internal reflection?","Qu'est-ce que la réflexion totale interne ?","Che cos'è la riflessione totale interna?","Licht kann an Grenzfläche nicht mehr austreten",["Licht vollständig absorbiert","Licht kann an Grenzfläche nicht mehr austreten","Licht total von Wand reflektiert","Objekt transparent"],"Glasfaserkabel nutzen Totalreflexion.","Licht bleibt im Medium."),
        fib("lo41","3","Glasfaserkabel übertragen Daten als ___ durch Totalreflexion.","Fiber optic cables transmit data as ___ through total internal reflection.","Les câbles à fibre optique transmettent des données sous forme de ___.","I cavi in fibra ottica trasmettono dati come ___.","Lichtimpulse","Licht = sehr schnell.","Glasfaser = Internet."),
        mc("lo42","3","Was ist Polarisation von Licht?","What is polarization of light?","Qu'est-ce que la polarisation de la lumière ?","Che cos'è la polarizzazione della luce?","Ausrichtung der Lichtschwingungen in eine Richtung",["Brechung","Ausrichtung der Lichtschwingungen","Reflexion","Absorption"],"Polfilter-Brillen filtern Licht.","LCD-Screens = Polarisation."),
        fib("lo43","3","Ein Beugungsgitter trennt Licht in Farben durch ___ von Lichtwellen.","A diffraction grating separates light through ___ of waves.","Un réseau de diffraction sépare la lumière par ___ des ondes.","Un reticolo di diffrazione separa la luce per ___ delle onde.","Interferenz","Konstruktiv + destruktiv.","Wellenprinzip."),
        mc("lo44","3","Was ist ein Laser?","What is a laser?","Qu'est-ce qu'un laser ?","Che cos'è un laser?","Kohärentes, monochromatisches Licht in engem Strahl",["Normales helles Licht","Kohärentes monochromatisches Licht","Ein Spiegel","Ein Prisma"],"LASER = Licht-Verstärkung durch stim. Emission.","Barcode-Scanner, CD-Player."),
        fib("lo45","3","Infrarot-Strahlung nehmen wir als ___ wahr.","We perceive infrared radiation as ___.","Le rayonnement infrarouge est perçu comme ___.","La radiazione infrarossa viene percepita come ___.","Wärme","Infrarot = Wärmestrahlung.","Wärmebildkameras."),
        mc("lo46","3","Was ist der photoelektrische Effekt?","What is the photoelectric effect?","Qu'est-ce que l'effet photoélectrique ?","Che cos'è l'effetto fotoelettrico?","Licht schlägt Elektronen aus Metall (Einstein 1905)",["Licht erwärmt Metall","Licht schlägt Elektronen aus Metall","Licht reflektiert","Licht bricht an Metall"],"Solarzellen nutzen Photoeffekt.","Nobel 1921 für Einstein."),
        fib("lo47","3","Sichtbares Licht hat Wellenlängen zwischen ~380 nm (___ ) und ~780 nm (___ ).","Visible light has wavelengths from ~380 nm (___ ) to ~780 nm (___ ).","La lumière visible a des longueurs d'onde de ~380 nm (___ ) à ~780 nm (___ ).","La luce visibile ha lunghezze d'onda da ~380 nm (___ ) a ~780 nm (___ ).","violett bis rot","Violett = kurze Wellenlänge.","Rot = längste sichtbare Wellenlänge."),
        mc("lo48","3","Was ist Beugung (Diffraktion) von Licht?","What is diffraction of light?","Qu'est-ce que la diffraction de la lumière ?","Che cos'è la diffrazione della luce?","Umbiegen von Licht um Hindernisse",["Reflexion","Umbiegen von Licht um Hindernisse","Brechung","Absorption"],"Schlitze erzeugen Beugungsmuster.","Licht als Welle."),
        fib("lo49","3","UV-Strahlung hat eine ___ Wellenlänge als sichtbares Licht.","UV radiation has a ___ wavelength than visible light.","Le rayonnement UV a une longueur d'onde ___ que la lumière visible.","La radiazione UV ha una lunghezza d'onda ___ della luce visibile.","kürzere","UV < violett.","Kurzwellig = hochenergetisch."),
        mc("lo50","3","Was unterscheidet kohärentes von inkohärentem Licht?","Coherent vs incoherent light?","Différence lumière cohérente et incohérente ?","Differenza tra luce coerente e incoerente?","Kohärent: gleiche Phase und Wellenlänge; Inkohärent: verschiedene Phasen",["Beide gleich","Kohärent: gleiche Phase; Inkohärent: verschiedene Phasen","Kohärent heller","Inkohärent = Laser"],"Laser = kohärent.","Glühbirne = inkohärent."),
    ]

def make_licht_g4():
    base = make_licht_g3()
    result = []
    for line in base:
        line = re.sub(r'id: "lo(\d+)"', lambda m: f'id: "lo{m.group(1)}b"', line)
        result.append(line)
    return result

def make_raeume_g3():
    return [
        mc("rk11","1","Was zeigt eine Karte?","What does a map show?","Que montre une carte ?","Cosa mostra una cartina?","Eine verkleinerte Darstellung eines Gebietes",["Ein Foto","Verkleinerte Darstellung","Ein Buch","Eine Liste"],"Karten verkleinern die Wirklichkeit.","Aus der Vogelperspektive."),
        fib("rk12","1","Ein Kompass zeigt immer in Richtung ___.","A compass always points ___.","Une boussole pointe toujours vers ___.","Una bussola punta sempre verso ___.","Norden","Kompassnadel = magnetisch.","Erdmagnetfeld."),
        mc("rk13","1","Wie viele Himmelsrichtungen gibt es?","How many cardinal directions are there?","Combien y a-t-il de points cardinaux ?","Quanti punti cardinali ci sono?","4 (Nord, Süd, Ost, West)",["2","3","4","6"],"NOSW = vier Himmelsrichtungen.","N, O, S, W."),
        fib("rk14","1","Die Sonne geht im ___ auf und im Westen unter.","The sun rises in the ___ and sets in the west.","Le soleil se lève à l'___ et se couche à l'ouest.","Il sole sorge a ___ e tramonta a ovest.","Osten","Tagsüber von O nach W.","Sonne zieht von Ost nach West."),
        mc("rk15","1","Was ist die Hauptstadt der Schweiz?","What is the capital of Switzerland?","Quelle est la capitale de la Suisse ?","Qual è la capitale della Svizzera?","Bern",["Zürich","Bern","Genf","Basel"],"Bundeshaus in Bern.","Nicht Zürich!"),
        fib("rk16","1","Die ___ sind das grösste Gebirge der Schweiz.","The ___ are Switzerland's largest mountain range.","Les ___ sont la plus grande chaîne montagneuse en Suisse.","Le ___ sono la più grande catena montuosa della Svizzera.","Alpen","Matterhorn, Jungfrau = Alpen.","Teilen Nord und Süd."),
        mc("rk17","1","Welcher Fluss fliesst durch Bern?","Which river flows through Bern?","Quel fleuve coule à travers Berne ?","Quale fiume scorre attraverso Berna?","Aare",["Rhein","Rhone","Aare","Limmat"],"Bern liegt an der Aare.","Aare fliesst ins Mittelland."),
        fib("rk18","1","Norden ist auf einer Karte meistens ___ (Richtung).","On a map, north is usually ___.","Sur une carte, le nord est généralement en ___.","Su una cartina, il nord è solitamente in ___.","oben","Oben = Norden = Konvention.","Hilft beim Orientieren."),
        mc("rk19","1","In wie viele Kantone ist die Schweiz aufgeteilt?","Into how many cantons is Switzerland divided?","En combien de cantons la Suisse est-elle divisée ?","In quanti cantoni è divisa la Svizzera?","26",["20","23","26","30"],"26 Kantone in der Schweiz.","Uri, Schwyz, Bern usw."),
        fib("rk20","1","Auf einer Karte ist eine ___ ein Zeichen mit Erklärung.","On a map, a ___ explains what each symbol means.","Sur une carte, une ___ explique les symboles.","Su una cartina, una ___ spiega i simboli.","Legende","Legende = Zeichenerklärung.","Blau = Wasser, Grün = Wald."),
        fib("rk21","1","Die ___ beschreibt das Verhältnis zwischen Karten- und Wirklichkeits-Entfernung.","The ___ is the ratio between map and real distance.","L'___ est le rapport carte/réalité.","La ___ è il rapporto tra carta e realtà.","Massstab","1:100000 = 1 cm → 1 km.","Massstab = Verkleinerungsfaktor."),
        mc("rk22","2","Was bedeutet Massstab 1:50'000?","What does scale 1:50,000 mean?","Que signifie l'échelle 1:50'000 ?","Cosa significa scala 1:50'000?","1 cm auf Karte = 500 m in Wirklichkeit",["1 m = 50 m","1 cm = 500 m","1 cm = 50'000 km","1:1"],"50'000 cm = 500 m.","Karten verkleinern um Faktor 50'000."),
        fib("rk23","2","Höhenlinien verbinden Punkte gleicher ___.","Contour lines connect points of equal ___.","Les courbes de niveau connectent des points de ___ égale.","Le curve di livello collegano punti della stessa ___.","Höhe (m ü. M.)","Dicht = steiles Gelände.","Höhenlinie = gleiche Höhe."),
        mc("rk24","2","Welche Sprachen werden in der Schweiz gesprochen?","What languages are spoken in Switzerland?","Quelles langues parle-t-on en Suisse ?","Quali lingue si parlano in Svizzera?","Deutsch, Französisch, Italienisch und Rätoromanisch",["Nur Deutsch","Deutsch, Französisch, Italienisch und Rätoromanisch","Deutsch und Englisch","Nur Deutsch und Französisch"],"4 Nationalsprachen.","Vier Sprachen."),
        fib("rk25","2","Der grösste rein schweizerische Binnensee ist der ___ see.","Switzerland's largest inland lake is Lake ___.","Le plus grand lac intérieur suisse est le lac de ___.","Il più grande lago interno svizzero è il lago di ___.","Zürich","Zürichsee = rein schweizerisch.","Genfer See ist grösser, aber geteilt."),
        mc("rk26","2","Was ist das Mittelland?","What is the Swiss Plateau?","Qu'est-ce que le Plateau suisse (Mittelland) ?","Che cos'è l'Altopiano svizzero?","Flachere Region zwischen Alpen und Jura",["Das Gebirge","Flachere Region zwischen Alpen und Jura","Die Alpensüdseite","Die Westschweiz"],"Mittelland = dicht besiedelt.","Bern, Zürich, Basel."),
        fib("rk27","2","Der ___ ist der längste Fluss der Schweiz.","The ___ is the longest river in Switzerland.","La ___ est le plus long fleuve de Suisse.","La ___ è il fiume più lungo della Svizzera.","Aare","Aare = längster Schweizer Fluss.","Von Gletschern bis zum Rhein."),
        mc("rk28","2","Was sind die fünf Nachbarländer der Schweiz?","What are Switzerland's five neighbours?","Quels sont les cinq pays voisins de la Suisse ?","Quali sono i cinque paesi confinanti con la Svizzera?","Deutschland, Frankreich, Italien, Österreich, Liechtenstein",["Nur D und F","D, F, I, A, FL","Spanien, Portugal, F, D, A","D, F, B, A, FL"],"5 Nachbarländer.","CH hat keine Meeresküste."),
        fib("rk29","2","Die drei Hauptregionen der Schweiz: Alpen, Mittelland und ___.","Switzerland's three main regions: Alps, Plateau and ___.","Les trois régions principales: Alpes, Plateau et ___.","Le tre regioni principali: Alpi, Altopiano e ___.","Jura","Jura = nordwestliches Gebirge.","Drei Grossregionen."),
        mc("rk30","2","Was zeigt eine topografische Karte?","What does a topographic map show?","Que montre une carte topographique ?","Cosa mostra una carta topografica?","Gelände, Höhen, Gewässer und Siedlungen",["Nur Strassen","Gelände, Höhen, Gewässer, Siedlungen","Nur Grenzen","Nur Städte"],"Höhenlinien = Topografie.","Topo = Gelände."),
        fib("rk31","2","Längengrad beschreibt den ___ Wert einer Position.","Longitude describes the ___ value of a position.","La longitude décrit la valeur ___ d'une position.","La longitudine descrive il valore ___ di una posizione.","Ost-West-","Längengrad = Ost-West.","Breitengrad = Nord-Süd."),
        mc("rk32","2","Was ist ein Massstabsbalken?","What is a scale bar?","Qu'est-ce qu'une barre d'échelle ?","Che cos'è una barra di scala?","Grafisches Lineal auf der Karte",["Eine Legende","Grafisches Lineal","Eine Kompassrose","Ein Nordpfeil"],"Massstabsbalken = visueller Massstab.","Ohne Zahlen lesbar."),
        fib("rk33","2","Eine ___ zeigt die Himmelsrichtungen auf einer Karte.","A ___ shows cardinal directions on a map.","Une ___ indique les points cardinaux sur une carte.","Una ___ mostra i punti cardinali su una cartina.","Kompassrose / Windrose","N, O, S, W auf der Karte.","Orientierung."),
        mc("rk34","2","Was ist ein Stadtplan?","What is a city map?","Qu'est-ce qu'un plan de ville ?","Che cos'è un piano urbano?","Detaillierte Karte einer Stadt",["Eine Landkarte","Detaillierte Karte einer Stadt","Topografische Karte","Wetterkarte"],"Strassen, Gebäude = Stadtplan.","Kleinmassstäbig."),
        fib("rk35","2","Massstab 1:25'000: 1 cm auf der Karte = ___ m in der Wirklichkeit.","Scale 1:25,000: 1 cm on map = ___ m in reality.","Échelle 1:25'000 : 1 cm = ___ m.","Scala 1:25'000: 1 cm = ___ m.","250","25'000 cm = 250 m.","Massstab rechnen: Zahl ÷ 100."),
        mc("rk36","2","Was ist ein Satellitenbild?","What is a satellite image?","Qu'est-ce qu'une image satellite ?","Che cos'è un'immagine satellitare?","Foto der Erde aus dem Weltall",["Kartenausschnitt","Foto der Erde aus dem Weltall","Topografische Karte","Stadtplan"],"Google Earth = Satellitenbilder.","Satelliten umkreisen die Erde."),
        fib("rk37","3","Der Nullmeridian (Längengrad 0°) verläuft durch ___, England.","The prime meridian (longitude 0°) runs through ___, England.","Le méridien zéro passe par ___, Angleterre.","Il meridiano di Greenwich passa per ___, Inghilterra.","Greenwich","Greenwich = Nullmeridian.","Ost und West davon gemessen."),
        mc("rk38","3","Was ist der Unterschied zwischen Breiten- und Längengraden?","Difference between latitude and longitude?","Différence entre latitude et longitude ?","Differenza tra latitudine e longitudine?","Breitengrade: N/S; Längengrade: O/W",["Beide gleich","Breitengrade: N/S; Längengrade: O/W","Längengrade vertikal","Breitengrade vertikal"],"Äquator = 0° Breite.","Greenwich = 0° Länge."),
        fib("rk39","3","Die Koordinaten der Schweiz liegen zwischen ___ und 48° N Breite.","Switzerland's coordinates: between ___ and 48° N latitude.","La Suisse se situe entre ___ et 48° N de latitude.","La Svizzera si trova tra ___ e 48° N di latitudine.","45°","45° bis 48° N.","Mitteleuropa."),
        mc("rk40","3","Was ist GIS?","What is GIS?","Qu'est-ce qu'un SIG ?","Che cos'è un GIS?","System zur Erfassung und Darstellung raumbezogener Daten",["Normales Computerprogramm","System zur Erfassung raumbezogener Daten","Eine Wetter-App","Ein Satellit"],"GIS = digitale Kartographie.","Google Maps = einfaches GIS."),
        fib("rk41","3","Auf Karten werden gleichhohe Bereiche mit ___ dargestellt.","Areas of equal height are shown with ___ on maps.","Les zones de même altitude sont représentées par ___.","Le zone della stessa altezza sono rappresentate da ___.","Höhenstufen / Farbschichtung","Hypsometrie.","Braun = hoch, grün = tief."),
        mc("rk42","3","Was ist Kartografie?","What is cartography?","Qu'est-ce que la cartographie ?","Che cos'è la cartografia?","Wissenschaft der Kartenherstellung",["Kartenlesen","Wissenschaft der Kartenherstellung","Navigieren","Fotografieren"],"Kartografen = Kartenhersteller.","Von Hand bis digital."),
        fib("rk43","3","Mercator-Projektion verzerrt Flächen in der Nähe der ___.","Mercator projection distorts areas near the ___.","La projection de Mercator déforme les surfaces près des ___.","La proiezione Mercatore distorce le aree vicino ai ___.","Pole","Grönland sieht riesig aus.","Projektion = Verzerrung."),
        mc("rk44","3","Was ist eine Projektion in der Kartografie?","What is a map projection?","Qu'est-ce qu'une projection cartographique ?","Che cos'è una proiezione cartografica?","Methode, die Erdkugel auf Karte zu übertragen",["Foto der Erde","Methode, die Erdkugel auf Karte zu übertragen","Art von Kompass","Eine Legende"],"Kugel → Flach = Projektion.","Verzerrung unvermeidbar."),
        fib("rk45","3","Google Maps und GPS nutzen das ___ als globales Koordinatensystem.","Google Maps and GPS use ___ as the global coordinate system.","Google Maps et GPS utilisent le ___.","Google Maps e GPS usano il ___.","WGS 84","WGS 84 = globaler Standard.","GPS = WGS 84."),
        mc("rk46","3","Was ist eine thematische Karte?","What is a thematic map?","Qu'est-ce qu'une carte thématique ?","Che cos'è una carta tematica?","Karte zu einem bestimmten Thema (Bevölkerung, Klima, Wirtschaft)",["Topografische Karte","Karte zu einem Thema","Strassenkarte","Landeskarte"],"Klimakarte, Bevölkerungskarte = thematisch.","Ein Thema im Fokus."),
        fib("rk47","3","Der ___ eines Karte sagt aus, wie gross 1 cm auf der Karte in Wirklichkeit ist.","The ___ of a map says how large 1 cm represents in reality.","L'___ d'une carte indique ce que vaut 1 cm en réalité.","Il ___ di una carta indica quanto grande è 1 cm nella realtà.","Massstab","Massstab = Verkleinerungsfaktor.","Massstab = wichtig beim Lesen."),
        mc("rk48","3","Was ist Isothermen?","What are isotherms?","Que sont les isothermes ?","Cosa sono le isoterme?","Linien gleicher Temperatur auf einer Karte",["Linien für Regen","Linien gleicher Temperatur","Linien für Höhe","Linien für Luftdruck"],"Iso = gleich. Therm = Wärme.","Temperaturverteilung."),
        fib("rk49","3","Das Rütli liegt im Kanton ___ (Gründungsort der Schweiz).","The Rütli is in canton ___ (Switzerland's founding site).","Le Rütli est dans le canton ___ (lieu de fondation).","Il Rütli è nel cantone ___ (luogo di fondazione).","Uri","Rütli am Vierwaldstättersee.","Uri = Gründungskanton 1291."),
        mc("rk50","3","Was ist der Unterschied zwischen Karte und Globus?","Difference between map and globe?","Différence entre carte et globe ?","Differenza tra carta e globo?","Globus ist 3D; Karte ist flach",["Beide gleich","Globus ist 3D; Karte ist flach","Globus zeigt nur Europa","Karten sind grösser"],"Globus = keine Verzerrung.","Karte = Verzerrung durch Projektion."),
    ]

def make_raeume_g4():
    base = make_raeume_g3()
    result = []
    for line in base:
        line = re.sub(r'id: "rk(\d+)"', lambda m: f'id: "rk{m.group(1)}b2"', line)
        result.append(line)
    return result

def make_weltall_g5():
    return [
        mc("wa11","1","Welcher Planet ist am nächsten zur Sonne?","Which planet is closest to the sun?","Quelle planète est la plus proche du soleil ?","Quale pianeta è più vicino al sole?","Merkur",["Venus","Erde","Merkur","Mars"],"Merkur = erster Planet.","Nächster zur Sonne."),
        fib("wa12","1","Die Erde umkreist die Sonne in ungefähr ___ Tagen (1 Jahr).","Earth orbits the sun in about ___ days (1 year).","La Terre orbite autour du soleil en environ ___ jours.","La Terra orbita intorno al sole in circa ___ giorni