import assert from 'node:assert/strict';
import fs from 'node:fs';
import { createHash } from 'node:crypto';
import { downloadContext, shouldRecordDownload } from '../src/lib/worksheets/downloadPolicy';
import resources from '../src/lib/worksheets/free-manifest.json';
let checks = 0;
const req = (path = '/api/worksheets', headers: Record<string,string> = {}, method = 'GET') => new Request('https://www.cleverli.ch' + path, {headers,method});
const expect = (actual: unknown, expected: unknown) => { assert.deepEqual(actual, expected); checks++; };
expect(downloadContext(req(), 'production'), {source_path:null,is_qa:false,qa_reason:null,is_automated:false});
for (const env of [undefined,'development','preview']) expect(downloadContext(req(),env).is_qa,true);
expect(downloadContext(req(),'production','TEST@CLEVERLI.CH').qa_reason,'test_account');
expect(downloadContext(req(),'production','customer@example.invalid').is_qa,false);
expect(downloadContext(req('/api/worksheets?internal_qa=1'),'production').qa_reason,'explicit_qa');
expect(downloadContext(req('/api/worksheets',{'x-cleverli-internal-qa':'1'}),'production').is_qa,true);
expect(downloadContext(req('/api/worksheets',{referer:'https://www.cleverli.ch/arbeitsblaetter/bibliothek?token=never-store&internal_qa=1'}),'production'),{source_path:'/arbeitsblaetter/bibliothek',is_qa:true,qa_reason:'explicit_qa',is_automated:false});
expect(downloadContext(req('/api/worksheets',{referer:'https://evil.example/arbeitsblaetter?internal_qa=1'}),'production'),{source_path:null,is_qa:false,qa_reason:null,is_automated:false});
for(const ref of ['not-a-url','https://www.cleverli.ch/login?email=secret','https://www.cleverli.ch/arbeitsblaetter/unsafe%22']) expect(downloadContext(req('/api/worksheets',{referer:ref}),'production').source_path,null);
expect(downloadContext(req('/api/worksheets',{referer:'https://www.cleverli.ch/arbeitsblaetter/brueche-3-klasse?email=secret'}),'production').source_path,'/arbeitsblaetter/brueche-3-klasse');
expect(downloadContext(req(),'preview','test@cleverli.ch').qa_reason,'non_production,test_account');
expect(downloadContext(req('/api/worksheets',{'user-agent':'Googlebot'}),'production').is_automated,true);
expect(downloadContext(req('/api/worksheets',{'user-agent':'Mozilla/5.0 Chrome/128'}),'production').is_automated,false);
expect(shouldRecordDownload(req()),true);
for(const m of ['HEAD','POST','OPTIONS'])expect(shouldRecordDownload(req('/api/worksheets',{},m)),false);
const prefetchHeaders: Record<string,string>[] = [{purpose:'prefetch'},{'sec-purpose':'prefetch;prerender'},{'x-middleware-prefetch':'1'}];
for(const h of prefetchHeaders)expect(shouldRecordDownload(req('/api/worksheets',h)),false);
expect(resources.length,12);expect(new Set(resources.map(r=>r.file)).size,12);
for(const r of resources){const bytes=fs.readFileSync('public/worksheets/'+r.file+'.pdf');expect(bytes.length,r.file_bytes);expect(createHash('sha256').update(bytes).digest('hex'),r.file_sha256);expect(r.file.includes('/')||r.file.includes('..'),false);}
expect(resources.some(r=>r.file==='../../.env'),false);expect(resources.filter(r=>r.file_type==='worksheet').length,6);expect(resources.filter(r=>r.file_type==='solution').length,6);
const server=fs.readFileSync('src/lib/worksheets/server.ts','utf8');assert(server.indexOf('await recordWorksheetDownload')>server.indexOf('createHash("sha256")'));checks++;
console.log(checks+' deterministic tracking/privacy/QA/manifest checks passed');
