import { readFile } from 'node:fs/promises';
import path from 'node:path';
import {FLIGHT_COOKIE,FLIGHT_PATH,SESSION_SECONDS,flightAuthConfigured,flightCookieFrom,flightLoginLimited,signFlightSession,verifyFlightPassword,verifyFlightSession} from '@/lib/numberFlightTestAuth';
export const dynamic='force-dynamic';export const runtime='nodejs';
const headers={'Cache-Control':'private, no-store, max-age=0','X-Robots-Tag':'noindex, nofollow, noarchive','X-Content-Type-Options':'nosniff','Vary':'Cookie'};
function login(message=''){return '<!doctype html><html lang="de-CH"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow,noarchive"><title>Zahlenflug · Privater Testzugang</title><style>body{font:16px system-ui;background:#f0fdf4;color:#234331;margin:0;min-height:100dvh;display:grid;place-items:center}main{max-width:380px;padding:30px;margin:20px;border:1px solid #b5d8b6;border-radius:22px;background:white}h1{font-size:26px}p{color:#48684e;line-height:1.6}input,button{box-sizing:border-box;font:inherit;width:100%;min-height:50px;border-radius:12px;padding:12px;margin-top:12px}input{border:1px solid #648497;background:#fafff7;color:#234331}button{background:#2e7d32;color:white;border:0;font-weight:800}label{font-weight:700}a{color:#9cedd4}small{display:block;margin-top:20px;color:#527154}</style></head><body><main><h1>🚀 Dein privater Zahlenflug</h1><p>Dieser Spieltest ist nicht öffentlich. Gib das Testpasswort ein, um zu starten.</p>'+(message?'<p role="alert">'+message+'</p>':'')+'<form method="post" action="'+FLIGHT_PATH+'"><label for="password">Testpasswort</label><input id="password" name="password" type="password" autocomplete="current-password" required maxlength="200"><button type="submit">Testzugang öffnen</button></form><small>Keine Änderungen an Medaillen, XP oder Lernfortschritt.</small></main></body></html>';}
type Context={params:Promise<{asset?:string[]}>};
export async function GET(request:Request,{params}:Context){const{asset=[]}=await params;const file=asset.length===0?'index.html':asset.length===1&&asset[0]==='engine.js'?'engine.mjs':asset.length===1&&asset[0]==='game.js'?'game.mjs':asset.length===1&&asset[0]==='theme.js'?'theme.mjs':null;if(!file)return new Response('Not found',{status:404,headers});if(!flightAuthConfigured())return new Response('Testzugang momentan nicht verfügbar',{status:503,headers});if(!verifyFlightSession(flightCookieFrom(request)))return file==='index.html'?new Response(login(),{headers:{...headers,'Content-Type':'text/html; charset=utf-8'}}):new Response('Anmeldung erforderlich',{status:401,headers});const body=await readFile(path.join(process.cwd(),'spikes','number-flight',file),'utf8');return new Response(body,{headers:{...headers,'Content-Type':file==='index.html'?'text/html; charset=utf-8':'text/javascript; charset=utf-8'}});}
export async function POST(request:Request,{params}:Context){const{asset=[]}=await params;const origin=request.headers.get('origin');if(origin!==new URL(request.url).origin)return new Response('Nicht erlaubt',{status:403,headers});if(!flightAuthConfigured())return new Response('Testzugang momentan nicht verfügbar',{status:503,headers});if(asset.length===1&&asset[0]==='logout')return new Response(null,{status:303,headers:{...headers,Location:FLIGHT_PATH,'Set-Cookie':FLIGHT_COOKIE+'=; Path='+FLIGHT_PATH+'; HttpOnly; Secure; SameSite=Lax; Max-Age=0'}});if(asset.length)return new Response('Not found',{status:404,headers});if(flightLoginLimited(request))return new Response(login('Bitte warte kurz vor einem weiteren Versuch.'),{status:429,headers:{...headers,'Retry-After':'600','Content-Type':'text/html; charset=utf-8'}});if(!request.headers.get('content-type')?.startsWith('application/x-www-form-urlencoded'))return new Response('Ungültige Anfrage',{status:415,headers});if(Number(request.headers.get('content-length')||0)>2048)return new Response('Anfrage zu gross',{status:413,headers});const body=await request.text();if(body.length>2048)return new Response('Anfrage zu gross',{status:413,headers});const form=new URLSearchParams(body);if(form.getAll('password').length!==1||!verifyFlightPassword(form.get('password')||''))return new Response(login('Das Testpasswort stimmt nicht.'),{status:401,headers:{...headers,'Content-Type':'text/html; charset=utf-8'}});return new Response(null,{status:303,headers:{...headers,Location:FLIGHT_PATH,'Set-Cookie':FLIGHT_COOKIE+'='+signFlightSession()+'; Path='+FLIGHT_PATH+'; HttpOnly; Secure; SameSite=Lax; Max-Age='+SESSION_SECONDS}});}
