import Image from "next/image";
import Link from "next/link";
import type { Metadata } from "next";
export const metadata: Metadata = {
  title: "Arbeitsblätter für die Primarschule",
  description: "Arbeitsblätter für die 1. bis 6. Klasse: Ein PDF kostenlos kennenlernen. Mit Premium 303 Themen mit je einem Arbeitsblatt und separater Lösung entdecken.",
  alternates: { canonical: "https://www.cleverli.ch/arbeitsblaetter" },
};
const button = "inline-flex min-h-12 items-center justify-center rounded-2xl px-6 py-3 font-bold transition focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-green-700";
export default function WorksheetsPage() {
  return <main className="bg-[#fbfaf5] text-slate-800 pb-20">
    <section className="mx-auto max-w-6xl px-5 py-12 sm:px-8 lg:py-20">
      <nav aria-label="Brotkrümel" className="mb-10 text-sm text-slate-600"><Link href="/" className="underline underline-offset-4">Cleverli</Link><span className="mx-3">/</span>Arbeitsblätter</nav>
      <div className="grid items-center gap-12 lg:grid-cols-[1.1fr_1fr]">
        <div><p className="mb-5 inline-flex rounded-full bg-green-100 px-4 py-2 text-sm font-bold text-green-900">Für zu Hause und den Unterricht</p>
          <h1 className="text-4xl font-extrabold leading-tight tracking-tight sm:text-5xl lg:text-6xl">Kleine Lernmomente.<br/><span className="text-green-700">Auch auf Papier.</span></h1>
          <p className="mt-6 max-w-xl text-lg leading-8 text-slate-600">Auswählen, ausdrucken und in Ruhe üben. Entdecke liebevoll gestaltete Arbeitsblätter für die 1. bis 6. Klasse, mit einer separaten Lösung zu jedem Thema.</p>
          <div className="mt-8 flex flex-col gap-3 sm:flex-row"><Link href="/arbeitsblaetter/bibliothek" className={`${button} bg-green-700 text-white hover:bg-green-800`}>Zur Premiumbibliothek <span aria-hidden="true" className="ml-3">→</span></Link><a href="#beispiel" className={`${button} border border-green-200 bg-white text-green-800 hover:bg-green-50`}>Beispiel kennenlernen</a></div>
          <p className="mt-4 text-sm leading-6 text-slate-600">Ein Beispiel ist frei zugänglich. Die ganze Bibliothek gehört zu Premium.</p>
          <dl className="mt-9 grid grid-cols-3 gap-3 border-t border-stone-200 pt-7">{[["303","Themen"],["1–6","Klassen"],["606","PDFs mit Lösungen"]].map(([value,label])=><div key={label}><dt className="text-xs sm:text-sm text-slate-600">{label}</dt><dd className="mt-1 text-2xl font-extrabold text-green-900">{value}</dd></div>)}</dl>
        </div>
        <a href="#beispiel" className="relative mx-auto block w-full max-w-md rounded-[2rem] bg-[#e5eddf] p-7 sm:p-9" aria-label="Zum Beispielarbeitsblatt Brüche, 3. Klasse"><span className="absolute -top-3 right-4 z-10 rounded-full bg-amber-200 px-4 py-2 text-sm font-bold text-amber-950 shadow-sm">Ein Blick ins echte PDF</span><Image src="/worksheets/beispiel-klasse-3.png" alt="Originalseite des Cleverli Arbeitsblatts Brüche für die 3. Klasse" width={849} height={1200} priority className="h-auto w-full -rotate-2 rounded-sm bg-white shadow-xl"/><span className="mt-6 block text-center text-sm font-semibold text-green-900">Mathematik · 3. Klasse · A4</span></a>
      </div>
    </section>
    <section id="beispiel" className="scroll-mt-24 border-y border-green-100 bg-white"><div className="mx-auto grid max-w-6xl gap-8 px-5 py-12 sm:px-8 md:grid-cols-[1fr_auto] md:items-center"><div><p className="text-sm font-bold uppercase tracking-widest text-green-700">Dein kostenloses Beispiel</p><h2 className="mt-3 text-3xl font-extrabold">Brüche entdecken</h2><p className="mt-4 max-w-2xl leading-7 text-slate-600">Ein ganzes Arbeitsblatt aus der 3. Klasse, genau so, wie es in der Bibliothek bereitliegt. Öffne die Originalseite oder lade sie zum Ausdrucken herunter.</p><p className="mt-3 text-sm text-slate-500">1 Seite · PDF · A4 · Die separate Lösung findest du mit Premium in der Bibliothek.</p></div><div className="flex flex-col gap-3"><a href="/worksheets/beispiel-klasse-3.pdf" target="_blank" rel="noopener" className={`${button} border border-green-200 text-green-800`}>PDF ansehen <span className="sr-only">(neuer Tab)</span></a><a href="/worksheets/beispiel-klasse-3.pdf" download="Cleverli-Brueche-Klasse-3.pdf" className={`${button} bg-green-700 text-white hover:bg-green-800`}>Beispiel herunterladen ↓</a></div></div></section>
    <section className="mx-auto max-w-6xl px-5 py-14 sm:px-8"><p className="text-sm font-bold uppercase tracking-widest text-green-700">Gut sortiert, schnell gefunden</p><h2 className="mt-3 text-3xl font-extrabold">Was üben wir heute?</h2><p className="mt-4 max-w-3xl leading-7 text-slate-600">Wähle die Klasse und finde passende Themen in Mathematik, Deutsch, Natur, Mensch, Gesellschaft sowie ab der 3. Klasse auch Englisch, Französisch und Medien und Informatik.</p><div className="mt-8 grid grid-cols-2 gap-4 md:grid-cols-3">{[36,35,51,61,60,60].map((count,i)=><Link key={i} href={`/arbeitsblaetter/bibliothek?klasse=${i+1}`} className="group rounded-2xl border border-stone-200 bg-white p-5 transition hover:border-green-500 hover:shadow-md"><span className="flex items-center justify-between"><span className="text-2xl font-extrabold text-green-900">{i+1}. Klasse</span><span aria-hidden="true" className="text-green-700 group-hover:translate-x-1 transition">→</span></span><span className="mt-3 block text-sm text-slate-600">{count} Themen</span><span className="mt-1 block text-xs font-semibold text-green-700">Arbeitsblatt + Lösung</span></Link>)}</div>
      <div className="mt-10 grid gap-6 md:grid-cols-3">{[["01","Passendes Thema finden","Nach Klasse und Fach filtern oder direkt nach einem Thema suchen."],["02","In Ruhe üben","Ein übersichtliches Arbeitsblatt pro Thema. Für kleine Lernpausen und gezielte Wiederholungen."],["03","Gemeinsam nachschauen","Separate Lösungen unterstützen Eltern und Lehrpersonen beim Besprechen."]].map(([n,t,d])=><article key={n} className="rounded-2xl bg-[#f0f3e9] p-6"><p className="font-bold text-green-700">{n}</p><h3 className="mt-3 text-lg font-bold">{t}</h3><p className="mt-2 leading-7 text-slate-600">{d}</p></article>)}</div>
      <p className="mt-8 max-w-4xl text-sm leading-6 text-slate-600">Die Themen orientieren sich an ausgewählten Bereichen des Lehrplans 21. Die Klassenangaben helfen bei der Auswahl; Lernstand und Reihenfolge können je nach Schule und Kanton abweichen. Ein Arbeitsblatt deckt nicht alle Kompetenzen eines Themas ab. Die Materialien sind deutschsprachig, mit Aufgaben in der jeweiligen Fremdsprache.</p>
    </section>
    <section className="mx-5 rounded-3xl bg-green-900 px-6 py-10 text-center text-white sm:mx-auto sm:max-w-5xl"><h2 className="text-3xl font-extrabold">Dein nächster Lernmoment wartet.</h2><p className="mx-auto mt-4 max-w-2xl leading-7 text-green-100">Mit Premium findest du alle 303 Arbeitsblätter und die 303 passenden Lösungen an einem Ort. Bestehender Premiumzugang und gültiger Lehrpersonenzugang gelten auch hier.</p><Link href="/arbeitsblaetter/bibliothek" className={`${button} mt-6 bg-white text-green-900 hover:bg-green-50`}>Bibliothek öffnen →</Link><p className="mt-5 text-sm text-green-100"><Link href="/upgrade?returnTo=%2farbeitsblaetter%2fbibliothek" className="underline underline-offset-4">Premium kennenlernen</Link></p></section>
  </main>;
}
