export const GRADE_LABELS=['','Zählen und Plus bis 10','Plus bis 100','Einmaleins und Teilen','Grosse Zahlen und Rechenwege','Brüche und Kommazahlen','Prozente, Anteile und Rechenketten'];
export const PROFILES={1:{static:true,choices:2,seconds:0,goals:3,speed:.08,dots:true,max:10},2:{static:true,choices:3,seconds:0,goals:4,speed:.1,max:100},3:{static:false,choices:3,seconds:120,goals:0,speed:.13,max:100},4:{static:false,choices:3,seconds:110,goals:0,speed:.15,max:5000},5:{static:false,choices:3,seconds:100,goals:0,speed:.16,max:1200},6:{static:false,choices:3,seconds:90,goals:0,speed:.18,max:1000}};
export function rng(seed=1){let n=seed>>>0;return()=>{n=(Math.imul(n,1664525)+1013904223)>>>0;return n/4294967296;};}const int=(r,a,b)=>a+Math.floor(r()*(b-a+1));const gcd=(a,b)=>b?gcd(b,a%b):a;
export function display(units,grade){if(grade===5)return(units/100).toLocaleString('de-CH',{maximumFractionDigits:2}).replace('.',',');return String(units);}
export function labelFor(units,grade,r){if(grade===3){const f=[];for(let a=2;a<=10;a++)if(units%a===0&&units/a<=10)f.push(a);if(f.length&&r()<.65){const a=f[int(r,0,f.length-1)];return{label:a+' × '+units/a,kind:'multiply',a,b:units/a}}return{label:units*2+' ÷ 2',kind:'divide',a:units*2,b:2};}
if(grade===4){const d=int(r,1,Math.max(1,Math.min(99,units-1)));return r()<.5?{label:units-d+' + '+d,kind:'add',a:units-d,b:d}:{label:units+d+' − '+d,kind:'subtract',a:units+d,b:d};}
if(grade===5){if(r()<.5){const d=gcd(units,100);return{label:units/d+'/'+100/d,kind:'fraction',a:units/d,b:100/d}}return{label:(units/100).toFixed(2).replace('.',','),kind:'decimal',a:units,b:100};}
if(grade===6){const k=int(r,0,2);if(k===0){const p=[10,20,25,50][int(r,0,3)];return{label:p+'% von '+units*100/p,kind:'percentOf',a:p,b:units*100/p};}if(k===1){const d=[2,3,4,5][int(r,0,3)];return{label:'1/'+d+' von '+units*d,kind:'fractionOf',a:1,b:d,c:units*d};}const a=Math.max(0,Math.floor(units/3)-int(r,1,4)),c=units-a*3;return{label:a+' × 3 + '+c,kind:'chain',a,b:3,c};}
return{label:String(units),kind:'integer',a:units,b:1};}
export function createMission(grade,r=Math.random){if(!PROFILES[grade]||!Number.isInteger(grade))throw Error('Invalid grade');let a,b,c=0;if(grade===1){const target=int(r,3,10);a=int(r,1,Math.min(5,target-1));b=target-a;}if(grade===2){const target=int(r,20,100);a=int(r,3,Math.min(40,target-3));b=target-a;}if(grade===3){a=int(r,2,8)*int(r,2,6);b=int(r,2,8)*int(r,2,6);}if(grade===4){a=int(r,120,900);b=int(r,120,900);}if(grade===5){a=int(r,4,28)*5;b=int(r,4,28)*5;}if(grade===6){a=int(r,18,80);b=int(r,18,80);c=int(r,18,80);}return{grade,target:a+b+c,first:a,scale:grade===5?100:1};}
export function makeWave(m,energy,r=Math.random){const remaining=m.target-energy,step=m.grade===5?5:1;let good=energy===0?m.first:remaining;if(m.grade===6&&energy>0&&energy<m.target*.65)good=Math.max(1,Math.floor(remaining/2));let values;if(m.grade===1){const other=Math.min(10,good===1?2:good+1);values=[good,other];if(r()<.5)values.reverse();return[{units:values[0],...labelFor(values[0],1,r)},null,{units:values[1],...labelFor(values[1],1,r)}];}if(m.grade>=4){values=[good,Math.max(step,good-step),Math.min(PROFILES[m.grade].max,good+step*(m.grade===6?2:3))];}else{values=[good,Math.min(PROFILES[m.grade].max,m.target+step*int(r,1,3)),Math.max(step,good-step)];}const shift=int(r,0,2);return values.map((_,i)=>{const units=values[(i+shift)%3];return{units,...labelFor(units,m.grade,r)}});}
export function applyEnergy(energy,units,target){if(![energy,units,target].every(Number.isSafeInteger)||units<=0||energy<0||target<=0)throw Error('Invalid energy');const next=energy+units;return next===target?{energy:0,outcome:'boost'}:next>target?{energy:0,outcome:'overshoot'}:{energy:next,outcome:'collect'};}
export function evaluateChoice(c,scale=1){if(c.kind==='multiply')return c.a*c.b;if(c.kind==='divide')return c.a/c.b;if(c.kind==='add')return c.a+c.b;if(c.kind==='subtract')return c.a-c.b;if(c.kind==='percentOf')return c.a/100*c.b;if(c.kind==='fractionOf')return c.a/c.b*c.c;if(c.kind==='chain')return c.a*c.b+c.c;return c.a/c.b*scale;}
