import {drawAlpine,drawToken,drawCelebration,sceneReady,drawCompanion} from '/labs/number-flight/theme.js';
import {rng,createMission,makeWave,applyEnergy,display,GRADE_LABELS,PROFILES} from '/labs/number-flight/engine.js';
const $=id=>document.getElementById(id),canvas=$('game'),ctx=canvas.getContext('2d'),Y=[.28,.51,.74];
const mascot=new Image();mascot.src='/cleverli-wave.png';
let w=960,h=530,last=0,random=rng(Date.now()),s,cols=[],clouds=[],sparks=[],spawn=0,flash=0,toast=0,raf=0;
let slow=true,grade=1;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const touchDevice=matchMedia('(pointer: coarse)').matches;
function key(){return 'cleverli_number_flight_prototype_v2:'+grade+':'+(slow?'slow':'normal');}
function best(){try{return Math.max(0,Number(localStorage.getItem(key()))||0);}catch{return 0;}}
function reset(){s={phase:'ready',grade,energy:0,stars:0,boosts:0,combo:0,lane:grade===1?0:1,y:Y[grade===1?0:1],elapsed:0,travel:0,cooldown:0,mission:createMission(grade,random)};cols=[];clouds=[];sparks=[];spawn=.25;flash=0;toast=0;hud();updateGuide();lanes();}
function hud(){const target=s.mission.target;$('energy').textContent=display(s.energy,grade)+' / '+display(target,grade);$('remaining').textContent='Noch '+display(target-s.energy,grade);$('need').textContent='Sammle noch '+display(target-s.energy,grade);$('fill').style.width=(s.energy/target*100)+'%';$('stars').textContent=s.stars+' ★';$('combo').textContent='Ziele: '+s.boosts;const left=Math.max(0,Math.ceil(PROFILES[grade].seconds-s.elapsed));$('time').textContent=PROFILES[grade].seconds?Math.floor(left/60)+':'+String(left%60).padStart(2,'0'):s.boosts+'/'+PROFILES[grade].goals;$('distance').textContent=Math.floor(s.travel)+' m';$('mode').textContent=GRADE_LABELS[grade];$('profile-note').textContent=PROFILES[grade].seconds?'Klasse '+grade+': '+GRADE_LABELS[grade]+'. Rechne die Blasen aus und triff dein Ziel.':'Klasse '+grade+': Die Blasen warten auf deine Wahl. '+PROFILES[grade].goals+' Ziele, ohne Zeitdruck.';document.body?.setAttribute('data-phase',s.phase);document.body?.setAttribute('data-grade',String(grade));$('grade').disabled=['playing','paused'].includes(s.phase);$('slow').disabled=['playing','paused'].includes(s.phase);$('pause').disabled=s.phase!=='playing';}
function say(text){$('status').textContent=text;toast=3.5;}
function lanes(){for(const b of document.querySelectorAll('[data-lane]')){b.hidden=grade===1&&Number(b.dataset.lane)===1;b.setAttribute('aria-pressed',String(Number(b.dataset.lane)===s.lane));}}
function steer(lane){const active=grade===1?[0,2]:[0,1,2];s.lane=active.includes(lane)?lane:active[0];if(PROFILES[grade].static&&s.phase==='playing'){const c=cols.find(c=>!c.crossed);if(c&&c.choices[s.lane])c.launched=true;}lanes();}
function particles(x,y,color,n=15){if(reduced)return;for(let i=0;i<n;i++)sparks.push({x,y,vx:(random()-.5)*.3,vy:(random()-.5)*.5,t:1+random(),color});}
function pickup(units){if(s.phase!=='playing')return;const before=s.energy,result=applyEnergy(s.energy,units,s.mission.target);s.energy=result.energy;
 if(result.outcome==='boost'){s.boosts++;s.combo++;s.stars+=10+Math.min(s.combo,5);s.travel+=200;s.cooldown=1.15;flash=1;particles(.18,s.y,'#ffe18b',32);say(display(before,grade)+' + '+display(units,grade)+' = '+display(s.mission.target,grade)+'! Ziel geschafft. Turbo +'+(10+Math.min(s.combo,5))+' Sterne');s.mission=createMission(grade,random);cols=[];clouds=[];spawn=1.1;}
 else if(result.outcome==='overshoot'){if(grade===1){s.energy=before;say('Diese Zahl ist zu gross. Dein gesammelter Vorrat bleibt.');cols=[];spawn=.35;hud();return;}s.combo=0;flash=-.6;particles(.18,s.y,'#f5a6ac',10);say(display(before,grade)+' + '+display(units,grade)+' ist zu viel. Neuer Versuch mit leerem Tank.');cols=[];spawn=.5;}
 else{particles(.18,s.y,'#8fffd3',10);say('Energie gesammelt! Noch '+display(s.mission.target-s.energy,grade)+' bis zum Turbo.');}
 hud();
}
function column(){const choices=makeWave(s.mission,s.energy,random);cols.push({x:PROFILES[grade].static?.72:1.13,choices,crossed:false,launched:!PROFILES[grade].static});if(grade>=3&&s.boosts>0&&random()<.5)clouds.push({x:1.53,lane:Math.floor(random()*3),hit:false});}
function update(dt){if(s.phase!=='playing')return;s.elapsed+=dt;if(PROFILES[grade].seconds&&s.elapsed>=PROFILES[grade].seconds){s.elapsed=PROFILES[grade].seconds;finish();return;}if(PROFILES[grade].goals&&s.boosts>=PROFILES[grade].goals&&s.cooldown===0){finish();return;}s.y+=(Y[s.lane]-s.y)*Math.min(1,dt*13);s.cooldown=Math.max(0,s.cooldown-dt);const speed=PROFILES[grade].speed*(slow?1:1.3)*(s.cooldown>0?1.55:1);s.travel+=dt*(slow?17:25);spawn-=dt;
 if(spawn<=0&&s.cooldown===0&&cols.length===0){column();spawn=slow?3.5:2.9;}
 for(const c of [...cols]){if(c.launched)c.x-=(PROFILES[grade].static?.44:speed)*dt;if(!c.crossed&&c.x<=.19){c.crossed=true;const lane=Y.findIndex(y=>Math.abs(s.y-y)<.085);if(lane>=0&&c.choices[lane])pickup(c.choices[lane].units);}}
 const consumed=cols.some(c=>c.crossed);cols=cols.filter(c=>!c.crossed&&c.x>-.13);if(consumed)spawn=Math.max(spawn,.35);
 for(const c of clouds){c.x-=speed*dt;if(!c.hit&&c.x<=.2&&c.x>.08&&Math.abs(s.y-Y[c.lane])<.08){c.hit=true;s.combo=0;particles(.18,s.y,'#b4cadd',8);say('Eine kleine Wolke! Deine Energie bleibt im Tank.');}}clouds=clouds.filter(c=>c.x>-.1);
 for(const p of sparks){p.x+=p.vx*dt;p.y+=p.vy*dt;p.t-=dt;}sparks=sparks.filter(p=>p.t>0);flash=Math.sign(flash)*Math.max(0,Math.abs(flash)-dt);toast=Math.max(0,toast-dt);if(toast===0)$('status').textContent='Wähle deine Flugbahn. Fülle den Tank genau bis zum Ziel.';hud();
}
function draw(){drawAlpine(ctx,w,h,s.travel);for(let i=0;i<3;i++){if(grade===1&&i===1)continue;ctx.strokeStyle=i===s.lane?'#ffffff8a':'#ffffff36';ctx.lineWidth=1.5;ctx.setLineDash([3,13]);ctx.beginPath();ctx.moveTo(0,Y[i]*h);ctx.lineTo(w,Y[i]*h);ctx.stroke();}ctx.setLineDash([]);
 const visible=s.phase==='ready'?[{x:.68,choices:makeWave(s.mission,0,rng(21))}]:cols;
 for(const c of visible)for(let lane=0;lane<3;lane++){const choice=c.choices[lane];if(!choice)continue;const x=c.x*w,y=Y[lane]*h,bw=Math.max(w<600?60:76,choice.label.length*(w<600?9:12)+18),bh=Math.min(w<600?48:58,h*.18);drawToken(ctx,x,y,bw,bh,'number');ctx.fillStyle='#0b344b';ctx.font='800 '+(h<300?16:w<600?16:21)+'px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';if(choice.label.length>12){const chunks=choice.label.split(' '),cut=Math.ceil(chunks.length/2);ctx.font='800 '+(w<600?13:17)+'px system-ui';ctx.fillText(chunks.slice(0,cut).join(' '),x,y-8);ctx.fillText(chunks.slice(cut).join(' '),x,y+9);}else ctx.fillText(choice.label,x,y-(grade===1?6:0));if(grade===1){ctx.fillStyle='#15803d';for(let d=0;d<choice.units;d++){ctx.beginPath();ctx.arc(x+(d%5-2)*7,y+9+Math.floor(d/5)*7,2.5,0,Math.PI*2);ctx.fill();}}}
 for(const c of clouds){const x=c.x*w,y=Y[c.lane]*h;ctx.fillStyle=c.hit?'#60758c55':'#a9bfd0';ctx.beginPath();ctx.ellipse(x,y,32,15,0,0,Math.PI*2);ctx.arc(x-10,y-10,17,0,Math.PI*2);ctx.arc(x+12,y-8,20,0,Math.PI*2);ctx.fill();ctx.fillStyle='#3b5267';ctx.font='bold 17px system-ui';ctx.textAlign='center';ctx.fillText('≈',x,y+2);}
 const rx=w*.17,ry=s.y*h,size=Math.min(74,h*.28);drawCompanion(ctx,mascot,rx,ry,size,'flight');
 for(const p of sparks){ctx.globalAlpha=Math.min(1,p.t);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x*w,p.y*h,3,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;
 if(flash!==0){ctx.fillStyle=flash>0?'#ffe8a30f':'#f7a5ad10';ctx.fillRect(0,0,w,h);if(flash>0){drawCelebration(ctx,w,h,'Ziel geschafft!');}}
}
function updateGuide(){const a=grade===1?2:grade===5?25:4,b=grade===1?3:grade===5?75:6,target=a+b;$('demo-goal').textContent=display(target,grade);$('demo-first').textContent=display(a,grade);$('demo-second').textContent=display(b,grade);$('demo-total').textContent=display(target,grade);$('control-tip').textContent=PROFILES[grade].static?'Die Blasen warten. Tippe eine Blase oder eine Bahn.':touchDevice?'Tippe auf Oben, Mitte oder Unten.':'Drücke ↑ oder ↓. Oder klicke eine Bahn.';}
function frameGameArea(){if(touchDevice||w<740)requestAnimationFrame(()=>$('hud').scrollIntoView({block:'start',behavior:'auto'}));}
function hideGuide(){document.body?.setAttribute('data-guide','false');}
function show(title,text,button,badge,help=false){const guide=s.phase==='ready'||help;$('guide').hidden=!guide;document.body?.setAttribute('data-guide',String(guide));updateGuide();$('overlay-title').textContent=title;$('overlay-text').textContent=text;$('start').textContent=button;$('badge').textContent=badge;$('overlay').hidden=false;$('overlay').scrollTop=0;if(s.phase==='ready'||help)canvas.style.height='';$('best').textContent='Persönlicher Testrekord: '+best()+' Sterne · Nur auf diesem Gerät';}
function start(){random=rng(crypto.getRandomValues(new Uint32Array(1))[0]);reset();s.phase='playing';if(PROFILES[grade].static)column();$('overlay').hidden=true;hideGuide();$('again').hidden=true;say('Los geht’s! Ziel: '+display(s.mission.target,grade)+' Energie.');hud();canvas.focus({preventScroll:true});frameGameArea();}
function pause(){if(s.phase!=='playing')return;s.phase='paused';show('Kurze Flugpause','Der Tank und die Flugzeit bleiben genau so stehen.','Weiterfliegen','☁️');$('again').hidden=false;hud();}
function resume(){if(s.phase!=='paused')return;s.phase='playing';$('overlay').hidden=true;hideGuide();$('again').hidden=true;hud();canvas.focus({preventScroll:true});frameGameArea();}
function finish(){s.phase='ended';const old=best();if(s.stars>old)try{localStorage.setItem(key(),String(s.stars));}catch{}show('Dein Testflug ist geschafft!',s.boosts+' Turbo'+(s.boosts===1?'':'s')+', '+s.stars+' Sterne und '+Math.floor(s.travel)+' Meter. '+(s.stars>old?'Ein neuer persönlicher Testrekord!':'Jeder Flug ist ein neues Abenteuer.'),'Noch einen Testflug starten','🌟');$('again').hidden=false;hud();}
$('help').onclick=()=>{if(s.phase==='playing')pause();show('So fliegst du','',s.phase==='paused'?'Weiterfliegen':'Losfliegen!','🚀',true);};
$('start').onclick=()=>s.phase==='paused'?resume():start();$('pause').onclick=pause;$('again').onclick=()=>{reset();show('So fliegst du','','Losfliegen!','🚀');$('again').hidden=true;};
$('grade').onchange=()=>{grade=Number($('grade').value);reset();show('So fliegst du','','Losfliegen!','🚀');};$('slow').onclick=()=>{slow=!slow;$('slow').setAttribute('aria-pressed',String(slow));$('slow').textContent=slow?'Gemütlich ✓':'Normal ⚡';$('best').textContent='Persönlicher Testrekord: '+best()+' Sterne · Nur auf diesem Gerät';};
for(const b of document.querySelectorAll('[data-lane]'))b.onclick=()=>steer(Number(b.dataset.lane));
const clampLane=(i,n)=>Math.max(0,Math.min(n-1,i));
function point(e){const rect=canvas.getBoundingClientRect(),y=(e.clientY-rect.top)/rect.height,active=grade===1?[0,2]:[0,1,2];steer(active.reduce((a,i)=>Math.abs(Y[i]-y)<Math.abs(Y[a]-y)?i:a,active[0]));}
canvas.addEventListener('pointerdown',e=>{if(s.phase!=='playing')return;point(e);canvas.setPointerCapture(e.pointerId);});canvas.addEventListener('pointermove',e=>{if(e.buttons&&s.phase==='playing')point(e);});
window.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(s.phase==='playing'&&['ArrowUp','ArrowDown','w','s','W','S'].includes(e.key)){e.preventDefault();const active=grade===1?[0,2]:[0,1,2],dir=['ArrowUp','w','W'].includes(e.key)?-1:1;steer(active[clampLane(active.indexOf(s.lane)+dir,active.length)]);}if(e.key==='Escape'&&s.phase==='playing'){e.preventDefault();pause();}});
document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});window.addEventListener('blur',pause);
function resize(){const r=canvas.getBoundingClientRect();w=r.width;h=r.height;const d=Math.min(3,devicePixelRatio||1);canvas.width=Math.round(w*d);canvas.height=Math.round(h*d);ctx.setTransform(d,0,0,d,0,0);}
new ResizeObserver(resize).observe(canvas);window.addEventListener('pagehide',()=>cancelAnimationFrame(raf));
function frame(now){const dt=last?Math.min(.05,(now-last)/1000):0;last=now;update(dt);draw();raf=requestAnimationFrame(frame);}
reset();resize();raf=requestAnimationFrame(frame);
if(new URLSearchParams(location.search).get('internal_qa')==='1')window.numberFlightTest={state:()=>structuredClone(s),pickup,step:seconds=>{for(let t=0;t<seconds;t+=.02)update(Math.min(.02,seconds-t));},wave:()=>structuredClone(cols),steer,sceneReady:()=>sceneReady(ctx)};
